### ISSUE TITLE
error on IOS: ArgumentNullException: Value cannot be null. Parameter name: shader 

### ISSUE THREAD

**Issue by anupamdas2012** [atteneder/glTFast#102]
hi, im trying to load duck.gltf from your minimal sample. Works great on desktop/ editor.
when i run the app on IOS (Ipad), I get this error:

error on IOS: ArgumentNullException: Value cannot be null. Parameter name: shader 

I have tried a number of other objects and none seem to work on IOS but they all work on desktop.

Am I setting up something wrong? Please advise?

**Comment by atteneder** [comment]
Hi,

Please read the section [Materials and Shader Variants](https://github.com/atteneder/glTFast#materials-and-shader-variants) of the [README](https://github.com/atteneder/glTFast) very carefully.

Regards
