### ISSUE TITLE
To record Loading time of glb file

### ISSUE THREAD

**Issue by waseemkhan1989** [atteneder/glTFast#103]
Hi,

I am importing a glb file into my scene as follows:

` var model = gameObject.AddComponent<GLTFast.GltfAsset>();
model.url = "https://dummy.com/model.glb";
ResetWrapper();
model.transform.SetParent(wrapper.transform);`

To determine the loading efficiency of GLTFast, I would like to record how much time it takes:

1. To downloading a glb file from remote server to a local location(on hard drive on a local computer)

2. And the time it takes to import glb file from this local location into the scene

I would like to record these timings on Quest(Android). I went through the library and got an idea but I would like to know the exact location where I should start and stop the time. Any help @atteneder ?

**Comment by atteneder** [comment]
Hi @waseemkhan1989 ,

That's a good idea. Performance profiling is something I pay close attention to.

When I started out I had code that made A/B comparisons with UnityGLTF. glTFast was clearly faster at some point and I stopped maintaining this comparison projects to focus on improving glTFast itself.

After that I usually did look at the [Unity Profiler](https://docs.unity3d.com/Manual/Profiler.html) in builds (on-device) to watch the impact of changes/improvements.

To remove the impact of Network speeds I usually load models from disk (StreamingAssets folder).

Note: The loading scene in [glTFastDemo](https://github.com/atteneder/glTFastDemo) does measure the time, so that's a starting point for you to look at. I'm not 100% sure if those timings are correct, so I tend to trust the profiler more.

hth,
Andi

**Comment by waseemkhan1989** [comment]
@atteneder Thanks for replying. Currently, I am also doing the same thing i.e. the performance comparison of UnityGLTF and GLTFast on various models. Can I have that code where you made comparison  with UnityGLTF in terms of load timings?

I will look into the gltFastDemo for calculating loading time. For a fair comparison, I am also considering some factors like in Unity GLTF, they have some parameters which can affect performance such as

1. Multithreading is on/off?
2. What is the value of Budget Per Frame in Seconds?
3. Load on Start option
4. Using stream or not

My question is, does GLTFast supports the above parameters? If yes then where can I enable/disable it? 

Thanks.
Best,
Waseem

**Comment by atteneder** [comment]
> Can I have that code where you made comparison with UnityGLTF in terms of load timings?

I actually re-used the scripts from the glTFastDemo within the UnityGLTF project with the `UNITY_GLTF` scripting define on (search for it). I'm almost certain, that this `UNITY_GLTF` mode is broken at the moment. If you find time to fix it, please share it with me. I'd be interested in up-to-date comparisons as well.

>     1. Multithreading is on/off?

On by default in glTFast (cannot be disabled)

>     2. What is the value of Budget Per Frame in Seconds?

It's configurable. Take a look at `TimeBudgetPerFrameDeferAgent` and the [Tune loading performance](https://github.com/atteneder/glTFast#tune-loading-performance) section in the README.

>     3. Load on Start option

Load on start is not an option, but you can always create your own loader.

>     4. Using stream or not

Streaming is not supported atm.

hth

**Comment by waseemkhan1989** [comment]
> I actually re-used the scripts from the glTFastDemo within the UnityGLTF project with the `UNITY_GLTF` scripting define on (search for it)

I searched the whole UnityGLTF project but I could not find out `UNITY_GLTF`  within the UnityGLTF project. 

Regarding the time calculation, I am calling UWR by myself for downloading a file from remote server. Once the file is downloaded on local location on Android(Quest) then I am calling GLTFast/UnityGLTF importer to import the model into the scene. The reason is, I want to rule out the network speed. Unfortunately, GLTFast library gave me a tough time in importing a model from local location due to due to Android file path problem and I spent 3 days on it.

This is how I am calculating loading time for GLTFast:
`var model = gameObject.AddComponent<GLTFast.GltfAsset>();
                    DateTime started = DateTime.Now;
                    Debug.Log("import start time" + started);
                    Debug.Log("The path as an Input to GLTFast: " + path);   
                    model.url = Path.Combine("file://" + path);
                   model.onLoadComplete += (arg0, b) =>
                    {
                        TimeSpan elapsedTime = DateTime.Now - started;
                        Debug.Log("Time spent in importing file: " + elapsedTime.TotalSeconds + "s");
                    };
                    ResetWrapper();
                    model.transform.SetParent(wrapper.transform);
`

For UnityGLTF, I was confused about where I should stop the timer. So, I found out that this library also has "onLoadComplete" i.e. at line 351 in GLTFSceneImporter.cs script.  So, I think, I should stop timer there. 
Do you think, my approach is right to calculate time for both libraries?

I will look at gltFastdemo in this week.

Thnx.
Best,
Waseem Khan

**Comment by waseemkhan1989** [comment]
I compared the loading time of GLTFast(v2.1.0) with the UnityGLTF(v1.0.1). GLTFast and UnityGLTF has the loading speed ratio of around 2:1, means GLTFast is twice as fast as UnityGLTF on Oculus Quest.

I will update the comparison with the new update of UnityGLTF soon.

**Comment by atteneder** [comment]
The difference depends heavily on the content, but yes...2x speedup is within my measures as well.

And it'll get even better over time with DOTS support (#92 ), so stay tuned.
