### ISSUE TITLE
Question: Tested on Hololens 2

### ISSUE THREAD

**Issue by Spoon2311** [atteneder/glTFast#104]
Hey Great tool you wrote here!

I tested it on the HL2 and it sadly didn't work, but on the editor it does.
Have you had any experience with it or are there any changes I'd need to make to make it work?

Thanks for the answer.

**Comment by atteneder** [comment]
Hi @Spoon2311,

Thanks for reaching out.

Unfortunately I don't have the hardware to test. I think somebody once wrote me they tested it on Hololens 1, but I'm not sure.

Can this be emulated (by me) somehow? Can you reproduce in an emulator?

Can you give me more informations (exact error message(s) and the models you try to load) ?

Can you load models from a HTTP server (not locally) that have neither Draco compression nor KTX textures? (that eliminates KtxUnity or DracoUnity as sources of error)

**Comment by Spoon2311** [comment]
Ahhh ok.
There should be the possibility to emulate HL2, some documentation can be found [here](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/platform-capabilities-and-apis/using-the-hololens-emulator).

Concerning the errors I attached 2 Log files, one of the compressed and one of the uncompressed .glb file.
[UnityPlayer_Log_Uncompressed.log](https://github.com/atteneder/glTFast/files/5531010/UnityPlayer_Log_Uncompressed.log)
[UnityPlayer_Log_Compressed.log](https://github.com/atteneder/glTFast/files/5531011/UnityPlayer_Log_Compressed.log)

Both files I tried to load from the persistent path within the HL2.
I didn't try to load it from a Server, but the way it seems to me is that it has issues loading the graphics rather then getting the data-files, but not sure about that one.

**Comment by JSWorkspace1** [comment]
In the Uncompressed.log you have the Excpection

  ```
"ArgumentNullException: Value cannot be null.
Parameter name: shader"
```
It's the same exception as Issue #102  for example 
To fix this Please read the section Materials and Shader Variants of the README very carefully.

**Comment by kircher1** [comment]
Looking at the Draco package, it doesn't have a DLL for ARM64 UWP, so the plugin wouldn't work on HL2. +1 to generating Draco DLLs for all flavors of UWP (x86/x64/ARM/ARM64).

**Comment by Spoon2311** [comment]
@JSWorkspace1 Thanks for the input.
Yeah I installed the Draco 3D Data Compression Unity Package. In the Editor everything works totally fine, independend of compressed or uncompressed data.
But I'll change the Shader Settings and give it another try.

@kircher1 I guess also then from +1 such that we can have compressed data 👍

**Comment by Spoon2311** [comment]
@JSWorkspace1 Just gave it a try after following the steps in Materials and Shaders.
Sadly still didn't work an the Log messages seems to be the same, except for the part:
`"ArgumentNullException: Value cannot be null.
Parameter name: shader"`

**Comment by atteneder** [comment]
Cool, you figured it out! Neither DracoUnity nor KtxUnity includes binaries for UWP ARM64 atm....that's the problem. I'll look if those are easy to build.

Regarding missing shaders:
It should work if you always include shaders starting with `glTF...`. To do so, add them to the list "Always Included Shaders" under *Project Settings* -> *Graphics* (The build size/time will be bigger though).

**Comment by atteneder** [comment]
I'll try to provide native libs for HoloLens soon. I'd appreciate if you could help testing. You'd have to install a test version of DracoUnity from GIT URL (I'll provide).

Might have to make some C/C++ changes according to the [documentation](https://docs.unity3d.com/2020.2/Documentation/Manual/windowsstore-plugins-il2cpp.html).

See <https://github.com/atteneder/KTX-Software-Unity/pull/5> for native lib progress

**Comment by atteneder** [comment]
Interesting: HoloLens 1 support would require x86 32-bit libraries...I might consider doinig those as well.

**Comment by Spoon2311** [comment]
@atteneder Thanks for the Input.
So I had 3 shaders that I was able to add, adding all 3 Unity gave me a failed built, because the `glTF/PbrMetallicRoughness`-Shader was too large. 
Using the other 3 Shaders it gave me the following error 3 times, but with a successful build:
`TLS Allocator ALLOC_TEMP_THREAD, underlying allocator ALLOC_TEMP_THREAD has unfreed allocations, size 648856
0x00007FF6B0ECD2CC (Unity) StackWalker::GetCurrentCallstack
0x00007FF6B0ED1281 (Unity) StackWalker::ShowCallstack
0x00007FF6AF593F55 (Unity) GetStacktrace
0x00007FF6B1B559FE (Unity) DebugStringToFile
0x00007FF6B1B55712 (Unity) AssertImplementation
0x00007FF6AFFB7B7D (Unity) TLSAllocator::FrameMaintenance
0x00007FF6AFF97D00 (Unity) MemoryManager::FrameMaintenance
0x00007FF6B08DC5A4 (Unity) `InitPlayerLoopCallbacks'::`2'::PostLateUpdateMemoryFrameMaintenanceRegistrator::Forward
0x00007FF6B08C5958 (Unity) ExecutePlayerLoop
0x00007FF6B08C5A2D (Unity) ExecutePlayerLoop
0x00007FF6B08CAF5C (Unity) PlayerLoop
0x00007FF6AEC4390C (Unity) PlayerLoopController::UpdateScene
0x00007FF6AEC418A8 (Unity) Application::TickTimer
0x00007FF6AF5B99B5 (Unity) MainMessageLoop
0x00007FF6AF5C3B98 (Unity) WinMain
0x00007FF6B261CFC2 (Unity) __scrt_common_main_seh
0x00007FF9C5917034 (KERNEL32) BaseThreadInitThunk
0x00007FF9C5D3CEC1 (ntdll) RtlUserThreadStart
`

I anyways tried to deploy it to HL2 and it didn't start.

When only uploading the `glTF/Unlit`-Shader the app builds fine, but when deployed still the same errors as in to Logs above appear.

Everything I tested with the uncompressed file.

**Comment by atteneder** [comment]
The error message indicates a Unity Bug. At least I cannot make anything out of it. Feel free to report it to Unity.

Regarding shaders I can't do more than point you to [Materials and Shader Variants](https://github.com/atteneder/glTFast#materials-and-shader-variants) in the documentation. It'll make sure the exact shaders (variants) you need are present and the build size stays low enough.

I hope there's no HoloLens specific shader bug.

**Comment by atteneder** [comment]
@Spoon2311 Please install DracoUnity from this GIT URL:

`git@github.com:atteneder/DracoUnity.git#24c171d81e404402335e56f2e95115b8706df444`

This is a pre-release of 1.4.0 that shoud work with HoloLens. Plese test draco compressed glTFs with it.

Thanks!

**Comment by camnewnham** [comment]
Hi folks,
Just came across this - I have tested this library and DracoUnity and found working on HoloLens 2. There's a PR for it open here: https://gitlab.com/atteneder/DracoUnity/-/merge_requests/3. The notes for building the library for UWP are in the PR - I had to supress some warnings which can probably be automated but cmake is out of my area of expertise!

No changes were required on the glTFast side. I assume that the same process would build for ARM32 (as you can also build ARM32 HL2 apps) but this also has not been tested.

(I haven't done _extensive_ testing - just enough to load some basic models and assert that the DracoUnity for UWP built and ran successfully on some simple test models)

**Comment by camnewnham** [comment]
Ah - it looks like you've moved the repo back to github from gitlab @atteneder, should github.com/atteneder/DracoUnity that be considered the primary repo now?

**Comment by atteneder** [comment]
@camnewnham Thanks. Sorry for not responding on gitlab...Seems I missed the notification.

Yes, gitlab was only there to avoid the GIT LFS limit on github. Nowadays OpenUPM covers most traffic (plus I pay github).

Sorry about that confusion! I'll clear it up (and keep both up to date in the meantime)

Did the libs work for you without `-DCMAKE_SYSTEM_NAME:String=WindowsStore` and `-DCMAKE_SYSTEM_VERSION:String="10.0"` ? Just curious.

**Comment by atteneder** [comment]
@camnewnham Or in other words: I did not use those parameters (only set the arch via `-A ARM64`). Did you successfully test my native libraries or your builds?

**Comment by camnewnham** [comment]
I haven't tested them (only just came across this post now) - it could be a while before I can do so but I'll update here when I can, hopefully another can test in the mean time!

**Comment by atteneder** [comment]
@Spoon2311 Would be great if you can test!

I presume not using the WindowsStore toolchain is not a problem, since we don't use any Windows related API anyways.

**Comment by Spoon2311** [comment]
@atteneder Just tried to install the preview, sadly it didn't work.
Could it be that the link changed or that I can download it from somewhere else?

**Comment by atteneder** [comment]
> @atteneder Just tried to install the preview, sadly it didn't work.
> Could it be that the link changed or that I can download it from somewhere else?

No, it should work. Use this **exact** GIT link (notice it's Git**Hub** and not GitLab anymore):

`git@github.com:atteneder/DracoUnity.git#7c2095e1494fb10d303f1c808ecb835d5be937b1`

Alternatively click the `Clone` button and then `Download ZIP` at this site:
<https://github.com/atteneder/DracoUnity/tree/uwp_and_apple_silicon>

hth

**Comment by camnewnham** [comment]
In Unity 2020.1.16f1 I get an error adding the package using that verbatim URL:

```
Error adding package: ssh://git@github.com/atteneder/DracoUnity.git#7c2095e1494fb10d303f1c808ecb835d5be937b1
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()
```

I added the package with this URI:
`https://github.com/atteneder/DracoUnity.git#7c2095e1494fb10d303f1c808ecb835d5be937b1`

And tested with the glTFast commit: `https://github.com/atteneder/glTFast.git#9d7732462484b81002f4cf45a671db47929c5a47`

Works as expected in editor, but **does not** run on device in an ARM64 release build (HoloLens 2), with the error:
```
Autoconnected Player DllNotFoundException: Unable to load DLL 'dracodec_unity': The specified module could not be found.
```

With no other changes swapping the package url for Draco to `https://gitlab.com/camnewnham/DracoUnity.git#05d50e63aed80e5de35c428b59ab7c9878c47859` does run on device. So I guess the `-DCMAKE_SYSTEM_NAME:String=WindowsStore` and `-DCMAKE_SYSTEM_VERSION:String="10.0"` are required? */shrug*

**Comment by atteneder** [comment]
Thanks for testing!

> With no other changes swapping the package url for Draco to `https://gitlab.com/camnewnham/DracoUnity.git#05d50e63aed80e5de35c428b59ab7c9878c47859` does run on device. So I guess the `-DCMAKE_SYSTEM_NAME:String=WindowsStore` and/or `-DCMAKE_SYSTEM_VERSION:String="10.0"` are required? _/shrug_

That's reasonable to presume. I'll re-build the binaries and prepare an updated test version.

**Comment by atteneder** [comment]
Well, the build didn't succeed and I won't have access to a Windows machine until after the holidays :(

**Comment by camnewnham** [comment]
No worries - from the log it looks like the cause is the same as I experienced: `error C4146: unary minus operator applied to unsigned type, result still unsigned`

Since I was building with VS I suppressed this warning as described:
> For draco_core, draco_compression_entropy, draco_compression_bit_coders, draco_io:
> 1. Go to Project Properties > Configuration Properties > C/C++ > All Options
> 2. Set "Additional Options" to `/wd4146`

I'm not sure whether the correct behaviour is to suppress these during the build process (can this be done with cmake?) or whether a change to the source is required.

**Comment by atteneder** [comment]
Alright, I gave it another shot!

Please test [DracoUnity 1.4.0](https://github.com/atteneder/DracoUnity/releases/tag/v1.4.0) (OpenUPM package should be available soon).

It worked in an UWP x64 build, but I don't have ARM(64) hardware to verify the rest.

Let me know if it worked *fingerscrossed*

**Comment by atteneder** [comment]
And while you're on it, I'd be happy to get feedback if [KtxUnity 1.0.0-preview](https://github.com/atteneder/KtxUnity/releases/tag/v1.0.0-preview) works on HoloLens2 as well.

Merci!

**Comment by atteneder** [comment]
I got confirmation that both of those packages are working on UWP ARM and ARM64 now!

**Comment by camnewnham** [comment]
@atteneder great! I can also confirm that 1.4 (Draco) works on ARM64 / HoloLens 2. 

Cheers
