### ISSUE TITLE
Extension EXT_mesh_gpu_instancing

### ISSUE THREAD

**Issue by atteneder** [atteneder/glTFast#107]
Add support for the vendor extension [EXT_mesh_gpu_instancing](https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Vendor/EXT_mesh_gpu_instancing)

**Comment by anupamdas2012** [comment]
this is AWSOME. so you are saying meshes "instanced" via gltfpack for example will work now? I must try this!

**Comment by anupamdas2012** [comment]
Hi, i tried to load a glb file with instancing support and im getting an error "Required glTF extension EXT_mesh_gpu_instancing is not supported!" . I downloaded the package "Install-com.atteneder.gltfast-2.2.0.unitypackage". Is there another repo with a more up-to-date package?

**Comment by atteneder** [comment]
Hi,

Thanks for your feedback. Unfortunately this is not supported at the moment.

Feel free to provide a sample glTF file for testing and stay subscribed to this issue to get notified once this gets supported.

**Comment by anupamdas2012** [comment]
sure, here is some stuff which im sure you are aware of. Ive been using gltfpack which supports instanced geometry. The uninstanced gltf/glb file is processed and then via EXT_Mesh_gpu_instancing, a new instanced glb file is generated. Ive been using bablyonJS and works great with that. Much faster than the original mesh and its great for CAD data where there are lots of instances. Now to get this functionality working in unity! 

For instanced sample meshes look at "instancing.zip" on this thread : https://github.com/KhronosGroup/glTF/pull/1691. Ive been testing this with the ice-stadium model. If you look at the thread above that you can see the link to the original unprocessed mesh as well.
and again.. this all uses gltfpack https://github.com/zeux/meshoptimizer/pull/142

**Comment by anupamdas2012** [comment]
curious, has there been any progress made on this?  there seems to be a lot of movement on this on other platforms.

**Comment by atteneder** [comment]
Hi @anupamdas2012,

Thanks for your curiosity and offer to support.

No, `EXT_mesh_gpu_instancing` support is not being worked on thus far.

Could you elaborate what you mean with "a lot of movement on this other platforms" ? Especially if you could point out performance numbers gained, I might re-evaluate the priority of this topic.

Thanks!

**Comment by anupamdas2012** [comment]
Hi, sure I can point you to some information. Im not sure about specific statistics such as MS gained but you can try out some sample models using the BabylonJS gltf viewer using models with. vs without instancing. As you are probably aware instancing will greatly reduce draw-calls. This is especially useful for models with many repeated elements such as models coming from CAD software. 

1)------
First i'll invite you to try some models with and without instancing.
check this out first. loads this " Ice-Stadium" model in about one second and framerate is much better than the original un-instanced  model.

https://wallabyway.github.io/gltf-AEC-fast/
This is done using Zeux compression (gltfpack: https://www.npmjs.com/package/gltfpack)  and three.js R108 loader. 
this uses the -mi option in gltf pack to enable mesh instancing.

2)---------
I realize there are ways to do GPU instancing in unity without using this gltf extension. However it would be great to support the same web-standard in unity. Not to mention EXT_mesh_gpu_instancing can greatly reduce file size and transit time.

So...in summery, if we could support the mesh instancing extension directly within unity, we could utilize the same pipeline as what is used on web platforms (via threejs/bablyjs ..etc)


3)----- im terms of perf numbers, im unable to provide you that at the moment but honestly its better if you try it yourself. 

the original un-instanced "ice-stadium" gltf and glb files are here. You can use this as a base for testing and performance comparison. 
https://drive.google.com/file/d/1u4-2KH7eoyx2fcaWThPzY1KNcZbjhFhu/view

1. install gltfpack via npm
2. download original ice stadium model above
3. use command line to optimize model using instancing (use the -mi parameter)
4. you can drag and drop the orignal gltf vs optimized gltf model into the babylonjs GLTF sandbox just for some quick perf comparisons (https://sandbox.babylonjs.com/)

Let me know if you need further clarification or assistance. Glad to help!

**Comment by atteneder** [comment]
@anupamdas2012 ,

That's great! I'll do tests in the next days.

Thanks and happy 2021!

**Comment by anupamdas2012** [comment]
Hi Again! I see you added this to the ToDo. Super cool... does this mean you will be working on this at some point soonish? If not I was going to perhaps open the hood and give it a shot myself but if you are working on it I'd be happy to help you test/debug..etc.

**Comment by anupamdas2012** [comment]
Revisiting this topic. Any progress/interest in furthering this effort?

**Comment by atteneder** [comment]
Hi,

sorry to keep you waiting. It is high on my list, but I'm quite busy atm. I've read the extension spec and I'm confident it's quick to implement. I'll start next week.

**Comment by anupamdas2012** [comment]
No worries, the support you have provided already to this project is
amazing. I look forward to next steps. Thanks!

**Comment by anupamdas2012** [comment]
@atteneder <https://github.com/atteneder> DUDE!! you rock!! thanks for
turning this around so fast. I can't wait to test this. If you have a
patrion or something please let me know. Happy to support your efforts. By
far this is the best GLTF library for unity.

**Comment by atteneder** [comment]
> @atteneder <https://github.com/atteneder> DUDE!! you rock!! thanks for turning this around so fast. I can't wait to test this. If you have a patrion or something please let me know. Happy to support your efforts. By far this is the best GLTF library for unity.

Thanks for the kind words ❤️ Much appreciated!
Feel free to support me by contributing (like reporting issues for example) and spreading the word.
Cheers!
