### ISSUE TITLE
Glb loading progress bar

### ISSUE THREAD

**Issue by waseemkhan1989** [atteneder/glTFast#109]
Hi,

Its a little bit urgent so plz help @atteneder , I would highly appreciate. For downloading from remote server to local location, I used UWR.downloadProgress to track the download progress. I am only adding the component of `GltfAsset` in my application to load a file from local location into my scene as described in `Readme.` I am assuming that the downloading from remote server to local location only takes 20% of the total time(downloading + importing from local location into scene).

Now I would like to track the progress of importing a model into scene from local location on Android. I know that GLTFast calls UWR in `DefaultDownloadProvider` to load a file and there is also a separate call of UWR for texture. I would like to use  `UWR.downloadProgress` for GLTfast too. But I do not know how to do that. 

I would like to control the whole functionality of progress bar within my main source file of application and the progress bar would be tracking both the downloading and importing of model into scene at runtime on a scale of 1-100%. 

Please guide me in a little bit detail how can I achieve this with GLTFast?  

Best,
Waseem

**Comment by atteneder** [comment]
Thanks for the input, good suggestion! (loosely relates to #3)

Making a good progress property is not trivial though. You'd have to consider:

- Main glTF(-binary) Download
- JSON parsing
- Buffer Downloads
- Buffer View imports
- Textures
  - Downloads
  - Decode/Transcode
  - GPU upload
- Instantiation (probably best as a separate progress)

Calculating a good progress involves making predictions based on statistics from profiling.

Updating progress during loading (for example by considering actual download speed) may lead to progress jumping back/forth.

I'll definitely put it on the feature list, but no timeline for now.

**Comment by waseemkhan1989** [comment]
Thanks for your prompt reply. Due to my very little experience in C#, I would like to have some more details to accomplish this enhancement as I can't wait and have to accomplish this task today.

 **Main glTF(-binary) Download:** Are you here referring to the UWR call in `DefaultDownloadProvider` script in the range of lines (45-48) i.e.

  `        protected virtual void Init(Uri url) {
            request = UnityWebRequest.Get(url);
            asynOperation = request.SendWebRequest();
        }
`
I can use here UWR.downloadProgress and through profiling, lets say if it takes 40% of the total time then I can add this time to the previous calculated time(time taken to download from server).

The problem that I am facing is, gltFast files are in package folder and these files are decompiled by the compiler. How can I access UWR object in my main application?  

In another case, The progress bar in my scene is attached to a gameobject within my application. This progress bar is Unity Engine UI image. How can I access this in DefaultDownloadProvider? I am just stuck on how can I access this class in my application to track down the downloading.

**JSON parsing and Buffer Downloads:** I think, it is implemented in `GLTFast.cs` source file in `void ParseJsonAndLoadBuffers( string json, string baseUri )` method. Right?

And what about the **texture and viewpoints**? Where exactly I can find their implementations?

I would highly appreciate your guidance in this regard.

Best,
Waseem Khan

**Comment by atteneder** [comment]
@waseemkhan1989 I'm not sure I can give you all tools required to finish this, but I'll give you some starting points:

If you download glTFast (either via Clone -> Download ZIP or cloning the repository), you can add it to your project via local path in the package manager (any pre-installed glTFast version gets replaced/override). You then can edit and develop glTFast. If you plan to make pull requests (meaning make your changes public), I recommend cloning the git repository.

Hooking up UI:
A clean way (and the only way I'd allow in a PR) is having glTFast expose the progress in a clean interface that keeps UI code and glTF loading code separate. It may be an event or similar.

hth

**Comment by waseemkhan1989** [comment]
Hi,
Thanks for your reply. I think, if I download GLTFast and put it in Assets folder then it will also work and may be I can access these classes like `AwaitableDownload`(where you call UWR) in my main application.

You did not confirm/tell the location of Main glTF(-binary) Download, JSON parsing, Buffer Downloads, Buffer View imports, Textures( Downloads, Decode/Transcode, GPU upload) and instantiation in the GLTFast. If you could confirm/tell then it will be a great help.

**Comment by atteneder** [comment]
> I think, if I download GLTFast and put it in Assets folder then it will also work and may be I can access these classes like `AwaitableDownload`(where you call UWR) in my main application.

Why not as suggested? You'll still be able to access ALL scripts (look under `Packages` in the project view) and won't have conflicts with the OpenUPM package.

**Comment by waseemkhan1989** [comment]
> > I think, if I download GLTFast and put it in Assets folder then it will also work and may be I can access these classes like `AwaitableDownload`(where you call UWR) in my main application.
> 
> Why not as suggested? You'll still be able to access ALL scripts (look under `Packages` in the project view) and won't have conflicts with the OpenUPM package.

Ok sure, I just mentioned it for my own understanding. Thanks for the quick feedback. And what about the other part of the question?

**Comment by atteneder** [comment]
Alright. Trust me, it works like a charm :)

Regarding the details: No offence, but I'd like you to investigate on your own first. If you cannot make anything out of it, chances are it won't make a difference if I direct you. Thanks for understanding.

**Comment by atteneder** [comment]
Closing in favor of #3
