### ISSUE TITLE
Extension KHR_materials_variants

### ISSUE THREAD

**Issue by atteneder** [atteneder/glTFast#112]
Add support for extension [KHR_materials_variants](https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Khronos/KHR_materials_variants)

**Comment by bojankostic81** [comment]
Any info on this extension?

**Comment by atteneder** [comment]
Next release will have a first implementation for import.

**Comment by atteneder** [comment]
Check out [glTFast 6.7.1](https://docs.unity3d.com/Packages/com.unity.cloud.gltfast@6.7/manual/index.html) for material variants import support!
