### ISSUE TITLE
Plugins: Couldn't open Draco

### ISSUE THREAD

**Issue by Vaxela** [atteneder/glTFast#113]
Hi I try to install GLTF fast on unity 2018.4.9f1 

The first error : 
Assembly has reference to non-existent assembly 'Ktx' (Packages/com.atteneder.gltfast/Runtime/Scripts/glTFast.asmdef)
When I click on it , unity seems to fix it 

But I have this issue 

Plugins: Couldn't open /Users/Vaxela/Documents/syslorprojects/unity/ar.implantation/Library/PackageCache/com.atteneder.draco@00d28a7cbf4b016d0b017a25935b8c59b749ffad/Runtime/Plugins/x86_64/dracodec_unity.bundle/Contents/MacOS/dracodec_unity, error: dlopen(/Users/Vaxela/Documents/syslorprojects/unity/ar.implantation/Library/PackageCache/com.atteneder.draco@00d28a7cbf4b016d0b017a25935b8c59b749ffad/Runtime/Plugins/x86_64/dracodec_unity.bundle/Contents/MacOS/dracodec_unity, 2): no suitable image found.  Did find:
	/Users/Vaxela/Documents/syslorprojects/unity/ar.implantation/Library/PackageCache/com.atteneder.draco@00d28a7cbf4b016d0b017a25935b8c59b749ffad/Runtime/Plugins/x86_64/dracodec_unity.bundle/Contents/MacOS/dracodec_unity: file too short
	/Users/Vaxela/Documents/syslorprojects/unity/ar.implantation/Library/PackageCache/com.atteneder.draco@00d28a7cbf4b016d0b017a25935b8c59b749ffad/Runtime/Plugins/x86_64/dracodec_unity.bundle/Contents/MacOS/dracodec_unity: file too short

Do you have so information ?

Bye 👯

**Comment by atteneder** [comment]
Thanks for the report!

First issue: I've renamed that package, so I might have to fix this.

Second issue: How did you install glTFast? If you used a GIT URL, please make sure you have GIT LFS working.

I recommend reading the [Installing](https://github.com/atteneder/glTFast#installing) section of the readme and use the package installer from there.

**Comment by Vaxela** [comment]
Via the gitUrl

**Comment by atteneder** [comment]
You can check whether the git clone worked (used LFS) by navigating to the path `Packages/com.atteneder.draco/Runtime/Plugins/x86_64/dracodec_unity.bundle/Contents/MacOS/dracodec_unity` in the Project view.
Right click it and choose `Reveal in Finder`. How big is the file? It should be ~900kB. If it is just 130 Bytes, you didn't have GIT LFS installed.

**Comment by Vaxela** [comment]
Plugins: Couldn't open /Users/Vaxela/Documents/syslorprojects/unity/2020/ar.implantation/Library/PackageCache/com.atteneder.draco@00d28a7cbf/Runtime/Plugins/x86_64/dracodec_unity.bundle/Contents/MacOS/dracodec_unity, error: dlopen(/Users/Vaxela/Documents/syslorprojects/unity/2020/ar.implantation/Library/PackageCache/com.atteneder.draco@00d28a7cbf/Runtime/Plugins/x86_64/dracodec_unity.bundle/Contents/MacOS/dracodec_unity, 2): no suitable image found.  Did find:
	/Users/Vaxela/Documents/syslorprojects/unity/2020/ar.implantation/Library/PackageCache/com.atteneder.draco@00d28a7cbf/Runtime/Plugins/x86_64/dracodec_unity.bundle/Contents/MacOS/dracodec_unity: file too short
	/Users/Vaxela/Documents/syslorprojects/unity/2020/ar.implantation/Library/PackageCache/com.atteneder.draco@00d28a7cbf/Runtime/Plugins/x86_64/dracodec_unity.bundle/Contents/MacOS/dracodec_unity: stat() failed with errno=35


Yes my file 133 bytes

Same issues in 2020 with git url ,

**Comment by Vaxela** [comment]
I try to install Git LFS and retry

**Comment by atteneder** [comment]
I don't understand why you didn't try that in first place after I recommended it to you. Again:

> I recommend reading the [Installing](https://github.com/atteneder/glTFast#installing) section of the readme and use the package installer from there.

To quote the [Unity documentation on GIT packages](https://docs.unity3d.com/2020.1/Documentation/Manual/upm-git.html):

> If the repository tracks files with Git LFS, make sure the Git LFS client is also installed on your machine. If it is not installed, the Package Manager can’t retrieve the files stored on the LFS server and instead checks out the LFS pointer files without any error or warning messages.

**Comment by Vaxela** [comment]
I was working on 2020 when I was speaking with you, I'm trying to install Git LFS and reinstall your git

**Comment by Vaxela** [comment]
Ok so i've reinstall it with the package manager. And no error that a good sign but 

<img width="1312" alt="Capture d’écran 2020-12-10 à 10 29 46" src="https://user-images.githubusercontent.com/32814462/101754110-a96dfc00-3ad3-11eb-86be-cdd15431bab1.png">

Ive just have a little problem model are like in 2D ?
Do you know why  ?

**Comment by atteneder** [comment]
Do you have a non-uniform scale on your GameObject?

**Comment by Vaxela** [comment]
That why, thanks you very much can't wait to use your solution in your application.
At the moment we where using KhronosGroup/UnityGLTF, but its outdated 
Just a last question can we retrieve easily the GLTF extras informations from a mesh ?

**Comment by atteneder** [comment]
> That why, thanks you very much can't wait to use your solution in your application.

Thanks, much appreciated. I'm always happy when people give the project a star!

> At the moment we where using KhronosGroup/UnityGLTF, but its outdated

There's already a discussion how to procede with this situation. I'll keep you posted.

> Just a last question can we retrieve easily the GLTF extras informations from a mesh ?

I presume you mean the application specific data in the `extras` JSON fields, right?
I have to test this first. The JSON parser I'm using is somewhat limited, so it might not work on arbitrary data. Feel free to provide me with sample files.

> i will read all the doc to find the information !

Great idea, but there's no doc about extras or meta data yet.

**Comment by Vaxela** [comment]
Yeah we want a better solution to load our GLTF fast, we work on big GLTF model for Augmented Reality , and sometime the model can take 5 minutes to load on a phone :/ so we wanna use your solution to make the loading faster.
And we wanna recover the extras data from the mesh

Yes data from extras json fields, we make a little improvement to Kronos to get the data before they clean it, but for me its not efficient, it could be interesting to create like a class with the mesh and the extra data from the mesh 
I will send you a GLTF I ask to my team

**Comment by atteneder** [comment]
Sounds good. Expect more speed improvements over the next months.
