### ISSUE TITLE
Hide glTF model while loaded

### ISSUE THREAD

**Issue by dudziakl** [atteneder/glTFast#114]
Hi @atteneder, many thanks for this great plugin!

I would like to know if there is a way to hide the the model while it is loaded? I would like to load bigger model in the background and then show part of it without displaying full model. When I disable the game object that have script GltfAsset.cs then the coroutine that is loading glTF model is not working. I cannot disable the Renderer because this game object is empty and has no mesh renderers yet. Is there any smarter way to hide it instead of setting scale to zero?

**Comment by atteneder** [comment]
Hi @dudziakl,

There's no straightforward way for your exact use case, but the instantiation can be customized to your way.

1. Create a custom implementation of `IInstantiator` ( inspect `GameObjectInstantiator`, as it's the default implementation). You can disable all renderers in there you don't require or don't instantiate them at all.
2. Create a custom version/derive from `GltfAsset` and pass your custom instantiator like so:

```csharp
        protected override void OnLoadComplete(bool success) {
            if(success) {
                // Auto-Instantiate
                var myCustomInstantiator = new CustomInstantiator(transform, custom filters, ...);
                gLTFastInstance.InstantiateGltf(myCustomInstantiator);
            }
            base.OnLoadComplete(success);
        }
```

With that being said: It's always more performant to strip the glTFs of unrequired assets at authoring time, if possible.

hth and thanks,
Andi

**Comment by dudziakl** [comment]
Many thanks for the instruction Andi! It solved my problem.

**Comment by atteneder** [comment]
Great to hear!

Let me know if you have suggestions regarding improving the interface.

**Comment by AhmadMansy** [comment]
i don't find onLoadComplete method anywhere in the newer version . is it removed or replaced

**Comment by AhmadMansy** [comment]
@atteneder Thanks
