### ISSUE TITLE
JobTempAlloc has allocations that are more than X frames old

### ISSUE THREAD

**Issue by dudziakl** [atteneder/glTFast#115]
@atteneder once again I need your help :)
My model is loading fine and everything looks good but I have few warnings for each mesh inside of one glTF model. What I'm doing wrong? Should I ignore it?

> JobTempAlloc has allocations that are more than 4 frames old - this is not allowed and likely a leak
>
>Internal: deleting an allocation that is older than its permitted lifetime of 4 frames (age = 15)
Unity.Collections.LowLevel.Unsafe.UnsafeUtility:Free(Void*, Allocator)
Unity.Collections.NativeArray`1:Deallocate()
Unity.Collections.NativeArray`1:Dispose()
GLTFast.VertexBufferConfig`1:Dispose() (at 
Library/PackageCache/com.atteneder.gltfast@2.2.0/Runtime/Scripts/VertexBufferConfig.cs:251)
GLTFast.GLTFast:DisposeVolatileData() (at Library/PackageCache/com.atteneder.gltfast@2.2.0/Runtime/Scripts/GltFast.cs:930)
GLTFast.<LoadRoutine>d__49:MoveNext() (at Library/PackageCache/com.atteneder.gltfast@2.2.0/Runtime/Scripts/GltFast.cs:222)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

**Comment by atteneder** [comment]
I'll have to make temporary buffer allocation safer by allocating them permanent. This might be a bit slower, but will resolve those warnings (and potential memory leaks/corruption).
