### ISSUE TITLE
"Invalid matrix on node 2" error when importing working file

### ISSUE THREAD

**Issue by Bersaelor** [atteneder/glTFast#116]
Dear @atteneder , thank you for your work on this importer tool.

I've also been looking into [The khronos framework](https://github.com/KhronosGroup/UnityGLTF) but yours looks more promising.

Many of my models successfully import, yet with one model I get the following error:

```
Invalid matrix on node 2
UnityEngine.Debug:LogErrorFormat (string,object[])
GLTFast.GLTFast:CreateGameObjects (GLTFast.Schema.Root,GLTFast.IInstantiator) (at Library/PackageCache/com.atteneder.gltfast@2.2.0/Runtime/Scripts/GltFast.cs:1007)
GLTFast.GLTFast:InstantiateGltf (GLTFast.IInstantiator) (at Library/PackageCache/com.atteneder.gltfast@2.2.0/Runtime/Scripts/GltFast.cs:604)
GLTFast.GLTFast:InstantiateGltf (UnityEngine.Transform) (at Library/PackageCache/com.atteneder.gltfast@2.2.0/Runtime/Scripts/GltFast.cs:599)
GLTFast.GltfAsset:OnLoadComplete (bool) (at Library/PackageCache/com.atteneder.gltfast@2.2.0/Runtime/Scripts/GltfAsset.cs:33)
GLTFast.GLTFast:OnLoadComplete (bool) (at Library/PackageCache/com.atteneder.gltfast@2.2.0/Runtime/Scripts/GltFast.cs:266)
GLTFast.GLTFast/<LoadRoutine>d__49:MoveNext () (at Library/PackageCache/com.atteneder.gltfast@2.2.0/Runtime/Scripts/GltFast.cs:224)
UnityEngine.SetupCoroutine:InvokeMoveNext (System.Collections.IEnumerator,intptr) (at /Users/bokken/buildslave/unity/build/Runtime/Export/Scripting/Coroutines.cs:17)
```

Now the object imports fine into other gltf programs, so the issue must be non-fatal, would it be possible to make gltFast less strict when importing, so that even if some part of a transform matrix may be invalid, the other parts are imported fine?
I.e. just instantiate the parts that do work, instead of aborting the whole import?

Here's the model in question (1.6MB), we bought it from some 3D stock database, so please don't use it commercially without getting a license (for anyone seeing it here).
[aviator-1606853253750.glb.zip](https://github.com/atteneder/glTFast/files/5632127/aviator-1606853253750.glb.zip)

**Comment by atteneder** [comment]
Please pull the main branch and give it a spin!

Feel free to reach out to me if you need sensitive data tested. I suggest to not upload it here and remove it.

**Comment by Bersaelor** [comment]
Thanks @atteneder , you are quick indeed!

**Comment by atteneder** [comment]
@Bersaelor No problemo :)
Feel free to thank me by starring the project.
Thanks!
