### ISSUE TITLE
Back-face Culling problem

### ISSUE THREAD

**Issue by waseemkhan1989** [atteneder/glTFast#120]
Hi,

I am facing a problem of back face culling in one of my models. The picture is attached for the reference.

![image](https://user-images.githubusercontent.com/25552247/102628279-b7fa8a00-4149-11eb-8ecc-f36d18e8516a.png)

Any solution @atteneder ?

**Comment by atteneder** [comment]
The glTF model would be helpful

Have you tried loading it in another glTF viewer?

What glTFast version?

**Comment by atteneder** [comment]
I assume this was a content error. Feel free to re-open if it was not.

**Comment by waseemkhan1989** [comment]
Thanks for your response. I checked this model. The problem was in the model.
