### ISSUE TITLE
Building project with glTFast+URP will fail (Unity 2019.4.13f1)

### ISSUE THREAD

**Issue by msub2** [atteneder/glTFast#121]
I discovered while doing some experimentation in Unity 2019.4.13f1 that building a project for WebGL using URP and glTFast will fail with the following errors:

`Library\PackageCache\com.atteneder.gltfast@2.5.0\Runtime\Scripts\MaterialGenerator.cs(48,42): error CS0161: 'MaterialGenerator.GetDefaultMaterialGenerator()': not all code paths return a value`

and

`Library\PackageCache\com.atteneder.gltfast@2.5.0\Runtime\Scripts\StandardShaderHelper.cs(136,37): error CS0103: The name 'KW_ALPHABLEND_ON' does not exist in the current context`

**Comment by atteneder** [comment]
Thanks for reporting!
This was fixed in 2.5.1
