### ISSUE TITLE
Setting model axes during import

### ISSUE THREAD

**Issue by dudziakl** [atteneder/glTFast#122]
Hi @atteneder, I would like to know if it is possible to change model axes during import? Can I use custom Instantiator for that? 
In my very basic scene I have just GltfAsset script and my model is pointing wrong direction on the Z axis. I would like to do the mesh manipulation to avoid game object rotation.  

![image](https://user-images.githubusercontent.com/12583808/103179159-5cd34080-4889-11eb-9fba-accb29d481ed.png)

Here is the link to sample model 
https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/BoomBoxWithAxes/glTF

**Comment by atteneder** [comment]
Hi @dudziakl,

The coordinate systems of glTF and Unity are not identical and thus the difference in the arrows from the boombox scene and Unity's axis gizmo is correct.

Changing glTFast to another coordinate system (efficiently) is a bit more complicated than just changing the GameObject transforms. Also the vertex data has to be interpreted differently.

What are you trying to accomplish?

**Comment by dudziakl** [comment]
In short words: I have lots of generated gltf files that were created for other importer. During the development we found some limitations and needs to replace this importer with another. After short evaluation I'm very happy with gltFast plugin but I just realized that all my models are now rotated to wrong axis after import. I would like to avoid to re-generation of all gltf files, as it is difficult and takes lots time. I would like to not touch game object transform as well, as it will be hard to remember which models needs this axis rotation fix and which don't. So my question was if it would be possible to change the axis during mesh building or it is not possible? 

I tried yesterday few alternative plugins for Unity and saw that some of them are adjusting models to X+ axis and others to Z+ axis. Is there any standard for this?

**Comment by atteneder** [comment]
Indeed the coordinate system of glTF is specified:

https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#coordinate-system-and-units

Hacking glTFast (or any other importer-exporter) to support non-standard coordinate systems is not something I'd recommend. Instead re-export the models correctly according to the standard.

That being said, it might be possible to do so, but you'd have to change the GameObject transforms and also the vertex data (if you want to avoid negative scaling values).

Hth

**Comment by dudziakl** [comment]
Thanks for the link. I didn't know about it. 
It says that the front of the model  should be +Z axis, so.. why your importer is setting this model -Z as you can see on my picture?

**Comment by atteneder** [comment]
> It says that the front of the model should be +Z axis, so.. why your importer is setting this model -Z as you can see on my picture?

"the front should be +Z" relates to the glTF space/context (the front of the boom box indeed points towards the +Z(glTF).

I aligned the +X(glTF) axis with the +X(Unity) axis, hence the respective +Z axes oppose each other. This was a design decision. I could've also aligned the +Z axes, but then the +X axes would oppose each other.

Given the fact that cameras in Unity "look" towards +Z(Unity) I thought this makes more sense.

If you want it the other way (effectively rotating objects 180 degrees around Y), rotating the parent GameObject is the right solution. No need to change the complete loading behavior.

hth

Re-open if you feel like I've left something unanswered.
