### ISSUE TITLE
Animation support

### ISSUE THREAD

**Issue by atteneder** [atteneder/glTFast#124]
Add support for animation as specified here:

<https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#animations>

**Comment by Epiczzor** [comment]
Hey not to sound pushy, but any idea how long this could possibly take ?

**Comment by atteneder** [comment]
Thanks for your interest.

I've started a promising prototype two weeks ago (then my son was born :) )
I don't want to make promises before end of next week, but so far it looks good.
