### ISSUE TITLE
Test scripts are missing namespace

### ISSUE THREAD

**Issue by hybridherbst** [atteneder/glTFast#125]
Would be great if these would have GLTFast.Tests as namespace or so:

![image](https://user-images.githubusercontent.com/2693840/103677170-3e083480-4f82-11eb-9b48-e2aa6ec75e08.png)
![image](https://user-images.githubusercontent.com/2693840/103677228-511b0480-4f82-11eb-9933-4a28a3d6406e.png)

**Comment by atteneder** [comment]
Thanks for pointing that out!

I see an oportunity to learn: did you use some analyzer/tool to get the list above? Seems handy.
