### ISSUE TITLE
Use Unity-typical shader property names

### ISSUE THREAD

**Issue by hybridherbst** [atteneder/glTFast#126]
Unity shaders typically follow a naming convention for shader properties (e.g. "_BaseColor", "_BaseColorMap").
This helps when creating custom shaders to use for import, or when switching from a typical shader to a GLTF shader (e.g. for better control over properties when export might be supported in a future version).

I'm aware that there's multiple "standards" - not only did URP and HDRP ditch the old built-in names, they went with slightly different conventions ... choose your poison I guess, but in general properties have the format _MyPropertyName.

**Comment by atteneder** [comment]
Thanks for pointing that out. Although it was some struggle to change this, it makes totally sense.
fixed in 2.5.1
