### ISSUE TITLE
glTFast does not build for WebGL with URP

### ISSUE THREAD

**Issue by Exatex** [atteneder/glTFast#129]
When trying to build for WebGL in combination with URP, in MaterialGenerator.GetDefaultMaterialGenerator() not all code paths return a value due to a combination of pre-compiler statements. Can be fixed for that specific case by ignoring all other branches and assuming that a pipeline asset is set:

```
public static IMaterialGenerator GetDefaultMaterialGenerator() {
     defaultMaterialGenerator = new UniveralRPMaterialGenerator((UniversalRenderPipelineAsset) GraphicsSettings.renderPipelineAsset);
     return defaultMaterialGenerator;
}
```

**Comment by atteneder** [comment]
Thanks for reporting!
Has been fixed in 2.5.1
