### ISSUE TITLE
WebGL: ArgumentNullException: Value cannot be null. 

### ISSUE THREAD

**Issue by NickPeelman** [atteneder/glTFast#130]
When trying to load a model from my server on my WebGL build I get the following error:

![image](https://user-images.githubusercontent.com/15141922/105249542-8fb2e080-5b78-11eb-8f12-5c7f891750ae.png)

With full error log I get:

```
Unity.Collections.LowLevel.Unsafe.UnsafeUtility.MemCpy (System.Void* destination, System.Void* source, System.Int64 size) (at <00000000000000000000000000000000>:0)
DracoMeshLoader.CreateMesh (System.IntPtr dracoMesh, System.Boolean& hasNormals, System.Boolean& hasTexcoords) (at <00000000000000000000000000000000>:0)
GLTFast.PrimitiveDracoCreateContext.CreatePrimitive () (at <00000000000000000000000000000000>:0)
GLTFast.GLTFast+<Prepare>d__71.MoveNext () (at <00000000000000000000000000000000>:0)
GLTFast.GLTFast+<LoadContent>d__50.MoveNext () (at <00000000000000000000000000000000>:0)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <00000000000000000000000000000000>:0)
```

I'm using unity 2020.2, tested with 2020.1. Works perfectly in editor.

The code I used:

		var gltfAsset = new GameObject("GltfAsset").AddComponent<GLTFast.GltfAsset>();
		gltfAsset.url = ${connectionInfo.hostname}api/file/lod/{projectId}/{lodToLoad.OrderOfLoading}.glb";
		
So nothing too special I suppose. When I tried the WebGL demo with my url it loaded just fine. 

I'm on:
![image](https://user-images.githubusercontent.com/15141922/105250021-529b1e00-5b79-11eb-950c-cc82259e4cf9.png)

**Comment by NickPeelman** [comment]
Tested with Unity 2019 LTS and still having this error, very weird.

**Comment by NickPeelman** [comment]
Tested with Duck:
https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/Duck/glTF-Binary/Duck.glb

Works.

My Model is a file of 30MB compressed. I'm going to try to set the initial memory of the WebGL Player to 1GB.

**Comment by atteneder** [comment]
Hi Nick,

Thanks for the report. Any chance you can provide the model (or a similar one that crashes as well) ?

**Comment by NickPeelman** [comment]
You can try the following files:

https://www.novicius.be/uploads/DCA_Office.glb 
(18MB) includes textures

https://www.novicius.be/uploads/Handelsbeurs.glb  
(24MB) no textures, just a big junk of mesh ;).

Thanks !

**Comment by NickPeelman** [comment]
Some more info about my WebGL player:

![image](https://user-images.githubusercontent.com/15141922/105373680-3a71e000-5c07-11eb-92ce-f0e31c871180.png)
![image](https://user-images.githubusercontent.com/15141922/105373720-452c7500-5c07-11eb-9ba1-d36cd02c615e.png)
![image](https://user-images.githubusercontent.com/15141922/105373756-4bbaec80-5c07-11eb-8ba4-c9901014792d.png)

**Comment by NickPeelman** [comment]
My crusade is coming to an end!

Confirmed working with:
![image](https://user-images.githubusercontent.com/15141922/105462346-c7ac4780-5c8e-11eb-81af-e8d54c7f90be.png)

I switched from many versions of GLTFast, but it seems like the issue was with the Draco plugin. I downgraded to 1.2 which seems to have done the job!

My editor crashes on 2020.2 regardless of GLTFast or Draco version. So if anyone is having the same issues, use:

Unity 2020.1.13f1
GLTFast 1.0.0
Draco 1.2

I assume there won't be any issue with the latest GLTFast version, but I'm uploading a build with 1.0 for now and will test latest version later.

**Comment by atteneder** [comment]
Awesome, thanks!
I will look to fix this in recent versions.

**Comment by atteneder** [comment]
The good news is, it is working locally (development versions of both glTFast and DracoUnity). I'll test it again upon next release and close it here if it works (so you get notified, if subscribed).

<img width="604" alt="image" src="https://user-images.githubusercontent.com/2593014/105505689-8d13d080-5cc9-11eb-932b-91fca873bb75.png">

Kind regards

**Comment by NickPeelman** [comment]
I can confirm this is not occuring again with the latest versions of GLTFast and Drako.

One hell of a guy. Amazing work!

👏👏👏
