### ISSUE TITLE
Bug when trying to load 2 GLB in WebGL at the same time

### ISSUE THREAD

**Issue by De-Panther** [atteneder/glTFast#131]
I try to start loading to GLB files at the same time on WebGL:
https://cdn.jsdelivr.net/npm/@webxr-input-profiles/assets/dist/profiles/oculus-touch/right.glb
https://cdn.jsdelivr.net/npm/@webxr-input-profiles/assets/dist/profiles/oculus-touch/left.glb

The first one(`right.glb`) loads, the second one(`left.glb`) fails but without returning `success=false`.
It just stops loading at `gltfRoot = await Task.Run( () => ParseJson(json) );`
https://github.com/atteneder/glTFast/blob/cc3c7a38f37f03e0337419ea99d7ee9a2e5bdd0a/Runtime/Scripts/GltFast.cs#L292

Waiting for one model to load and then loading the other, does work.

I did notice that while the second model stuck, the first model is in the process of `await Prepare()`
https://github.com/atteneder/glTFast/blob/cc3c7a38f37f03e0337419ea99d7ee9a2e5bdd0a/Runtime/Scripts/GltFast.cs#L255

Unity 2019.4.7f1

Also, the package works much faster now and with less stuttering while loading. Thanks :)

**Comment by De-Panther** [comment]
It seems that `Task.Yield()` works well on WebGL, but `Task.Run()` has issues.

I created an `IDeferAgent` that returns false for `ShouldDefer(float duration)` and call `Task.Yield` in `BreakPoint()` and `BreakPoint(float duration)`,
and now I do manage to load two models at the same time.

**Comment by atteneder** [comment]
Thanks for the report, and detecting the issue...you pinned it down already! :)

Looks like `Task.Run` [does not work](https://forum.unity.com/threads/async-await-and-webgl-builds.472994/) in WebGL yet (more on [threading in WebGL](https://forum.unity.com/threads/multithreading-and-webgl.817986/)).

I'll fix it today.
