### ISSUE TITLE
What is the preferred way of loading a glb asset in WebGL? [CORS compatible]

### ISSUE THREAD

**Issue by Bersaelor** [atteneder/glTFast#133]
So far, glTFast worked great on Android, we even released our our(my) first Android app using the framework.

Now, I wanted to share some code with the WebGL target platform and am facing some issues:

The original assets come from our server, but are edited and modified before writing them to the local `Application.persistentDataPath/...`. 
I load the *.glb assets as follows:

```c#
            var success = await gltfAsset!.Load(filePath, null, deferAgent, null);
```
and that works on Android, but on WebGL, it has problems loading from the local `file://idfbs` since GltFast seems to be using `XMLHttpRequest` internally to load the file and that leads to:

```
XMLHttpRequest cannot load file:///idbfs/f1f3898c49207985a430adb811afb485/clubmaster-1607002257541.glb due to access control checks.
```

This is probably not a core GltFast issue, but more about making the in-memory filesystem the browser offers to work with CORS. Those local paths can be read and written to using `File.*` but apparently not accessed via XMLHttpRequest ( `Cross origin requests are only supported for HTTP.`).

Have other people used gltFast with WebGL, loading local idfbs files, or is everyone just reading the *.glbs from servers where the servers have the CORS headers?

**Comment by Bersaelor** [comment]
I mean, I could read the file into memory using File.IO, but I can't find any API in gltFast where the application can provide a memory blob/ object instead of a url to the file.

**Comment by Blocovin** [comment]
Hi,

We got same issue with CORS in WebGL, so we add this code in GltFast.cs to load byte[]

```cs
 public async Task<bool> Load(byte[] content) {
    return await LoadRoutine(content);
}

async Task<bool> LoadRoutine( byte[] content ) {
    var success = await LoadGltfBinary(content);
    if(success) await LoadContent();
    success = success && await Prepare();

    DisposeVolatileData();
    loadingError = !success;
    loadingDone = true;
    return success;
}
```

**Comment by Bersaelor** [comment]
@atteneder if this is something two of us need, maybe it would be an APi lifting into the next release?

**Comment by atteneder** [comment]
Hi @Bersaelor ,
Thanks for reaching out and congratulations on shipping your Android app! Feel free to send me a link to it (via PM if you prefer)...always interested in seeing it in production.

I agree, a simple API method to load from `byte[]` (or `NativeArray`) does make sense. I cannot promise when, but this will be added.

I'm not a web expert, so...

I presume the `persistentDataPath` on WebGL gives you access to the browser's [IDBObjectStore](https://developer.mozilla.org/en-US/docs/Web/API/IDBObjectStore). Seems like the URI you use to try to restore it does not work. glTFast uses `UnityWebRequest` under the hood, so I'd start by trying if you can store and load simple content this way.

Afaik CORS related issues should be resolved server-side by configuring who an access the assets. But I'm curious now: How do you load the content byte[] before passing it to glTFast and how does it differ to the way glTFast would load?

Last but not least:
You can override the download behavior by providing your own implementation of `IDownloadProvider`. As an example, you can use `CustomHeaderDownloadProvider` to set certain HTTP headers before requesting glTFs or their respective bin buffers or textures.

hth

**Comment by Bersaelor** [comment]
Yeah, so:

1. UnityWebRequest = XMLHttpRequest which needs CORS headers on CORS enabled browsers
2. our server sets the CORS headers on files that can be downloaded
3. files are downloaded to the browser WebGL app, edited, saved, reloaded, modified and eventually converted to glft format and saved in the browsers IDBObjectStore, all inside the WebGL app 
4. the path to the file in the IDBObjectStore is something like `file:///idbfs/f...`
5. when setting this path `gltfAsset!.Load(filePath,..` it will try to use UnityWebRequest to load it from the local `file:///idbfs/f...` but the local idbfs doesn't set CORS headers. I mean it isn't really Cross-domain as it's all inside the same browser, the problem is the `file:` protocol immideately forces CORS checks.  

> @Bersaelor : Thanks for chipping in and helping out!
Afaik CORS related issues should be resolved server-side by configuring who an access the assets. But I'm curious now: How do you load the content byte[] before passing it to glTFast and how does it differ to the way glTFast would load?

The difference seems to be that reading file from `file:///idbfs/f...` using File.IO is totally allowed, so I can read it to byte[]. The way the current GLTfast api is setup I just can't provide the bytes to GLTfast. 

> Last but not least:
You can override the download behavior by providing your own implementation of IDownloadProvider. As an example, you can use CustomHeaderDownloadProvider to set certain HTTP headers before requesting glTFs or their respective bin buffers or textures.

I think this way I could only set HTTP headers on the download-request going "out" ("out" in quotation because it's really to the local file idbfs), but the browser expects it on the "response".
Can I maybe adjust `IDownloadProvider` to use `File.OpenRead(..)` instead of UnityWebRequest?

PS: Our Android App is available here: https://play.google.com/store/apps/details?id=com.LooC.MyLooC (it's just the demo app at this point, so far customers have only bought the iOS client for their products but it looks like we'll probably sell the android one too this year).

**Comment by Blocovin** [comment]
We got same problem as @Bersaelor.
We download and save file in the IDBObjectStore from WebGL app and then pass local file url to GltFast.
We use netlify and we got this error :
`Security Error: Content located at https://test-unity-webgl.netlify.app/ cannot load data or link to file:///idbfs/9af3761ca9ebfc54ae88f4b0a0c69070/test.glb.`
Maybe UnityWebRequest can't load file from IDBObjectStore from security reason ?

```cs
public class DownloadAndLoadLocalGLB : MonoBehaviour {
    public string glbUrl;

    IEnumerator Start () {
        // Download file
        UnityWebRequest request = UnityWebRequest.Get (glbUrl);
        yield return request.SendWebRequest ();
        if (request.result == UnityWebRequest.Result.Success) {
            string fileLocalPath = $"{Application.persistentDataPath}/test.glb";
            Debug.Log ($"Save file at: {fileLocalPath}");
            System.IO.File.WriteAllBytes (fileLocalPath, request.downloadHandler.data);

            // Load file from local path => Security Error...
            UnityWebRequest localRequest = UnityWebRequest.Get (new Uri (fileLocalPath, UriKind.RelativeOrAbsolute));
            yield return localRequest.SendWebRequest ();
            if (localRequest.result == UnityWebRequest.Result.Success) {
                Debug.Log ("Success !");
            } else {
                Debug.LogError (localRequest.error);
            }
        } else {
            Debug.LogError (request.error);
        }
    }
}
```

**Comment by atteneder** [comment]
Thanks, very useful information.

glTFast loads everything via UnityWebRequest (and formerly WWW), because it provides a nice abstraction from File I/O and HTTP. In this particular case this is troublesome and there are further reasons to not use it for direct file I/O in the future.

So my mid-term solution is to write a new loading abstraction that uses file I/O for local files and supports streaming.

As a short-term solution, loading a byte[] seems to be the most reasonable thing.

@Bersaelor : Yes, you could make an `IDownloadProvider` that loads via `File.IO`. Would love to get a PR, as this could be useful for many.

@Blocovin : Thanks for the script. I can confirm your observation. UnityWebRequest does indeed not load IDBObjectStore.

**Comment by Bersaelor** [comment]
Thanks for the tips @atteneder , I have something running that sort of works, just one question.

First the `LocalFileProvider`:

```c#
    public class LocalFileProvider : IDownloadProvider {
        public async  Task<IDownload> Request(Uri url) {
            var req = new FileLoad(url);
            while (req.MoveNext()) {
                await Task.Yield();
            }
            return req;
        }
    }

    public class FileLoad : IDownload {

        protected FileStream fileStream;

        protected int length;
        protected int sumLoaded;
        protected byte[] bytes;
        protected string readError = null;

        public FileLoad() {}

        public FileLoad(Uri url) {
            if (url.Scheme != "file") {
                throw new ArgumentException("FileLoad can only load uris starting with file:");
            }
            Init(url);
        }

        public void Close() {
            fileStream.Close();
        }

        protected void Init(Uri url) {
            fileStream = new FileStream(url.LocalPath, FileMode.Open, FileAccess.Read, FileShare.Read, 4096, true);
            length = (int)fileStream.Length;
            sumLoaded = 0;
            bytes = new byte[length];
        }

        public object Current { get { return fileStream; } }
        public bool MoveNext() { 
            try {
                var count = fileStream.Read(bytes, sumLoaded, length - sumLoaded);
                sumLoaded += count;
                return count > 0; 
            } catch (Exception e) {
                readError = e.Message;
                throw e;
            }
        }
        
        public byte[] data => bytes;
        public string text { get { return System.Text.Encoding.UTF8.GetString(bytes); } }

        // ...
```

Now this is just a class that wraps what I would usually write as:

```c#
        try
        {
            // read until Read method returns 0
            while ((count = fileStream.Read(imageBytes, sum, length - sum)) > 0)
                sum += count;

            success = true;
        }
        finally
        {
            fileStream.Close();
        }
```

In the context of `IDownloadProvider` and `IDownload` where should I put the `fileStream.Close()` in your opinion?

The above seems to work actually, my glb's are shown, but it makes me itchy to never have called `.Close()`.

Also I guess I should maybe handle non-birary `.gltf` differently, I guess?

**Comment by Bersaelor** [comment]
Update: Had to work on some other things for a while, but now created a [minimal sample project](https://github.com/Bersaelor/UnityGltfWebGlTest) to look more into the local file loading. It works fine in the editor but has the CORS header issue.
On my 4.0Ghz iMac even the minimal example needs 151s to build the WebGL, WebGL building in Unity is really slow isn't it?
(My full project takes 10min each time, not really great for iterating on code).

**Comment by atteneder** [comment]
@Bersaelor thanks for providing the code + sample. I'll try to look at it as soon as time allows for it.

Yes, WebGL builds are slow. I prefer to do as much as possible in Editor and Standalone builds and iterate only very Web/Browser specific things in WebGL builds.
Having continuous integration / cloud build is something to think about.

regards,
andi

**Comment by Bersaelor** [comment]
I also get what @Blocovin said earlier, I mean, I don't necessarily need to read the file from the `idbfs`, since I:
• download file to idbfs
• open read stream of downloaded file
• use a CryptoStream that the readstream is piped to
• writestream outputs the result to a new file

I think, since the `idbfs` files in the browser are only in the memory anyway, I could also just pipe the result to a byte-blob and then read that `byte[] content` the way @Blocovin describes.
Using the `idbfs` would have the advantage that I could share more code with android though..

**Comment by atteneder** [comment]
I don't have experience with IndexedDB, but I thought it is persistent? (so not just in temporary memory)

But yes, both solutions are OK imho. The browser cache should also kick in if you don't use idbfs.

**Comment by Bersaelor** [comment]
So, my browser experience is limited too, but basically no persistent filestorage is available for browsers. Unity emulates a filesystem by using `idbfs`. For your unity app , anything you save under `Application.persistentDataPath` will be saved in this `idbfs` file storage and API wise it's all just paths to seamingly local files (even though they are stored in memory). The problem is accessing `file://` via a `UnityWebRequest` will trigger CORS, yeah.

**Comment by Bersaelor** [comment]
Furthermore, now that I was just reading [this article about reducing memory pressure during large web requests](https://thoughtbot.com/blog/avoiding-out-of-memory-crashes-on-mobile), I realized it should be possible to build the whole approach into gltf.
I.e. `DefaultDownloadProvider` already has this `MoveNext` approach of potentially loading incremental blocks of data. [My PR also does chunk sized reading from file](https://github.com/atteneder/glTFast/pull/146/files#diff-8fe39c3ced36fe4659a0f8bfb4ae02c1b3c5482b00b7b85ba182bc150e0a6b06R90).
Most decryption algorithms also rely on a block-cypher. It would be cool to make a version of `DefaultDownloadProvider` that handles this use case, of an encrypted gltf/glb file. Something like `EncryptedDownloadProvider`.

I can't pull all the necessary C# out of my sleeves, just now, but it should be possible to load the file chunk-wise and decrypt each chunk along the way. 
A sample code to decrypt a file would look like this:

```
    private const int blockSize; // 128/256/512;
    private const CipherMode mode = CipherMode.CBC;
    private static byte[] Key = ""; // key of size matching the blocksize
    
    public static void Decrypt(string sourceFile, string toFile, bool hasPrefix = true)
    {
        // Decrypt the source file and write it to the destination file.
        using (var sourceStream = File.OpenRead(sourceFile))
        using (var destinationStream = File.Create(toFile))
        using (var provider = new RijndaelManaged())
        {
            provider.BlockSize = blockSize;
            provider.Mode = mode;
            var IV = new byte[provider.IV.Length];
            if (hasPrefix) sourceStream.Read(IV, 0, IV.Length);
            using (var cryptoTransform = provider.CreateDecryptor(Key, IV))
            using (var cryptoStream = new CryptoStream(sourceStream, cryptoTransform, CryptoStreamMode.Read))
            {
                cryptoStream.CopyTo(destinationStream);
            }
        }
    }
```

This way gltFast could load encrypted gltf's. The Ciphermode, Key and blocksize could be constructor arguments to the `EncryptedDownloadProvider`.
I'm sure there are other companies around who don't want their 3D models transmitted over the internet in clear text/bytes.

**Comment by atteneder** [comment]
Created [dedicated issue](https://github.com/atteneder/glTFast/issues/148) for loading from buffers.

**Comment by Bersaelor** [comment]
Thank your for the addition of loading via [gltf.LoadGltfBinary](https://github.com/atteneder/glTFast/blob/main/Documentation%7E/glTFast.md#load-from-byte-array). That works and has solved my use case.
Sorry for not being around, was working on other projects for a while.

**Comment by cvetelinast** [comment]
Hi, [Bersaelor](https://github.com/Bersaelor), just wanted to say thanks! 
In my file format, the gltf files are located inside a zip, along with other files. So, for WebGL, I'm extracting the .zip in `Application.persistentDataPath` and I have to read all files (.gltf, .bin, and the others) from there. Your LocalFileProvider is a life-saver, the async version in your sample project didn't work for me, but the sync works perfectly. Thanks again!
