### ISSUE TITLE
Points Support

### ISSUE THREAD

**Issue by camnewnham** [atteneder/glTFast#135]
I'm interested in doing some work to extend support of POINTS geometry and would like to scope it and determine whether it's a welcome extension to this library beforehand. 

The current behaviour is:

**Gltf**
* GLTFast.GLTFast:PreparePrimitiveIndices logs an error (Primitive mode Points is untested!)
* Points are visible (in editor) but vertex colors do not appear

**With Draco**
* Fails to load with "Failed: Decoding error."

Technically it's not in the spec (see [spec ](https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Khronos/KHR_draco_mesh_compression#restrictions-on-geometry-type)and discussion https://github.com/KhronosGroup/glTF/issues/1809), but the default three.js GltfLoader/DracoLoader will load a point cloud compressed with Draco without issue and the file size reduction is of course significant.

From what I can tell, the main changes would appear to be:
1) Modifying `draco_unity_plugin.cc` to allow points. Currently:

```  
if (geom_type != draco::TRIANGULAR_MESH) {
    return -2;
  }
```
2) Investigation of vertex colors & shaders, which could be in response to either:
a. Creation/addition of a point rendering shader including vertex colors, used when topology == points
b. VertexColorUnlit is showing jumbled colors on the points, so this may need more investigation.

For clarity of 2b, here's in Unity with glTFast and the VertexColors material:
![image](https://user-images.githubusercontent.com/19278856/107998904-35ebec00-703a-11eb-9891-8da88fb68b82.png)

And here's the same with three.js:
![image](https://user-images.githubusercontent.com/19278856/107998867-22408580-703a-11eb-88a3-b6e5e187cf9a.png)

@atteneder at a cursory glance are there any other parts that would need modification, or do you have any other tips?

**Comment by atteneder** [comment]
Hi @camnewnham ,

Thanks for the great suggestion and putting in the effort.

You're right about the Draco limitation. Currently I refactor the Draco integration (re-base on recent version plus use the advanced Mesh API). It would make sense to wait for this new version or start working on the according branch( [draco](https://github.com/atteneder/draco/tree/unity2)  and [DracoUnity](https://github.com/atteneder/DracoUnity/tree/draco2)).

I'm not experienced in point cloud rendering in Unity. I'm pretty sure we can make sure that the vertex colors are imported correctly. It is likely the material/shader that's not using the vertex colors correctly. This assumption would have to be put to test. Otherwise I see no obvious blockers for this feature.

Regards,
Andi

**Comment by camnewnham** [comment]
Cool. I'll do some testing with the older version and just to isolate any issues and determine what needs to be done and then move it over to the new one.

I'll post some updates here as I work out what's going on. Starting with a simple colored point cloud:

three.js:
![image](https://user-images.githubusercontent.com/19278856/108278000-73817e00-71ce-11eb-988d-ba43046c19cb.png)

![image](https://user-images.githubusercontent.com/19278856/108277608-cc9ce200-71cd-11eb-9557-3a53fb6eac87.png)

Left is glTFast pts, using VertexColors shader
Right is an exported/importer .ply using the same shader. Subsequently I suspect that the issue is IO related rather than shader related.

The same test using colored meshes:

three.js:
![image](https://user-images.githubusercontent.com/19278856/108278050-885e1180-71ce-11eb-84c3-7e0a0889d898.png)

Left is glTFast, right is .ply using VertexColors shader
![image](https://user-images.githubusercontent.com/19278856/108278374-0de1c180-71cf-11eb-8073-fac30a9b6270.png)

Given the close-up I suspect the color order is getting shuffled somewhere?
![image](https://user-images.githubusercontent.com/19278856/108278431-24881880-71cf-11eb-85bf-ce01fd00fd4a.png)

**Comment by camnewnham** [comment]
It looks like the color ordering is a result of the indexing in the jobs. i.e. `GetColorsVec4UInt8Job`:

Rather than
```

        public void Execute(int i) {
            byte* src = input + (i * inputByteStride);
            result[i] = new Color {
                r = src[i] / (float) byte.MaxValue,
                g = src[i+1] / (float) byte.MaxValue,
                b = src[i+2] / (float) byte.MaxValue,
                a = src[i+3] / (float) byte.MaxValue
            };
        }
```
we need:
```
        public void Execute(int i)
        {
            byte* src = input + (i * inputByteStride);
            result[i] = new Color
            {
                r = src[0] / (float)byte.MaxValue,
                g = src[1] / (float)byte.MaxValue,
                b = src[2] / (float)byte.MaxValue,
                a = src[3] / (float)byte.MaxValue
            };
        }
```

This likely also resolves https://github.com/atteneder/glTFast/issues/138

I'll make a PR accordingly before moving onto the draco component.

**Comment by atteneder** [comment]
Awesome finding!

**Comment by camnewnham** [comment]
Here's a first go at allow draco to work with the point clouds.

**Draco** changes: https://github.com/camnewnham/draco/commit/817d74b065a871d208804b1901eec9116f62737c
* Add `DRACO_POINT_CLOUD_COMPRESSION_SUPPORTED` flag for `BUILD_FOR_GLTF` in CMakeLists
* Decode either `TRIANGULAR_MESH` or `POINT_CLOUD` based on the `EncodedGeometryType`

(note I am a C++ amateur so any advice is most welcome - there's a bunch of code duplication here for mesh vs pt processing)


**DracoUnity** changes: https://github.com/camnewnham/DracoUnity/commit/8a3daba7bdb39939aacb1695090596e560ed7d57
* Check if any triangles are in the `DracoToUnityMesh`, and use this as a flag to either set indices (points) or triangles (mesh)

Originally I had thought to pass a value based on the topology declared in the glTF - but this logic doesn't work when using the draco file importer (and could lead to conflicts for poorly formatted files).


**glTFast** changes: https://github.com/camnewnham/glTFast/commit/a3ffa8371b8e699b4f8c42ef553a12cd0244a7ca
* `RecalculateNormals` doesn't work with `MeshTopology.Points`

Last remaining is to include and map an appropriate vertex color material/shader when topology is points - I think it's a reasonable assumption that point clouds should prioritize vertex colors over GLTF assigned material and select a vertex color shader instead (i.e. they might have a PBR assigned due to their creation process).

**Comment by atteneder** [comment]
Thanks, much appreciated!
I'll try to have a look early this week.

**Comment by camnewnham** [comment]
Addition of default points shader `IMaterialGenerator.GetDefaultPointsMaterial` (gltf/Unlit) has been added to the glTFast fork too.

**Comment by atteneder** [comment]
Sorry for the delay. I had a look across it (didn't test so far). glTFast and DracoUnity look good overall.

Some thoughts about the native part:

- It is based on the current version (my `unity` branch). I couldn't finish the more up to date work due to an open blocking issue, but that has to be ported soonish
- I'd like to have a look at the impact on the build size first. I don't expect it to be big/a blocker, but none the less
- Code seems a bit redundant. Can we leverage synergies between `DecodeMesh` and `DecodePointCloud` a bit better?

Thank you very much!

**Comment by camnewnham** [comment]
Thanks for having a look. I'll move the changes up to the latest once there's a stable glTFast/DracoUnity/draco combination (or is this the case now?) so that I can tell if breaking things are my issue or pre-existing.

I ran the CI here: https://github.com/camnewnham/draco/actions/runs/587740664 so comparing to the prior builds: https://github.com/atteneder/draco/actions/runs/525167332 we get:

**Existing**
![image](https://user-images.githubusercontent.com/19278856/109079266-d20ca600-7752-11eb-90c9-9746d04de17b.png)

**Including point clouds**
![image](https://user-images.githubusercontent.com/19278856/109079308-ddf86800-7752-11eb-8b88-25c665921675.png)

So that seems like a pretty negligible change in size for the feature?

Agree on the redundant code - my C++ is a bit lacking. I've updated again (https://github.com/atteneder/draco/compare/unity...camnewnham:unity_point_clouds) using templates which seems to work well and removes the majority of the duplication.

**Comment by atteneder** [comment]
Now that points support is tested (both regular and Draco compressed) I am closing this issue.

For improved/dedicated point cloud materials I created issue #246 

Thanks!
