### ISSUE TITLE
Index was outside the bounds of the array

### ISSUE THREAD

**Issue by Blocovin** [atteneder/glTFast#136]
Hi,

We got an error when we try to load [this glb file](https://fromsmash.com/Ar7qF.2Wv3-ct) in Unity Editor (2019.4.20f1) with GltFast 3.0.2 : 

``System.IndexOutOfRangeException: Index was outside the bounds of the array. at GLTFast.VertexBufferConfig`1[VType].ScheduleVertexJobs (GLTFast.VertexInputData posInput, System.Nullable`1[T] nrmInput, System.Nullable`1[T] tanInput, GLTFast.VertexInputData[] uvInputs, System.Nullable`1[T] colorInput, System.Nullable`1[T] weightsInput, System.Nullable`1[T] jointsInput) [0x00167] in /glTFast/Runtime/Scripts/VertexBufferConfig.cs:104 
  at GLTFast.GLTFast+<LoadAccessorData>d__82.MoveNext () [0x009b5] in /glTFast/Runtime/Scripts/GltFast.cs:1541 ``

**Comment by atteneder** [comment]
Hi @Blocovin ,

sorry for the inconvenience. Is this reproducable consistently?

I could load it successfully in Unity 2021.1.b6 and 2019.4.20f1, but it is a very heavy model that renders slowly. I can only recommend to optimize it.

regards,

**Comment by Blocovin** [comment]
We no longer got error, we tried to load glb 20 times and it's load successfully all the time...

It's a mistake, sorry for the inconvenience !

Thanks for your support !

**Comment by atteneder** [comment]
That's great to hear!

No worries. Feel free to re-open or create a new issue if it re-surfaces.
