### ISSUE TITLE
Best way to add MeshCollider on every GameObject

### ISSUE THREAD

**Issue by Blocovin** [atteneder/glTFast#137]
Hi,

We try to add mesh colliders on every GameObject in CustomInstantiator but we got some errors in unity :

```csharp
public class CustomGameObjectInstantiator : GameObjectInstantiator {
  public CustomGameObjectInstantiator (Transform parent) : base (parent) { }
  
  public override void AddPrimitive (uint nodeIndex, string meshName, Mesh mesh, Material[] materials, int[] joints = null, bool first = true) {
      base.AddPrimitive (nodeIndex, meshName, mesh, materials, joints, first);
      nodes[nodeIndex].AddComponent<MeshCollider> ();
  }
}
```

```console
[Physics.PhysX] cleaning the mesh failed
UnityEngine.MeshCollider:set_sharedMesh(Mesh)
CustomGameObjectInstantiator:AddPrimitive(UInt32, String, Mesh, Material[], Int32[], Boolean) (at Assets/Scripts/CustomGameObjectInstantiatorcs:12)
```

```console
[Physics.PhysX] TriangleMesh::loadFromDesc: desc.isValid() failed!
UnityEngine.GameObject:AddComponent()
CustomGameObjectInstantiator:AddPrimitive(UInt32, String, Mesh, Material[], Int32[], Boolean) (at Assets/Scripts/CustomGameObjectInstantiator.cs:12)
```

How to avoid errors ?

**Comment by atteneder** [comment]
Hi @Blocovin ,

Thanks for reporting.

I'd have to try, but maybe it is related to the mesh flags (see [this comment](https://github.com/atteneder/glTFast/issues/100#issuecomment-777022328))

I'll try to test soon

**Comment by Blocovin** [comment]
Thank you for your answer !
I forgot to specify that we use draco, so `PrimitiveDracoCreateContext.cs`is called and there is no 'MeshUpdateFlags'.

**Comment by atteneder** [comment]
> Thank you for your answer !
> I forgot to specify that we use draco, so `PrimitiveDracoCreateContext.cs`is called and there is no `MeshUpdateFlags`.

Good point!
I've created a corresponding [issue](https://github.com/atteneder/DracoUnity/issues/7). The next DracoUnity version will support this.

**Comment by Blocovin** [comment]
I fork "UnityDraco" and I try to set 
`defaultMeshUpdateFlags = MeshUpdateFlags.Default`
and
`defaultMeshUpdateFlags = MeshUpdateFlags.DontNotifyMeshUsers | MeshUpdateFlags.DontResetBoneBounds | MeshUpdateFlags.DontValidateIndices;`

I always got the unity error when I load a draco model (only on specific draco model)

`[Physics.PhysX] TriangleMesh::loadFromDesc: desc.isValid() failed!
UnityEngine.GameObject:AddComponent<UnityEngine.MeshCollider> ()`

`[Physics.PhysX] TriangleMesh::loadFromDesc: desc.isValid() failed!`

Do you have another suggestion to fix it ?

**Comment by atteneder** [comment]
Erm....no, nothing obvious. I'll try to look into it next week.

**Comment by Blocovin** [comment]
I found the solution, in Unity 2021.2.X the error is more explicit (https://issuetracker.unity3d.com/issues/physics-dot-raycast-throws-errors-when-used-on-a-navmesh).
So in Unity 2021.2.0a12 we got error : ```mesh must have at least three distinct vertices to be a valid collision mesh```

It's a problem in our mesh, not in gltfast 😆 
So I fix it with `mesh.vertices.Distinct ().Count () >= 3` check.

```csharp
using System.Linq;

public class CustomGameObjectInstantiator : GameObjectInstantiator {
  public CustomGameObjectInstantiator (Transform parent) : base (parent) { }
  
  public override void AddPrimitive (uint nodeIndex, string meshName, Mesh mesh, Material[] materials, int[] joints = null, bool first = true) {
      base.AddPrimitive (nodeIndex, meshName, mesh, materials, joints, first);
      if (mesh.vertices.Distinct ().Count () >= 3) {
        nodes[nodeIndex].AddComponent<MeshCollider> ();
      }
  }
}
```

**Comment by atteneder** [comment]
@Blocovin  Great you found a solution!

My suspicion is that it isn't performant though (fetching `Mesh.vertices` and doing `Distinct`). Also LINQ increases build size drastically in my experience.

I'd try to avoid this checks in production code.

regards,
Andreas

**Comment by Blocovin** [comment]
@atteneder Indeed you are right it is not performant.
I use mesh.bounds.extents to check minimal requirement, it is much more performant.

3D models are send by our customer so unfortunately we must add this check in unity for the moment.

We will see if we can clean the mesh from our pipeline.

Thank you very much for your help and advice !
