### ISSUE TITLE
Wrong Colors when using Vertex Colors exported from Blender 

### ISSUE THREAD

**Issue by chrisssssy** [atteneder/glTFast#138]
Hi,

i have problems with displaying corrects colors when using vertex colors. With standard materials and textures exported from blender, everything looks fine. But exporting only the mesh with vertex color results in weird colors like in this picture:

![image](https://user-images.githubusercontent.com/52048986/108108113-76765480-7090-11eb-8201-653100c3a324.png)

But it should look like this (same glb-file in Windows 10 3D-Viewer):

![image](https://user-images.githubusercontent.com/52048986/108108145-82621680-7090-11eb-929f-7f389d84bfc4.png)

Other GLTF-Viewers display the colors correctly. Here is the zipped glb-file:

 [Suzanne.zip](https://github.com/atteneder/glTFast/files/5991035/Suzanne.zip)

Also sometimes i get this unity warning "_Mesh vertex buffer attributes were supplied in non-standard order_". What does this mean? Can you give me a tipp how to fix this problem? Maybe a export setting in blender?

Thanks for your support!

Unity Warning Message:
Mesh vertex buffer attributes were supplied in non-standard order. Layout was adjusted to this order: Position, Normal, Color, TexCoord0.
UnityEngine.Mesh:SetVertexBufferParams(Int32, VertexAttributeDescriptor[])
GLTFast.VertexBufferConfig`1:ApplyOnMesh(Mesh, MeshUpdateFlags) (at Library/PackageCache/com.atteneder.gltfast@5602e1e9c4/Runtime/Scripts/VertexBufferConfig.cs:237)
GLTFast.PrimitiveCreateContext:CreatePrimitive() (at Library/PackageCache/com.atteneder.gltfast@5602e1e9c4/Runtime/Scripts/PrimitiveCreateContext.cs:56)
GLTFast.<Prepare>d__78:MoveNext() (at Library/PackageCache/com.atteneder.gltfast@5602e1e9c4/Runtime/Scripts/GltFast.cs:909)
GLTFast.<LoadContent>d__57:MoveNext() (at Library/PackageCache/com.atteneder.gltfast@5602e1e9c4/Runtime/Scripts/GltFast.cs:260)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

**Comment by chrisssssy** [comment]
Ok i did some further testing, and the glb-file (Suzanne.zip) from is correctly displayed in your WebGl-Demo. Also the [BoxVertexColors.glb](https://github.com/atteneder/glTFast/files/5991748/BoxVertexColors.zip) File from the Khronos sample files ist working fine in my unity project, so i really don't know what's the problem here.

**Comment by chrisssssy** [comment]
Seems like it's an issue with the exporter (Khronos glTF Blender I/O v1.4.40) in blender 2.91.2. With blender 2.8 LTS (exporter: Khronos glTF Blender I/O v1.2.75) the problem is gone. Export settings where the same.

**Comment by atteneder** [comment]
Hi @chrisssssy ,

Thanks for reporting. Great that you found a workaround in using 2.8 LTS, but I suspect this is clearly a bug on glTFast's side.

I'll look into it soon.

Regards

**Comment by chrisssssy** [comment]
#139 did fix this problem for me. Now i can use the files exported with blender 2.91.2 without any issues, thank you.
