### ISSUE TITLE
KTX kompressed model crashing in browser but works fine in Editor

### ISSUE THREAD

**Issue by M4kHack** [atteneder/glTFast#149]
Hello,

I have a KTX Compressed model that loads fine in the editor but in the browser I get:

Exception: Could not determine default MaterialGenerator
  at GLTFast.Materials.MaterialGenerator.GetDefaultMaterialGenerator () [0x00000] in <00000000000000000000000000000000>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x00000] in <00000000000000000000000000000000>:0 
 
(Filename: currently not available on il2cpp Line: -1)

Any idea as to how to fix this or what is causing it?

Model: [80481-tc.zip](https://github.com/atteneder/glTFast/files/6075671/80481-tc.zip)
//M4k

**Comment by atteneder** [comment]
I presume you found a fix yourself and closed the issue for that reason.

Looks like you had a non-matching RenderPipelineAsset assigned. This can happen when you try a scripted render pipeline (like URP or HDRP), remove them in the package manager, but still have the RenderPipelineAsset assigned in the Render settings.

hth

Let me know if you still have trouble with this.

**Comment by M4kHack** [comment]
Yeah, That is exactly what happened.

I'm very grateful for all you do Andreas!

All the best =)

//Marcus

Från: Andreas Atteneder <notifications@github.com>
Skickat: den 3 mars 2021 12:58
Till: atteneder/glTFast <glTFast@noreply.github.com>
Kopia: Marcus Gärdskog Hill <marcus.gardskog@synsam.com>; State change <state_change@noreply.github.com>
Ämne: Re: [atteneder/glTFast] KTX kompressed model crashing in browser but works fine in Editor (#149)


I presume you found a fix yourself and closed the issue for that reason.

Looks like you had a non-matching RenderPipelineAsset assigned. This can happen when you try a scripted render pipeline (like URP or HDRP), remove them in the package manager, but still have the RenderPipelineAsset assigned in the Render settings.

hth

Let me know if you still have trouble with this.

-

**Comment by atteneder** [comment]
You are very welcome ❤️

Keep the feedback coming! It helps me improve the developer experience for all users.
