### ISSUE TITLE
How to get a reference to the game object that is instantiated

### ISSUE THREAD

**Issue by sarangborude** [atteneder/glTFast#152]
I have my GLTF file downloaded  and I have a file path to it, I am trying to instantiate a game object with it. previously the work flow was I add a GLTFAsset component to the game object and then call Load method with the file path.  The there was a OnLoadComplete callback that I can subscribe to  and do additional things with my loaded GLTF. 

Now the OnLoadComplete method is gone. How should I handle loading a gltf model to a gameobject and then have a reference to that gameobject?

**Comment by atteneder** [comment]
Hi @sarangborude,

There's an example for that [in the documentation](https://github.com/atteneder/glTFast/blob/main/Documentation~/glTFast.md#custom-post-loading-script).

You could also derive from `GltfAsset` and override `Load` like so:

```csharp
public class MyGltfAsset : GltfAsset {

public override async Task<bool> Load( string url, IDownloadProvider downloadProvider=null, IDeferAgent deferAgent=null, IMaterialGenerator materialGenerator=null ) {
    var success = await base.Load(url, downloadProvider, deferAgent, materialGenerator);
    if(success) {
        Debug.Log("Do your custom post-loading stuff here");
    }
    return success;
}
```

> Note: Since `Load` is async, calling `base.Load` does not stall the method, but loads the glTF in background.

hth

**Comment by sarangborude** [comment]
This works perfectly, but @atteneder how do I get the hold of the game object that gets instantiated. 
Sorry if this is a newbie question. Thanks.

**Comment by atteneder** [comment]
Whatever GameObject your`GltfAsset` is a component of will serve as the root for glTF scenes loaded.

If you don't want it this way, customize it the way its described in the documentation (link in previous reply). You have to create the GameObject yourself, call `InstantiateGltf` and pass it an `GameObjectInstantiator`. The latter takes the transform of your GameObject as constructor parameter and creates child GameObjects (depending on glTFs scenes and nodes).

To complete the example above:

```csharp
public class MyGltfAsset : GltfAsset {

public override async Task<bool> Load( string url, IDownloadProvider downloadProvider=null, IDeferAgent deferAgent=null, IMaterialGenerator materialGenerator=null ) {
    var success = await base.Load(url, downloadProvider, deferAgent, materialGenerator);
    if(success) {
        // Custom GameObject
        var myGameObject = new GameObject("Root Object");
        // Instantiate glTF
        gLTFastInstance.InstantiateGltf(new GameObjectInstantiator(myGameObject.transform));

        Debug.Log("Do your custom post-loading stuff here");
    }
    return success;
}
```

I hope it's clear now

**Comment by sarangborude** [comment]
very clear, ended up using the custom instantiator approach
