### ISSUE TITLE
URL query strings brake image format determination (with a "tested" fix)

### ISSUE THREAD

**Issue by JonathanB-Vobling** [atteneder/glTFast#158]
I had issues with files that had query strings for the images. I fixed that by changing the format determination code to this:
![SnippedGLTFastChange](https://user-images.githubusercontent.com/78907491/112475167-ce2f6c00-8d70-11eb-9140-41c17f329f8f.png)

Worked fine in a few quick and dirty tests. Don't have write access and since it (to me at least) seems like a very small fix I thought that maybe just creating an issue would be easier.

Not used to contributing to other repos so I'm sorry if I went about this the wrong way.

**Comment by atteneder** [comment]
Hi @JonathanB-Vobling,

Thanks for the submission and sorry for the delayed answer (I'm on paternity leave).

Without testing it, you seem to made a good find. I'd say it's a great opportunity to learn how to make a proper contribution via PR (pull request; it might be the start of more to come ;) ). This raises the chances of your work getting accepted a lot.

1. It's always good to describe how to reproduce the original problem and attach the gltf files that don't work. This makes it easy for me to reproduce.

2. It's true, you don't get write permission on my original repository, but you can make a *fork* of your own (fork button to the upper right). Clone this fork and you'll notice you can commit and push your changes to it.

3. Back on GitHub, if you open your fork's site, it'll suggest to create a pull request on top to you, if you pushed changes before.

If you're stuck along the way, open the github documentation how to make a PR

Looking forward to hear from you

**Comment by atteneder** [comment]
Nevermind, saw your PR #160
