### ISSUE TITLE
Valid objects cause ArgumentException: Invalid vertex attribute dimension value (0, should be [1,4])

### ISSUE THREAD

**Issue by hybridherbst** [atteneder/glTFast#162]
I'm getting an exception with a specific mesh:
```
ArgumentException: Invalid vertex attribute dimension value (0, should be [1,4])
UnityEngine.Mesh.SetVertexBufferParams (System.Int32 vertexCount, UnityEngine.Rendering.VertexAttributeDescriptor[] attributes) (at <42a5878ce129403083acccf18e43363f>:0)
GLTFast.VertexBufferConfig`1[VType].ApplyOnMesh (UnityEngine.Mesh msh, UnityEngine.Rendering.MeshUpdateFlags flags) (at D:/git/quest-app-launcher/development/com.atteneder.gltfast/Runtime/Scripts/VertexBufferConfig.cs:248)
GLTFast.PrimitiveCreateContext.CreatePrimitive () (at D:/git/quest-app-launcher/development/com.atteneder.gltfast/Runtime/Scripts/PrimitiveCreateContext.cs:55)
GLTFast.GLTFast+<Prepare>d__76.MoveNext () (at D:/git/quest-app-launcher/development/com.atteneder.gltfast/Runtime/Scripts/GltFast.cs:1055)
```

What I see when debugging the exception from GltFast - looks like duplicate "position" attribute?
![210406-154326530-AppLauncher_–_VertexBufferConfig cs_ Debugger](https://user-images.githubusercontent.com/2693840/113720573-16df1180-96ef-11eb-98ba-57fd17cfc343.png)

How it looks in Gestaltor:
![image](https://user-images.githubusercontent.com/2693840/113720625-22323d00-96ef-11eb-903f-3322186cef31.png)

I sent the mesh via the "usual channels" for debugging purposes.

**Comment by atteneder** [comment]
confirmed!

Bug is triggered if a mesh has two UV sets and vertex colors. This results in faulty vertex attribute descriptors.
