### ISSUE TITLE
glTFast has compile errors if com.unity.testframework.graphics is present but glTFast is not in testables list

### ISSUE THREAD

**Issue by hybridherbst** [atteneder/glTFast#168]
Seems that the SamplesSetEditor lives in the package and is defined away with #if GLTFAST_RENDER_TEST (through the AsmDef), but that define is active once the Graphics Test Framework is present in a project. Now, in that particular case, I don't actually want to run glTFast tests (so it's not in the "testables" list in the manifest) - not sure what the best way is to resolve this case.

**Comment by atteneder** [comment]
Oh, crap.

Thanks for pointing out.

first thought: Shat's the actual error? can we somehow prefix this code?

second thought: Should we separate testing from the main package, create a dedicated glTF-Test package and move stuff like SampleSets there. Benefit: we could expand those tests to work with other packages like UnityGLTF as well.

The solutions don't exclude each other (we could make a short-term fix and transition later on)

Any thoughts?

**Comment by hybridherbst** [comment]
The actual error is just
`D:\git\unity-gltf-tests\packages\atteneder-glTFast\Editor\GltfSampleSetEditor.cs(26,15): error CS0234: The type or namespace name 'Tests' does not exist in the namespace 'GLTFast' (are you missing an assembly reference?)`

I found this issue while setting up a gltf-tests repo for tests that touch on multiple GLTF solutions, so yes, I think separating those out makes sense. I'll let you know once the basics of that are set up, happy to help transition the existing tests over.

**Comment by ThimoDEV** [comment]
I believe its a good idea to split testing from the main package. I dont think people need the testing in the package most of the time. If you have a reference in the documentation/ some sort of text file or pop up window that a testing utility is something additional to install, it would make the gltfast pacakge a bit cleaner I think.

**Comment by atteneder** [comment]
That's true!

People who want to develop glTFast can always add the test suite. The question to me is, would the separation break anything or make it (much) less convenient to me? If so, simply fixing it might be the preferable.

I'll look into it soon.
