### ISSUE TITLE
sRGB/Linear issue with texture indices

### ISSUE THREAD

**Issue by hybridherbst** [atteneder/glTFast#172]
This has already been fixed in https://github.com/atteneder/glTFast/tree/fix_texture_index, but opening this issue so it's not forgotten :)
Symptom is that for some models that have both albedo and normal maps, the albedo maps import as linear and the normals as sRGB, resulting in incorrect rendering.

**Comment by atteneder** [comment]
Thanks for the heads up! Did I give you this to test and forgot to merge?
Sorry about that.

**Comment by hybridherbst** [comment]
Think so! I did test and it fixes the issue :)
