### ISSUE TITLE
Generated bounds is too small

### ISSUE THREAD

**Issue by MaxymShtoyko** [atteneder/glTFast#173]
Hello,

generated bounds for model from this url: " https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/BrainStem/glTF-Embedded/BrainStem.gltf" is up to 100 times smaller than the expected ones.
Does anyone have any ideas how to resolve the problem?

Thanks in advance!

**Comment by atteneder** [comment]
Hi @MaxymShtoyko ,

Thanks for reporting.

This asset is an animated and has skinned meshes, which is probably the factor that sets it apart. I'll look if the error is in the file or glTFast calculates it wrong (presuming the latter).

For an animated object it is hard to define and calculate the bounds. Should they cover the object at the starting frame? or rest position? or encapsulate all keyframes?...difficult.

**Comment by MaxymShtoyko** [comment]
hi @atteneder, 
it will be fine for me even if bounds cover the object only at the starting frame

**Comment by atteneder** [comment]
I assume you were using `GltfBoundsAsset` and you were referring to it. Well, I found that only the bounds of the first primitive was considered (a mesh can have multiple primitives and in this scene it's basically just one node/mesh holding all the primitives)
