### ISSUE TITLE
Crashing Unity while downloading glb

### ISSUE THREAD

**Issue by levin1902** [atteneder/glTFast#174]
When i try to download the following *.glb model from server using Gltfast 3.2.0, Unity crashes. But, when i tried to download the same model from older gltfast version 1.1.1 it worked.
[https://coobo.azureedge.net/assets/AE668B32-D02A-4A57-9FE5-4FE182A86400/713BCDC2-0D53-43A7-AB07-87ED0B0449E5.glb](url)

Unity - 2019.4.13f1
Gltfast - 3.2.0
Draco - 1.4.0

**Comment by atteneder** [comment]
Hi @levin1902 ,

Thanks for reporting and sorry for the inconvenience.

I successfully loaded it in this setup:

Unity 2019.4.26f1 (macOS Intel)
glTFast 3.2.1
Draco 1.4.0

![image](https://user-images.githubusercontent.com/2593014/118036528-f6991700-b36c-11eb-8b7d-5dde547a8f60.png)

Do you mean the Unity Editor crashes in playmode or your build crashes? In any case, which platform are you on?

**Comment by levin1902** [comment]
Crashed in Unity Editor in playmode. Platform - Android. 
Will update to 3.2.1 and check.

**Comment by levin1902** [comment]
@atteneder Tried with 3.2.1,
**Crashes** in Unity 2019.4.13f1 (Editor, playmode)
**Works** in Unity 2019.4.21f1 (Editor, playmode)

OS - Windows
Processor - i7
Build Platform - Android

* I guess, the issue is because of Unity version.

**Comment by atteneder** [comment]
Hi @levin1902 ,

could you get it to work? Did you find out the problem?

**Comment by levin1902** [comment]
Hi @atteneder 
could you get it to work? - Yes. Updated to 3.2.1 and tried it in Unity 2019.4.21f1. It worked.
Did you find out the problem? - No. But, will try to find out.

**Comment by atteneder** [comment]
That's great to hear!
In case we missed something and it re-surfaces it would be great if you'd reopen the issue.
Thanks!
