### ISSUE TITLE
Unlit shader that supports transparency 

### ISSUE THREAD

**Issue by avseoul** [atteneder/glTFast#180]
Hi, I'm trying to replace the current unlit shader with a custom one that supports transparency. What would be the best way to let GLTFast uses custom unlit shader over `glTFUnlit.shader`?  

Custom shader code is something like this: 
```
SubShader {
    LOD 100

    Pass {
        Cull [_CullMode]
        Blend [_SrcBlend] [_DstBlend]
        ZWrite [_ZWrite]

        CGPROGRAM
            #pragma vertex vert
            #pragma fragment frag
            #pragma target 2.0
            #pragma multi_compile_fog
            #pragma shader_feature_local _UV_ROTATION
            #pragma shader_feature_local _ _ALPHATEST_ON _ALPHABLEND_ON _ALPHAPREMULTIPLY_ON

            #include "UnityCG.cginc"

            struct appdata_t {
                float4 vertex : POSITION;
                float2 texcoord : TEXCOORD0;
                fixed4 color : COLOR;
                UNITY_VERTEX_INPUT_INSTANCE_ID
            };

            struct v2f {
                float4 vertex : SV_POSITION;
                float2 texcoord : TEXCOORD0;
                fixed4 color : COLOR;
                UNITY_FOG_COORDS(1)
                UNITY_VERTEX_OUTPUT_STEREO
            };

            half4 _Color;
            sampler2D _MainTex;
            float4 _MainTex_ST;
            float4 _MainTexRotation;
            fixed _Cutoff;

            v2f vert (appdata_t v)
            {
                v2f o;
                UNITY_SETUP_INSTANCE_ID(v);
                UNITY_INITIALIZE_VERTEX_OUTPUT_STEREO(o);
                o.vertex = UnityObjectToClipPos(v.vertex);

#ifdef _UV_ROTATION
                // 2x2 matrix multiplication to apply rotation
                o.texcoord.x = v.texcoord.x * _MainTexRotation.x + v.texcoord.y * _MainTexRotation.z;
                o.texcoord.y = v.texcoord.x * _MainTexRotation.y + v.texcoord.y * _MainTexRotation.w;
                o.texcoord = TRANSFORM_TEX(o.texcoord, _MainTex);
#else
                o.texcoord = TRANSFORM_TEX(v.texcoord, _MainTex);
#endif

                UNITY_TRANSFER_FOG(o,o.vertex);
                o.color = v.color;
                return o;
            }

            fixed4 frag (v2f i) : SV_Target
            {
                fixed4 col = tex2D(_MainTex, i.texcoord) * _Color;
                col *= i.color;
#ifdef _ALPHATEST_ON
                clip(col.a - _Cutoff);
#endif
                UNITY_APPLY_FOG(i.fogCoord, col);
#if !defined(_ALPHATEST_ON) &&  !defined(_ALPHABLEND_ON) && !defined(_ALPHAPREMULTIPLY_ON)
                UNITY_OPAQUE_ALPHA(col.a);
#endif
                return col;
            }
        ENDCG
    }
}
```

Thanks in advance!

**Comment by atteneder** [comment]
Hi @avseoul ,

Thanks for getting in touch!

In case your version only adds features/improvements without any drawbacks it would be great to just replace the original with your improved version. In order to make your changes easy to inspect and test, please open a PR (pull request; read the [github documentation](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests) if you don't know how to do that).

In case your shader-changes are specific to your project/needs and do not qualify to be merged into the main project: 

You can implement a custom `IMaterialGenerator` and pass it to glTFast. The easiest way is to derive from `BuiltInMaterialGenerator` (in case you use the Built-In render pipe) and override `FinderShaderUnlit` to return your shader.

Would be great to have your work submitted in a PR. In case you decide to make one, I'm looking forward to it.

**Comment by atteneder** [comment]
In any case: let me know how you want to proceed. Thanks

**Comment by avseoul** [comment]
Hi @atteneder 

Thanks for the fast following up! That works! 

RE: PR for changes - Thanks for the suggestion. Happy to contribute! It might be useful for models that don't have any PBR parameters but still have transparency. I'll prepare a PR and link this issue

**Comment by avseoul** [comment]
It seems I need a permission. Branch is ready, I'll push it when the permission is granted. Thanks

**Comment by atteneder** [comment]
The usual procedure is not to give people permission to the main repository. Instead try creating a fork (button on the upper right), clone your personal fork (or add your remote to the local repository), make your changes (in a branch ideally) and push them to your fork. After that GitHub will detect your push and recommend creating a PR on top.

hth

**Comment by atteneder** [comment]
This might seem tedious at first, but don't let it intimidate you. Learning to contribute to projects is great and opens many possibilities.

**Comment by avseoul** [comment]
You got it. I'll give it a try

**Comment by atteneder** [comment]
It's merged. Thanks you very much for your work!
