### ISSUE TITLE
GetMesh bounds after loading.

### ISSUE THREAD

**Issue by umresh** [atteneder/glTFast#182]
Hi @atteneder is there a way to get the mesh bounds? Or where can I add mesh bounds calculation while mesh creation.
I tried adding calculation of mesh bounds after loading the model but It hangs unity when the high poly object is loaded. 

Thanks

**Comment by atteneder** [comment]
Have a look at [`GltfBoundsAsset`](https://github.com/atteneder/glTFast/blob/main/Runtime/Scripts/GltfBoundsAsset.cs), specifically its [`bounds`](https://github.com/atteneder/glTFast/blob/32a81867bda08d66875b6abeb0c72f8a65560840/Runtime/Scripts/GltfBoundsAsset.cs#L29) member.

**Comment by umresh** [comment]
Thanks for the reply, Tried the GltfBountsAsset, and the model is instantiated twice.

` async void Init()
    {
        string url = @"https://raw.githubusercontent.com/CesiumGS/cesium/master/Apps/SampleData/models/CesiumMan/Cesium_Man.glb";
        GameObject intantiatedObject = new GameObject("Model");
        GLTFast.GltfBoundsAsset gltfAsset = intantiatedObject.AddComponent<GLTFast.GltfBoundsAsset>();
        gltfAsset.loadOnStartup = false;
        gltfAsset.url = url;
        await gltfAsset.Load(url);
    }` 
This is the code I'm using to load model.

**Comment by atteneder** [comment]
Hi @umresh ,

Thanks for reporting! It would have been better to create a dedicated issue though (or reopen this one). Now this went under the radar.

Luckily it's fixes in [3.3.1](https://github.com/atteneder/glTFast/releases/tag/v3.3.1) now.

hth
