### ISSUE TITLE
DracoUnity 2.0.0 support

### ISSUE THREAD

**Issue by NeluQi** [atteneder/glTFast#183]
DracoUnity v2.0.0-preview with glTFast not supported?

![image](https://user-images.githubusercontent.com/16963395/118229208-49b9b980-b494-11eb-8f59-82fb67078a4d.png)

https://github.com/atteneder/DracoUnity/releases/tag/v2.0.0-preview

There are nice changes: "Experimental encoding support (ability to convert Unity Meshes into compressed Draco)"

**Comment by atteneder** [comment]
> DracoUnity v2.0.0-preview with glTFast not supported?
> 
> ![image](https://user-images.githubusercontent.com/16963395/118229208-49b9b980-b494-11eb-8f59-82fb67078a4d.png)
> 
> https://github.com/atteneder/DracoUnity/releases/tag/v2.0.0-preview

Yes, DracoUnity 2 requires some changes to glTFast (which I'm working on already).

> There are nice changes: "Experimental encoding support (ability to convert Unity Meshes into compressed Draco)"

Yes, this one's really cool 😎
