### ISSUE TITLE
beginner's question: Unable to load textures after build for PC standalone in Unity

### ISSUE THREAD

**Issue by rlatif97** [atteneder/glTFast#185]
Hi Andreas, 

I have setup your library and I tried to load a gltf model(exported from blender) at runtime which works fine with unity. However, when I build a PC, Mac& Linux Standalone app and run it independent of Unity, the textures do not load. I just get a pink model which does not have any textures on it. 

I am using Unity 2019.4.19f1 and I am loading from the memory using `async void LoadGltfBinaryFromMemory()` method.

I cannot figure out what could be the problem. I would really appreciate your help! If you need any more info, please let me know.

Thanks!

**Comment by rlatif97** [comment]
Answer found in documentation.

**Comment by atteneder** [comment]
Hi Rohan,

Great that you found a solution on your own! Taking a look into the docs first is best practice. If you find no answer there nor an existing issue, raise a new one.

kind regards
