### ISSUE TITLE
Draco 3D Data Compression version 2.0.0 and 3.0.0

### ISSUE THREAD

**Issue by NeluQi** [atteneder/glTFast#186]
![image](https://user-images.githubusercontent.com/16963395/119136984-fa9df680-ba48-11eb-9ca3-be98dfe99633.png)
![image](https://user-images.githubusercontent.com/16963395/119137209-3a64de00-ba49-11eb-9e2d-432b5dc6b2de.png)

It seems to have been fixed in the latest versions, but errors keep popping up

**Comment by atteneder** [comment]
It will be fixed in the upcoming version 4.0.0

Draco 2.x and 3.x have breaking changes and won't work with glTFast 3.x
