### ISSUE TITLE
Surface bug and PbrMetallicRoughness

### ISSUE THREAD

**Issue by NeluQi** [atteneder/glTFast#188]
Some surfaces only render on one side when using PbrMetallicRoughness

![image](https://user-images.githubusercontent.com/16963395/119376969-3ba23f00-bcc5-11eb-994d-68c9873c7bf6.png)

On the other hand, the object is not transparent
![image](https://user-images.githubusercontent.com/16963395/119376980-3e9d2f80-bcc5-11eb-9257-e44db55bd559.png)

Surface renders fine when using glTF / Unlit
![image](https://user-images.githubusercontent.com/16963395/119377064-5a083a80-bcc5-11eb-9a34-583c03241620.png)

**Comment by atteneder** [comment]
Thanks for reporting.
In glTF (or real-time rasterization in general) rendering only the front side of triangles is the default. If you want both sides to render, make sure the materials have the [`doubleSided`](https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#double-sided) property set to `true`. If you only want the outside to render, make sure the normals of the roof mesh are correct and flip them properly if not.

If at all, the Unlit shader shows an error when rendering the outside as well.

hth
