### ISSUE TITLE
Issues in loading glb after updating to 4.0

### ISSUE THREAD

**Issue by umresh** [atteneder/glTFast#192]
Hi,
   I have updated to 4.0 and Draco to 3.0 using OpenUPM and when I load the .glb I'm facing issues. If I add packages using git URL old version of  Draco package is loaded.

-- Using --
Unity 2019.4.21
Mac OS

<img width="1325" alt="Screenshot" src="https://user-images.githubusercontent.com/6183803/120286524-f771f880-c2db-11eb-8be9-8eea196df129.png">

**Comment by Blocovin** [comment]
Hi @umresh,
Do you target WEBGL or IOS platform ?

I got same problem when I target IOS platform so I create a pull request : https://github.com/atteneder/DracoUnity/pull/22

You can test the pull request by edit `manifest.json` with :
https://github.com/bloc-in-bloc/DracoUnity.git#v3.0.3

**Comment by umresh** [comment]
My target is Android.
This is the file 
[GLB](https://coobo.azureedge.net/assets/A165DBA0-DDF3-11EA-9DE0-2BE9E0078026/3CF8E7DB-7B07-4278-B40D-F579216DBD91.glb)

**Comment by umresh** [comment]
I'm using Mac Unity 2019.4.21 and the target is Android. I'll try the above fix and update.

**Comment by Blocovin** [comment]
Hum ok, the pull request will not fix your issue I think...

**Comment by umresh** [comment]
Still getting the 

![Uploading Screenshot 2021-06-01 at 2.58.39 PM.png…]()
same error.

**Comment by Blocovin** [comment]
Do you have burst installed ?

**Comment by umresh** [comment]
yes its installed. I fixed it. We were using another plugin Trilib to load .fbx removing it fixed the issues.

**Comment by atteneder** [comment]
> yes its installed. I fixed it. We were using another plugin Trilib to load .fbx removing it fixed the issues.

Oh no. I've heard this before. Seems like Trilib includes a copy of the dracodec_unity library (not sure if the original or from my fork) which is in conflict with DracoUnity's version.

I'd ecourage you to file an issue to Trilib asking them to fix it on their end. The reason: DracoUnity is build with modularity in mind whereas Trilib is one big package. It would be easy for them to either use DracoUnity or rename their copy of dracodec_unity. I don't see a reason DracoUnity should ship around every other project's conflict that makes a copy of the library.

Feel free to link them to me/this comment, so we can reason about it.

Thanks!
