### ISSUE TITLE
Google Poly Model fails silently to load from URL, filesystem, streaming asset but works when loaded as asset.

### ISSUE THREAD

**Issue by lizelive** [atteneder/glTFast#195]
here is url to model for reference.
This model is from google poly.
https://ipfs.io/ipfs/QmfWBanKx2cMy6BU93C5NmgDUcnNGSpcgB3nprDbNsRjNt/model.gltf
obviously something about the gltf is causeing a problem but how might i figure out what?

**Comment by atteneder** [comment]
Hi @lizelive ,

Thanks for reporting!

This glTF file does not specify a default scene. According to the glTF specification the correct behavior in that case is to not instantiate any object/scene. You can circumvent this by either:

- Specifying a default scene by adding a `scene` property to the glTF JSON
- Defining a scene ID to load

In the `GltfAsset` component this can be done like so:

<img width="467" alt="image" src="https://user-images.githubusercontent.com/2593014/121499977-2aa04000-c9de-11eb-866c-d0da7825ca05.png">

Notice the `Scene Id` is set to 0 (default is -1).

hth
