### ISSUE TITLE
Coordinate system in 4.0.0+

### ISSUE THREAD

**Issue by De-Panther** [atteneder/glTFast#200]
I updated to 4.0.0 (and 4.0.1).
While in general, rotating models by 180 degrees on Y axis works fine, I had issues with complex models.

I have poses (position + orientation) of hands joints in Unity's coordinate system, and I'm using these models:
https://github.com/immersive-web/webxr-input-profiles/tree/main/packages/assets/profiles/generic-hand
Before, applying the poses using Unity's coordinate system, to each joint of those models, worked as it should.
Now, after applying each pose, I need to rotate it by 180 degrees.
It's done for 50 times per frame (25 joints on each hand).

Any suggestion, how can I minimize the number of calculations on each frame?
Maybe an option to select which coordinate system I want to use for the model when loading?

**Comment by atteneder** [comment]
Hi @De-Panther ,

Thanks for reporting.

IMHO 50 rotation conversions aren't too bad. What system provides the pose rotations and in which format (euler/quaternion? coordinate system?). Would you mind pointing me to your conversion code? Maybe it helps me figuring out a good way.

I'd prefer to keep the number of options as low as possible. In case of coordinate system I don't see a strong enough reason, but feel free to bring convincing arguments.

Regards,
Andi

**Comment by De-Panther** [comment]
Thanks for the great package and the help.

I'm trying to have my calcs as low in numbers as I can (I do know that I have other places to optimize) as it runs on WebGL on Mobile...

This is the commit with the current fix:
https://github.com/De-Panther/unity-webxr-export/commit/4a56774965443bd82a95494319b372f2cfdf8b98
What happens there:
I load controllers models, rotate them by 180 using another package, then I rotate a model by 180 again if it's a hand model.
Then each frame I get the Inverse of the wrist joint, and calc all the joints according to it.

The models were made in such a way, that the coordinate system WebXR is based on, would work out of the box, and you won't need to have extra rotations for each joint.

As Unity has another coordinate system, before I send the data from JS to C#, I do the coordinate system transformation in JS.
Then in Unity the developers can work with the coordinate system they are used to...

As far as I know, when you import other model formats to Unity, Unity transform them to Unity's coordinate system, e.g. OBJ.

The intention of the modeler was for the model to work according to the coordinate system it's imported into.

**Comment by De-Panther** [comment]
Is it possible that it's just a bug in glTFast regarding to orientation of child joints?

**Comment by atteneder** [comment]
> Is it possible that it's just a bug in glTFast regarding the orientation of child joints?

I'd say no. In itself the model is consistent. glTFast *has* to do a coordinate system conversion (since glTF and Unity have different systems) and it's a design question which way to do it. The new (4.x) way is correct/more precise according to the spec.

What I'd do in your position:

- Profile if the additional processing actually has a negative impact. An additional quaternion multiplication adds 16 mul and 12 add/sub (times 50 in your case). CPUs are **fast**, so I'd be surprised if the actual impact is significant.
- Investigate if fixing the hand models can solve the problem. If you rotate the models 180 degree at authoring time (before glb export). I'd be surprised if it works, but I'm not entirely sure.
- Optimize the conversion math. Flipping a rotation by 180 degree in one axis is a special operation that might not require a full quaternion multiplication. I'm not a linear algebra guru, but I'm confident there's a cheaper way.

Regards

**Comment by De-Panther** [comment]
Those are not models that made by me, those are controllers and hand models created by manufactures and creators to dynamically load on runtime in WebXR experiences.
In the case of the hands models, there are the generic ones, but there are more with the same structure in different themes.

Rotating the hands by 180 degrees won't solve it. The modeler would have to rotate each joint separately for this to work.

Maybe there is a way to optimize the math operations I ended doing, but I'm as well not a linear algebra guru😀

I do think that the specs are important, but I think that the intention of the model creator and the developer that use those models is also important.
Unity's own models importers flip the models when importing them.
I needed to create OBJ exporter in the past, and exporting OBJ using Unity's coordinate system and importing it back to Unity ended flipped.

Does creating a model in blender, exporting it in FBX and GLTF results with the same orientation of the model when importing to Unity? Same joint rotations? (Installing blender now just for this experiment)

**Comment by De-Panther** [comment]
Installed blender, imported right hand GLB to blender, exported as FBX.
Loaded the FBX in Unity, and the GLB with glTFast 4.0.1 and they have the same orientations 😱

**Comment by De-Panther** [comment]
My bad. Sorry about that issue.
I'll try to figure out if there's a cost effective mathematical solution after importing.

**Comment by atteneder** [comment]
Oh, don't worry. Better opening a non-issue too much than not detecting an actual one.

I quickly tried to optimize the flipping:

```csharp
static Quaternion FlipY180(Quaternion rot) {
    return new Quaternion(-rot.z, rot.w, rot.x, -rot.y);
}
```

Even better: flipping in-place (one float temporary garbage allocation instead of four):

```csharp
public static class QuaternionExtension {
    public static void FlipY180(this ref Quaternion rot) {
        var tmp = rot.x;
        rot.x = -rot.z;
        rot.z = tmp;
        tmp = rot.y;
        rot.y = rot.w;
        rot.w = -tmp;
    }
}
```

use like so:

```csharp
Quaternion myRotation = ... ;
myRotation.FlipY180();
myTransform.localRotation = myRotation;
```

hth

**Comment by De-Panther** [comment]
Thanks!
