### ISSUE TITLE
Problems resolving package dependencies when importing glTFast into custom package [Question]

### ISSUE THREAD

**Issue by Bersaelor** [atteneder/glTFast#203]
Hey there, as the crowd here is super helpful, some of you may have done this before:

I'm trying to refactor some of our common code that uses gltf's into a custom package, to be shared by Unity Projects.

Now, my package.json looks like this:

```
{
  "name": "io.looc.tryon.core",
  "version": "1.0.0",
  "displayName": "TryOn Core classes",
  "description": "Shared tools for Unity projects so that WebGL does not have to import XR",
  "unity": "2021.1",
  "author": {
    "name": "Konrad Feiler",
    "email": "konrad@looc.io",
    "url": "https://looc.io"
  },
  "dependencies": {
    "com.unity.modules.jsonserialize": "1.0.0",
    "com.unity.modules.unitywebrequest": "1.0.0",
    "com.unity.modules.unitywebrequesttexture": "1.0.0",
    "com.unity.localization": "1.0.0-pre.9",
    "com.atteneder.gltfast": "4.0.0",
    "com.unity.textmeshpro": "3.0.6"
  },
  "scopedRegistries": [
    {
      "name": "OpenUPM",
      "url": "https://package.openupm.com",
      "scopes": [
        "com.atteneder",
        "com.atteneder.gltfast",
        "com.openupm"
      ]
    }
  ]
}
```

Yet, when I import this package into a unity project I get:

```
An error occurred while resolving packages:
  Package io.looc.tryon.core@file:/Users/konradfeiler/Source/tryoncore has invalid dependencies or related test packages:
    com.atteneder.gltfast (dependency): Package [com.atteneder.gltfast@4.0.0] cannot be found
```

I'm assuming this is a general UPM issue, not necessarily gltFast, but I thought maybe I could pick your brains? (I thought adding the `scopedRegistries` entry should be enough to get it to work?)

**Comment by atteneder** [comment]
Hi @Bersaelor ,

good question! Unfortunately I never implemented a (hard) package to package dependency involving a scoped registry.

If nobody answers here I'd try the Unity forums. Let me know if you find a solution!

Thanks

**Comment by Bersaelor** [comment]
thanks @atteneder , I posted a question in the forums: https://forum.unity.com/threads/third-party-package-dependency-for-custom-local-package-not-working.1134247/

It seems hard to find any solutions for this via google, because a lot of questions are very basic or from a time when Unity's UPM was still in beta prior to `2018.3`.

**Comment by Bersaelor** [comment]
Ok, so since `openupm` didn't work from the command line, what I had to do was add
```
  "scopedRegistries": [
    {
      "name": "OpenUPM",
      "url": "https://package.openupm.com",
      "scopes": [
        "com.atteneder",
        "com.atteneder.gltfast",
        "com.openupm"
      ]
    }
  ]
  ```
  manually to the main projects `manifest.json`. So Unity just ignores the `scopedRegistries` in the `package.json` of the local package and you have to add it manually.
