### ISSUE TITLE
Include shaders at runtime?

### ISSUE THREAD

**Issue by Thebinoman** [atteneder/glTFast#212]
I saw the documentation about having to include all expected shaders into the list of included shaders before build. Lets say I want to create some sort of a GLTF viewer, so users could load whatever file they want at runtime. What can be done to include the related shaders as well?
Thanks!

**Comment by atteneder** [comment]
Hi @Thebinoman ,

Thanks for your interest.

What I did with [glTFastWebDemo](https://github.com/atteneder/glTFastWebDemo) is load all models of the sample set at once in the Editor and export the currently used shaders (via `Save to Asset` in Project Settings > Graphics > Currently tracked shaders/variants). I then added this variant to the preloaded shaders.

But that won't work as soon as a variant is required that's not used in said set. You can also add all shaders (either built-in or ShaderGraphs, depending on your render pipeline) from glTFast to the "Always Included Shaders" (also in  in Project Settings > Graphics), but those are a lot of shader variants to carry along. So it would be good if you can cross some variants off the list (e.g. if you know you never load specular-glossiness based materials).

hth

**Comment by Thebinoman** [comment]
So, if I add all the shaders under /Pachages/glTFast/Runtime/Shader into the "Always included Shaders" list, a viewer like I mentioned can work correctly?

**Comment by atteneder** [comment]
> So, if I add all the shaders under /Pachages/glTFast/Runtime/Shader into the "Always included Shaders" list, a viewer like I mentioned could work correctly?

Yes!

One caveat: You need either the shaders in `/Packages/glTFast/Runtime/Shader/Built-In` (if you use the built-in render pipeline) OR the shader graphs inside `/Packages/glTFast/Runtime/Shader` if you use URP/HDRP, for example. Never both!

Inspect your build size though. It might be quite huge.

**Comment by Thebinoman** [comment]
Thank you!

**Comment by Thebinoman** [comment]
Using URP, it took 31 MB for an .apk build, if anyone is interested to know...
