### ISSUE TITLE
How to speed up loading multiple GLB files without lagging in Unity?

### ISSUE THREAD

**Issue by IvanMax3212** [atteneder/glTFast#216]
Dear @atteneder. Thanks for your attention to the pull requests which implemented the gltfast based on DOTS system.

This time I want to improve my app loading function. 
For my purpose, I have to open several GLB files (around 20 Files : 30MB ~ 200MB per each file) from file menu.
I used your IDeferAgent (both way) and referenced your sample codes which loads multiple files.
But if I call the function asynchronously, the FPS was 500~600 but even loading one file took unexpected time.
So for now, I am calling the load function synchronously. But as the result, the app gets stuck for a while (around 10 ~ 15 seconds).
I wanna smooth the loading progress like the others. 
Is there any solution for this?

Here are my PC's performance specs :

*intel Core i7-8700 (3.4GB, Cores : 6)
*16 GB of RAM
*Nvidia GTX 750 Ti

**Comment by atteneder** [comment]
Hi @IvanMax3212 ,

Seems like the files you intend to load are quite big, so I'm not surprised you struggle keeping the FPS constant.

What exactly do you mean with "unexpected time"? Do they load slowly or not at all or is the loading time inconsistent?
500-600 frames per second sounds like a lot/way too many. Can you check if those are correct? How did you measure them?

Anyway, it's hard to analyze without having the same content. If you can, please provide your assets (or representive parts of it).

Regards

**Comment by IvanMax3212** [comment]
The answer is "Not at all". I tried  loading one file using async function and waited over 5 minutes. But there was no result. 
The file I tried was only 40MB.
Here are the all file I have to load at once.
![image](https://user-images.githubusercontent.com/50035118/125846789-03c676fc-70b4-436d-9fe0-e8930d6ce447.png)

**Comment by IvanMax3212** [comment]
Or is this repository compatible with GPU Instancer unity asset?

**Comment by atteneder** [comment]
I've loaded files that are going into the giga bytes, so I presume something is wrong with your async loading code. Would you mind sharing either your code or a sample file? I see no other way to help you.

Can you elaborate what "GPU Instancer unity asset" is? glTFast supports the extension [EXT_mesh_gpu_instancing](https://github.com/KhronosGroup/glTF/blob/master/extensions/2.0/Vendor/EXT_mesh_gpu_instancing/README.md), if it's that what you mean.

**Comment by IvanMax3212** [comment]
Ok. sure. 
Here is the code file. I couldn't upload cs file directly so added txt extension to it.
As you can see in this file, I called the async function "LoadAllFiles" in sync function "BrowseFiles" with "Task.Run" command.

[Manager.cs.txt](https://github.com/atteneder/glTFast/files/6830115/Manager.cs.txt)

**Comment by IvanMax3212** [comment]
And in unity editor, nothing is showing in that case.
![image](https://user-images.githubusercontent.com/50035118/125936568-1843c5b5-959d-4ea3-a71a-9a6ebbf5f2b2.png)

**Comment by atteneder** [comment]
As far as I can see you're loading the glTF file, but you don't instantiate any scene it contains.

The reason that this is a two-step process is that this allows you to efficiently instantiate scenes of a glTF multiple times.

If you want an easier (but less flexible) way of loading a glTF file, have a look at the `GltfAsset` component, which takes care of instantiation as well.

Please have a look at the corresponding [documentation](https://github.com/atteneder/glTFast/blob/main/Documentation%7E/glTFast.md#custom-post-loading-behaviour)

Regards
