### ISSUE TITLE
error CS0246: The type or namespace name 'BurstCompile' could not be found (are you missing a using directive or an assembly reference?)

### ISSUE THREAD

**Issue by pxim** [atteneder/glTFast#222]
![image](https://user-images.githubusercontent.com/5111701/127279719-d5be1933-0416-4ead-91a8-f575ed6805df.png)
unity 2020.2
glTFast main

**Comment by sai-sen-tan** [comment]
Same here.
![CS0246error](https://user-images.githubusercontent.com/75355838/127447295-8d1b18d7-8d3b-4f77-a2f5-281bfe9d575c.png)

**Comment by hoATwhiskytree** [comment]
Hi,
I'm using Unity 2020.3.8f1. To get it working. I enabled preview packages and installed "Jobs." It fixes the error and seems to be fine afterwards

**Comment by atteneder** [comment]
Thanks for providing emergency help!

> Note: I'm currently on paternal leave and will only answer sporadically. I'll be able to provide help later this month.
