### ISSUE TITLE
Can I export GLB format from Unity with this plugin ?

### ISSUE THREAD

**Issue by pxim** [atteneder/glTFast#223]
Can I export GLB format from Unity with this plugin ?

**Comment by atteneder** [comment]
No, not yet at least.

For exporting I recommend to try this [fork of UnityGLTF](https://github.com/prefrontalcortex/UnityGLTF) by @hybridherbst for now.

> Note: I'm currently on paternal leave and will only answer sporadically. I'll be able to provide help later this month.

**Comment by pxim** [comment]
> No, not yet at least.
> 
> For exporting I recommend to try this [fork of UnityGLTF](https://github.com/prefrontalcortex/UnityGLTF) by @hybridherbst for now.
> 
> > Note: I'm currently on paternal leave and will only answer sporadically. I'll be able to provide help later this month.

Ok,.
Thanks, I'm using babylon plugin export gltf now.
