### ISSUE TITLE
NullReferenceException occur in MeshPrimitive Equals

### ISSUE THREAD

**Issue by decoc** [atteneder/glTFast#224]
## Problem

if `attributes.Equals(b.attributes)` equals false  or `targets == null` equals false, `targets` and `b.targets` require to be not null

```cs
 public override bool Equals(object obj)
        {
            ........

            // NullReference occur when
            // (attributes.Equals(b.attributes)) == false
            // or
            // (targets==null) == false
            // and
            // targets or b.targets are null
            return attributes.Equals(b.attributes) && targets==null ||  targets.Equals(b.targets);
        }
```

## Proposal

```cs
 public override bool Equals(object obj)
        {
            ........

            // Check if both targets and b.targets are not null 
            return attributes.Equals(b.attributes) && targets==null || (targets != null && b.targets != null) && targets.Equals(b.targets);
        }
```

**Comment by atteneder** [comment]
> Note: I'm currently on paternal leave and will only answer sporadically. I'll be able to provide help later this month.

**Comment by atteneder** [comment]
Hi @decoc ,

Good find, thanks! Can you share a glTF file that let's me reproduce this bug?

I'm writing a test for this currently and there's another issue: `targets.Equals(b.targets)` is not properly comparing array elements.

**Comment by atteneder** [comment]
Fix is pushed. Will test extensively later. Please test your own scenes as well!

Thanks!
