### ISSUE TITLE
Unity Content Delivery?

### ISSUE THREAD

**Issue by hoATwhiskytree** [atteneder/glTFast#225]
Hi,
Has anyone been able to get glb files hosted on Unity Content Delivery to work? If I have a full URL with filename and extension in the path, it works fine. But I can't seem to get it to work on IOS or Android, but it loads up in the editor. Any thoughts or suggestions?

**Comment by atteneder** [comment]
> Note: I'm currently on paternal leave and will only answer sporadically. I'll be able to provide help later this month.
