### ISSUE TITLE
Issue with essentially empty .glb file

### ISSUE THREAD

**Issue by bpepers-me** [atteneder/glTFast#227]
I have an example GLB file which I think is valid but it has zero geometry in it.  Looks like the code doesn't take this corner case into account and expects if it parses something, it results in some geometry.  I'm looking at a patch to fix this but thought I'd report it in case there is already some knowledge of the problem?

I can of course provide the file is needed.  It's just 128 bytes and the JSON chunk content is:

{"asset":{"generator":"cesium-osm","version":"2.0"},"nodes":[{}],"scenes":[{"nodes":[0]}],"scene":0}

**Comment by bpepers-me** [comment]
Here's the file.  Didn't realize I could just drag and drop it though I had to zip it to be accepted.

[128.zip](https://github.com/atteneder/glTFast/files/6935651/128.zip)

**Comment by atteneder** [comment]
@bpepers-me Thanks for the feedback!

glTFast's next release won't choke on this file anymore.

Note: I'd say this file, although nonsensical, is a valid glTF. Only thing I'd consider an error is that the glb file has an empty (zero length) binary chunk. I'd argue that shouldn't be there. Please forward this feedback to whoever created this file (or the maintainers of the software that exported it).

Thanks!

**Comment by bpepers-me** [comment]
Thanks for fixing it!  I agree it's a silly file to create.  It was Cesium that had this where they have content at each node in their 3D Tiles file format which is stored as a GLB file.  Guess when there is no content they are still generating this empty file.  I'll contact them about it.


--
Brad

On August 24, 2021 at 2:30 AM, Andreas Atteneder ***@***.***> wrote:






@bpepers-me Thanks for the feedback!

glTFast's next release won't choke on this file anymore.

Note: I'd say this file, although nonsensical, is a valid glTF. Only thing I'd consider an error is that the glb file has an empty (zero length) binary chunk. I'd argue that shouldn't be there. Please forward this feedback to whoever created this file (or the maintainers of the software that exported it).

Thanks!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
