### ISSUE TITLE
Support for multiple materials on one mesh

### ISSUE THREAD

**Issue by wangyanmeego** [atteneder/glTFast#239]
I have use glTFFast to load glb at run-time, it works great except for it can not support multiple material on one mesh. it seperate meshes by one material. I wan to keep the mesh completely. Is there any ways to  set options for this. Looking for reply.

**Comment by atteneder** [comment]
Hi @wangyanmeego ,

Thanks for bringing it to my attention. Would you mind sharing, what exact problem this would fix for you? That would help me prioritize the fix properly.

This has been brought up already in #153 (therefore I close this one) and I acknowledge the problem and want to solve this at some point.

Unfortunately it's not a low-hanging fruit, so it'll have to wait for the next refactoring of that particular code.

Thanks

**Comment by wangyanmeego** [comment]
Thanks for your attention to this problem. I make a run-time editor to mark notes based on a mesh, and show the meshes on AR. When I model a 3D file and apply some materials on one mesh. But when I load it into Unity scene, it seperates meshes by materials, that's not what i want. So I hope the loaded mesh is the same structure as 3D model software. By the way, i use Blender to create models. If any time you have solved this, please let me know, I'll really appreciate it. Maybe you can make a option to support single material and multiple materials on one mesh.
