### ISSUE TITLE
specularFactor and diffuseFactor is not respected in KHR_materials_pbrSpecularGlossiness extension

### ISSUE THREAD

**Issue by digimatic** [atteneder/glTFast#241]
When loading a model that uses the KHR_materials_pbrSpecularGlossiness and sets specularFactor and diffuseFactor and have no texture, it shall use that specularFactor and diffuseFactor. Seems not to be implemented?

By request I can send you an example file.

**Comment by atteneder** [comment]
Hi @digimatic ,

Thanks for the report. A test file would indeed be great, please!

**Comment by digimatic** [comment]
Hello,

Here is a sample:https://www.dropbox.com/s/pbv4zczbpgmazoe/Pump3.glb?dl=0
The small bolt in the center for the long shaft shall be orange (that is
material 11, 0-based), if I open in vs code it is on line 4462.

/Peter Westerström

Den mån 6 sep. 2021 kl 15:04 skrev Andreas Atteneder <
***@***.***>:
