### ISSUE TITLE
Exception in New Release  

### ISSUE THREAD

**Issue by JSWorkspace1** [atteneder/glTFast#245]
**Describe the bug**
After Upgrading to 4.3.0 this Exception appears when loading the first model after application start.
The model itself loaded fine and the exception didnt repeat when loading multiple models.

![Screenshot 2021-09-10 162521](https://user-images.githubusercontent.com/23420842/132874645-42ea91de-53c9-4c30-a07a-514acf8a2170.png)

Also some unity Crashes accrued could not really repo reliably sometimes while loading sometimes minutes later but they stopped after downgrading to glTFast 4.2.1. 

**Desktop **
 - glTFast 4.3.0
 - Unity Editor version [2021.2.0b9]
 - Platform: [Windows Mono Net Standart]

**Comment by atteneder** [comment]
Thanks for the report!

Any chance you can provide a file that causes this?

**Comment by JSWorkspace1** [comment]
I can check again on Monday but i think a wasnt any specific on. Just happened with any on first load.  
Oh and I was loading directly from a byte[] if that makes a difference.

**Comment by JSWorkspace1** [comment]
Ok quickly  made a demoProject to reproduze exception.
I tried some diffrent .glb. It had happend for all of them.
I put one in the Ressource Folder. Just copy to a folder and paste the path into Textfield and hit load.
 
[Bug_reportDemo.zip](https://github.com/atteneder/glTFast/files/7152548/Bug_reportDemo.zip)

**Comment by atteneder** [comment]
@JSWorkspace1 first tests with Unity2019LTS and Burst 1.4.11 were successful. I'll test 2021.2 beta soon.

Which Burst version did you use?

**Comment by JSWorkspace1** [comment]
Packing Manager says Burst Version 1.6.0-pre.2

**Comment by atteneder** [comment]
The Burst errors should be gone now (with 4.3.1; to be released).

For other instability issues, please raise a dedicated issue, preferably with reproducable steps and assets.

Thanks ❤️
