### ISSUE TITLE
Animation Jitter on import of humanoid animated GLTF - need InterpolationMode settings!

### ISSUE THREAD

**Issue by ROBYER1** [atteneder/glTFast#250]
**Describe the bug**
We have found this issue across most Unity GLTF importers and haven't found a fix yet, the same models play back just fine using web GLTF viewers like https://sandbox.babylonjs.com/

When importing a humanoid animated character in a gltf in Unity, the playback is jittery and skipping, we have tried various export settings with Blender and Cinema4D only to see consistent results of jittering, even using mixamo characters and, separately with our own motion capture data.

**Files**

Direct links:
https://drive.google.com/uc?export=download&id=1uBO5gmF1wssFvYfwL1kGQDO3AyE0jjpO
https://drive.google.com/uc?export=download&id=1aP3cnlMdPla1GC3aZ6XA5n1uhaZInvq0

Gdrive links
https://drive.google.com/file/d/1uBO5gmF1wssFvYfwL1kGQDO3AyE0jjpO/view?usp=sharing
https://drive.google.com/file/d/1aP3cnlMdPla1GC3aZ6XA5n1uhaZInvq0/view?usp=sharing

**To Reproduce**
1. Use the links above to import the models
2. See in playback in Unity the animation is jittery

**Expected behavior**
Animation playback of a file should be smooth, this seems to only happen if keyframe interpolation is set to step rather than linear

**Screenshots**

![Glitchninja1](https://user-images.githubusercontent.com/10745594/135838888-aeea8130-e3d0-4955-83d6-638bea694e31.gif)

**Desktop (please complete the following information):**
 - glTFast version 4.3.1
 - Unity Editor version 2020.1.1.17f1
 - Render Pipeline and version 11.0.0
 - Platform: Editor Windows, Windows exe build, Android, IOS
 
**Additional context**

**Comment by ROBYER1** [comment]
In order to fix this, we found that the ImportSettings.InterpolationMode.ImportFromFile was not working correctly or the exported files we had were not including the interpolation mode in the GLTF file.

To fix we had to do this:
``` legacyAnimSetting = new ImportSettings();
legacyAnimSetting.interpolationMode = InterpolationMode.STEP;```

**Comment by atteneder** [comment]
After some investigation I'm quite sure the tangent calculation for (at least) LINEAR is incorrect. Alternative Unity glTF importers seem to do it different, but also incorrect :(

**Comment by atteneder** [comment]
Regarding default interpolation method we have to adhere to the specification, which says [LINEAR is the default](https://www.khronos.org/registry/glTF/specs/2.0/glTF-2.0.html#_animation_sampler_interpolation).

**Comment by atteneder** [comment]
I'll fix this in the package by adding a check at run-time.

One could argue that this check/fix should be done at engine level, but that would add a bit of run-time overhead for all users, even ones that have their rotation values correct in first place. Also, landing a fix in the engine takes longer.

I'd say it would be best if all glTF exporters would make sure their quaternion rotations are pre-fixed. If that was the case, we wouldn't see this artifact and the check could me removed (or made optional).

**Comment by atteneder** [comment]
> Great stuff, thanks and looking forward to the next release, now I can work on removing SimpleGLTF from our project and moving to using GLTFast

@ROBYER1 that's great to hear! Let me know if that goes smooth. I'll keep on giving support and I'm always happy to se use-cases in the wild.

> still baffled as I seem to be one of the few people to find this issue when the Khronos Group official UnityGLTF importer has the same issue! Baffling.

My theory: Not all animations are affected, out of those only a minority of users report an issue (others move on, away from glTF) and lastly, most projects don't have the time/resource to provide the necessary support. Luckily my work is funded 💪

Cheers!
