### ISSUE TITLE
Occasionally one-frame animation twitch

### ISSUE THREAD

**Issue by Hiverlab-Ray** [atteneder/glTFast#251]
**Describe the bug**
When playing GLB animation, its animation sometimes twitches unexpectedly within one frame in a non-consistent pattern (i.e. the twitching doesn't happen on same frame of animation clip but happens at random frames).

**Files**
Pinocchio: [Pinocchio.zip](https://github.com/atteneder/glTFast/files/7291393/Pinocchio.zip)
Betty Boop: [BettyBoop.zip](https://github.com/atteneder/glTFast/files/7291394/BettyBoop.zip)

**To Reproduce**
1. Load attached GLB files using GLTFast.GltfImport() and gltf.Load function.
2. Once loading success, instantiate result model using gltf.InstantiateMainScene function.

**Expected behavior**
Pinocchio: The limbs should be smoothly animated without any twitching.
Betty Boop: The facial expressions should be always sticking to the face without any twitching and offsetting.

**Screenshots**
Pinocchio: https://youtu.be/qBx1BPphLbs
Betty Boop: https://youtu.be/Fjt1HQ2MSZc

**Desktop (please complete the following information):**
 - glTFast version: 4.3.1
 - Unity Editor version: 2020.3.7f1
 - Render Pipeline and version: Universal Render Pipeline 10.5.0
 - Platform: Editor, WebGL (Chrome), Android

**Additional context**
The atttached GLB models animate smoothly when opened using https://gltf-viewer.donmccurdy.com/ and Windows 3D Viewer.

**Comment by atteneder** [comment]
@Hiverlab-Ray thanks for reporting!

It seems similar to the issue #250. I was able to reproduce it and I'm investigating now.

**Comment by atteneder** [comment]
The fix landed in the main branch and will soon be in the next release (after some more testing).
