### ISSUE TITLE
2019.4.20f1 Compiler Errors after importing the installer package

### ISSUE THREAD

**Issue by ThanosRestas** [atteneder/glTFast#252]
**Describe the bug**
After importing the recommended installer package from **main** I get compiler errors related to the BurstAotCompiler

**Screenshots**
![image](https://user-images.githubusercontent.com/5999342/136659962-b38898f6-1c12-4346-b679-cca2cc1a1395.png)

 - **glTFast version :** 2.0
 - **Unity Editor version** : 2019.4.20f1

**Comment by De-Panther** [comment]
Had the same issues with Unity 2019.4.7f1.
It's a bug in the Unity Burst package.
Reported a bug to Unity - 1371912
Hope it'll get to their priority

**Comment by ThanosRestas** [comment]
> And if you update to a more recent version of burst?

Same unfortunately :(

![image](https://user-images.githubusercontent.com/5999342/136786499-595c2489-af20-4513-a76f-3206760d3f38.png)

**Comment by atteneder** [comment]
@ThanosRestas Thanks for reporting!

I'm not having this error, so until the original problem is fixed we might figure out why it's not compiling for you, shall we?

What is your active build platform?
What packages are activated/installed in your project?

I'm using 2019.4.31f1 and Burst 1.4.11 with Standalone(macOS) as the active target. Here's the list of the packages:

```
    "com.atteneder.draco": "3.3.1",
    "com.atteneder.gltfast": "4.3.1",
    "com.atteneder.ktx": "1.1.1",
    "com.unity.burst": "1.4.11",
    "com.unity.ext.nunit": "1.0.6",
    "com.unity.ide.rider": "3.0.7",
    "com.unity.jobs": "0.2.10-preview.13",
    "com.unity.performance.profile-analyzer": "1.1.0",
    "com.unity.test-framework": "1.1.29",
    "com.unity.test-framework.performance": "2.8.0-preview",
    "com.unity.testtools.codecoverage": "1.1.0",
    "com.unity.ui.builder": "1.0.0-preview.17",
    "com.unity.modules.animation": "1.0.0",
    "com.unity.modules.imageconversion": "1.0.0",
    "com.unity.modules.imgui": "1.0.0",
    "com.unity.modules.jsonserialize": "1.0.0",
    "com.unity.modules.physics": "1.0.0",
    "com.unity.modules.physics2d": "1.0.0",
    "com.unity.modules.unitywebrequest": "1.0.0",
    "com.unity.modules.unitywebrequesttexture": "1.0.0"
```

Could you try and figure out if you still have the error when using a similar setup?
Also, whenever you install or up-/downgrade Burst, make sure to restart the Editor.

**Comment by De-Panther** [comment]
I think that in the middle of ths major versions, Unity added some platforms (new xbox, ps5...).
So in later versions of 2019.4 or 2020.2 it'll work, but on earliers it won't

**Comment by ThanosRestas** [comment]
After tinkering around for a while, updating my project to version **2020.3.20f1** works perfectly and also supports the rest of the tools I'm using. Probably related to what  @De-Panther mentioned here:
> I think that in the middle of ths major versions, Unity added some platforms (new xbox, ps5...). So in later versions of 2019.4 or 2020.2 it'll work, but on earliers it won't

Still the issue exists on some Unity versions so I guess it can be noted on the repo or something ? I guess the issue can be closed for now but I wouldn't want anyone else to face the issue I was having and lose his precious time from creating ! 😅
