### ISSUE TITLE
Runtime Export

### ISSUE THREAD

**Issue by atteneder** [atteneder/glTFast#259]
Make comprehensive export available at runtime.

The lack of access to source assets (especially meshes and texture) makes runtime export somewhat harder.

Also there's an increased priority on performance and frame rate stability.

**Comment by hybridherbst** [comment]
Please don't forget runtime animation export :)

USD for Unity solves that in a pretty elegant way via a Timeline Recorder track + clip setup. (but they're lacking editor-time animation clip export, so not quite perfect either).

In an ideal world there would be:
- edit-time animation clip and timeline export 
- and runtime timeline export (no animation clip access here)

**Comment by dev9spatial** [comment]
> Please don't forget runtime animation export :)
> 
> USD for Unity solves that in a pretty elegant way via a Timeline Recorder track + clip setup. (but they're lacking editor-time animation clip export, so not quite perfect either).
> 
> In an ideal world there would be:
> 
> * edit-time animation clip and timeline export
> * and runtime timeline export (no animation clip access here)

@hybridherbst 
Is there a repo you know of for runtime USD export?

**Comment by hybridherbst** [comment]
The official (but still preview) USD Unity Package can do that (at least it could when I last tested it), since it's using the PlayableGraph API:
https://docs.unity3d.com/Manual/com.unity.formats.usd.html

**Comment by AnasMadhav** [comment]
In which asmdef , gltFast and gltFast.Exort to be added to get the GLTFast.Export header file ?????

**Comment by atteneder** [comment]
> In which asmdef , gltFast and gltFast.Export to be added to get the GLTFast.Export header file ?????

In the one that also contains your code that triggers the export (i.e. your own asmdef). This implies that you have to structure your own code in an asmdef. hth.
