### ISSUE TITLE
gltfpacked `BoxAnimated`: animation is incorrect

### ISSUE THREAD

**Issue by atteneder** [atteneder/glTFast#264]
The animation works with the original and also non-compressed (but quantized) gltfpack version.

with meshopt compression the translation is not working.

Expected the same animation as the original.

 - glTFast version 4.4.3
 - Unity Editor version 2019.4.31f1
 - Render Pipeline and version BiRP
 - Platform: Editor macOS
 - gltfpack 0.16

Note: Looks like gltfpack creates a lot of in-between keyframes.

**Comment by ROBYER1** [comment]
I am hopefully going to be testing this out to compress animation in files to reduce bandwidth, are there any current fixes in the works for this?

**Comment by atteneder** [comment]
@ROBYER1 Not yet, as I'm not certain how big the actual usage/user pain on this newish feature is. Did you ran into trouble? If so, feel free to provide additional reproduction glTFs and I'll take a look sooner.

**Comment by atteneder** [comment]
There was an error in the meshoptimizer decompression for Unity package. A fixed version 0.1.0-preview.3 is in the making.

**Comment by ROBYER1** [comment]
@atteneder Does that affect this issue also?
https://github.com/atteneder/glTFast/issues/294

**Comment by atteneder** [comment]
> @atteneder Does that affect this issue also? #294

@ROBYER1 Unfortunately the other issue is not resolved yet. I'll have a look after the holidays.

**Comment by atteneder** [comment]
fyi: The *meshoptimizer decompression for Unity* package was updated just now!
