### ISSUE TITLE
Error building with 4.4.4: `Library/PackageCache/com.atteneder.gltfast@4.4.4/Runtime/Scripts/Schema/Root.cs(149,17): error CS0103: The name 'animations' does not exist in the current context`

### ISSUE THREAD

**Issue by Bersaelor** [atteneder/glTFast#267]
**Describe the bug**
Updated Gltfast dependency to 4.4.4, got the error:

```
Library/PackageCache/com.atteneder.gltfast@4.4.4/Runtime/Scripts/Schema/Root.cs(149,17): error CS0103: The name 'animations' does not exist in the current context
```

**Expected behavior**
Project compiles

**Desktop (please complete the following information):**
 - glTFast version: 4.4.4
 - Unity Editor version 2021.2.0f1
 - Platform: WebGL

**Comment by Bersaelor** [comment]
This is probably again because my WebGL project is slimmed down , so it's file size is minimal:

<img width="503" alt="Screenshot 2021-10-31 at 15 19 27" src="https://user-images.githubusercontent.com/4517582/139588024-92e48352-f2a5-47a6-903d-56e836ac5354.png">

**Comment by atteneder** [comment]
@Bersaelor Thanks a lot for reporting.

I'll take a look at it right now.
As far as I remember this is the second time you reported that some update broke a non-animation project. That and the other hotfixes I had to do recently are a clear sign that proper testing and CI has to happen soon.

**Comment by atteneder** [comment]
glTFast 4.4.5 with a fix is in the build.

Sorry for the inconvenience
