### ISSUE TITLE
Error: Normalized Positions will likely produce incorrect results

### ISSUE THREAD

**Issue by hybridherbst** [atteneder/glTFast#268]
**Describe the bug**
The console told me to log a bug so I do :)
The attached files log
```Normalized Positions will likely produce incorrect results. Please report this error```
upon import.

**Files**
[MultiRange.zip](https://github.com/atteneder/glTFast/files/7478422/MultiRange.zip)
[MultiRange2.etc1s+meshopt.zip](https://github.com/atteneder/glTFast/files/7478423/MultiRange2.etc1s%2Bmeshopt.zip)

**To Reproduce**
Import via glTFast, for the etc1s+meshopt file make sure to have the right packages installed.

**Expected behavior**
Clean import

**Screenshots**
 
![image](https://user-images.githubusercontent.com/2693840/140418811-b23edf39-6300-4dc4-b647-21344a4d8264.png)
![image](https://user-images.githubusercontent.com/2693840/140418834-7c0f8d3b-8af6-4cae-ac39-597a16c201a5.png)

**Comment by atteneder** [comment]
Note: I noticed the file took 14 sec on my machine to load, which is way too much. I've found the problem and fixed it:

https://github.com/atteneder/glTFast/commit/44141f2c9511a399dbe07790f1ce01829233e28d

It's now down to 1.2 sec here.
