### ISSUE TITLE
Assets/gltfManager.cs(4,15): error CS0234: The type or namespace name 'Export' does not exist in the namespace 'GLTFast' 

### ISSUE THREAD

**Issue by klauskobald** [atteneder/glTFast#270]
**Describe the bug**
It does not compile when I add that test script for exporting.
Namespace is not found.

**To Reproduce**
I installed it as described.
The Menu File > Export is actually working. Export is done.

**Expected behavior**
no compile error

**Screenshots**
<img width="573" alt="image" src="https://user-images.githubusercontent.com/278428/140665621-e2e74da7-a466-476b-93cf-7d31717c83e3.png">

**Desktop (please complete the following information):**
 - glTFast version 4.4.5
 - Unity Editor version 2020.3.21
 - Render Pipeline and version build in
 - Platform: Editor Mac M1

**Comment by atteneder** [comment]
Hi @klauskobald ,

Thanks for trying it out and sorry for the inconvenience. The assembly of glTFast export is not auto-referenced, so you **have to** use an assembly definition and reference both `glTFast` and `glTFast.Export`.

I'm working on updating the documentation properly.

**Comment by Morgan-6Freedom** [comment]
I did that in my Visual Studio : 
![image](https://user-images.githubusercontent.com/49686866/140993445-3b6ff91a-7d8d-4097-a897-d143161f89b5.png)

but my Unity says that : 
![image](https://user-images.githubusercontent.com/49686866/140993513-f125ad11-c776-444a-b760-541f3456be99.png)

**Comment by Morgan-6Freedom** [comment]
I succeeded to make it work :
1) create an assembly definition in the same folder as your script : 
![image](https://user-images.githubusercontent.com/49686866/140993731-352c8aae-82a6-4bb2-b77c-9c1e8c7bfbe8.png)

2) references the GLTFast + GlTFastExport : 
![image](https://user-images.githubusercontent.com/49686866/140993893-2ebf1e09-ee3b-4238-ab5e-bc5c4ce0ab20.png)

**Comment by atteneder** [comment]
Thanks @Morgan-6Freedom , that's a great guide!

**Comment by Morgan-6Freedom** [comment]
you can use thoses image for your documentation if you want to
