### ISSUE TITLE
glTF export (containing meshes) is currently not supported on Unity 2020.1 and older

### ISSUE THREAD

**Issue by rrrzzz** [atteneder/glTFast#273]
I get this message although I am on Unity 2019.4.32f1. Trying to export from File -> Export Selection a unity primitive cylinder

**Comment by atteneder** [comment]
This is expected (you might want to re-read the message with emphasis on the last two words). For export you currently have to use 2020.2 or newer.

At some point I might implement a different mesh export that is backwards compatible, but atm it is a low priority. Is there a strong reason for you to stick with 2019 LTS and what is it?

**Comment by rrrzzz** [comment]
Thanks for the reply. I am terribly sorry, I totally missed the second part. At my job we use a custom Unity version which is 2019 so you might say it's personal reasons. How much of a rework is needed to enable backwards compatibility? I think I might try adding it myself if it doesn't require to dig too deep.

**Comment by atteneder** [comment]
Ok, here are short-term solutions:

- Use the alternative [UnityGLTF][https://github.com/prefrontalcortex/UnityGLTF] for now. It should work with older versions as well
- If export is a one-time thing
  - Make a copy of your project
  - Open it with 2020.2 (or newer)
  - Export your assets (once) and delete the copy

If you want to look into porting to 2019:

We need an alternative for `GltfWriter.BakeMeshes` that uses the simple Mesh API. On a high-level it should iterate all meshes (`m_Meshes`), convert its attributes and indices into buffers and write them to the main buffer via `WriteBufferViewToBuffer`.

> Note: This requires in-depth knowledge of glTF's structure, so make sure you read the specification thoroughly.

hth
