### ISSUE TITLE
Loaded animated model blinks

### ISSUE THREAD

**Issue by wonkee-kim** [atteneder/glTFast#274]
**Describe the bug**
**Screenshots**
![aeWvH0fx0g](https://user-images.githubusercontent.com/830808/140819570-f5313d31-85ba-46dd-897c-d099a1cdd961.gif)
This animated model appeared blinking and this is because positions of some keyframes are NaN.
![gltfastAnimation copy](https://user-images.githubusercontent.com/830808/140820142-dec28adc-ebd2-49ed-94fb-e292eaf9fc2e.jpg)

This can be fixed when I import this model to Blender and export it again.

**Files**
I sent this file to andreas dot atteneder at gmail dot com

**To Reproduce**
1. Import Trooper.glb model.
2. Play animation.
3. See model is blinking.

**Expected behavior**
Keyframe values are imported properly and animated smoothly.

**Desktop (please complete the following information):**
 - glTFast version : 4.4.0
 - Unity Editor version : 2020.3.19f1
 - Render Pipeline and version : Built-in render pipeline
 - Platform: Any platform.
 
additionally (if significant for the bug):

 - Device: Any device
 - OS: Any os

**Additional context**
This didn't happen before. (old version)

**Comment by atteneder** [comment]
Hi @wonkee-kim ,

First of all, thanks for the excellent report. Unfortunately I couldn't reproduce (even with 4.4.0; did you send the correct file to me?), but I have the suspicion that this was solved via #262. Could you please update to the most recent version (4.4.5) and test again?

Regards

**Comment by atteneder** [comment]
I assume it was solved. Please re-open if I'm mistaken.
