### ISSUE TITLE
Just opened the stuff up for the first time and

### ISSUE THREAD

**Issue by Siccity** [atteneder/glTFast#28]
![image](https://user-images.githubusercontent.com/6402525/40510298-8b24b302-5f9c-11e8-82ba-20a12555e2b7.png)

**Comment by atteneder** [comment]
Thanks for the report!
Looks like the bufferView's byteStride/byteOffset is not taken into consideration when fetching the vertex positions.

**Comment by atteneder** [comment]
fixed in 8d855bae0eafcc97dbad722c9832ee468d872dc7
