### ISSUE TITLE
GLB texture in android 

### ISSUE THREAD

**Issue by A9191** [atteneder/glTFast#280]
I'm using the same code as mentioned in the documentation:  
var gltf = gameObject.AddComponent<GLTFast.GltfAsset>();
gltf.url = "https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/Duck/glTF/Duck.gltf";

I loaded my GLB file with the texture in Unity on windows player, but when I run the same thing on android, the texture doesn't work and stays in pink color. 

 - glTFast version : 4.4.7
 - Unity Editor version 2021.2.1f1
 - Render Pipeline and version Universal Render Pipeline  12.1.1
 - Platform: Android

![Graphic](https://user-images.githubusercontent.com/21275654/142269496-fc76c3a7-6ede-46e9-afd5-66460a45af75.JPG)

**Comment by mikeskydev** [comment]
This sounds like an instance of not including all the required shaders in the android build, which would explain why it works in editor but not on android: https://github.com/atteneder/glTFast/blob/main/Documentation~/glTFast.md#materials-and-shader-variants. You're in the right panel, you may just have to include the shaders you require for your model:
![image](https://user-images.githubusercontent.com/9121007/142412003-c6ee9047-8fdb-40b7-96d8-d9310161a0ab.png)

Note: including everything can take a long time to build all the shader variants, so if you know which corners you need to cut, it may be worth taking them!
