### ISSUE TITLE
Assets/GLTFast/GLTFast.cs(345,31): error CS1644: Feature `null propagating operator' cannot be used because it is not part of the C# 4.0 language specification

### ISSUE THREAD

**Issue by Rysm** [atteneder/glTFast#29]
Occurs when I import into fresh Unity 2018.3 project

**Comment by atteneder** [comment]
Is there a reason why you closed the issue?
I don't have access to 2018.3 (2018.2 is in beta atm). I'm wondering whether you are an insider or confused a digit :)

**Comment by Rysm** [comment]
I confused a digit - whoops! 

Also, I closed it because I figured out the issue by selection the correct version .NET

**Comment by atteneder** [comment]
Note: glTFast 0.7.0 now supports Unity back to 2018.2, also with legacy C# settings
