### ISSUE TITLE
glb动画设置成Mecanim时 无法循环播放

### ISSUE THREAD

**Issue by qq3600605** [atteneder/glTFast#291]
glb动画设置成Mecanim时 无法循环播放
直接在unity里设置glb的Animtion为Mecanim时，glb里面的动画的Loop Time也未勾选
运行时设置AnimationClip的wrapMode为loop也不行

**Comment by atteneder** [comment]
@qq3600605 Thanks for the report.

Paraphrasing via Google Translate:
> When glb animation is set to Mecanim, it cannot be played in a loop. When the animation of glb is set to Mecanim directly in unity, the Loop Time of the animation in glb is also unchecked. Setting the wrapMode of AnimationClip to loop during runtime is also not working

I'll try to have a look soon

**Comment by atteneder** [comment]
I have now hard-coded glTFast to set the Loop Time to true.

The glTF specification does not contain a definition for using or looping clips, but at least now it's consistent with legacy clips (where WrapMode.Loop is set hard coded as well).

The better solution would be providing a proper Inspector GUI to customize each and every AnimationClip, but that's a larger endeavor in the context of Editor Import improvements I'll note down.

hth
