### ISSUE TITLE
Readme - how to install meshoptimizer decompression for Unity?

### ISSUE THREAD

**Issue by ROBYER1** [atteneder/glTFast#293]
This is more of a Readme update request and a post to help others than a bug, I couldn't seem to find much online about the EXT_mesh decompression plugin for Unity or how to add it (the unity documentation here was also [vague](https://docs.unity3d.com/Packages/com.unity.meshopt.decompress@0.1/manual/index.html))

I had to manually add this to the package manifest json in my Unity project
`"com.unity.meshopt.decompress": "0.1.0-preview.2",`

**Comment by atteneder** [comment]
I approve this message!

Thanks @ROBYER1
