### ISSUE TITLE
Issue with armature/animation on EXT_Meshopt_compression model

### ISSUE THREAD

**Issue by ROBYER1** [atteneder/glTFast#294]
**Describe the bug**
I am finding that imported humanoid models using KTX and EXT_Meshopt_compression have issues with visibility of alpha textures and parts of the animation playback appear to have stretched or exaggerated weights at some joints.

This can be seen in the screenshots below, from some angles the hair on this model disappears and the shoulders/groin are stretched outwards

**Files**

Original GLTF model, all I did was export it from Adobe Mixamo as FBX for Unity, 30fps, import to Blender then re-export as a gltf embedded file
https://drive.google.com/file/d/1OG8QqIrMuJzFJTx_RxBlbR0y2NdnhRt8/view?usp=sharing

Same GLTF compressed into a GLB file using [MeshOptimizer-gltfpack](https://github.com/zeux/meshoptimizer/tree/master/gltf) with KTX and Meshopt_Compression,
the command was:
`gltfpack -i testcompress.gltf -o compressed.glb -cc -tc`
https://drive.google.com/file/d/1HKmcFf6G6aAQR9xQqAHTIMSwQGtyGQbA/view?usp=sharing

**To Reproduce**
1. Download the base file, install [MeshOptimizer-gltfpack](https://github.com/zeux/meshoptimizer/tree/master/gltf)
2. I had to manually add this to the package manifest json in my Unity project
"com.unity.meshopt.decompress": "0.1.0-preview.2",
3. Add KTX Compression to project - https://github.com/atteneder/KtxUnity.git for KTX texture compression
4. With the base file, in command line use this to convert the file `gltfpack -i testcompress.gltf -o compressed.glb -cc -tc`
5. Test out the compressed file in a Web GLTF viewer like this one - https://gltf-viewer.donmccurdy.com/
6. Load the same model with GLTFast in Unity, notice that the hair on the character disappears at some angles in scene/game view and the shoulders/bum are stretched outwards 

**Expected behavior**
Model should animate and look similar to how it does with other GLTF viewers using the compressed file

**Screenshots**
![Tester1](https://user-images.githubusercontent.com/10745594/145417340-7cac95a2-cb60-49dd-b6b1-cabbe46d9813.gif)
![KTXandCompress](https://user-images.githubusercontent.com/10745594/145416127-06236aff-bcdd-42fd-bdc3-135bd0d432ad.JPG)

How the model looks when correct (and should look) when using the [Don Mccurdy GLTF web viewer](https://gltf-viewer.donmccurdy.com/)
![donmccurdy](https://user-images.githubusercontent.com/10745594/145418026-4118a08f-3d09-4355-af47-d4b0af0b386e.JPG)

**Desktop (please complete the following information):**
 - glTFast version 4.4.8
 - Unity Editor version 2021.1.17f1
 - Render Pipeline and version URP 11.0.0
 - Platform: Editor Mainly, Windows, Android, IOS, WebGL
 -I had to manually add this to the package manifest json in my Unity project
"com.unity.meshopt.decompress": "0.1.0-preview.2",

**Comment by ROBYER1** [comment]
Just to add, the hair node disappears at certain zoom based on the property 'Update when offscreen' on the MeshRenderer. If I enable that property, the hair stays visible always. I am not sure what the best practice should be here in this case, it's not the end of the world if I have to search for the skinned renderers on the spawned object and enable that at runtime but it's a bit of a weird one!

**Comment by atteneder** [comment]
@ROBYER1 Thanks for the report.

The disappearing of hair seems to be covered in #301 already.

The strange skinning artifacts I can reproduce with meshopt 0.1.0-preview.3. I'll have a look.

**Comment by atteneder** [comment]
It looks like after the meshopt compression the per-vertex joints are not sorted by weight anymore. glTF comes with quadruplets of bone joints/weights, but Unity may only consider the first 1 or two joints for skin deformation (depending on the quality setting).

I have a fix in the making (sorting joints per vertex in a C# job)

**Comment by atteneder** [comment]
Note: Thanks to @zeux future versions of gltfpack will sort joints by weight

https://github.com/zeux/meshoptimizer/pull/399

**Comment by ROBYER1** [comment]
@atteneder Thanks for looking into this for the fix, if there is anything to fix I can test this with, please let me know!
