### ISSUE TITLE
Unity webgl build- out of memory error in runtime

### ISSUE THREAD

**Issue by TEAServ** [atteneder/glTFast#295]
Hello,
I have an issue in run-time for the webgl build 
when I try to run-time import a big and heavy glb file the app is freezing and the browser console shows an error of memory allocation "Out of memory",
my unity project is so lightweight and simple, just using the gltfast package,
when I tried to import the same file with the **[demo webgl build](https://gltf.pixel.engineer/)** 
it goes so smoothly without any error, so I'm wondering! should I modify the project with someway to be able to act with the heavy duty files the same way that the webgl demo does?
my build works well with the low and medium duty files,

thanks in advance!

**Comment by ROBYER1** [comment]
See Large Allocation HTTP Header here and try that first :)
"Large-Allocation HTTP header"
 https://docs.unity3d.com/Manual/webgl-memory.html#:~:text=Settings%20%3E%20Publishing%20Settings.-,Large%2DAllocation%20HTTP%20header,-Your%20server%20can

**Comment by TEAServ** [comment]
Hi @ROBYER1,
thank for the advice, gonna try it,
but I noticed that it's only supported for only (mozilla firefox browser) for now, but I need it to be working on the most common browsers like(chrome and edge)!
btw I'm going to try the Large-Allocation header,
thanks,

**Comment by ROBYER1** [comment]
I would suspect it is a server side configuration for your WebGL build but I'm sure the plugin maker here will chime in if I'm wrong. Just trying to help out as I had a similar issue before solved by server configuration

**Comment by TEAServ** [comment]
Hey @ROBYER1,
can you help me a little bit on how to impalement this ?
I'm using "Varcel" as a hosting service for my build 
[sample](https://gamee.vercel.app/)
I don't know how to configure the server side configuration for my WebGL build to add the Large-Allocation response header!
I checked [this](https://docs.unity3d.com/2020.1/Documentation/Manual/webgl-server-configuration-code-samples.html) but really don't know what to exactly do as I'm not so familiar with that :(

**Comment by ROBYER1** [comment]
Unfortunately I don't know much about servers or the web I'm no expert there, I usually have the server set up for me!

**Comment by TEAServ** [comment]
want to add more information:
my webgl app crashed with "out of memory" error when it reach its limit of 2GB heap memory of ram (about 2.7GB total memory[app data + heap])
but in the[ Webgl demo](https://gltf.pixel.engineer/) when importing the same file the process is done successfully without errors or warnings even after the heap memory exceeded **5GB** of ram on single chrome tab!
here is my screen shoot:

![gltfast](https://user-images.githubusercontent.com/92520122/146002102-ce5d47e2-3c49-4eb6-8f04-79af3c6e29a6.png)

**Comment by TEAServ** [comment]
the link of my file :
https://www.mediafire.com/file/wiy1dsldl1yxzsz/65.glb/file

**Comment by atteneder** [comment]
Hi @TEAServ ,

that's surprising. Are you loading the glTF via the `GltfAsset` component or in a custom way?

**Comment by TEAServ** [comment]
Hey @atteneder ,
After deep memory tracing I found that the webgl demo not using the 5GB of memory heap, after importing my big glb file using the webgl demo I found that the app is using (1.98GB) of heap memory and the rest of the used 5GB consumed by the GPU process, so that's why the demo app didn't crash because it didn't reach the unity/browser limit of memory usage (2GB), It's almost reach it but it didn't, So I assume that if I try to import more bigger glb file which will lead the app to consume >= 2GB, it will crash 
My app crashed because after importing the file using the GltfAsset I tried to add some mesh colliders on the objects which lead it to exceed the 2GB of memory heap then crash!
I'm so disappointed, in 2022 we still have this limitation of 2GB heap memory in the unity webgl build and the browsers support!
then this is not a bug in the package but it's just a limitation in the platform itself,
btw thanks for the great package <3

**Comment by atteneder** [comment]
@TEAServ 

Yeah, that's a pity. Creating a collider mesh essentially makes a full copy of the mesh for PhysX. My mid-/long-term hope is with Unity or Havok Physics with DOTS though.

Thanks for the kind words!
