### ISSUE TITLE
When playing back certain skinned animations, the model is flickering

### ISSUE THREAD

**Issue by vcand** [atteneder/glTFast#298]
When playing back animations on some models with skinned meshes, the model is flickering.
When stepping forward frame by frame, you can clearly see that the model vanishes between frames, and various parts come and go randomly.

To reproduce:
1. Download the glTF version of this model from Sketchfab and import into Unity editor: 
https://sketchfab.com/3d-models/aj-hiphop-f5abe05ff2124527a6871060b2809bb2
2. Instance into a test scene.
3. Play back the animation.
4. Here is what it looks like: https://youtu.be/QJ0B4IcD28I
Additional models with the same problem: https://sketchfab.com/3d-models/paluxysaurus-afb6b5c7221b4f43a40762cdd9cdf90c

Side note: if I import the same glTF file into Blender and save out as glTF file again, the flickering is gone!

**Comment by atteneder** [comment]
@vcand Thanks for your report!

I cannot reproduce the flickering! Please report exact versions of glTFast, Unity and render pipeline you are using.

I noticed other problems:
- Hiphop dancer: The face won't render correctly, as it uses UV set 2 (only 0 and 1 are supported atm)
- Dinosaur: animation was smooth, but skin artifacts (maybe not all bone weigths are considered); spec-gloss shading is broken (on my dev branch)

**Comment by atteneder** [comment]
I *can* reproduce in 2020.3 now, but it's working in 2021.2

**Comment by atteneder** [comment]
@vcand I suspect the animation curve tangent calculation has errors. If that's true, then there'll be a fix for 2020.3.

And yeah, the wrong dinosaur shading was a regression in my branch, which you'll now likely never see (thanks for the incidental hint)

**Comment by atteneder** [comment]
@vcand The error is at sketchfab's glTF export, but I have a solution!

If you run the files through the glTF-Validator, you'll notice they got **many** errors. The one that pops out (example):

```json
{
    "code": "ACCESSOR_ANIMATION_INPUT_NON_INCREASING",
    "message": "Animation input accessor element at index 2 is less than or equal to previous: 0.03333333507180214 <= 0.03333333507180214.",
    "severity": 0,
    "pointer": "/animations/0/samplers/0/input"
}
```

So some (around half of all) subsequential animation keyframes have identical input (time) resulting in strange artifacts. I'm actually surprised that Unity 2021's API is taking care of the faulty data.

Ignoring the duplicates seems to work just fine without being too much of a burden. Expect a fix in the upcoming version.

**Comment by atteneder** [comment]
So I contacted Sketchfab about those models and their errors. Turns out those were exported a while ago (glTF asset -> generator was `Sketchfab-3.19.6`). They triggered a re-export (now with `Sketchfab-12.38.0`) and the validation errors are gone!

Guess the lesson to learn is always check against the glTF-Validator and a well-tested, alternative viewer first.

**Comment by vcand** [comment]
Thank you so much for this fix @atteneder . I had the chance to integrate it now into our product and it works flawlessly.
