### ISSUE TITLE
So I can't load GLTF files?

### ISSUE THREAD

**Issue by Rysm** [atteneder/glTFast#30]
Do I need to use another library to convert a GLTF file into GLB in order to use :

```
var loadModel = new GameObject().AddComponent<GLTFast.GlbAsset>();
loadModel.url = gltf;
```

**Comment by atteneder** [comment]
At the moment, yes. Priority is on use cases where you have control over the content and can convert to gltf-binary. You have to re-export your models to glb at the moment. It's a bit of work, but it can be automated as well.
I plan to do gltf support later on (see #6 )
