### ISSUE TITLE
Add an asmdef so this can be used in other packages

### ISSUE THREAD

**Issue by gfaraj** [atteneder/glTFast#303]
I haven't found a way to reference this project's assemblies in my own UPM package. It seems like the only way to do that would be to expose an asmdef so it produces its own assembly.

**Comment by gfaraj** [comment]
I just noticed it generates an assembly called glTFast.dll -- sorry, I was importing it incorrectly.

**Comment by atteneder** [comment]
No worries.

The naming of the assembly is not ideal, since I didn't know about best practice when this project started. It'll probably change at some next major release.
