### ISSUE TITLE
Building with Unity Cloud build fails

### ISSUE THREAD

**Issue by gfaraj** [atteneder/glTFast#306]
There's some issue with lfs when building in Unity Cloud Build:

`1: [Unity] An error occurred while resolving packages:
2: [Unity]       Error when executing git command. Downloading Documentation~/img/Unity-glTF-workflows.png (46 KB)
3: [Unity]       Error downloading object: Documentation~/img/Unity-glTF-workflows.png (863cfd7): Smudge error: Error downloading Documentation~/img/Unity-glTF-workflows.png (863cfd7cb36fdf3434a306a2c74972a0732d344bc99090ef7a233b8f235a44cc): batch response: Bad credentials
4: [Unity]       error: external filter 'git-lfs filter-process' failed`

Does anyone know of a workaround? Unity has some details about Git LFS support here:

https://docs.unity3d.com/Manual/upm-git.html#git-lfs

Might need to add an .lfsconfig file?

**Comment by atteneder** [comment]
Hi @gfaraj ,

How did you install glTFast? Via OpenUPM, GIT URL (ssh) or GIT URL (https) ?

**Comment by gfaraj** [comment]
Hey @atteneder ! I'm using an HTTPS git URL in the manifest. Would it be better to use something else?

I ended up forking and removing LFS to resolve the issue last night, but ideally I'd like to avoid using a fork.

https://github.com/gfaraj/glTFast

I didn't see a huge need for LFS though, currently only a handful of small images are being tracked in LFS.

**Comment by atteneder** [comment]
Yeah, I'd try the scoped registry/OpenUPM way.

True, LFS is not used heavily right now, but I want to keep the option (think adding test or sample glTF-binary files)

**Comment by gfaraj** [comment]
Yeah I do understand the reasoning, my experience with LFS hasn't been positive usually 🙂  -- the other option would be making a separate repo for samples, with possibly a submodule of this repo within. I hesitate to go the scoped registry route because my plan is to install this on _many_ projects and I like the fact that I can simply add 1 line to the project's manifest and be done. 🤔

**Comment by atteneder** [comment]
I decided to not fix this on my side.

Please use the OpenUPM scoped registry with Unity Cloud Build.

Thanks
