### ISSUE TITLE
WebGL Materials not loading [Unity 2019.4.34]

### ISSUE THREAD

**Issue by kfina91** [atteneder/glTFast#307]
**Describe the bug**
Materials do not load in WebGL build, but load fine in Editor using "Load from byte array" code from docs.

**Code**
```private Dictionary<string, GltfImport> importedGLTF = new Dictionary<string, GLTFast.GltfImport>();
private async void importGLTF(string key, byte[] data) {
    GltfImport gltf = new GltfImport();
    bool success = await gltf.LoadGltfBinary( data, null );
    if (success) {
        importedGLTF.Add( key, gltf );
    }
}
private void InstantiateGLTF(Transform t, GltfImport gltf) {
    if (t != null)
        gltf.InstantiateMainScene( t );
    else Debug.LogError($"InstantiateGLTF failed, transform of cube not found.");
}
```

**Information**
I saw these 2 issues:
https://github.com/atteneder/glTFast/issues/151
https://github.com/atteneder/glTFast/issues/149
but no pipeline is installed or referenced.
![image](https://user-images.githubusercontent.com/72922128/150512827-b4ab0d4d-1c24-415f-aebd-b73ab5dcd02a.png)
![image](https://user-images.githubusercontent.com/72922128/150513716-105176f8-9b0c-4b1a-952c-15eb6bb84f4c.png)
![image](https://user-images.githubusercontent.com/72922128/150513762-210ce91a-0e8a-4c96-ae2c-25cc379ba4c4.png)

For testing I converted my file (see attached file) by converting it to a base64 string in pasting that base64 string in the script and loading it via:
`importGLTF("test.glb", "<base64string...>");`

**Files**
// File I converted to base64
[monkey.zip](https://github.com/atteneder/glTFast/files/7912574/monkey.zip)

**Steps to reproduce**
1. Import GLTFast 4.4
2. Create game object and put this script on it (GLTFTest.cs)
[GLTFTest.zip](https://github.com/atteneder/glTFast/files/7912639/GLTFTest.zip)
3. Run in editor (it works)
4. Build WebGL (materials are missing)

**Expected behavior**
Materials should be same as in editor.

**Screenshots**
WebGL:
![image](https://user-images.githubusercontent.com/72922128/150511186-eacbe63f-8c66-4754-805e-ea8bebba2efe.png)
UnityEditor:
![image](https://user-images.githubusercontent.com/72922128/150512961-8aa52175-6fbb-4d04-b408-ce1f8d37404f.png)

 - glTFast version: 4.4 (EDIT: installed via the Installer Package)
 - Unity Editor version: 2019.4.34f1
 - Render Pipeline: Built-In Renderpipeline
 - Platform: WebGL, Google Chrome 64 Bit

EDIT 2: There are no errors in the browser console and I confirmed that success was true via a Debug.Log();

**Comment by atteneder** [comment]
Hi @kfina91 ,

most likely your build is missing the shader variants it requires to create the materials for your model. In the Editor they are compiled on-demand, but you have to make sure that your build includes them.

Please read [the documentation](https://github.com/atteneder/glTFast#materials-and-shader-variants)

**Comment by Bersaelor** [comment]
PS: [The documentation](https://github.com/atteneder/glTFast/blob/main/Documentation%7E/ProjectSetup.md) has moved.
