### ISSUE TITLE
Problem when loading asset with more than 65k vertices

### ISSUE THREAD

**Issue by taharaza16** [atteneder/glTFast#31]
when i load low poly assets they build just fine.. however if i try to import one with around 300k vertices this is what i get
![image](https://user-images.githubusercontent.com/16437355/44136312-cbfd658e-a085-11e8-8baf-d5d6e37d21dd.png)
instead of 
![image](https://user-images.githubusercontent.com/16437355/44136421-30a162e2-a086-11e8-9e6e-2792738aa8e2.png)

**Comment by taharaza16** [comment]
[tile.zip](https://github.com/atteneder/glTFast/files/2297059/tile.zip)
here you go!

**Comment by atteneder** [comment]
I noticed another problem with this one: There are two sub meshes with different materials. That does not work atm, so I created a follow up issue #32
