### ISSUE TITLE
Is it possible to import animations yet ?

### ISSUE THREAD

**Issue by nigelmerle** [atteneder/glTFast#312]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by atteneder** [comment]
Animation import has been working since [3.2.0](https://github.com/atteneder/glTFast/blob/main/ChangeLog.md#320---2021-04-13).

At runtime, the legacy `Animation` component is used. For Editor import you can choose between Mechanim and Legacy.

I hope that clarifies the question.

**Comment by nigelmerle** [comment]
I tried to import a 3d model with animations but the animations were not
showing up, thats why i was asking. Does it mean that i need to download an
older version for it to work?

**Comment by nigelmerle** [comment]
Why it doesn’t use mechanim  ?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by atteneder** [comment]
No, just use the most recent version and you're good.

If you want me to look at your problem, you have to provide more useful information. For example attach the glTF file in question.

What does "not showing up" mean?

**Comment by nigelmerle** [comment]
I am missing the humanoid  and the animation import interface,  I need to bake the transform of the character as I usually do to prevent foot sliding…etc. I also need to resize the length of my animations.
I have tried many gltf importers but none have worked for me so far. This is a test I am doing because I wanted to switch from fbx to gltf, I see the animations looks better.
This same animation that I have sent to you as attachment I have tried to export it as an fbx with blender but the fbx is broken on export. I was surprised when I exported the animation to gltf in blender, it  look so good but now I need to bring it in unity. This is another challenge for me.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

________________________________

**Comment by nigelmerle** [comment]
I also need to have the event options so that I can reference the animations with the game engine

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

From: Nigel ***@***.***>
Sent: Sunday, January 30, 2022 02:40 AM
To: ***@***.***>; ***@***.***>
Cc: ***@***.***>
Subject: RE: [atteneder/glTFast] Is it possible to import animations yet ? (Issue #312)

I am missing the humanoid  and the animation import interface,  I need to bake the transform of the character as I usually do to prevent foot sliding…etc. I also need to resize the length of my animations.
I have tried many gltf importers but none have worked for me so far. This is a test I am doing because I wanted to switch from fbx to gltf, I see the animations looks better.
This same animation that I have sent to you as attachment I have tried to export it as an fbx with blender but the fbx is broken on export. I was surprised when I exported the animation to gltf in blender, it  look so good but now I need to bring it in unity. This is another challenge for me.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by atteneder** [comment]
@nigelmerle 

Ahh, now I get it. Thanks.

So I already did research if it is possible to re-use the FBX import tools (which are indeed powerful), but unfortunately that's not the case. I'll try to look into this topic at some point, but don't expect a near-term solution here. I think we're gonna have to decide what the best glTF workflow is and implement it in a way, that is universally usable (for other formats as well).

For now I recommend you to pre-solve everything that's possible in the glTF (like animation lengths). Other things you can fix by duplicating certain sub-assets (like materials or animations) and, frankly, for some things there's no good solution yet.

Thanks!

P.S.: Please don't respond with your email client. It clutters up your message and that's very distracting.I cleaned that up manually for now.

**Comment by nigelmerle** [comment]
Also i want to comment on something. When i checked the humanoid options in the importer in unity, the character doesn't play other unity animations that was retargeted as humanoid, this is problematic if we cannot retarget our characters properly

**Comment by atteneder** [comment]
> Also i want to comment on something. When i checked the humanoid options in the importer in unity, the character doesn't play other unity animations that was retargeted as humanoid, this is problematic if we cannot retarget our characters properly

I see. I suggest you file a bug (Menu -> Help -> Report a Bug) or consult the Unity forum regarding this one.
