### ISSUE TITLE
[Editor Import] Projects without Library folder will fail to import previously imported glTFs

### ISSUE THREAD

**Issue by mikeskydev** [atteneder/glTFast#315]
**Describe the bug**
Opening a pre-existing project, which doesn't have it's Library folder already present, will fail to import previously imported glTFs.
This use case occurs due to CI pipelines on GitHub starting with the fresh clone of a project, with no library file, though is reproducible by manually wiping your Library folder. Error seems to be coming from a NRE, GltfImporter.cs:123 when attempting to add a material:
```cs
                for (var i = 0; i < m_Gltf.materialCount; i++) {
                    var mat = m_Gltf.GetMaterial(i);
                    AddObjectToAsset(ctx, $"materials/{mat.name}", mat);
                }
```

**Files**

Attach or link to *.gltf/*.glb files that trigger the bug.
Should work with any gltf/glb, but here:
[rounded_cube_test.zip](https://github.com/atteneder/glTFast/files/7979919/rounded_cube_test.zip)

**To Reproduce**
- Add any glTF to a Unity Project through the editor
- It will import successfully
- Close the project
- Delete Library folder
- Re-open the project
- Note errors in console (see screenshot) and glTF has not imported.

**Expected behavior**
The glTF imports sucessfully.

**Screenshots**
![image](https://user-images.githubusercontent.com/9121007/152003706-5a0f5069-1cef-442d-9ec0-c601923a32ef.png)

**Desktop (please complete the following information):**
 - glTFast version: Tested on 4.0.0, 4.5.0
 - Unity Editor version: 2020.3.14f1, 2020.3.26f1
 - Render Pipeline: Universal Render Pipeline 10.5.1 (on .14f1)
 - Platform: Windows, Linux CI

**Additional context**
Originally filed at: https://github.com/atteneder/DracoUnity/issues/39

**Comment by atteneder** [comment]
Looks like upon opening a project first-time glTFast's shaders are imported after the glTF import is running, causing it to fail.

Replacing `Shader.Find` by `AssetDatabase.LoadAssetAtPath<Shader>` seems to solve. Now I'm certifying that this is a good solution and will fix it asap.

@hybridherbst fyi

**Comment by atteneder** [comment]
@hybridherbst yeah, seems like it's the way to go.

I intend to use paths instead of GUIDs though. GUIDs are flexible, but not very intuitive. Plus some paths are constructed from a naming pattern that I want to re-use. Feel free to raise concerns though.

**Comment by hybridherbst** [comment]
I'm fine with paths, it's just error prone when refactoring folders (which does not break GUIDs) - guess it's a case-by-case decision, similar to AsmDef references either using GUIDs or strings.

What you could also look into is using LazyLoadReference<T>. The SRPs seem to use that, for example, in their scriptable objects that hold all required references.

**Comment by mikeskydev** [comment]
Thanks for this fix!
