### ISSUE TITLE
Imported GLB mesh bounds are incorrect when meshopt compression is used

### ISSUE THREAD

**Issue by hybridherbst** [atteneder/glTFast#323]
**Describe the bug**
Seems mesh bounds are wrong when files use meshopt.
This is most noticeable in the import inspector (as wrong bounds = mesh not visible) but probably might have other side effects as well.

**Files**

[Arm.glb + meshopt variants](https://github.com/donmccurdy/glTF-Transform/files/8023253/AnimatedArm.zip)

**To Reproduce**
1. Unzip
2. Add files to Assets/ in Unity, make sure glTFast + meshopt packages are present
3. Select Arm > Cube, note mesh bounds size (1,1,1)
4. Select Arm.meshopt-medium > Cube, note mesh bounds size (6.554e+04, 6.554e+04, 6.554e+04)

**Expected behavior**
Identical mesh bounds independent of meshopt compression

**Screenshots**
_Without meshopt:_
![image](https://user-images.githubusercontent.com/2693840/152980559-6b573ceb-d4a0-4844-b571-7293c65df351.png)
_With meshopt:_
![image](https://user-images.githubusercontent.com/2693840/152980583-e68f1da8-783d-443c-8d36-6b6a6a9d816d.png)

**Desktop (please complete the following information):**
 - glTFast 4.5.0
 - Unity Editor 2020.3.25f1

**Comment by atteneder** [comment]
@hybridherbst  Thanks for reporting.

Haven't looked, but it's possible that this is expected.

gltfpack/meshopt uses quantization as well. Meaning the vertex positions are converted to normalized ints (e.g. unsigned shorts) and the node's scale counter-acts the effect (so that the final size matches the original).

Try looking at the node's transforms.

Also note that the shading is broken at times (see #75 )

**Comment by hybridherbst** [comment]
The node is indeed scaled, so I can see how the bounds need to be different as well, but not sure why the mesh display in the inspector would then be broken... might be a Unity bug then?

Side note, do I get it right that you're scaling animation values to counter the node scale?

**Comment by atteneder** [comment]
> The node is indeed scaled, so I can see how the bounds need to be different as well, but not sure why the mesh display in the inspector would then be broken... might be a Unity bug then?

Most likely, yeah.

> Side note, do I get it right that you're scaling animation values to counter the node scale?

glTFast does not do any smart thing here. It's the glTF generator (or compressor; gltfpack) that does it.

**Comment by hybridherbst** [comment]
Hi @atteneder I looked into this again just now (wanted to report a bug to Unity) and still think the bounds are incorrectly set when importing.

Maybe I'm doing something wrong, but here I exported the same file as FBX, and when importing in Unity (with those meta files) I get identical transform hierarchies and visual results (so, same scale for everything), but different bounds, and the meshes and main object display correctly with FBX but don't display correctly with GLB:
[glb-and-fbx.zip](https://github.com/atteneder/glTFast/files/8115294/glb-and-fbx.zip)

Let me know what you think, I think this should be reopened :)

**Comment by atteneder** [comment]
@hybridherbst Oh, you're right! It seems like that for normalized accessors the min-max values are pre-normalization and glTFast assumes they are already normalized. I'll double check with the extension spec and fix that.

Thanks for staying persistent on this one 💪

**Comment by atteneder** [comment]
yep:
> Implementation Note: For quantized data, accessor.min and accessor.max properties also contain quantized values. Applications that use these properties, e.g. for bounding box computations, will need to dequantize them first.

[source](https://github.com/KhronosGroup/glTF/blob/main/extensions/2.0/Khronos/KHR_mesh_quantization/README.md#extending-mesh-attributes)
