### ISSUE TITLE
Importer Gamma issue

### ISSUE THREAD

**Issue by philippebedard** [atteneder/glTFast#324]
I think there's an issue with the baseColorFactor when we import a gltf. 
Looks like there's a mismatch of color with the imported gltf compared with original gltf and other software.

You can see over here the difference between my original RBG color and the resulting color in Unity when I import it.
![Untitled](https://user-images.githubusercontent.com/47433856/153058701-761c5d26-3bbf-4e06-a798-b28c948dc0a1.png)

Important to note that I have created my own surface shader but the field _Color is still wrong. 

**To Reproduce**
-Create a GLTF with only a color (no texture)
-Import it with the GLTFast 

Also if I remove the following gamma. The import seems to be fine. 

Script : BuiltInMaterialGenerator.cs
![image](https://user-images.githubusercontent.com/47433856/153059710-a32e089d-60fb-4283-85d7-436f33cc60ab.png)

**Desktop**
 - glTFast version 4.4.3
 - Unity Editor version 2020.3.24f1
 - Built-in Render Pipeline
 - Platform: Editor, Windows Player
 
 [original.zip](https://github.com/atteneder/glTFast/files/8026752/original.zip)

**Comment by atteneder** [comment]
Hi @philippebedard ,

Thanks for the report! Follow up questions:

- Did you export with glTFast as well?
- Is your project's color space Gamma or Linear?

Maybe your suggestion is on point, but I'd be surprised (since it's quite good tested and established).

Another explanation could be that the export does not properly convert from gamma to linear. I know that Blender's UI shows linear values (except for HEX, those are gamma). I don't know from the top of my head what values Unity shows, plus it could depend on the project settings.

**Comment by philippebedard** [comment]
Hi @atteneder,

I didn't export with the glTfast. 
I did a test exporting with Blender and a test exporting with [https://github.com/KhronosGroup/UnityGLTF](url)

In both case the color aren't correct when I import with glTfast.

My project is in Linear color space.

Thanks for your fast reply.

**Comment by philippebedard** [comment]
Alright after some investigation it looks like the issue is probably from the [https://github.com/atteneder/glTFast/issues/url](url) export which doesn't convert the unity color to linear prior the export.. 

If I apply the linear to gamma factor on my export it seem to be fine on most of the gltf viewer I found.

Probably my mistake

**Comment by atteneder** [comment]
@philippebedard I'm still not sure where the source of the error lies, so I'm going to leave this open until I've done some proper round-trip tests. Those should cover:

- URP/HDRP/BuiltIn
- BaseColor, Emission, Unlit, ...
- Linear and Gamma project workflows

In case you tracked down the problem, let me know.

Thanks

**Comment by atteneder** [comment]
I could not reproduce the change in values. Here's my steps:

1. import your glTF
2. copy the imported material (so it can be edited)
3. change the shader to `Lit` and assign it to a new cube
4. export this new cube to glTF
5. import the new glTF again

The color values stayed constant.

What I noticed, however, is that the visual color between glTF shader graph and Lit shader is not identical. There may be a color space issue in the shader graph.

**Comment by atteneder** [comment]
There actually is an error in the shader graphs! A fixis in branch [fix-sg-color-space](https://github.com/atteneder/glTFast/tree/fix-sg-color-space) and to be merged for the next major release (since it's a breaking change)

**Comment by philippebedard** [comment]
Thanks for your feedback!

It was my mistake for the original issue. Good thing you found out another issue will investigating this one.
