### ISSUE TITLE
Missing namespaces

### ISSUE THREAD

**Issue by jeffries7** [atteneder/glTFast#33]
I've just cloned the project and opened inside of Unity 2018.3.0 which is causing missing namespaces. These are:
- TestTools
- NUnit
- TestAttribute
- Unity TestAttribute
- Unity Test

Is this because i'm using a newer version of Unity or are these carried over from the Kronos project and i'm missed something?

**Comment by atteneder** [comment]
Quickfix: switch platform to WebGL and back to standalone (did the trick here).
I'm working on a better solution.

**Comment by atteneder** [comment]
I guess this is obsolete => closing
