### ISSUE TITLE
Surface Type of imported materials is Opaque even if the material has been exported as transparent.

### ISSUE THREAD

**Issue by fra3point** [atteneder/glTFast#331]
I'm trying to import in Unity a very simple transparent .glb cube, created in Blender 2.92 using the following material:

![immagine](https://user-images.githubusercontent.com/34285897/153870738-cd3953fa-ae97-4459-89b6-b708cdec7f6d.png)

I would expect glTFast to import a transparent material in Unity, but it is set to Opaque surface type.

![immagine](https://user-images.githubusercontent.com/34285897/153870279-eed1ca0f-08dc-464b-8fb0-c98237631741.png)

 - glTFast version: 4.5.0
 - Unity Editor version: 2021.2.9
 - Render Pipeline and version: URP 12.1.4
 - Platform: Any

[TransparentCube.zip](https://github.com/atteneder/glTFast/files/8060902/TransparentCube.zip)

**Comment by fra3point** [comment]
I was looking a bit more in deep in these issue.
it seems that the import code itself does the right job, **UniversalRPMaterialGenerator.SetShaderModeBlend** enables the **_SURFACE_TYPE_TRANSPARENT** keyword. I've placed a conditional breakpoint at the end of **GltfImporter.OnImportAsset** to check if at the end of the import process, the keyword was still correctly enabled. And it was!

But as soon as I look at the Unity Editor, the keyword disappears from the imported materials. 

I'm not sure where the problem is, if it's some black magic that Unity Editor does under the hood, or if that's something that can be fixed on glTFast side.

Any idea?

**Comment by atteneder** [comment]
Hi @fra3point ,

Thanks for the report and going the extra mile and debugging a bit. I noticed that this was indeed incomplete, so I made some fixes specific to URP and HDRP 12.x. It's fixed in the main branch and will be released soon.
Sorry for the inconvenience.
