### ISSUE TITLE
First editor import after adding glTFast or library clear fails

### ISSUE THREAD

**Issue by hybridherbst** [atteneder/glTFast#332]
**Describe the bug**
It seems that currently, the first import of a glTFast asset via ScriptedImporter fails.
This affects, besides other cases
- workflows where one coworker adds glTFast to a project, adds a GLB file (that works on his machine), and then a colleague pulls
- library clears and reimports

**Files**

This zip contains a full repro project which is also a git repo (so you can conveniently reset history again).
[glTFast-StartupBug.zip](https://github.com/atteneder/glTFast/files/8087852/glTFast-StartupBug.zip)

**To Reproduce**
1. Unpack
2. Open project
3. Note exception, seems to come from material instantiation

And beyond that, 
4. When you rightclick > reimport on the affected file(s), import will work just fine.
5. Close project, delete the Library folder
6. Start again at (2)

**Expected behavior**
First import after library clear or adding the package + file works

**Screenshots**
![image](https://user-images.githubusercontent.com/2693840/154458815-a26dd52d-bb94-4cc7-a01f-debefcf43c61.png)

**Desktop (please complete the following information):**
 - glTFast version 4.5.0
 - Unity Editor version [tested with 2020.3 and 2021.2]
 - Render Pipeline and version [tested with builtin+URP]
 - Platform: [Editor]

**Comment by mikeskydev** [comment]
Hey @hybridherbst I think this is the same bug I documented in #315?

**Comment by hybridherbst** [comment]
Yep, probably a duplicate of #315. Didn't find that one – let me know if you need more info here!
