### ISSUE TITLE
Give the user control over Legacy Animation automatic play

### ISSUE THREAD

**Issue by fra3point** [atteneder/glTFast#339]
[glTFast 4.6.0, Unity 2021.2]

**GameObjectInstantiator:397** calls **animation.Play()** right after adding the legacy Animation component to the instance object.
This causes animations to start automatically, and the only way to stop them is to manually stop and reset the animation component.

It would be great for users to have the possibility to load models choosing whether to start playing animations or not. In order to do this, I imagine an additional bool parameter, maybe optional with default value = true to keep backwards compatibility, in the **GltfImport.InstantiateMainScene** function.

**Comment by atteneder** [comment]
Hi @fra3point ,

Thanks for the suggestion, I will definitely consider it. Another option could be to not start playing and leave it up to the entity that triggered the instantiation. `GltfAsset` could trigger the auto-play, to keep the current behavior.

**Comment by fra3point** [comment]
I agree with your solution!
