### ISSUE TITLE
Importer should allow flipping model UV to match Unity importer, to allow for consistent round trip

### ISSUE THREAD

**Issue by bitinn** [atteneder/glTFast#342]
**Is your feature request related to a problem? Please describe.**

[Based on what I read](https://github.com/KhronosGroup/glTF/issues/1021), glTF enforce UV coordinate (0,0) at lower left and this is different from the default Unity import direction.

glTF spec is saying the sampling of such texture under OpenGL should be flipped. I see glTFast provides a default shader to achieve the correct sampling by flipping Y coordinate; same can be done in default Lit shader.

But there is a problem: this behaviour breaks the "round trip", meaning if you have a material setup for a normal FBX model, then you export the model as glFT, re-import, the material setup is no longer correct without manual change.

This also breaks material sharing if you mixed glTFast models with other FBX models.

**Describe the solution you'd like**

Most of the time we won't be using the glTFast's shader, it make sense to allow users to import glTF that matches the default behaviour of Unity built-in importers.

**Describe alternatives you've considered**

See above.

**Additional context**

![Screenshot 2022-03-01 144943](https://user-images.githubusercontent.com/1484279/156125930-5e649fab-e2b3-4327-8fbb-0b228ad86093.jpg)
![Screenshot 2022-03-01 145004](https://user-images.githubusercontent.com/1484279/156125962-d23ec0c9-9883-44e0-a4b0-d8bae9953469.jpg)

**Comment by atteneder** [comment]
I agree. It's going to get scheduled.

**Comment by FrogsInSpace** [comment]
Just stumbled over the V flipping issue:
* export via GLTFast to GLB 
* import GLB in different project and assign a different material -> leads to V flipped textures

thats a pretty unfortunate behavior because you want detect the issue until you start to swap materials 
Any time frame to get this fixed ?
