### ISSUE TITLE
Import-Export-Import Roundtrip

### ISSUE THREAD

**Issue by Anubit93** [atteneder/glTFast#347]
**Is your feature request related to a problem? Please describe.**
Exporting models already imported through glTFast cause issues with the textures being swizzled and not looking as desired being imported again, or opened in another 3D application. 

**Describe the solution you'd like**
Either supporting a non-swizzle boolean option in the export settings, or potentially having a list of shaders not to swizzle.

While investigating this, I realised that the exported textures would appear as a mix of png's and jpg's. It would be great to be able to have an option to force one of the two formats.

**Comment by atteneder** [comment]
Hi @Anubit93 ,

You are referring to runtime (as opposed to design-time), right?

Two potential ways:

- Import to Lit shaders - Export Lit shaders (preferred for design-time, but involves swizzles)
- Import to glTF shaders - Export from glTF shaders (runtime-friendly; no swizzle required)

**Comment by atteneder** [comment]
Opened #351 for glTF shader export

**Comment by Anubit93** [comment]
Hi @atteneder,

Yes I'm sorry that I missed that part in the description - it is indeed meant during runtime.

**Comment by atteneder** [comment]
I'm going to close this issue, since it's too high level.

For runtime round-trips, #351 has been tackled already.
For design-time round-trips, #258 tracks the state of Lit material import.

For all other issues please open dedicated issues.

Thanks.
