### ISSUE TITLE
Cannot enable meshoptimizer

### ISSUE THREAD

**Issue by petrbroz** [atteneder/glTFast#348]
**Describe the bug**
When following the installation steps in the [README](https://github.com/atteneder/glTFast#installing) it sounds like the meshoptimizer decompression plugin should appear in _Package Manager_ but it doesn't.

**To Reproduce**
1. Create a new Unity (2020.3) project
2. Install _glTFast_ (4.6.0) via a scoped registry
3. Open _Package Manager_ and go to _My Registries_
4. See that Draco and KTX/Basis plugins are available there, but meshoptimizer is not

**Expected behavior**
Meshoptimizer plugin should appear in the _Package Manager_. Or the README should explain how the plugin can be installed.

**Screenshots**
<img width="1079" alt="Screenshot 2022-03-02 at 14 58 30" src="https://user-images.githubusercontent.com/1470668/156378735-09c3b866-2fc8-40ab-b8e0-eef9fa2e3689.png">

**Desktop**
 - glTFast version: 4.6.0
 - Unity Editor version 2020.3.29f1
 - Render Pipeline and version [e.g. Universal Render Pipeline 12.0]
 - Platform: editor/macOS 12.1

**Comment by atteneder** [comment]
Thanks for reporting. The installation instructions for meshopt are not correct. I'm in the process of updating them. Here's the correct way:

The package identifier to add is:

`com.unity.meshopt.decompress`

or with exact version for Unity 2020.3 and older:

`com.unity.meshopt.decompress@0.1.0-preview.4`

## Installation

To install this package, refer to the instructions that match your Unity Editor version:

### Version 2021.1 and later

To install this package, follow the instructions for [adding a package by name](https://docs.unity3d.com/2021.1/Documentation/Manual/upm-ui-quick.html) in the Unity Editor. 

### Version 2020.3 and earlier

To install this package, follow the instructions for [installing hidden packages](https://docs.unity3d.com/Packages/Installation/manual/upm-ui-quick.html).
