### ISSUE TITLE
Support embedded base64-encoded data

### ISSUE THREAD

**Issue by atteneder** [atteneder/glTFast#35]
For images and buffers.

**Comment by Giorat** [comment]
Any news on the use of remote textures? Is it a complex task to complete?

**Comment by atteneder** [comment]
Hi!
Remote textures (as in URL links within the glTF JSON) are already supported (let me know if this is not the case).
This feature is about buffers and images embedded into the glTF JSON.

To be honest, this is not really hard to implement, just not a high priority. Base64 embedded buffers are just not very efficient (~20% data overhead plus decoding effort). If you have control over the content/glTFs, create them with binary buffers right away.

hth
