### ISSUE TITLE
Export glTF shaders/materials

### ISSUE THREAD

**Issue by atteneder** [atteneder/glTFast#351]
glTF export currently only supports Unlit, Standard and Lit shaders (across BiRP, URP and HDRP)

Adding support for our own glTF shaders and shader graphs would allow (close to) lossless import-export round-trips without having to swizzle texture channels around.

**Comment by 6099sin** [comment]
i can't export normal map glTF

**Comment by atteneder** [comment]
Released with [glTFast 6.5.0](https://docs.unity3d.com/Packages/com.unity.cloud.gltfast@6.6/changelog/CHANGELOG.html#650---2024-05-15).
