### ISSUE TITLE
Incorrect gamma applied for PNG BaseColor export

### ISSUE THREAD

**Issue by bitinn** [atteneder/glTFast#353]
**Describe the bug**

When exporting `glb`, glTFast used incorrect color space conversion for BaseColor texture (in PNG format). The exported BaseColor map is darker than the original file. (And I have verified it in both Unity and Blender, it is not an importer issue.)

I wonder if this has anything to do with "Ignore PNG file gamma" settings. We are in Linear color space with this option unchecked. (though checking it doesn't cause any visual change to the texture/material; while glTFast exports the texture as JPEG.)

**Files**

[cube.zip](https://github.com/atteneder/glTFast/files/8184483/cube.zip)

I included the original PNG texture + exported glb file + texture extracted from glb, for your investigation.

See also my comment here for a visual comparison: https://github.com/atteneder/glTFast/issues/352#issuecomment-1058954255

**To Reproduce**

It should be relatively easy to create a URP/Lit material, assign it to a cube, export glb then observe the incorrect BaseColor texture.

(Windows 10 3D Viewer, Blender, and other Unity glTF plugin can be used to verify this.)

**Expected behavior**

BaseColor should remain the same during an export-import round trip.

**Screenshots**

![Screenshot 2022-03-04 165502](https://user-images.githubusercontent.com/1484279/156734478-cdb99fbc-077b-433c-8c1a-0588b3012afe.jpg)
![Screenshot 2022-03-04 165514](https://user-images.githubusercontent.com/1484279/156734491-e40c5f46-7723-438b-99da-1a22550c18be.jpg)

**Desktop (please complete the following information):**

 - glTFast version: 4.6.0
 - Unity Editor version: 2021.2.10f1
 - Render Pipeline and version: URP 12
 - Platform: Windows

**Comment by atteneder** [comment]
@bitinn Thanks for the great report. I just pushed a fix to the main branch.

cheers!
