### ISSUE TITLE
Support GLTF extensions

### ISSUE THREAD

**Issue by Phlicess** [atteneder/glTFast#354]
Currently I am doing 3dtiles related rendering work，so
Would like to ask, will there be plans to support some GLTF extensions? 
E.g：
https://github.com/KhronosGroup/glTF/blob/main/extensions/1.0/Vendor/WEB3D_quantized_attributes/README.md

This is the rendering of my work:
![image](https://user-images.githubusercontent.com/11753644/156745542-50c0fd74-1c9c-4e8d-a2b0-9401b0902cb2.png)

**Comment by atteneder** [comment]
Hi @Phlicess 

Thanks for reaching out. I noticed that this extension is written against glTF 1.0, which is not supported. I'd have to check if this extension still works against 2.0.

It appears to me that [KHR_mesh_quantization](https://github.com/KhronosGroup/glTF/tree/main/extensions/2.0/Khronos/KHR_mesh_quantization), which is supported, is the logical successor, right? If yes and you are in control of the glTFs, I'd recommend to use KHR_mesh_quantization with normalized ushorts instead.

hth

**Comment by Phlicess** [comment]
Thank you for your reply.
I upgraded the version to 2.0 and found that some extensions are not supported, for example:
https://github.com/KhronosGroup/glTF/blob/main/extensions/2.0/Khronos/KHR_draco_mesh_compression/README.md
I saw the list of extensions and found that there are currently 6 supported, so will the rest of the 2.0 extensions be supported?

GltFast list:
<img width="430" alt="CA93E22B-BEE5-46C1-B7F4-CAB57F8B3147" src="https://user-images.githubusercontent.com/11753644/156859491-efaad834-3dc4-427a-996a-715e1d4b66cb.png">

My GLB:
<img width="443" alt="BA75CB8E-DA3E-47ED-8FCC-D81EE23183D0" src="https://user-images.githubusercontent.com/11753644/156859477-fb57813f-c5da-442a-9487-76cd8a9c14d3.png">

**Comment by Phlicess** [comment]
I noticed that this project, but I don't know how to use it.
https://github.com/atteneder/DracoUnity

**Comment by Phlicess** [comment]
HAHA，I find this from your code！
![image](https://user-images.githubusercontent.com/11753644/156862013-af112948-02b2-40d4-bacd-8bce82191d28.png)

**Comment by atteneder** [comment]
@Phlicess You're on the right track!

DracoUnity is a soft dependency of glTFast, meaning if DracoUnity is installed, the `DRACO_UNITY` define is set and it becomes available.

Please follow the [installation guide](https://github.com/atteneder/DracoUnity#installing) and let me know if and where you ran into trouble.

**Comment by Phlicess** [comment]
> @Phlicess You're on the right track!
> 
> DracoUnity is a soft dependency of glTFast, meaning if DracoUnity is installed, the `DRACO_UNITY` define is set and it becomes available.
> 
> Please follow the [installation guide](https://github.com/atteneder/DracoUnity#installing) and let me know if and where you ran into trouble.

I follow the guide，and success！Think you！
(✺ω✺)
