### ISSUE TITLE
Runtime Export - Non Matching Profiler Endsample Error

### ISSUE THREAD

**Issue by SceneForgeStudio** [atteneder/glTFast#357]
I just downloaded and setup this plugin to use the Runtime Export feature.  I setup the assemblies and all that.
When trying to export using the example code from the docs, I get a bunch (5-7) errors like the one below:

```
Non matching Profiler.EndSample (BeginSample and EndSample count must match): 
Previous 5 samples:
	GC.Alloc
	mscorlib.dll!System.Collections.Generic::List`1..cctor()
	GC.Alloc
	Mono.JIT
	GC.Alloc
In the scope:
	UnityEngine.CoreModule.dll!UnityEngine::UnitySynchronizationContext.ExecuteTasks() [Invoke]
	Update.ScriptRunDelayedTasks
	PlayerLoop
	Main Thread 
```
Surprisingly the export does actually work though, with the resulting gltf/glb files in the specified directory.  The problem is that this triggers these errors that I haven't seen before in my long-term project.
This happens with a complex gameObject or even somethng as simple as a cube + plane.

I'm using 2021.128 with URP on a capable Windows 11 Machine.
Has anyone else encountered this?
Thanks!

EDIT:  **Looks like this only happens when the profiler is set to record (the record toggle is on)**
To add some more info, this is all I'm doing:
```
 public async void Export()
    {
        var exportSettings = new ExportSettings
        {
            format = GltfFormat.Binary,
            fileConflictResolution = FileConflictResolution.Overwrite
        };
		
		// exportObjects is a list of gameObjects.  It's a list because I intend on populating it with another script.
        var export = new GameObjectExport(exportSettings);
        export.AddScene(exportObjects.ToArray(), "My Scene");
        bool success = await export.SaveToFileAndDispose(Path.Combine(Application.streamingAssetsPath, "exports/testFile.gltf"));
    }
```

**Comment by atteneder** [comment]
@SceneForgeStudio Thanks for reporting.

I somehow couldn't reproduce it, but I assume that the source of the error is mixing Profiler calls and await. I tried to the best of my possibilities to de-clutter them. If you could test the current `main` branch again (and re-open the issue if it's not resolved), that would be great.

**Comment by SceneForgeStudio** [comment]
I will do so when I can, thanks!
