### ISSUE TITLE
Skinning export support.

### ISSUE THREAD

**Issue by kyapp69** [atteneder/glTFast#365]
I assume that skinning won't be supported until you are less busy?
Will have to take you up on the code structure mentoring. Is anyone else taking up skinning and animation? Otherwise I'll take a stab at it.

**Comment by atteneder** [comment]
@kyapp69 Correct, I'm focusing on quality and CI at the moment.

BlendWeights and BlendIndices of a mesh should already get exported (haven't tested it though), so it boils down to detecting SkinnedMeshRenderers and see if they have `bones` assigned and convert them to a proper glTF `skin`.

**Comment by atteneder** [comment]
The starting point would be [here](https://github.com/atteneder/glTFast/blob/208e025c73399539600b0e601b884c136d5bab46/Runtime/Scripts/Export/GameObjectExport.cs#L158) by passing the newly created `skin` data to  `m_Writer`.

hth

**Comment by kyapp69** [comment]
> The starting point would be [here](https://github.com/atteneder/glTFast/blob/208e025c73399539600b0e601b884c136d5bab46/Runtime/Scripts/Export/GameObjectExport.cs#L158) by passing the newly created `skin` data to `m_Writer`.
> 
> hth

I see that a unityengine.mesh is passed in to the writer and eventually the gltf mesh schema is created during the serialization. Would it be better if the gltf skin is done in the writer also? Let me get it working first and see how to refactor. I see that the only thing to get it working is to export the skin. I'll get right on it.

Cheers
Kevin

**Comment by atteneder** [comment]
> Would it be better if the gltf skin is done in the writer also? 

I think so, yes....I didn't think it through though, so no strong opinion at this point.

**Comment by hierro** [comment]
@kyapp69 I've been testing all possible cases to export a character with rig, then i stepped into this thread.
 if I can be helpful, in terms of debug and test, let me know, thank you all.

**Comment by kyapp69** [comment]
> @kyapp69 I've been testing all possible cases to export a character with rig, then i stepped into this thread. if I can be helpful, in terms of debug and test, let me know, thank you all.

Sure, watch this thread.  I just forked it so I can do pull requests.

**Comment by hierro** [comment]
> Sure, watch this thread. I just forked it so I can do pull requests.

Following it, and also considering to modify shaders in untiy to be fully compliant with GLTF, in example using roughness maps.
There is a lot that can be done, but indeed the skin is necessary in order to have a valid export tool for interoperability.
Let me know how I may help on this, thank you.

**Comment by kyapp69** [comment]
> > Sure, watch this thread. I just forked it so I can do pull requests.
> 
> Following it, and also considering to modify shaders in untiy to be fully compliant with GLTF, in example using roughness maps. There is a lot that can be done, but indeed the skin is necessary in order to have a valid export tool for interoperability. Let me know how I may help on this, thank you.

You can take a look at my fork to do initial testing of the skinning for the time being. I have enabled legacy path exporting, as I am using that to understand the code. not surer what is missing tho. I just preliminarily tested and it seems to work.

https://github.com/kyapp69/glTFast

**Comment by Hugo-Pereira** [comment]
What is the status on this issue?

**Comment by atteneder** [comment]
@Hugo-Pereira 
No imminent plans to start implementing it, so definitely not happening before late Q4. Help is welcome though.

**Comment by Hugo-Pereira** [comment]
I'll try and tackle this. Should have a MR in the next few days.

**Comment by TechInterMezzo** [comment]
Are there any news on this?

**Comment by w100076575** [comment]
Are there any news on this?

**Comment by atteneder** [comment]
The good news: It's quite high in the backlog as I try to get most PRs merged before doing some refactoring.

The bad news: I'm on parental leave until early August, so it's likely delayed for at least two months.

Sorry for the delay.

**Comment by atteneder** [comment]
Released in glTFast [6.8.0](https://docs.unity3d.com/Packages/com.unity.cloud.gltfast@6.8/changelog/CHANGELOG.html#680---2024-09-05).
