### ISSUE TITLE
Cant ever load from file?

### ISSUE THREAD

**Issue by Pryme8** [atteneder/glTFast#366]
I have tried every method documented and still am unable to load a gltf from the file system.  The URL version of the GLTF asset loads not problem.  I am assuming that its something dumb that I am doing wrong, or a step that I am missing.  Kind of exhausted my options now which is why I am creating this issue.

![image](https://user-images.githubusercontent.com/1538857/157729711-139e10eb-a809-4866-9a5c-e64c0bbf9239.png)
I have also tried to load it from a binary array and that still did not work.

Sorry to waste your time with something so basic, but it seems I just don't get it.

I am assuming that its because all the files need to be relative to the resource folder but for some reason I have a disconnect on how to make that work.

*Update* I am able to get the JSON string through a UnityWebRequest to log but am still not able to get that to load into the system.  

Is there a way to load from the JSON string?   Is there a way to convert that string to a URI and load that?  What am I missing here?

![image](https://user-images.githubusercontent.com/1538857/157760746-3d0aa5ec-a4f5-4203-9f5e-0baae24a3cec.png)
![image](https://user-images.githubusercontent.com/1538857/157760801-686f1733-adf5-45fe-bc8d-1861a5798228.png)
![image](https://user-images.githubusercontent.com/1538857/157762476-3f9156d6-1502-4924-b4b8-f164c6ca8e6e.png)

I'm starting to feel like Helen Keller of programing...

**Comment by atteneder** [comment]
@Pryme8 Hi,

*googling Helen Keller*....haha, certainly not :D

Would be great to know what kind of error you get. If you don't get any, does your glTF file have a main scene at all? If not, nothing ill happen by design.

**Comment by Pryme8** [comment]
Yes sir, I am loading the Duck.gltf from the example documents.  When loaded as a URL "https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/Duck/glTF/Duck.gltf" everything works swimmingly. 

As soon as I have it as a file outside of a resource folder on the file system it just defaults to the generic "Debug.LogError("Loading glTF failed!");"

We are trying to import GLTFs into the Unity Runtime Editor and everything works great with it as a URL so its looking promising, I just gotta figure out this file system stuff now.

BTW - Thank you so much for responding, my project manager was giving me crap that they did not think you would get back to me but I had faith ^_^.

**Comment by Pryme8** [comment]
@atteneder Is there a JSON parsing method I can use directly by just passing it a string?

**Comment by atteneder** [comment]
@Pryme8 Thanks for your patience.

I just got on a Windows box to test it, and it works for me. The `Download buffer 0` error indicates that you did not copy the entire glTF correctly into the `D:\assets` folder. glTFs can consist of multiple files. the `.gltf` file is a JSON that potentially refereces more files like binary buffers (`.bin`) or textures (e.g. `.jpg`).

Your test file in particular consists of `Duck.gltf`, `Duck0.bin` and `DuckCM.png`. The `.bin` file is the `buffer 0` that is missing. Make sure it is in the same folder as the gltf file and you should be good.

hth
