### ISSUE TITLE
Shader is missing in build

### ISSUE THREAD

**Issue by lkaesberg** [atteneder/glTFast#368]
Hi guys,
I created a project which uses glTFast to import some gltf Files at runtime. In the editor it works fine, but when I create a build it says that the glTF-pbrMetallicRoughness Shader is missing.
![image](https://user-images.githubusercontent.com/33939116/158495326-688586c4-beb5-4946-8c6f-4caec9242c16.png)

Sadly, the referenced website doesn't exist anymore. I tried using the Project Settings -> Graphics -> Shaders to always include it, but that didn't work. The model loads, but the texture is missing:
![image](https://user-images.githubusercontent.com/33939116/158495609-eaad744e-9775-4df8-af14-b34724e1d432.png)

Unity tells me that there is some error with the shader. Maybe thats the reason why it doesnt get included:
![image](https://user-images.githubusercontent.com/33939116/158495689-42af344d-7d40-4b8d-b77d-fcc556d0acdb.png)

I already reimportet the whole package but that didnt help.

I hope somebody can help me. 
Kind regards
Lars

**Comment by atteneder** [comment]
Hi @lkaesberg,

Thanks for reporting. Indeed that link was outdated. Here's the correct one:

<https://github.com/atteneder/glTFast/blob/main/Documentation%7E/ProjectSetup.md#materials-and-shader-variants>

Let me know if that helped

Regards,
Andi

**Comment by lkaesberg** [comment]
Thanks a lot. That solved it.
