### ISSUE TITLE
glb import from network share failed

### ISSUE THREAD

**Issue by fagerbur** [atteneder/glTFast#37]
I tried to import a .glb from a network share and got the following error.

```
HTTP/1.1 502 Bad Gateway \\server\share\file.glb
UnityEngine.Debug:LogErrorFormat(String, Object[])
GLTFast.<LoadRoutine>d__6:MoveNext() (at Assets/GLTFast/GltfAsset.cs:41)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
```

**Comment by atteneder** [comment]
Hi,
I think the error message says it all: that is not a valid HTTP URL.
What you can try is to mount the network share and load the file like a regular local file. To do this set the `GltfAsset.url` to the local path, prefixed with `file://`, which indicates that it is a local path. On macOS this might look something like `file:///Volumes/Sharename/path/to/file.glb`.
The download is done via [UnityWebRequests](https://docs.unity3d.com/ScriptReference/Networking.UnityWebRequest.html). If a manual download via this class works for you, reopen the issue.

**Comment by fagerbur** [comment]
@atteneder in the use case I'm pursuing, asking all of my users to mount the file share locally isn't a very viable approach, would something like this fall under enhancement instead of issue?

**Comment by atteneder** [comment]
Sure!
UnityWebRequest  (and glTFast alike) handles local files as well as HTTP, so you could host your content on a HTTP web server, be it internal or public.

**Comment by fagerbur** [comment]
totally understand, thanks for the info!
