### ISSUE TITLE
glTF/PbrMetallicRoughness renders pink

### ISSUE THREAD

**Issue by atteneder** [atteneder/glTFast#377]
### Discussed in https://github.com/atteneder/glTFast/discussions/373

<div type='discussions-op-text'>

<sup>Originally posted by **rycsim** March 21, 2022</sup>
I'm testing gltF-demo-2020.3hdrp. When I use the shader "glTF/PbrMetallicRoughness" the runtime export work well but unity render it "pink" . Am I doing something bad ? Thanks for advance for the help

![Capture](https://user-images.githubusercontent.com/1567978/159269533-36a36a24-a54d-46b7-bc15-1ba1b9368711.JPG)
</div>

**Comment by atteneder** [comment]
Re-open if you find time to give feedback.

**Comment by ashkan-saeedi-mazdeh** [comment]
Upgrading materials to latest hdrp version from the HDRP wizard fixes this.
