### ISSUE TITLE
KTX support

### ISSUE THREAD

**Issue by seyfeb** [atteneder/glTFast#381]
I tried to load a file with KTX textures. To this end, I installed (as documented in the main README) in a clean Unity 2021.2.25f1 project:

1. glTFast via the Installer Package
2. [KTX/Basis Texture Unity Package](https://github.com/atteneder/KtxUnity) via giturl. I tried the installer Package first but there were errors  about scoped registries

    ```Failed to resolve packages: Registry configuration is invalid:
         Scoped registry at position 2 is invalid:
         "scopedRegistries[1].scopes" must contain at least 1 items. No packages loaded.
    ``` 
    so I threw out the second one in the manifest.json and decided to quickly install the package via giturl (https://github.com/atteneder/KtxUnity.git), which worked fine.

Then I added the file shared here: `https://github.com/KhronosGroup/glTF/issues/1750#issuecomment-580097079` which I expected to import successfully but on the asset properties in Unity’s Inspector window it reads

```
KtxUnity package needs to be installed in order to support glTF extension KHR_extension_basisu!
See https://github.com/atteneder/glTFast#installing for instructions
```

Are there any additional steps, packages, or something else required that I am missing? Sorry, if I’m overlooking something obvious here!

**Files**

https://github.com/KhronosGroup/glTF/files/4132437/Avocado.zip

**Desktop**
 - glTFast version 4.6.0
 - KTX/Basis Texture 2.0.1
 - Unity Editor version 2021.2.25f1
 - Platform: Editor

**Comment by atteneder** [comment]
Hi @seyfeb,

Do you mind sharing your `Packages/manifest.json` ?

It should be sufficient to install one package via the OpenUPM installer and add KTX via package manager. Don't know where you went off the rails.

**Comment by atteneder** [comment]
@seyfeb On another note: If you got as far as to the crash you reported in KtxUnity, then you had it installed successfully already.

I suggest to install it the way you did before. Feel free to re-open if you still have troubles.

**Comment by seyfeb** [comment]
Okay yeah that sounds sensible. I used the glTFast installer first and the KTXUnity installer afterwards. Each tried to install the scoped registry, which didn’t work out well ;)

Interestingly when adding the KtxUnity package via the scoped URL, on the malformed gltf+KTX file it reports 

```
KtxUnity package needs to be installed in order to support glTF extension KHR_extension_basisu!
See https://github.com/atteneder/glTFast#installing for instructions
```

while it works for the Avocado model encoded with a new version of gltfpack. So the message was just confusing since it _probably_ has to do with https://github.com/atteneder/KtxUnity/issues/52

**Comment by atteneder** [comment]
@seyfeb That does not make sense. Either installation worked and it loads correctly (or crashes) or you get the message about missing extension.

**Comment by seyfeb** [comment]
Sorry, you're right. I had to reimport the Asset for the Editor to be crashing again. The message that the package needs to be installed does not get dismissed since importing is not possible (only with a crash, which retains the message).
