### ISSUE TITLE
Import/Export round-trip does not preserve all material features

### ISSUE THREAD

**Issue by myartings** [atteneder/glTFast#385]
**Describe the bug**
Gltf Exporter gives a wrong result. First import a glb format asset into unity and add to the scene. Then export the select game object. The exported glb asset is different from the original one.

**Files**
glb model
[DamagedHelmet.zip](https://github.com/atteneder/glTFast/files/8531422/DamagedHelmet.zip)

**To Reproduce**
1. add the glb asset into unity
2. drag the model to the scene
3. select the game object, click menu-> GameObject->Export glTF -> GLB
4. add the exported glb file into asset folder, see the result.

**Expected behavior**
The exported file is exactly same with original one.

**Screenshots**

original
![Snipaste_2022-04-21_21-33-12](https://user-images.githubusercontent.com/4220108/164472947-cd73c6d2-0de3-4bdf-9756-2c1ad1b1b366.png)
![Snipaste_2022-04-21_21-33-35](https://user-images.githubusercontent.com/4220108/164470152-49c8458a-7035-4dab-9f86-6e8137163b04.png)
![Snipaste_2022-04-21_21-35-43](https://user-images.githubusercontent.com/4220108/164470167-f793e87a-5a82-4565-8d26-eb4f93184875.png)
exported
![Snipaste_2022-04-21_21-34-49](https://user-images.githubusercontent.com/4220108/164470190-596f0362-9657-4b9c-8ff2-1b5ca11da21c.png)
![Snipaste_2022-04-21_21-35-17](https://user-images.githubusercontent.com/4220108/164470212-72d1849f-8f5e-484d-bf0c-456dd4391a7d.png)
![Snipaste_2022-04-21_21-35-59](https://user-images.githubusercontent.com/4220108/164470226-8d259321-d161-4dae-bc9f-983b4729df1f.png)

The textures has lost when exported, the exported textures are also modified. And the material parameter is different with original one,  e.g. texture_ST. 

**Desktop (please complete the following information):**
 - glTFast 4.6.0
 - Unity 2020.3.30f1c1
 - Universal Render Pipeline 10.8.1
 - Windows Editor
 
**Additional context**

**Comment by atteneder** [comment]
@myartings Another question: Is this a test-run for a production workflow you're seriously aiming at or did you just stumble across it while playing.

If it's the former, I'm happy to hear insights about requirements (like what shaders would you prefer to import to).

**Comment by myartings** [comment]
@atteneder Thank you for your response. This is a test-run for a production workflow. We aim to make a avatar creator at rum time. It will combine multiple glb body asset into a single avatar model and expect to export the result game object to one glb model file for other use.  Considering shaders, we have no special requirements. It is just ok when rendering correctly.

**Comment by atteneder** [comment]
@myartings That's a helpful insight. My 2 cents regarding shader selection:

- Lit
  - pro: Battle prove standard
  - contra: ORM maps need to get converted at run-time, potentially slowing down loading/exporting
- glTF shaders:
  - pro: Faster loading/exporting
  - pro: Feature set is built around glTF, so round-trip is more likely to be lossless in the future
  - con: Not as well (there might be missed corner cases on ceratin platform/SRP/settings combination)

I think glTF shaders would be better in your case, but in case import to Lit is available sooner, I'd not rule that out as option either.

**Comment by atteneder** [comment]
Note: Export of glTFast shader based materials was added in [glTFast 6.5.0](https://docs.unity3d.com/Packages/com.unity.cloud.gltfast@6.6/changelog/CHANGELOG.html#650---2024-05-15). This means import-export round-trips now preserve most material features.
