### ISSUE TITLE
Performance on ios

### ISSUE THREAD

**Issue by robertrost** [atteneder/glTFast#39]
The (impressive) speed of this library in the editor gets lost when building for ios. The loading duration increases by 400%. Switching from .glb to .gltf does not affect the duration.

**Comment by atteneder** [comment]
Hi robert,

Thanks for the feedback.

What device are you using?
Which Unity Version?
I can offer to profile it myself, if you can provide your content.

**Comment by robertrost** [comment]
Hey, sorry for the lack of information:

Unity: 2019.1.4f1
device 1: iPhone XS running ios 12.3.1
device 2: iPad Pro 11" (6GB RAM) running ios 12.2
note 1:  The lack of speed seems to increase especially for large (> 1 mio vertices) geometries.
note 2: I am loading the geometry from the local filesystem using "file://......" as url.

thanks for your offer, that would be great! We will try to create an example project demonstrating the issue.

PS.: Even if the speed is a lower on my ios devices, I wanted to say thank you for the very very nice library. It saved me really a lot of time and I was absolutely impressed about how easy it is to use.

**Comment by atteneder** [comment]
Great to hear you like it!

Your devices are fast and loading from local drive should be no bottleneck. I never tested meshes this big though, so I'll look if there's room for optimization/improvements.

**Comment by atteneder** [comment]
might want to read #52, in case there are parallels.
Since you didn't provide test data, I'll close this one. Re-open if that changes.
