### ISSUE TITLE
SkinnedMeshRenderer bounds are incorrect

### ISSUE THREAD

**Issue by hybridherbst** [atteneder/glTFast#397]
**Describe the bug**
While trying to debug
- https://github.com/mrdoob/three.js/issues/24018

I found that a similar (but different) issue happens when importing the file via glTFast - when playing back the contained animation the skinned mesh is only sometimes visible, sometimes not, and it looks like the bounds are incorrectly updated.

This could well be a Unity bug, but the original comes from Unity and plays just fine, so I'm not sure...

**Files**

[SkinningCullingBug-truncated.zip](https://github.com/atteneder/glTFast/files/8651596/SkinningCullingBug-truncated.zip)

**To Reproduce**
1. Import the above file at edit time (drop it in Unity)
2. Place in scene, add a PlayableDirector, make a timeline, add the clip so you can scrub it
3. Scrub through the clip and move around in the scene view
4. Note that the mesh isn't always visible, it seems whenever the transform root is outside the scene view bounds the mesh is culled away.

**Expected behavior**
SkinnedMeshRenderer should have correct bounds to prevent this from happening I guess

**Screenshots**

https://user-images.githubusercontent.com/2693840/167409782-cdb94101-e266-4cf2-ad0b-9086dccf4b21.mp4

![20220509-142820-vbFZ-Unity_FmZS](https://user-images.githubusercontent.com/2693840/167409832-098897c6-69c5-467f-984c-301741c1d1b7.gif)

**Comment by atteneder** [comment]
glTFast cannot calculate the animated bounding box (yet; see #301 ), so `updateWhenOffscreen` is enabled by default, meaning the bounds are calculated by Unity each frame.

Observation: The bounds seem to be invalid whenever the scale of `LOD0` is animated to 0/0/0. I guess the bounds are calculated correctly, but then the 0/0/0 scale jams it.

Is that the same for the original?

Also: `RootNode` scale in Z is `-1`. Shouldn't be a problem, just logging the observation.

**Comment by hybridherbst** [comment]
Interesting: I wasn't aware that LOD0 is scaled to 0 in some of these frames, that definitely contributes to the issue, and it's not the same as in the original!
Also it seems something else on my end has set "Update when offscreen" to false, so I'd say glTFast behaves correctly here. Thanks!
