### ISSUE TITLE
UV value is broken when it's out of 0~1 range.

### ISSUE THREAD

**Issue by wonkee-kim** [atteneder/glTFast#398]
**Describe the bug**
The model's uv value is as below and it's broken when importing.
![treeUV](https://user-images.githubusercontent.com/830808/167667018-6569dd4e-3254-4f8e-861b-7b6b7098032d.JPG)

This happens only on URP version (built-in was fine) and happens on webgl build, in the editor it's okay.
(gltfast - built in)
![before](https://user-images.githubusercontent.com/830808/167508076-735f5bb7-ef65-4aed-93df-9857473d607e.JPG)

(gltfast - urp)
![after](https://user-images.githubusercontent.com/830808/167508082-88bcc6e8-978a-4e74-823a-62e23ac44db7.JPG)

**Files**
The model file that is broken.
[LowPolyTree.zip](https://github.com/atteneder/glTFast/files/8662997/LowPolyTree.zip)

The model file after changing the uv and fixed.
[LowPolyTree_after fixing uv.zip](https://github.com/atteneder/glTFast/files/8662998/LowPolyTree_after.fixing.uv.zip)

**To Reproduce**
1. Import the attached model using glTFast - URP on webgl build.
2. See the model appears okay.
3. This doesn't happen in the Editor, it happens on webgl build.
(I tested with command line `-force-gles` but it still is okay in the Editor.)

**Expected behavior**
The model appears the same when it's built-in render pipeline.

**Desktop (please complete the following information):**
 - glTFast version: 4.7.0
 - Unity Editor version: 2020.3.19f1
 - Render Pipeline and version: Universal Render Pipeline 10.2
 - Platform: WebGL build.
 
 
additionally (if significant for the bug):
 - Windows - Chrome

**Comment by atteneder** [comment]
@wonkee-kim Thanks for reporting.

I haven't finished investigating, but first significant observation:

[glTF-Validator](https://github.khronos.org/glTF-Validator/) reports that `[LowPolyTree.zip](https://github.com/atteneder/glTFast/files/8662997/LowPolyTree.zip)` contains invalid tangents (of length zero). I wouldn't be surprised that this is the cause of the invalid shading. I am surprised it's working for built-in though.
