### ISSUE TITLE
Burst 1.6.5 breaks UWP build

### ISSUE THREAD

**Issue by Holo-Krzysztof** [atteneder/glTFast#400]
**Describe the bug**
I tried upgrading to glTFast 4.7.0 in our project a few weeks ago, but that broke our UWP build; it seems to be due to the dependency on Burst 1.6.5.
I can't find it on the issue tracker right now, but Unity themselves have downgraded Burst in 2020.3.34 (see [release notes](https://unity3d.com/unity/qa/lts-releases?version=2020.3)) after having upgraded just one version prior to that.
Here's a forum thread about it: https://forum.unity.com/threads/unable-to-build-for-uwp.1264418/

**To Reproduce**
1. Create new URP project
2. Import glTFast 4.7.0
3. Build for UWP
4. See Burst compiler error

**Expected behavior**
The application builds for UWP

**Desktop (please complete the following information):**
 - glTFast version: 4.7.0
 - Unity Editor version: 2020.3.31
 - Render Pipeline and version: URP 10.8.1
 - Platform: UWP

**Comment by atteneder** [comment]
Hi @Holo-Krzysztof ,

Thanks for reporting and your patience. Annoying bug, but I'll wait for Burst 1.6.6 to fix this and keep this issue open, just in case anyone is looking for a solution.

**Comment by tsoen** [comment]
Hello,
I just faced this today.
Burst 1.6.6 seems to be resolving this issue : https://issuetracker.unity3d.com/issues/build-fails-with-error-mono-dot-cecil-dot-assemblyresolutionexception-failed-to-resolve-assembly-when-unity-iap-is-in-the-project 

Downgrading to glTFast 4.6.0 resolved the issue.
