### ISSUE TITLE
Loading Textures in Android and in Unity

### ISSUE THREAD

**Issue by alexs7** [atteneder/glTFast#405]
Hello,

I have a question about loading textures along side a .glb model.

First in Unity, if I install gltFast and then drag and drop the textures (.jpgs) with the .glb model the inspector then shows the model coloured.

Second, in Android do I need to load the textures in code or does the loader picks them up automatically ?
If so how does it know which files to pick?

Thanks!

**Comment by atteneder** [comment]
Hi @alexs7 ,

First off please elaborate your use-case/workflow. Do you want to import glTFs into your project (at design-time) or load them at run-time?

The advantage of a glTF-binary (glb) is that it can encapsulate all files/data within a single file (that includes textures). Now it is possible to still have external textures, but it is somewhat unusual. If you can share your data (or a similar test file), I could have a look.

**Comment by alexs7** [comment]
@atteneder Apologies for the late reply.

I want to upload files on an Android device at runtime. But also I wanted to know if the library is used when you drag and drop files in Unity

**Comment by alexs7** [comment]
@atteneder the texture part makes sense.

regarding the  "glTF drag'n'drop" part (editor- or design-time import), that is when used in the editor not in realtime (or run-time). 
For example if I drag and drop a model in the editor it will show up as expected, I was just wondering if this happens because of glTFast or is it Unity doing showing the model.

Ignore the upload part I got that sorted.

Thanks!

**Comment by atteneder** [comment]
@alexs7 Yes, glTFast will import files you drop into your Assets folder 🎉

If it looks different in-editor vs. at run-time, usually the shaders are not setup correctly.

Let me know if you have further questions or close the issue otherwise.

**Comment by alexs7** [comment]
@atteneder thanks!
