### ISSUE TITLE
Support for Universal Render Pipeline (URP)

### ISSUE THREAD

**Issue by atteneder** [atteneder/glTFast#41]
Currently there's only support for the Built-In render pipeline via `DefaultMaterialGenerator`. It implements the interface `IMaterialGenerator`.

To add support for the URP, the corresponding code creating the materials has to go into a new class implementing `IMaterialGenerator`.

It has to be used in the constructor of `GLTFast` instead of the default one (ideally dynamically).
```
        public GLTFast() {
            materialGenerator = new DefaultMaterialGenerator();
        }
```

**Comment by Giorat** [comment]
How can I help you with this task? How should be added support for URP? Which files to add or change?

**Comment by atteneder** [comment]
Hi @Giorat ,
help is very much welcome! I updated the description, which should give you a starting point. I haven't used  the URP (or its shaders) thus far myself. Let me know if this helped.

**Comment by reubenkcoutinho** [comment]
Hi @atteneder, thanks for making this plugin!

**Comment by atteneder** [comment]
Hi @reubenkcoutinho,
Thanks for your input. I was thinking about a very similar solution, but didn't find time yet.
I'll be making more planninig in the upcoming weeks and I'll be putting more time iinito glTFast soon, so stay tuned!
