### ISSUE TITLE
CreateUniqueNames assumes the presence of nodes, which are optional

### ISSUE THREAD

**Issue by chrisdjali-wrld3d** [atteneder/glTFast#417]
**Describe the bug**
The glTF 2.0 spec says
> glTF assets MAY define nodes, that is, the objects comprising the scene to render.

On import, if the `ImportSettings` are set to generate unique names, `GltfImport`'s `Prepare` method calls `CreateUniqueNames`, which accesses `gltfRoot.nodes.Length`. If a glTF asset has no `nodes`, then `gltfRoot.nodes` will be `null` and accessing `.Length` will throw a `NullReferenceException`.

This can be worked around by adding a dummy node to the glTF asset.

I'm intending to send runtime assets over the wire as a mixture of glTF for things it's good at, and another serialisation system for Unity-specific data that glTF can't express, so I don't need the scene structure to be duplicated in the glTF.

**Files**

Here's a glTF file with just a texture which reproduces the issue:
```gltf
{
    "asset": {
        "generator": "I wrote this by hand",
        "version": "2.0"
    },
    "textures": [
        {
            "name": "An unreferenced texture",
            "sampler": 0,
            "source": 0
        }
    ],
    "images": [
        {
            "uri": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAIAAAACCAIAAAD91JpzAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAATSURBVBhXY/jPwADEjEDi/38GAB72BP3Pc1wfAAAAAElFTkSuQmCC"
        }
    ],
    "samplers": [
        {
            "magFilter": 9729,
            "minFilter": 9986,
            "wrapS": 10497,
            "wrapT": 10497
        }
    ]
}
```

**To Reproduce**
1. Put the above glTF into a project's `Assets` directory.
2. Observe that a `NullReferenceException` appears in the Unity console.

The same happens if the asset is loaded at runtime by URI, although not with the default settings.

**Expected behavior**
The glTF asset is loaded without throwing an exception.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - glTFast version: 4.8.0
 - Unity Editor version: 2020.3.28f1
 - Render Pipeline and version: Built-in
 - Platform: Presumably all, Windows & Editor tested.

**Comment by atteneder** [comment]
Hi @chrisdjali-wrld3d ,

Thanks a lot for reporting. You're right, this shouldn't crash. I used to have material-only glTFs at one point and I plan to re-introduce them to my test set.
