### ISSUE TITLE
Textures and images aren't loaded unless a material is present

### ISSUE THREAD

**Issue by chrisdjali-wrld3d** [atteneder/glTFast#418]
**Describe the bug**

`LoadImages` skips loading textures and images if no materials are present: https://github.com/atteneder/glTFast/blob/3eab4a512a359e54f484dabc8e41360e00004ab7/Runtime/Scripts/GltfImport.cs#L793

[The glTF 2.0 spec](https://www.khronos.org/registry/glTF/specs/2.0/glTF-2.0.html#_gltf_materials) says materials are optional. It's possible to use a glTF as a bundle of textures without necessarily including any materials that reference them, and connect them up to Unity via other means.

**Files**

Here's the same glTF as reproduced #417, as it repros this problem, too:
```gltf
{
    "asset": {
        "generator": "I wrote this by hand",
        "version": "2.0"
    },
    "textures": [
        {
            "name": "An unreferenced texture",
            "sampler": 0,
            "source": 0
        }
    ],
    "images": [
        {
            "uri": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAIAAAACCAIAAAD91JpzAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAATSURBVBhXY/jPwADEjEDi/38GAB72BP3Pc1wfAAAAAElFTkSuQmCC"
        }
    ],
    "samplers": [
        {
            "magFilter": 9729,
            "minFilter": 9986,
            "wrapS": 10497,
            "wrapT": 10497
        }
    ]
}
```

**To Reproduce**
1. Run this code (e.g. as an editor script or part of a MonoBehaviour):
   ```cs
   var gltf = new GLTFast.GltfImport();
   await gltf.Load("file:///path/to/gltf");
   for (int i = 0; i < gltf.textureCount; i++)
   {
       var tex = gltf.GetTexture(i);
       Debug.Log($"Index: {i}, tex: {tex}");
   }
   for (int i = 0; gltf.GetSourceTexture(i) != null; i++)
   {
       var sourceTex = gltf.GetSourceTexture(i);
       Debug.Log($"Index: {i}, sourceTex: {sourceTex}");
   }
   ```
3. Observe that although the `sourceTex` line logged things, the `tex` one didn't.
4. Add the following to the glTF file (or load an alternative that already contains it):
   ```gltf
   "materials": [
       {}
   ]
   ```
5. Run the code again.
6. Observe that the `sourceTex` line and `tex` line log the same number of things.

**Expected behavior**
Textures are fully loaded even when the dummy material is not present.

**Desktop (please complete the following information):**
 - glTFast version: 4.8.0
 - Unity Editor version: 2020.3.28f1
 - Render Pipeline and version: Built-in
 - Platform: Presumably all, Windows & Editor tested.

**Comment by atteneder** [comment]
Hi @chrisdjali-wrld3d ,

Thanks for reporting.

So you intend to use glTF as a container for textures, right? Do you mind elaborating your use-case in more detail? For that case the only benefit glTF brings to the table (compared to a plain texture file list) is the sampler settings, right?

Another reason I want to understand is that I have some refactoring ideas planned that move away from generically loading all content upfront. Instead only the required resources are loaded on-demand. Think of instantiating just one of many scenes or showing only the first material variant. If this concept becomes reality, your use-case like needs some option to plainly load all textures, referenced or not.

Thanks

**Comment by atteneder** [comment]
@chrisdjali-wrld3d I fixed this. For now all textures are loaded (regardless if being referenced), but this might change in the future (meaning the default behavior changes; loading all textures should be possible with proper settings).

Still curious about your use-case. Thanks!

**Comment by chrisdjali-wrld3d** [comment]
As mentioned in #417, I'm intending to send runtime assets over the wire as a mixture of glTF for things it's good at, and another serialisation system for Unity-specific data that glTF can't express, so I don't need the scene structure to be duplicated in the glTF.

The other serialisation system is JSON-based, and doesn't use it particularly efficiently, either, so data like textures and vertex buffers end up a lot more bulky than in a binary glTF. If it were just texture data, sending a collection of texture files might make more sense, but as it's multiple textures per set of data and there's mesh data, too, `.glb` makes the most sense as a container.
