### ISSUE TITLE
LoadAccessorData assumes the presence of nodes, which are optional

### ISSUE THREAD

**Issue by chrisdjali-wrld3d** [atteneder/glTFast#422]
**Describe the bug**
The glTF 2.0 spec says
> glTF assets MAY define nodes, that is, the objects comprising the scene to render.

On import, if the glTF contains accessors, `LoadAccessorData` is called. It iterates over `gltf.nodes` without first checking whether it's null, which it will be when there aren't any nodes.

https://github.com/atteneder/glTFast/blob/6c9b3773e5f9fa72ab9540f761216f5f08efed28/Runtime/Scripts/GltfImport.cs#L2351

This throws an exception, which fails the `Task` and stops the rest of the import process.

**Files**

Here's a glTF file with just an accessor and its dependencies which reproduces the issue:
```gltf
{
    "asset": {
        "generator": "I wrote this by hand",
        "version": "2.0"
    },
    "accessors": [
        {
            "bufferView": 0,
            "componentType": 5126,
            "count": 1,
            "type": "SCALAR"
        }
    ],
    "bufferViews": [
        {
            "buffer": 0,
            "byteLength": 4,
            "byteOffset": 0
        }
    ],
    "buffers": [
        {
            "byteLength": 4,
            "uri": "data:application/gltf-buffer;base64,MTExMQ=="
        }
    ]
}
```
Side note: although dodgy, it's technically valid a glTF with `"uri": "data:application/gltf-buffer,1111"`, i.e. with the binary data as a plain ASCII string if all its bytes happen to be valid ASCII, but that triggers another bug in the data URI decoder.

**To Reproduce**
1. Put the above glTF into a project's `Assets` directory.
2. Observe that a `NullReferenceException` appears in the Unity console.

The same happens if the asset is loaded at runtime by URI.

**Expected behavior**
The glTF asset is loaded without throwing an exception.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - glTFast version: 4.8.0
 - Unity Editor version: 2020.3.28f1
 - Render Pipeline and version: Built-in
 - Platform: Presumably all, Windows & Editor tested.

**Additional context**

I basically copied and pasted most of this report from #417 as it's the same bad assumption causing the problem.

**Comment by atteneder** [comment]
@chrisdjali-wrld3d Thanks for reporting, I'm on it.

I'm curious, what's the motivation behind making those unusual test files? Is it some non-ordinary use-case or are you testing glTFast's robustness?

In general I have to admit that glTFast was not heavily tested on unusual (but valid) nor broken/invalid (or even malicious) data, but that's something I'd like to approach at some point.

I'd prefer a systematic way with automated tests, so maybe I can gather your feedback and requirements around this, once I understand your use-cases.

Thanks.

**Comment by chrisdjali-wrld3d** [comment]
As discussed here https://github.com/atteneder/glTFast/issues/418#issuecomment-1156367785, I've got to send chunks of scenes over a network connection. They're partially user-generated, so can't be put in Asset Bundles, which only the editor can create, but I've got another serialisation system that can work with Unity objects. While it *can* handle data like meshes and textures, it doesn't represent them as efficiently as binary glTF (or even as efficiently as JSON-based glTF) so I don't think it's going to scale. Instead, I'm planning on putting that kind of data in a binary glTF, and referencing it from the other system. I *could* just stick all that data in a big binary file with some metadata saying how to interpret byte ranges within it, but that's already what a binary glTF is if you leave out a bunch of optional fields, so there's no point reinventing the wheel.

The test files look the way they do because I'm still prototyping, and it's easiest to work with text-based glTF when I'm directly modifying them. The one I put in my other two issue reports was literally the file I was testing at the time, as I attempted loading a file containing just a texture before I attempted to reference that texture in the other system. I made this one specifically for this report, though, as the file I was working on had a bunch of other mess in it, and I thought a fresh file would more clearly illustrate the problem and also save me having to tidy up the mess in order to get a file that didn't upset the validator or reference bits in the middle of several separate buffer files.

**Comment by atteneder** [comment]
@chrisdjali-wrld3d Ah, ok. Got it :)

Well, thanks a lot and keep those reports coming!

**Comment by atteneder** [comment]
@chrisdjali-wrld3d Indeed the sample models are a wild mix :)

There's also the [asset generator](https://github.com/KhronosGroup/glTF-Asset-Generator), which should solve this problem, but I haven't included it in my unit tests and it's not very actively maintained.

I've also started collecting test models: [glTF-test-models](https://github.com/atteneder/glTF-test-models).
If you don't mind, I'll add your models (or create similar, CC-BY ones otherwise).

**Comment by atteneder** [comment]
@chrisdjali-wrld3d fyi:

<https://github.com/atteneder/glTF-test-models/tree/main/EmbedBufferInvalid>
<https://github.com/atteneder/glTF-test-models/tree/main/OnlyAccessors>

Fix is in `gltfast-4` branch. Fixed release coming this week.

Thanks!

**Comment by chrisdjali-wrld3d** [comment]
The one that's been called `EmbedBufferInvalid` actually has a *valid* buffer. The official validator doesn't complain about the file. Base64-encoding binary data in data URIs is optional. I've looked it up, and when base64 isn't used, printable 7-bit ASCII characters that don't interfere with anything else (e.g. not `"` as it's a quoted string) are okay, but other octets need percent-encoding. Obviously it's not used much, as for binary data, it'd be bigger than base64 on average, but it's not invalid, so the name in that repo isn't good.
