### ISSUE TITLE
If "Scene" element is not defined, but "scenes" contain nodes, then loader will fail to load that scene

### ISSUE THREAD

**Issue by artyomabgaryan** [atteneder/glTFast#424]
If "Scene" element is not defined, but "scenes" contain nodes, then loader will not load that scene, which 

[cat.zip](https://github.com/atteneder/glTFast/files/9029736/cat.zip)

// According to glTF specification, loading nothing is
// the correct behavior

[Here is gltf specs](https://www.khronos.org/registry/glTF/specs/2.0/glTF-2.0.html#scenes-overview)
> A glTF asset that does not contain any scenes SHOULD be treated as a library of individual entities such as materials or meshes.

The key word is scene**S**!.

File is tested in validator and it's valid.

**To Reproduce**
load file in unity

**Expected behavior**
Load cat model as every loader in js does

**Desktop (please complete the following information):**
 - glTFast version - 2.0
 - Unity Editor version [e.g. 2022.1.5f1]
 - Render Pipeline and version- Built in
 - Platform: Editor.Win

**Comment by atteneder** [comment]
Hi @artyomabgaryan ,

Thanks for reporting.

glTFast 4.0.0 added proper scene support. Please use the latest version and test again.

Remarks on your test file:

- It contains one item in `scenes`
- The `scene` property is not set, so instantiating nothing is the correct behavior (tested successfully with 4.8.2)

hth

**Comment by artyomabgaryan** [comment]
Hi @atteneder !
First of all, thank you soo much for creating this amazing loader (and other repos) and making them freely available for all.

We are using 4.8.2th version of glTFast ("com.atteneder.gltfast": "4.8.2" , not sure why I use that "2.0" above :) )
On your second remark you note that "instantiating nothing is the correct behavior" and referring to this line of gltf spec ?
> An additional root-level property, **scene** (note singular), identifies which of the scenes in the array **SHOULD** be displayed at load time. When scene is undefined, client implementations **MAY** delay rendering until a particular scene is requested.

I agree with you, but last sentence says that you MAY not load the scene if scene param isn't defined, but user can request a particular scene. So, is there a way to request specific scene at index? 
Or maybe the importer could be with options (pass to constructor maybe?) like ``` loadFirstSceneIfSceneParamIsNotDeifned = true ``` . This will allow developers to decide which behavior is more acceptable for them.

For now I copied glTFast from packages to project's plugins folder and made some changes to load the 0 index scene is scene param is not defined. But it would be great to have this in repo and get all updates you're making directly without manually fixing same thing each time.
