### ISSUE TITLE
Invalid Package Dependency

### ISSUE THREAD

**Issue by tylocook** [atteneder/glTFast#43]
I am not incredibly well versed in how Unity's fancy new Package Manager works, but when I follow your instructions on attempting to add glTFast to my `manifest.json` file, it returns the following error.

```
An error occurred while resolving packages:
  Package com.atteneder.gltfast@https://github.com/atteneder/glTFast.git has invalid dependencies:
    com.atteneder.draco: Package [com.atteneder.draco@1.0.1] cannot be found
```

**Comment by tylocook** [comment]
I see you made a change 19 days ago to "fix" this, but I'm curious as to how Unity tries to resolve seeing it in your `packages.json` file...

https://github.com/atteneder/glTFast/commit/8ef4fb7a22bb4d70f0efab75ff718376de362a17

**Comment by atteneder** [comment]
Hy @tylocook 

thanks a lot for pointing this out. I tested an installation from scratch myself and could confirm the issue. Turns you, you also need to add the DracoUnity package manually, which is a dependency. Add this line to your package manifest:

`"com.atteneder.draco": "https://gitlab.com/atteneder/DracoUnity.git",`

I updated the installation instructions as well.

Please let me know if this fixes your problem.

regards,
atti

**Comment by tylocook** [comment]
It did thanks. However I am also getting an error with your Draco package saying the Windows x64 DLL is not currently built for the x64 platform.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by atteneder** [comment]
Oh well :(

I can't fix this before October 21st, since I don't have access to a Windows Box until then.

I switched to build via [GitHub Actions](https://github.com/atteneder/draco/actions) recently. Seems like the build is not configured correctly.

**Comment by tylocook** [comment]
Ah I see. Well no rush for me, just wanted you to be aware of it. Looking forward to the fix of course, but I can build it myself in the meantime probably.


________________________________

**Comment by atteneder** [comment]
I couldn't reproduce the issue, but I have a suspicion:

Please navigate to the DLL file and inspect it. Check if it's only 100-200 bytes and its content looks something like this:

```
version https://git-lfs.github.com/spec/v1
oid sha256:4cac19622fc3ada9c0fdeadb33f88f367b541f38b89102a3f1261ac81fd5bcb5
size 84977953
```

If so, the package was not cloned properly. Make sure you have a recent version of GIT and GIT LFS installed on your system, since Unity may use your system's GIT to clone.

hth

If it's still not working, open another issue. The original one is solved.
