### ISSUE TITLE
Bind poses unavailable without instantiating scene

### ISSUE THREAD

**Issue by chrisdjali-wrld3d** [atteneder/glTFast#430]
**Is your feature request related to a problem? Please describe.**
As mentioned in #426, I'm attempting to use `.glb` files to transmit mesh and texture data buffers over a network connection with the minimum metadata to explain what's what, and will have things like the scene structure along with other non-glTF-friendly data like MonoBehaviours delivered by a less efficient JSON representation. The current item on my list is bind poses. In glTF, these are represented via the `skins` property, where each skin contains an optional reference to an accessor containing the inverse bind matrices (defaulted to the identity matrix if absent) and a mandatory list of joints, which are indices to the nodes making up the skeleton.

#426 discusses potentially using the an accessor with a meaningful name to store the bind matrices without needing a skin, which requires a joint list and therefore nodes for the joint list to reference, which I otherwise wouldn't need, and points out that I could work around that being currently impossible by eating the cost of storing otherwise-unnecessary nodes.

It turns out, though, that that isn't currently possible, either - `GltfImport.GetBindPoses` isn't public, so I'd need to instantiate a scene which used the skin to associate them with a mesh, which is explicitly something I don't want to do as the GameObjects I want to have come from elsewhere.

**Describe the solution you'd like**
The simplest solution would be to make `GltfImport.GetBindPoses` public.

Other, related, stuff might be made a bit easier by making the `gltfRoot` schema object accessible, too.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by atteneder** [comment]
Hi @chrisdjali-wrld3d 

Making `GetBindPoses` public (with proper XML docs) sounds about right to me. Also a getter for the root object (with a proper warning that this is fore read-only access, unless you want bad things to happen) would be great.

I'll have a look, but feel free to speed things up with a PR of yours.
