### ISSUE TITLE
UV wrong

### ISSUE THREAD

**Issue by triansion** [atteneder/glTFast#439]
@atteneder Hello,I found another bug😂. When I manually import a GLB file whose UVs are quantized to Short format, its textures are displayed wrong.

This is wrong file's screenshot：
![image](https://user-images.githubusercontent.com/48820794/180378076-b18c9fc4-52af-49e0-97d2-ecdef14340c7.png)

And this is right file's screenshot:
![image](https://user-images.githubusercontent.com/48820794/180378295-de65d82a-9629-4740-a179-b2a6de1dbe81.png)

So I found ConvertUVsInt16ToFloatInterleavedNormalizedJob code has wrong in line 740:
![image](https://user-images.githubusercontent.com/48820794/180378711-9603e43a-98c0-4e0e-9fb7-50b015099b2b.png)

Finally, it was working right after I fixed it like this:
![image](https://user-images.githubusercontent.com/48820794/180379063-d2fe5c27-92f0-450f-a3b0-889256c93c5f.png)

So I think I need to remind you
😜

**Comment by atteneder** [comment]
@triansion Thanks, great find and fix. This only surfaced when the jobs package is installed and the job system decided to split it in batches.

One question though: Why didn't you consider making a PR?

**Comment by atteneder** [comment]
fixed in 4.8.4
