### ISSUE TITLE
Out of Memory on Android Phone

### ISSUE THREAD

**Issue by zhang391239** [atteneder/glTFast#445]
The. Gltf model on the Android phone cannot release the memory correctly when it is destroyed

**Comment by atteneder** [comment]
Hi @zhang391239 ,

I require more information.

Do you experience out-of-memory errors during loading (maybe of a huge gltf) or afterwards (maybe after repeatedly loading and destroying models)?

If the latter, have you certified (via memory profiles) that there's a memory leak and figured what resources don't get destroyed properly?

How exactly do you destroy the glTF instance?

**Comment by atteneder** [comment]
I think #726 is about the same issue, but has more information, hence I'm closing this unanswered issue.
