### ISSUE TITLE
Materials should use Double Sided GI by default for editor import

### ISSUE THREAD

**Issue by hybridherbst** [atteneder/glTFast#452]
**Describe the bug**
Materials currently don't use double-sided GI. This means that when lightmapping scenes imported with glTFast, there's often problems with the results (the lightmapper assumes closed volumes).

I think the safer option, albeit with somewhat slower lightbake speeds, would be to assume double-sided.

**Comment by atteneder** [comment]
Hi,

The current behavior is that `doubleSidedGI` is set to the glTF material's `doubleSided` property.

If I get you right, you're saying sometimes it's beneficial to render front-face only, but bake GI double-sided, right?

Now the real question: is it just sometimes (or most often) or EVERY time? Depending on that answer I would:

1. Always set it to `true`
2. Add a `forceGIDoubleSided` import setting that allows overriding it to `true`

My guess would be option "sometimes" and thus solution 2

Thanks

**Comment by hybridherbst** [comment]
I think the right approach would be to respect the doubleSided property for mesh rendering, but always have double sided GI on. My understanding from the docs is that single-sided GI is only a performance improvement if and only if people know their scenes are "effectively watertight" and meshes are flush to each other.

**Comment by atteneder** [comment]
Resolved in 4.8.4
