### ISSUE TITLE
glb export in editor mode missing textures for custom shadergraph

### ISSUE THREAD

**Issue by tommynanny** [atteneder/glTFast#453]
**Describe the bug**
I tried to export glb file from both the context menu and from the code in editor mode, but it seems some textures are missing which use custom shader graphs. The only texture that is exported correctly is the one that uses "Universal Render Pipeline/Simple Lit", the other textures that use custom Shader Graphs are missing. I was wondering if I missed something.

**Files**

```c#
// CollectingLogger lets you programatically go through
// errors and warnings the export raised
var logger = new CollectingLogger();

// ExportSettings allow you to configure the export
// Check its source for details
var exportSettings = new ExportSettings {
  format = GltfFormat.Binary,
    fileConflictResolution = FileConflictResolution.Overwrite
};

var assetfolder = $ "{GBCityPath.Path(ExportPoint.AssetBundles)}/{CurrentLandSceneName}";
Utilities.PrepareFolder(assetfolder);

var path = $ "{assetfolder}/{fileName}.glb";

// GameObjectExport lets you create glTFs from GameObject hierarchies
var
export = new GameObjectExport(exportSettings, logger: logger);

// Add a scene
export.AddScene(new GameObject[] {
  land.gameObject
}, "My new glTF scene");

// Async glTF export
bool success = await export.SaveToFileAndDispose(path);

if (!success) {
  Debug.LogError("Something went wrong exporting a glTF");
  // Log all exporter messages
  logger.LogAll();
} else {
  Debug.Log($"Export to {path} Successfully");
  DestroyImmediate(land.gameObject);
}
```

**Expected behavior**
to generate a glb file that has no missing texture

**Screenshots**
![image](https://user-images.githubusercontent.com/22390882/185550651-72be8623-ffac-4d32-9b61-d13e8d011e97.png)

![image](https://user-images.githubusercontent.com/22390882/185552874-e415a8ac-d78d-496b-86cd-cbd2deae5a11.png)

![1660888535070](https://user-images.githubusercontent.com/22390882/185552571-09e88803-0692-49bb-8132-5a3f4c98dd40.png)

![1660888556559](https://user-images.githubusercontent.com/22390882/185552613-e3b88204-b67e-4457-b92d-d95d7223f57d.png)

![1660888771590](https://user-images.githubusercontent.com/22390882/185553066-3263ae88-5af1-4e8d-ae0c-85999a7f4705.png)

![1660888811719](https://user-images.githubusercontent.com/22390882/185553144-7d60b913-3b74-4950-b410-a6f745054acf.png)

**Desktop (please complete the following information):**
 - glTFast version: 4.8.3
 - Unity Editor version 2020.3.25f
 - Render Pipeline and version [e.g. Universal Render Pipeline 10.7.0]
 - Platform: [Editor]

**Comment by atteneder** [comment]
Hi @tommynanny,

Thanks for reporting.

Right now, only a [limited set of shaders is supported](https://github.com/atteneder/glTFast/blob/main/Documentation%7E/features.md#material-export).

glTFast cannot automatically figure out how to map a material's properties to glTF materials. The future plan is to offer a simple way to define the mapping, so that custom shader graphs can be exported as well.

hth

**Comment by atteneder** [comment]
Custom shader graphs either have to have identical properties than Lit/Standard shaders or you implement a custom material exporter ([IMaterialExport](https://docs.unity3d.com/Packages/com.unity.cloud.gltfast@6.9/api/GLTFast.Export.IMaterialExport.html)) and pass it into the constructor of [GameObjectExport](https://docs.unity3d.com/Packages/com.unity.cloud.gltfast@6.9/api/GLTFast.Export.GameObjectExport.html#GLTFast_Export_GameObjectExport__ctor_GLTFast_Export_ExportSettings_GLTFast_Export_GameObjectExportSettings_GLTFast_Export_IMaterialExport_IDeferAgent_ICodeLogger_).
