### ISSUE TITLE
UV not setted for pbrSpecularGlossiness material on URP

### ISSUE THREAD

**Issue by proto-ziii** [atteneder/glTFast#454]
**Describe the bug**
UV for glTF-pbrSpecularGlossiness material is not set correctly in URP, while the same gltf file works fine in standard pipeline.
I've tried to edit the related shader property references from "_MainTex" to "_BaseMap" in shader graph, and this seems to fix the issue.

**Files**
[Link to gltf file](https://storage.googleapis.com/protoworld-app.appspot.com/tmp/QmT7gLa7fUMeABEZXp3VjySyZXzZhVjB88v9PF4fcSaC8t_standard%20(2).glb)

**To Reproduce**
1. Create project with Unity URP template (2021.3.4f1)
2. Use "Gltf Assets" component to load the file (url as above)
3. The UV is wrong

**Expected behavior**
UV set properly as standard pipeline.

**Screenshots**
<img width="1826" alt="2022-08-19 15_47_50-Business Plan - 2208 - FigJam" src="https://user-images.githubusercontent.com/102203141/185580792-fd920ae7-fc66-4ed1-8c6e-804ec25c9de5.png">

**Desktop (please complete the following information):**
 - glTFast version - 4.8.3
 - Unity Editor version - 2021.3.4f1
 - Render Pipeline and version - URP 12.1.7
 - Platform: Editor & WebGL

**Comment by atteneder** [comment]
Thanks for spotting this and reporting! The references in the shader graph were incorrect.

Expect to land in a fix realease soon.

Note: The specular-glossiness material extension was archived and is deemed deprecated. Consider switching to metal-glossiness instead.
