### ISSUE TITLE
Support for Mesh instancing

### ISSUE THREAD

**Issue by ROBYER1** [atteneder/glTFast#461]
**Is your feature request related to a problem? Please describe.**
To recognise instanced meshes in a gltf file when loaded into Unity

**Describe the solution you'd like**
To save file sizes and if using during edit/editor time, to have those instances recognised by Unity as instances. My main reason for asking is that I am using[ Needle Tools](https://github.com/needle-tools/needle-engine-support) which exports the scene as gltf files to Three.js which also includes gltf files imported directly using GLTFast optionally. I have some large files with repeated meshes within that I could save hugely on file sizes by using instancing within the gltf files imported.

**Describe alternatives you've considered**
Currently I work around this by manually having empties in the positions I need meshes to be instanced at and only having one of the meshes within the file, then manually duplicate that mesh to those empty positions within Unity scene view myself. Needle recognizes and exports those Unity instanced meshes on export.

**Comment by atteneder** [comment]
I'm still don't know what this is exaclty about. Please answer the previously asked question:

> So you want the glTFast export to recognize Renderers with identical Meshes/Materials, so that it not only re-uses the Mesh, but adds a [EXT_mesh_gpu_instancing](https://github.com/KhronosGroup/glTF/blob/main/extensions/2.0/Vendor/EXT_mesh_gpu_instancing/README.md) extension, minimizing the instance overhead, right?

I ask, because glTFast supports instances upon import already and shouldn't duplicate a mesh if it is re-used upon export. However, it does not export GPU instances (via said extension).

Please elaborate the workflow and provide a sample scene/file if possible.

**Comment by ROBYER1** [comment]
I understand now! Was a bit confused about how the instanced assets are serialized but looks like Blender exports them fine with instanced meshes as a gltf.

I can leave this issue open for the exported GPU instancing as a feature request but it's nothing urgent. Feel free to close this otherwise, apologies I got in a bit of a muddle.

**Comment by atteneder** [comment]
Cool, got it now.
Don't worry, no harm done. I'm grateful for the feedback and I'm glad we could clarify your concern.
