### ISSUE TITLE
Import transformer

### ISSUE THREAD

**Issue by matrem** [atteneder/glTFast#463]
It could be good to add a mean for gltf import post transformation.

For example I need it to convert images from png/jpg to ktx2 at runtime, (and so changing gltfroot.images mimtype and uri), because blender exporter does not support ktx at the time.

**Proposal** :
In the materialGenerator or downloadProvider way add an _importTransformer_ based on this interface :
```
public interface IImportTransformer
{
    void Transform(Root gltfRoot, Uri baseUri);
}
```

At the end of ParseJsonAndLoadBuffers call it :
`this.importTransformer?.Transform(gltfRoot, baseUri);`

**Comment by atteneder** [comment]
Hi @matrem ,

In general I agree that the API to customize the loading behavior should get extended. The right API design is important. I'd argue your proposal is minimalist/straightforward, but the `IImportTransformer` has limited access to the glTF, which won't enable other use-cases.

Could you elaborate your use-case and workflow a bit more?
You're using design-time import (so not at run-time) and want to convert PNG/Jpeg textures to KTX ones, right?
Effectively turning glTFast into a pipeline tool that optimized the glTF.
Why don't you use existing tools like `gltf_transform` or `gltfpack`?

Not that I'm against the idea (I actually like it), but top prio atm are definitely the core features.

**Comment by matrem** [comment]
Hello, 

First we would like to use KTX to maximize loading performance, but for now blender gltf exporter seems not to manage KTX.

The worlkflow I described is at runtime, not design time, to avoid a manual step for our graphist. So the .gltf file is not modified.

So at runtime import, when the .ktx2 file does not exists (or older than the png/jpg), it's built from the existing png/jpg  (thanks to toktx khronos tool).
Then in order to get gltfast continue with loading the ktx file (instead of the other) gltroot.images[x] must be modified in memory (mimetype and/or uri). (at first I though providing a downloadProvider should suffice, but ktx code path is really not the same).

I guess gltf_transform or gltfpack are for design time usage in a post export step?

**Comment by atteneder** [comment]
> First we would like to use KTX to maximize loading performance, but for now blender gltf exporter seems not to manage KTX.

Understood. Good choice!

> The worlkflow I described is at runtime, not design time, to avoid a manual step for our graphist. So the .gltf file is not modified.
> 
> So at runtime import, when the .ktx2 file does not exists (or older than the png/jpg), it's built from the existing png/jpg (thanks to toktx khronos tool). Then in order to get gltfast continue with loading the ktx file (instead of the other) gltroot.images[x] must be modified in memory (mimetype and/or uri). (at first I though providing a downloadProvider should suffice, but ktx code path is really not the same).

I think I got it now. For every jpg/png image you're looking if there's a file with similar path, but .ktx2 extensions and use this one instead. If it does not exist, you fire up `toktx` to create it.

Calling `toktx` presumably only works on your developer machine (likely in the Editor's playmode), but that's not a problem, since you'll make sure you created the KTX files before shipping and (worst case) the png/jpeg fallback works.

> I guess gltf_transform or gltfpack are for design time usage in a post export step?

Exactly!

> But you're right another way could be to write a blender plugin to export the gltf in two ways (one with ktx for import one with png for graphist work).

Yeah. To me the optimization of glTFs is a step that should not be done in runtime code. There are many ways to do this in between export and loading, even in an automatic way. Writing a Blender script is one of them.

In case you reconsidered and chose to go after another solution, feel free to close the issue.

**Comment by matrem** [comment]
> Calling toktx presumably only works on your developer machine (likely in the Editor's playmode), but that's not a problem, since you'll make sure you created the KTX files before shipping and (worst case) the png/jpeg fallback works.
Our workflow is the same at shipping, for now, toktx is packaged in streamingasset folder (seems to work) (Window target).

But as you say it's perhaps a better idea to have everything ready at shipping to maximmize even the first loading time.

For now we'll stay on this solution (because it's the easyest, and with not so bad loading performance even at first loading with ktx conversion).

If you think this transformer concept is not worth it (or even open a door to bad practices), I'll close the issue.

**Comment by atteneder** [comment]
> > Calling toktx presumably only works on your developer machine (likely in the Editor's playmode), but that's not a problem, since you'll make sure you created the KTX files before shipping and (worst case) the png/jpeg fallback works.
> 
> Our workflow is the same in shipping build, for now, toktx is packaged in streamingasset folder (seems to work) (Window only target).

That sounds adventurous :)

> But as you say it's perhaps a better idea to have everything ready at shipping to maximmize even the first loading time.

Yes, encoding KTX is quite demanding, CPU-wise.

> For now we'll stay on this solution (because it's the easyest, and with not so bad loading performance even at first loading with ktx conversion).

Whatever floats your boat.

> If you think this transformer concept is not worth it (or even open a door to bad practices), I'll close the issue.

It definitely is a nice concept worth following. I'd like just put a bit more thought into it, so it can solve a broader range of use-cases and then think about a good naming (Transfomer is quite abstract and might not fit at all for other use-cases).

I'll close it for now, but I'll definitely consider your input when designing the Extension API.

Thanks!
