### ISSUE TITLE
Parsing issues when adding custom extensions

### ISSUE THREAD

**Issue by thompsoff** [atteneder/glTFast#464]
I have GLTF files that contain nodes with a custom extension, with a few strings inside :

```
"nodes": [
  {
    "extensions": {
      "custom_attributes": {
        "guid": "00000000-0000-0000-0000-0000000000000000",
        "publicName": "A public name"
      }
    },
    "name": "A name"
  }
]
```

I am now trying to retrieve those values using GLTFast. 

I realized that there are some open issues about support for custom extensions and extras, so in the meantime I forked the repo to have a try with implementing my custom extension in the node schema.

```
public class NodeExtensions {
    ...
    /// <inheritdoc cref="MeshGpuInstancing"/>
    public MeshGpuInstancing EXT_mesh_gpu_instancing;
    public NodeLightsPunctual KHR_lights_punctual;
    public CustomAttributes custom_attributes; // <-- Testing custom attributes in node schema
    ...
}
```
However, there is a peculiar null-check in the JsonParser class that doesn't appear to be doing its job anymore if it is extended with a null-check of my own custom extension.

```
// Step four:
// Further null checks on nodes' extensions
if (root.nodes != null) {
    for (int i = 0; i < root.nodes.Length; i++) {
        var e = root.nodes[i].extensions;
        if (e != null) {
            if (e.custom_attributes == null && // <-- Added this null-check for the custom extension
                e.EXT_mesh_gpu_instancing?.attributes == null &&
                (e.KHR_lights_punctual == null || e.KHR_lights_punctual.light < 0)) {
                root.nodes[i].extensions = null;
            }
        }
    }
}
```

In the instanciation phase, if a node has **only** a custom extension amongst its extensions, there will be a null reference exception, specifically in the GltfImport class:

```
var primitiveName =
    primitiveCount > 0
        ? $"{meshName ?? PrimitiveName}_{primitiveCount}"
        : meshName ?? PrimitiveName;

if (meshInstancing == null) {
    instantiator.AddPrimitive(
        nodeIndex,
        primitiveName,
        mesh,
        primitive.materialIndices,
        joints,
        rootJoint,
        gltf.meshes[node.mesh].weights,
        primitiveCount
    );
} else {

    var hasTranslations = meshInstancing.attributes.TRANSLATION > -1; <-- This will trigger a null reference exception
```

Which means that an instance of meshInstancing is created, even though no `EXT_mesh_gpu_instancing` extension was added to the node.

Its only when a node with both a `custom_attributes` and a `EXT_mesh_gpu_instancing` extension that this exception won't be triggered.

Why is a meshInstancing instance created, when there is none in the GLTF file? I don't really know what is happening under the hood in the parsing phase, but it appears that there is a specific purpose to the original null-check condition that eludes me.

Is there something I missed in my implementation of a new extension? Or in my general understanding of how GLTFast parsing works? Or could there be a limitation of how extensions are expected to work between the parsing and the instanciation phases?

For now here is the workaround I emplemented during the forth step of the parsing phase:

```
var e = root.nodes[i].extensions;
if (e != null) {
    if (e.EXT_mesh_gpu_instancing?.attributes == null)
    {
        e.EXT_mesh_gpu_instancing = null;
    }
    if ((e.KHR_lights_punctual?.light ?? -1) < 0)
    {
        e.KHR_lights_punctual = null;
    }
    if (e.custom_attributes == null && e.EXT_mesh_gpu_instancing == null && e.KHR_lights_punctual == null)
    {
        root.nodes[i].extensions = null;
    }
}
```

Unfortunatly, that means I had to edit existing code, which is something I prefer to avoid, especially if it is expected to see updates about how extensions are parsed in the future.

**Comment by atteneder** [comment]
Hi @thompsoff ,

Thanks for your patience. Excellent observations!

Yes, the problem lies within JsonUtility, which is used for parsing. Its the one that creates a default instance of `EXT_mesh_gpu_instancing` even though there is none in first place.

Your solution is valid and probably an improvement to the existing code. I'll try to adopt it soon. Thanks!

Also: I created a prototype that used Newtonsoft JSON instead of JsonUtility. This has other downsides, but with that you wouldn't need those ridiculous null checks anymore. If you're adventurous, It's here:

<https://github.com/atteneder/glTFast/tree/demo-metadata>

Thanks!

**Comment by atteneder** [comment]
You actually found a bug that's surfacing even without your custom code, so thanks again!
