### ISSUE TITLE
Support exporting for KHR_lights_punctual 

### ISSUE THREAD

**Issue by jf-gagnon** [atteneder/glTFast#470]
**Is your feature request related to a problem? Please describe.**
At the moment, KHR_lights_punctual  is only supported at import. Export is also desirable.

**Describe the solution you'd like**
Ability to export UnityEngine.Light to KHR_lights_punctual  at runtime (spot, directional and point light are sufficient)

**Describe alternatives you've considered**
Bespoke file format is a hassle knowing it's supported in gltf.

**Additional context**
I have a client in need to edit its lighting rig.

**Comment by atteneder** [comment]
Was added in 5.0.0
