### ISSUE TITLE
Bake animation for export

### ISSUE THREAD

**Issue by nick008a** [atteneder/glTFast#473]
**Is your feature request related to a problem? Please describe.**
Can gltfast bake vertex animations into a gltf export?

**Describe the solution you'd like**
Record (or bake) animation generated in runtime into GLTF

**Comment by atteneder** [comment]
glTFast does not export any animation yet.

What exactly do you mean by vertex animations? glTF supports morph targets for vertex level distortions. Did you mean that?

A search in the issues would've shown you #363 . Please subscribe to that for updates.
