### ISSUE TITLE
Build duration issue

### ISSUE THREAD

**Issue by giulianamuto** [atteneder/glTFast#476]
Hello, everyone. I use this plugin for the runtime import of gbl objects. I can get the plugin to work in VR, but the object is pink (lack of shaders)
I insert fast shaders then:
![image](https://user-images.githubusercontent.com/43480122/191322196-9b4d9d62-8771-4549-bba4-068d76fdce91.png)
But the builds turn out to last more than 40 minutes and do not end.

 Any advice?

**Comment by giulianamuto** [comment]
![image](https://user-images.githubusercontent.com/43480122/191326903-e045a9d9-25ab-4bd7-9109-0a4d59f95bd2.png)

**Comment by giulianamuto** [comment]
ok! ok! fixed by removing standard git fast shaders!

**Comment by atteneder** [comment]
In the readme, with big red exclamation marks, you'll find a link to the [Material/Shader setup](https://github.com/atteneder/glTFast/blob/main/Documentation~/ProjectSetup.md#materials-and-shader-variants).

In your case:

- Remove all but the actually required materials (do you need GLTFUtility? For sure you don't use the legacy shaders AND the shadergraphs)
- Don't include full Shaders (with all variants), but try to break it down to only the shader variants you need
