### ISSUE TITLE
Problem with build:  ability to use my shaders

### ISSUE THREAD

**Issue by giulianamuto** [atteneder/glTFast#477]
I am using GLFT asset and am having a lot of problems. reading the documentation for shaders and trying to make it as light as possible I find myself waiting +1h for a build of a half empty scene

![photo_2022-09-21_20-38-39](https://user-images.githubusercontent.com/43480122/191694289-0768a014-3c56-404d-b84d-5ad87faaa823.jpg)

**Comment by atteneder** [comment]
First, make sure you went throught the [documentation regarding shader setup](https://github.com/atteneder/glTFast/blob/main/Documentation~/ProjectSetup.md#materials-and-shader-variants).

TL:DR; Only pack the shader variants you actually need.

Second:
Feel free to inject your own materials by providing an implementation of `IMaterialGenerator` and feeding it into `GltfImport`'s constructor parameters. You can derive (or copy) the existing one, for example.

hth

**Comment by giulianamuto** [comment]
> First, make sure you went throught the [documentation regarding shader setup](https://github.com/atteneder/glTFast/blob/main/Documentation~/ProjectSetup.md#materials-and-shader-variants).
> 
> TL:DR; Only pack the shader variants you actually need.
> 
> Second: Feel free to inject your own materials by providing an implementation of `IMaterialGenerator` and feeding it into `GltfImport`'s constructor parameters. You can derive (or copy) the existing one, for example.
> 
> hth

thank you for your response. I'd like to insert some of my own materials, but I honestly don't understand where to put my hand! Do you happen to have any documentation on this that I can follow ?

**Comment by giulianamuto** [comment]
@atteneder
