### ISSUE TITLE
Material not loading

### ISSUE THREAD

**Issue by JPhilipp** [atteneder/glTFast#489]
**Describe the bug**
After the object was loaded via

        string url = "file:///E:/AIWorldGenerator/Assets/Resources/Models/Glb/00f9MZIwA1V.glb";
        gltfAsset = gameObject.AddComponent<GLTFast.GltfAsset>();
        gltfAsset.url = url;

it shows the meshes correctly, but none of them have any material (i.e. the Mesh Renderers shows "None (Material)"/ it's null).

**Files**
The used model chessboard.glb validates as per khronos.org and is attached here (license information: CC-BY-3.0 by Jarlan Perez):
[chessboard.zip](https://github.com/atteneder/glTFast/files/9665345/chessboard.zip)

The model looks fine when opened with e.g. Windows default glb displayer.

**To Reproduce/Expected behavior**
Use the code as above, run, zoom into the mesh, and check if the material is black and white and looking like a chessboard (correct) or magenta (missing).

**Screenshots**
![image](https://user-images.githubusercontent.com/1754503/192790700-61ca0a4d-c4ba-4810-90f0-eff1f3f5e741.png)
![image](https://user-images.githubusercontent.com/1754503/192790767-9ce215ef-684f-474e-948a-436ba24d94b8.png)

**Desktop:**
 - Current official release glTFast 4.8.5 (but I also tried e.g. today's code)
- Bug reproduced in the following versions:
    - 2022.1.10f1 (latest stable)
    - 2020 LTS
    - 2019 LTS
 - Built-in Render pipeline
 - Editor (using Windows 10)
 - Using the current Mathematics and Burst packages
 - No Player settings (or any other settings) were changed when trying in e.g. 2020 LTS or 2019 LTS

No console warnings or errors appear. Thanks for the work!

**Comment by atteneder** [comment]
That is really weird.

Is this path correct?

`file:///E:/AIWorldGenerator/Assets/Resources/Models/Glb/00f9MZIwA1V.glb`

the triple slash bothers me. You might try.

`file://E:/AIWorldGenerator/Assets/Resources/Models/Glb/00f9MZIwA1V.glb`

Which way did you install glTFast?
Can you inspect its shaders in `glTFast/Runtime/Shader/Built-In` and confirm they are not showing any errors?

Guess I have to use a Windows box to reproduce it.

**Comment by JPhilipp** [comment]
Holy Moly! It works in 2019 LTS via Package Manager setup. Thanks so much!

To recap:
- 2019 LTS works fine
- 2020 LTS works fine
- 2022 didn't work for me, no matter which installation method I picked, but maybe I did something wrong

As far as my issue goes, this is now solved and wasn't a bug (I suspected that might be the case, which is why I originally posted in the discussion forum). If you want to further investigate 2022.1.10f1, of course feel free to leave open.

**Comment by JPhilipp** [comment]
I restarted Unity 2022 and it now also worked there! All solved, thanks!

**Comment by JPhilipp** [comment]
Will do. I also just now answered your Twitter question on why someone might have posted to the Discussions forum first: the reason was that I wasn't sure if it's a bug (or if, as it turned out, it was me doing something wrong).

Either way, thanks for the fast help!
