### ISSUE TITLE
Draco compressed files do not load

### ISSUE THREAD

**Issue by sam598** [atteneder/glTFast#49]
I receive this error whenever the plugin tries to decode a gltf or glb compressed with draco:

'''
EntryPointNotFoundException: DecodeMeshForUnity
DracoMeshLoader+DracoJob.Execute () (at Library/PackageCache/com.atteneder.draco@b04c2d09ff4d4889e68e0cdfe6b3dc47f4a58a29/Runtime/Scripts/DracoMeshLoader.cs:64)
Unity.Jobs.IJobExtensions+JobStruct`1[T].Execute (T& data, System.IntPtr additionalPtr, System.IntPtr bufferRangePatchData, Unity.Jobs.LowLevel.Unsafe.JobRanges& ranges, System.Int32 jobIndex) (at /Users/builduser/buildslave/unity/build/Runtime/Jobs/Managed/IJob.cs:30)
'''

I've tried files exported from Blender 2.8 as well as this sample file:
https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/CesiumMilkTruck/glTF-Draco

I've also tried Unity 2019.2.3f1 on both Windows 10 and OSX with the same result.

**Comment by sam598** [comment]
Same issue happens when running the SampleScene in this project:
https://github.com/atteneder/DracoUnityDemo

**Comment by atteneder** [comment]
Please install GIT LFS and try again. The DLL library files are not downloaded correctly otherwise.

**Comment by sam598** [comment]
It looks like there is an issue with git-lfs and some versions of 2019.2.

I'll try 2019.3 later and see if that resolves things.

**Comment by atteneder** [comment]
Just make sure you have an up-to-date git client ( find it at <https://git-scm.com>; this should include the git LFS client).

An alternative is to download the package and all its dependency sub-packages manually and adding them via local path in the package manager.

**Comment by sam598** [comment]
Thanks for all of the quick help! It is up to date, but there are some versions of 2019.2 that have issues with git-lfs. 2019.3 is working now.
