### ISSUE TITLE
VR controllers (pico-neo3) models are broken

### ISSUE THREAD

**Issue by De-Panther** [atteneder/glTFast#491]
**Describe the bug**
The WebXR Input Profiles models for the pico-neo3 are broken.
This is how they look using glTFast 4.8.5
![image](https://user-images.githubusercontent.com/4749703/193379246-d10f1710-58f2-4dde-beb0-8b54c92e0a5a.png)
And this is how they look using [Khronos glTF-Sample-Viewer](https://github.khronos.org/glTF-Sample-Viewer-Release/)
![image](https://user-images.githubusercontent.com/4749703/193379263-2bcfb347-90fd-45b9-8b49-746ce1efd23b.png)

**Files**

https://cdn.jsdelivr.net/npm/@webxr-input-profiles/assets@1.0.11/dist/profiles/pico-neo3/left.glb
https://cdn.jsdelivr.net/npm/@webxr-input-profiles/assets@1.0.11/dist/profiles/pico-neo3/right.glb

In addition, make sure to run those files through the [glTF Validator](https://github.khronos.org/glTF-Validator) first. If you encounter errors or warnings, try to make sure they are not responsible for the issue and file a bug report with the software that generated the glTF file as well.

Checked both using the glTF Validator and got "The asset is valid".

**To Reproduce**
1. Load the models using glTFast.

**Expected behavior**
They should look similar to how they look on the Khronos viewer.

**Desktop (please complete the following information):**
 - glTFast version - 4.8.5
 - Unity Editor version - 2019.4.33f1
 - Render Pipeline and version - built-in
 - Platform: Editor

**Additional context**
Those models are downloaded dynamically for WebXR experiences, depending on which device the user is using, as part of https://github.com/immersive-web/webxr-input-profiles and https://github.com/De-Panther/webxr-input-profiles-loader
Also opened an issue at https://github.com/immersive-web/webxr-input-profiles/issues/223

**Comment by atteneder** [comment]
@De-Panther Thanks for reporting. I'm not yet sure, why the shading is like that.

But a workaround is to remove those lines from the material:
```
"alphaMode": "BLEND",
"doubleSided": true,
```

Not sure why you used alpha blending on this model, but it does not work.

**Comment by atteneder** [comment]
Closing, as it's likely just a content problem.

**Comment by De-Panther** [comment]
And it was also solved. Thanks
