### ISSUE TITLE
Export glb is different from Unity Scene

### ISSUE THREAD

**Issue by yc2768** [atteneder/glTFast#496]
###  **Export glb obj  color  is different from Unity Scene**
![image](https://user-images.githubusercontent.com/24848706/197764503-3fe976e6-0e65-4b08-9cd6-7c6d88fb2ac0.png)

![image](https://user-images.githubusercontent.com/24848706/197764133-24845261-0d8e-4ecd-b289-1e9cadf981bd.png)

**Comment by atteneder** [comment]
Hi,

What shaders are you using on those objects? Currently only Lit and Standard shader are know to work correctly.

**Comment by atteneder** [comment]
Support for glTFast based shaders has been added in the meantime, so feel free to re-validate.

Closing due to unanswered question.
