### ISSUE TITLE
Different visual when using Android / OpenGLES3

### ISSUE THREAD

**Issue by kexar** [atteneder/glTFast#498]
Hi guys. I want to use the runtime import on Android (OpenGLES3) but the shader looks very different (much worse) compared to Direct3D in Unity Editor Windows. After I switch the editor to OpenGLES3 it looks the same as on Android. 

I prefer the look of Direct3D, is it possible to get the same result on OpenGLES3?

Thanks!

**Comment by atteneder** [comment]
Which render pipeline are you using? Can you show screenshots? Also, what are your Quality settings?

I suspect that the shader scales on different hardware tiers and the difference is expected in order to maintain performance goals.

**Comment by atteneder** [comment]
I assume this is a duplicate of #694.

Hard to tell without answers, so closing it.
