### ISSUE TITLE
Animation.AddClip unable to use normally

### ISSUE THREAD

**Issue by lam-by** [atteneder/glTFast#504]
I use scripts to split a complete animation clip into multiple clips, but playing the animation is confusing.

https://docs.unity3d.com/ScriptReference/Animation.AddClip.html

public void AddClip(AnimationClip clip, string newName, int firstFrame, int lastFrame, bool addLoopFrame = false);

**Comment by atteneder** [comment]
I have no idea what your actual problem or question is. You only describe it as being confusing, which is not helping at all.

Is this actually a glTFast bug or a general Unity question? If the latter I'd refer you to the [forums](https://forum.unity.com/).
Is there a reason you ignored the bug report blue print? It would have guided you to giving more information.
