### ISSUE TITLE
KHR_Material_Variants Extension 

### ISSUE THREAD

**Issue by cafragachan** [atteneder/glTFast#510]
Hi @atteneder ,
First of all, amazing plugin...I'd like to extend the plugin using the KHR_material_variants protocol. Example here:
https://www.khronos.org/blog/streamlining-3d-commerce-with-material-variant-support-in-gltf-assets

Maybe you have already developed something along those lines and it would be great to build upon, if not I would give it a shot. 
Please let me know if you have any ideas and I'd be keen to stick to them in case you'd like to add this extension to the plugin.
Best,
Cesar

**Comment by bojankostic81** [comment]
Hi, any news on this extension?

**Comment by atteneder** [comment]
Happy to report that initial support for material variants landed in [6.7.0](https://docs.unity3d.com/Packages/com.unity.cloud.gltfast@6.7/manual/index.html).
