### ISSUE TITLE
GLTFast Importer with error

### ISSUE THREAD

**Issue by RafaelReis891** [atteneder/glTFast#511]
**Describe the bug**
When the Export in Runtime any model. I dont happen import it again in unity 3d.

**File exported with GLTFast**
https://github.com/RafaelReis891/Web_Models/blob/main/Test.gltf

**ERROR LOG BELLOW**

JsonParsingFailed
UnityEngine.Debug:LogError (object)
GLTFast.GltfImport/<ParseJsonAndLoadBuffers>d__95:MoveNext () (at Library/PackageCache/com.atteneder.gltfast@f6c014e6b0/Runtime/Scripts/GltfImport.cs:917)
UnityEngine.UnitySynchronizationContext:ExecuteTasks ()

**Comment by atteneder** [comment]
This file is a glTF-binary, but does not have the correct extension `.glb`.

When loading files via HTTP, glTFast does not have content-based detection of binary files (see #193). The recommended workaround currently is to configure your server to send the proper mime-type in the HTTP response.

hth
