### ISSUE TITLE
Error after import of SocketIOUnity

### ISSUE THREAD

**Issue by lc-spxl** [atteneder/glTFast#514]
**Describe the bug**

I have been using this library for a while (and it's great!) without issues.

Today I added this package https://github.com/itisnajim/SocketIOUnity to enable websocket events on my app and suddenly I have this error

`.../Library/PackageCache/com.atteneder.gltfast@f6c014e6b0/Runtime/Scripts/GltfImport.cs(419,13): error CS0518: Predefined type 'System.IAsyncDisposable' is not defined or imported`

Looking at the code, I can get rid of it by commenting this part at the file above
```csharp
// #if UNITY_2021_3_OR_NEWER
//             await using
// #endif
```
**To Reproduce**
1. Add `glFast` from git via Package Manager on a 3D unity project
2. Add `https://github.com/itisnajim/SocketIOUnity.git` from Package Manager
3. See error

**Desktop (please complete the following information):**
 - recent glTFast from git (~1 week ago)
 - Unity Editor version 2021.3.14f1
 - Platform: Editor
 - OS: linux

**Additional context**

Great work on the library!

**Comment by atteneder** [comment]
@lc-spxl  Thanks for reporting and the praise!

It is a problem of SocketIOUnity. I filed a [fix PR](https://github.com/itisnajim/SocketIOUnity/pull/37), so now it's up to them to fix it. In the meantime, feel free to use the [fixed branch](https://github.com/atteneder/SocketIOUnity/tree/fix-no-autoreference) of mine and please report if that works for you.

cc @alessandroperetti

thanks

**Comment by lc-spxl** [comment]
Awesome thanks!
