### ISSUE TITLE
Trying to import from cloud throws error

### ISSUE THREAD

**Issue by ArivazhaganDeeploop** [atteneder/glTFast#515]
I'm using the export in gltfast to export a gameobject as glb. After that i save the glb file into cloud. And i tried to retreive the data and load via the gltfast loader throws the error.
![image](https://user-images.githubusercontent.com/118797557/203944335-7c4cecdc-693d-4ed1-864c-8081b89bed5a.png)

**Comment by atteneder** [comment]
Sorry that this issue slipped.

Please re-open and provide the resulting glb file if you still need help.
