### ISSUE TITLE
Missing normals after runtime import when using the standard MRTK shader on UWP build

### ISSUE THREAD

**Issue by PecoreNere** [atteneder/glTFast#518]
Hi,

I currently use your importer for runtime imports within a UWP application on a Hololens 2. Since I wanted to use the MRTK standard shader, I derived the BuiltInMaterialGenerator to override the FindShader methods. Everything works fine in the editor, but unfortunately, not in the build. It looks like the meshes somehow lost their normals. I've been trying to figure out what's going wrong here for a few hours, but I'm not getting anywhere. Does anyone have any ideas?

Editor (MRTK/Standard):
![Editor](https://user-images.githubusercontent.com/55031848/204020838-33489a32-d140-4b33-b7d7-7f4a55b9cac9.png)

Hololens2 (MRTK/Standard): 
![HL](https://user-images.githubusercontent.com/55031848/204020852-6ac1fcd8-b5e8-495f-bdf6-b69b4847b06b.png)

**Comment by PecoreNere** [comment]
Apparently it is a problem with the shader itself. I have managed to solve it by changing these values in the Mixed Reality Standard Shader:

> #pragma shader_feature _DIRECTIONAL_LIGHT
> #pragma shader_feature _SPECULAR_HIGHLIGHTS

to

> #pragma multi_compile _DIRECTIONAL_LIGHT
> #pragma multi_compile _SPECULAR_HIGHLIGHTS

Additional infos can be found here: [MRTK Issue #6685](https://github.com/microsoft/MixedRealityToolkit-Unity/issues/6685)

**Comment by atteneder** [comment]
Happy to hear you found a fix! I'll close it now. Feel free to re-open if necessary
