### ISSUE TITLE
Empty name for mesh in project hierarchy for GLB model

### ISSUE THREAD

**Issue by rYuuk** [atteneder/glTFast#527]
**Description**
On adding draco compression package and loading a model, the mesh name is empty in the GLTF model file, check screenshot.

**Steps To Reproduce**
1. Import attached file in unity
2. Observe the mesh name in project hierarchy.

**GLB Asset***
[634950d8571c001b27d15fa0.zip](https://github.com/atteneder/glTFast/files/10112993/634950d8571c001b27d15fa0.zip)

**Expected behavior**
Proper naming imported from model data for mesh in project window.

**Screenshots**
![image](https://user-images.githubusercontent.com/1121080/204528189-951ffe5c-9c76-488e-add4-b19366218b8d.png)

**Desktop**
 - glTFast version : https://github.com/atteneder/glTFast.git#fbb449b8f5e1c6b1626fc153505da89cca0ddb72
 - draco version: https://github.com/atteneder/DracoUnity.git
 - Unity 2020.3.0f1.
 - Default Render Pipeline
 - Editor

**Comment by ROBYER1** [comment]
@atteneder Is this related to this issue? Having problems with gltfpack compressed meshes losing their names and being renamed to Node-1. Obviously being renamed to Node-1 is better than no naming but trying to diagnose if the issue is with gltfpack or glTFast
