### ISSUE TITLE
Problems loading large model files

### ISSUE THREAD

**Issue by nikeruga** [atteneder/glTFast#530]
**Describe the bug**
I'm trying to make a CAD viewer shape with Unity.
When loading a file that divides merchant ships into several model files (about 240)

Loading was fast in 20 to 30 model files, but
Since then, it is not loading at about one every 10 minutes.

Is it a library issue? Is this a Unity issue?
I am wondering how can this be solved.

**Files**
-- unity screenshot --
https://drive.google.com/file/d/1nAXfJ8IijHT8fJHyibdcePwwSyBW1LUS/view?usp=share_link

-- other cad viewer screenshot --
https://drive.google.com/file/d/1Tx4ioSW1zBGtWb1KUZjn2QeglD-ELx83/view?usp=share_link

-- model files --
https://drive.google.com/file/d/1mPa6sHZ97czDsxW5wfkv1x0JjZgEpjQi/view?usp=share_link

**Desktop (please complete the following information):**
* piXYZ Studio : v2022.1.r36
* Unity Editor : 2021.3.13f1
* glTFast 4.8.5
* Windows10 Pro 21H2

**Additional context**

  public async void GetShowGLBModelFile()
    {
       
        loadStopWatchStart = true;

        foreach (string userFile in UsrEnv.selectFileList)
        {
            if (!File.Exists(userFile))
            {
                //메세지 박스를 구현해서 사용자에게 보여준다.

                Debug.LogError("선택한 파일이 존재하지 않습니다.");
                return;
            }

            if (Path.GetExtension(userFile) == ".glb")
            {
                //파일을 오픈한다.
                await LoadGltfBinaryFromMemory(userFile);
                Debug.Log("모델 로드가 완료되었습니다........");
            }
            else if (Path.GetExtension(userFile) == ".gltf")
            {
                //파일을 오픈한다.
                await LoadGltfAsciiFromFile(userFile);
                Debug.Log("모델 로드가 완료되었습니다........");
            }

        }

        loadStopWatchStart = false;

    }

    public async Task LoadGltfAsciiFromFile(string gltfFile)
    {
        var gltf = new GLTFast.GltfImport();

        var success = await gltf.Load(gltfFile);
        if(success)
        {
            success = gltf.InstantiateMainScene(modelMainObject.transform);
        }
        else
        {
            Debug.LogError("Loading glTF failed!");
        }

    }

    public async Task LoadGltfBinaryFromMemory(string glbFile)
    {
        // var filePath = "/path/to/file.glb";
        byte[] data = File.ReadAllBytes(glbFile);
        var gltf = new GltfImport();
        bool success = await gltf.LoadGltfBinary(data, new System.Uri(glbFile));
        if (success)
        {
            success = gltf.InstantiateMainScene(modelMainObject.transform);
        }
        else
        {
            Debug.LogError("Loading glb failed!");
        }
    }

**Comment by atteneder** [comment]
I could load the entire boat.

<img width="861" alt="image" src="https://user-images.githubusercontent.com/2593014/205365039-635316b0-c130-49cf-ae0e-ccf70f2eb3c7.png">

But:

- The whole thing is totally unresponsive on my hardware
- Switching to the scene view led to a crash twice (somewhere in the Metal driver)

Memory shouldn't be the problem:

<img width="1174" alt="image" src="https://user-images.githubusercontent.com/2593014/205365260-ee09f725-9029-4d07-9597-4dd43fc6b93f.png">

**Comment by nikeruga** [comment]
My PC Spec is.. 
CPU :  12th Gen Intel(R) Core(TM) i9-12900F   2.40 GHz
RAM : 128GB
GrapicCard : Nvidia GeForce RTX 3080 TI

On my pc, it loads very slowly after loading a certain part.
If it's okay, could you send me the Unity project you tested?
I will test it on my PC.

**Comment by nikeruga** [comment]
> 배 전체를 실을 수 있었습니다.
> 
> <img alt="영상" width="861" src="https://user-images.githubusercontent.com/2593014/205365039-635316b0-c130-49cf-ae0e-ccf70f2eb3c7.png">
> 
> 하지만:
> 
> * 모든 것이 내 하드웨어에서 완전히 응답하지 않습니다.
> * 장면 보기로 전환하면 충돌이 두 번 발생했습니다(Metal 드라이버 어딘가에서).
> 
> 메모리가 문제가 되지 않아야 합니다.
> 
> <img alt="영상" width="1174" src="https://user-images.githubusercontent.com/2593014/205365260-ee09f725-9029-4d07-9597-4dd43fc6b93f.png">


My PC Spec is..
CPU : 12th Gen Intel(R) Core(TM) i9-12900F 2.40 GHz
RAM : 128GB
GrapicCard : Nvidia GeForce RTX 3080 TI

On my pc, it loads very slowly after loading a certain part.
If it's okay, could you send me the Unity project you tested?
I will test it on my PC.

**Comment by nikeruga** [comment]
My PC Spec is..
CPU : 12th Gen Intel(R) Core(TM) i9-12900F 2.40 GHz
RAM : 128GB
GrapicCard : Nvidia GeForce RTX 3080 TI

On my pc, it loads very slowly after loading a certain part.
If it's okay, could you send me the Unity project you tested?
I will test it on my PC.

**Comment by nikeruga** [comment]
Thank you comment.

First , all files (239 ea) are not loaded.
It's been an hour now and it hasn't finished loading.

my code  and youre code.

![gltfcode](https://user-images.githubusercontent.com/39543900/205690609-f88bede6-eea2-49d5-8569-1ae74101c8c6.jpg)

As the "D1001-SSO.glb" file is loaded, it seems to be mistaken that all files are loaded.
Please delete the "D1001-SSO.glb" file and load test all of glb files


![unityeditor](https://user-images.githubusercontent.com/39543900/205692194-615a6172-47c1-4ad1-bc5c-689432bbf442.jpg)

**Comment by nikeruga** [comment]
If the license is 'Personal'
Does the load stop in the middle?

**Comment by atteneder** [comment]
To me it seems it loads all 239 files just fine

<img width="1038" alt="image" src="https://user-images.githubusercontent.com/2593014/205703208-4f00f282-0ae6-4ead-a2b2-9cf7dd2cd4e2.png">

**Comment by nikeruga** [comment]
If you don't mind, please send us the project you used.
  I want to test it against my own project.

**Comment by atteneder** [comment]
> If the license is 'Personal' Does the load stop in the middle?

The code does not behave differently, regardless of license.

**Comment by nikeruga** [comment]
Or would you like to take a look at my project?
I'll upload it if it's okay.

I don't see any difference in my opinion.

**Comment by atteneder** [comment]
Sure, here's the project:

[LoadBoat.zip](https://github.com/atteneder/glTFast/files/10156549/LoadBoat.zip)

Open the SampleScene, select the `Boat` GameObject and enter the path to the files into the `LoadBoat` component's `Path` in the inspector.

**Comment by atteneder** [comment]
fyi: I was using the latest glTFast 4.9.1

**Comment by nikeruga** [comment]
my project gltFast 4.9.1
Youre Project No Problem.
Ah...~ ㅜㅜ
![chkEdit](https://user-images.githubusercontent.com/39543900/205709534-4bbc85e8-7a51-4bd4-a2f3-9f66780d32e3.jpg)

**Comment by atteneder** [comment]
No worries. Could you figure out the problem?

I'm closing the issue now. Re-open if you find a deeper problem with glTFast
