### ISSUE TITLE
GameObjectInstantiator not found settings.

### ISSUE THREAD

**Issue by nikeruga** [atteneder/glTFast#547]
**Describe the bug**

GameObjectInstantiator not found Settings function.

**Screenshots**
![2022-12-19 14 41 23](https://user-images.githubusercontent.com/39543900/208356023-288c0ba9-d8e5-41fa-ac66-c4ff587619b4.jpg)

**Desktop (please complete the following information):**
 - glTFast 5.0.0
 - Unity Editor version [ 2021.3.15f1]
 - Render Pipeline and version [e.g. Universal Render Pipeline 12.0]
 - Platform: [Editor, Windows Player]
 - OS: [WIN10]

**Comment by atteneder** [comment]
Hi,

`GameObjectInstantiator.Settings` was renamed/moved to `InstantiationSettings`

This information was only found in the [release log](https://github.com/atteneder/glTFast/blob/main/CHANGELOG.md#500---2022-12-09), so I added it to the [5.x upgrade guide](https://github.com/atteneder/glTFast/blob/main/Documentation%7E/UpgradeGuides.md#moved-or-renamed-types) as well, to avoid future confusion.

hth

**Comment by nikeruga** [comment]
Thank you for always.
