### ISSUE TITLE
Loading glb from Application.persistantdatapath in android.

### ISSUE THREAD

**Issue by umresh** [atteneder/glTFast#55]
Hi,
   I downloaded the glb files in persistantPath in Android and when I try to load from this path I get an error 
Unity: Cannot connect to destination host /storage/emulated/0/Android/data/com.xxx.xxxx/files/C772BCFB-B2FD-406E-8B32-05D3D5DEFAD6.glb

**Comment by atteneder** [comment]
Hi,

Thanks for the report!

I only ever loaded glTFs either via HTTP or from the StreamingAssets path. In both cases glTFast loads via UnityWebRequest.

I'm not sure if UnityWebRequest can load from an arbitrary local path (like in your case). Could you test if you can load the data via UnityWebRequest directly?

If not, then I should add the feature to load directly from local paths (via System.IO).

As a workaround, you could use StreamingAssets as well.

**Comment by umresh** [comment]
I'm downloading files and storing them so that I don't have to download them again and I can load offline too.

**Comment by atteneder** [comment]
I see. Did you test if UnityWebRequests work on downloaded files?

**Comment by umresh** [comment]
We are downloading using unuitywebrequests and then giving url to gltfast to load and it seems Gltfast using UnityWebRequests to load files.

**Comment by atteneder** [comment]
> We are downloading using unuitywebrequests 
I got that.
> and then giving url to gltfast to load and it seems Gltfast using UnityWebRequests to load files.
I know.

question is, is loading the cache data via UnityWebRequest not working and why.

You might have to prefix the URL with "file://". A simple google search for "UnityWebRequest local file" gives you this helpful thread on the forums:

<https://forum.unity.com/threads/unitywebrequest-for-local-files-on-android-failure.441655/>

**Comment by atteneder** [comment]
As this is probably not a glTFast issue and there was no more response I'm closing it.

**Comment by umresh** [comment]
Hi, Just tried in android files are loaded but there is some error. This is the log

`Unable to find _burst_generated
ArgumentNullException: Value cannot be null.
Parameter name: shader
at GLTFast.DefaultMaterialGenerator.GetPbrMetallicRoughnessMaterial (System.Boolean doubleSided) [0x00000] in <00000000000000000000000000000000>:0
at GLTFast.DefaultMaterialGenerator.GenerateMaterial (GLTFast.Schema.Material gltfMaterial, GLTFast.Schema.Texture[] textures, UnityEngine.Texture2D[] images) [0x00000] in <00000000000000000000000000000000>:0
at GLTFast.GLTFast+<Prepare>d__42.MoveNext () [0x00000] in <00000000000000000000000000000000>:0
at GLTFast.GltfAsset+<LoadContent>d__8.MoveNext () [0x00000] in <00000000000000000000000000000000>:0
at UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) [0x00000] in <00000000000000000000000000000000>:0`

**Comment by atteneder** [comment]
Seems to me like the necessary Shaders and its variants are included in the build. Is it working in the editor?
Please read `README.md` about including shader (variants).

**Comment by umresh** [comment]
yes its working in editor

**Comment by umresh** [comment]
I was the shader varient issue. 
I'm trying to load a drc file and load is failed. Link to file is below
[https://unity-video.s3-ap-southeast-1.amazonaws.com/Animal.drc](url)

**Comment by atteneder** [comment]
Assuming it's a Draco mesh file:
Use [DracoUnity](https://gitlab.com/atteneder/DracoUnity) and see [this demo project](https://github.com/atteneder/DracoUnityDemo) how.

Note: DracoUnity is a dependency of glTFast, but you don't need (all of) glTFast for loading Draco files.

**Comment by umresh** [comment]
I have both glb, gltf and just found out it had drc too. and I was hoping to load all the type using gltfast

**Comment by atteneder** [comment]
RTFM!
Please read my answers carefully:
You CAN via DracoUnity, which is a dependancy of glTFast. Read my links above.

**Comment by waseemkhan1989** [comment]
@atteneder Sorry for this inconvenience. I read the whole thread and also the links that you mentioned as well but still could not figure out how to solve the following problem.
![GLTFastIssue](https://user-images.githubusercontent.com/25552247/97456786-76afe000-1939-11eb-8afb-d90b944eb9c4.PNG)
 
The code that I am using for downloading glb file from static link to a location on Android on Quest with Unity Web request is here:

`public class ModelLoader : MonoBehaviour
{
    GameObject wrapper;
    string filePath;
    public int choice = 3;
    [SerializeField]
    private bool AndroidOn = true;
    private void Start()
    {
        if(AndroidOn)
            filePath = Application.persistentDataPath + "file:///sdcard/Android/data/";
        else
        {
            filePath = "F:/WaseemWork/WK_Projects/RunTimeImporter/Assets/Models/";
        }
        wrapper = new GameObject
        {
            name = "Model"
        };
    }
    public void DownloadFile(string url)
    {
        string path = GetFilePath(url);
        if (File.Exists(path))
        {
            Debug.Log("Found file locally, loading...");
            LoadModel(path);
            return;
        }

        StartCoroutine(GetFileRequest(url, (UnityWebRequest req) =>
        {
            if (req.isNetworkError || req.isHttpError)
            {
                // Log any errors that may happen
                Debug.Log($"{req.error} : {req.downloadHandler.text}");
            } else
            {
                // Save the model into a new wrapper
                LoadModel(path);
            }
        }));
    }

    string GetFilePath(string url)
    {
        string[] pieces = url.Split('/');
        string filename = pieces[pieces.Length - 1];

        return $"{filePath}{filename}";
    }

    void LoadModel(string path)
    {
       
        if (choice == 2) // GLTFast
        {
            var model = gameObject.AddComponent<GLTFast.GltfAsset>();
            model.url = path;
            ResetWrapper();
            model.transform.SetParent(wrapper.transform);
            //model.gameObject.AddComponent<Collider>();
           
        } 
     }
    void ResetWrapper()
    {
        if (wrapper != null)
        {
            foreach(Transform trans in wrapper.transform)
            {
                Destroy(trans.gameObject);
            }
        }
    }
`
As I do not have a lot of experience with UWR, it would be nice if you could mention the steps to get rid of this problem. I really liked this library and I am sure there would a way out.

**Comment by atteneder** [comment]
reading my last response here... sorry, I must've lost my temper for the moment :)

The path you try to load is invalid! The `file://` is supposed to be at the very beginning
```csharp
//  Change this
filePath = Application.persistentDataPath + "file:///sdcard/Android/data/";
// to this:
filePath = "file://" + Application.persistentDataPath + "/sdcard/Android/data/";
```

I also doubt that this new path is valid. You have to find out where your files are first!

```csharp
//  More likely it is:
filePath = Application.persistentDataPath + "Showroom.glb";
// or
filePath = "file://" + "/sdcard/Android/data/Showroom.glb";
```

**Comment by waseemkhan1989** [comment]
@atteneder I am again sorry for asking such dumb questions but as I am new to this field so please excuse me:)

After spending 1.5 days, I managed to import the models into VR. 

A comment for what I understood so far:
If I understand correctly then UnityWebRequest is already implemented within GLTFast and I just have to give the static link(URL) to the library as input. Previously, as mentioned in the above code, I assumed that GLTFast imports model from a local file location in Android and that's why I was first downloading the model using Unity Web request and was storing it at some local location in Android and then giving the path of this local file location to GLTFast. I think, that was the reason that I was first getting the error about " refusing connection at port 80" because I think tat port was already occupied by the call that I made to UWR. 

Now this problem is resolved. There is another problem for which I will create another issue. And thanks once again for this awesome library.

**Comment by atteneder** [comment]
> If I understand correctly then UnityWebRequest is already implemented within GLTFast and I just have to give the static link(URL) to the library as input.

[UnityWebRequst](https://docs.unity3d.com/Manual/UnityWebRequest.html) is provided by Unity and just used by glTF as a dependency. I mention that so you can read their docs and figure it out (there's tons of threads out there regarding loading files with it.

You have to give it the path or URL to the glTF asset (.glb or .gltf file). Paths have to be prefixed with `file://` on certain platforms (again, consult the docs)

> Previously, as mentioned in the above code, I assumed that GLTFast imports model from a local file location in Android and that's why I was first downloading the model using Unity Web request and was storing it at some local location in Android and then giving the path of this local file location to GLTFast. I think, that was the reason that I was first getting the error about " refusing connection at port 80" because I think that port was already occupied by the call that I made to UWR.

You can load both URLs or download assets to a file and load from there (which essentially can work as a cache for subsequent runs). Careful with non-binary glTFs though (.gltf)! They usually consist of external files as well (.bin file, textures etc.) which you'd have to download as well, if you manage the download yourself. For this advances use-case I'd recomment implementing `IDownloadProvider`  (see `DefaultDownloadProvider`)
 
> Now this problem is resolved. There is another problem for which I will create another issue. And thanks once again for this awesome library.

Glad you can put it to good use :)
