### ISSUE TITLE
New icon for editor imported glTF objects is confusing

### ISSUE THREAD

**Issue by hybridherbst** [atteneder/glTFast#557]
**Describe the bug**

Even when I understand the desire to do some marketing here, I think it's not good UX to show different icons for things that are actually GameObjects / imported prefabs. I'd reocmmend rolling that back and have objects fit right in instead of standing out as strange separate things.

Separate bug but hopefully obsolete: the icon is very pixelated on non-Retina displays.

**Additional context**
I don't think it's good practice to make filetype-specific importer icons, especially not for something on track to become default / built-in.

**Comment by atteneder** [comment]
Agreed. Will get reverted.
