### ISSUE TITLE
a lot of   same objects in one gltf, Use Instantiate?

### ISSUE THREAD

**Issue by veyvin** [atteneder/glTFast#56]
![image](https://user-images.githubusercontent.com/6776758/71244621-e7679280-234d-11ea-81fe-0fc0a4426699.png)

**Comment by atteneder** [comment]
Hi,

sorry for the late response. Could you provide a demo glTF file demonstrating this?

thanks

**Comment by atteneder** [comment]
I think a recent version of glTFast should do considerably better.

If not, provide a sample file and re-open the issue.

thanks
