### ISSUE TITLE
Spawning with box collider works only at world origin

### ISSUE THREAD

**Issue by Urganway** [atteneder/glTFast#565]
When i try to spawn a model at runtime with the GLTF Bounds Asset, the generated box collider will only be aligned when the transform is at world's origin

Model used is on URL "https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/Duck/glTF/Duck.gltf"

Create a GameObject set it's position to ( 1 ; 1 ; 1 )
Add a GLTF Bounds Asset to gameObject
Set Url to some model
Press Play
When model is loaded, select gameObject to visualise Box collider
Box collider's center is not aligned on model's center (size is fine)

Box Collider's center is alligned with model's center

Expected Result : (here the gameObject position is at ( 0 ; 0 ; 0 ))
![image](https://user-images.githubusercontent.com/77050324/215761599-91872ba0-cb91-4a0a-b37b-a49da9464dfd.png)

Actual Result : (here the gameObject position is at ( 1 ; 1 ; 1 ))
![image](https://user-images.githubusercontent.com/77050324/215761110-02682bdd-1497-4ca4-8e8c-ff09ecccf541.png)

 - glTFast version : 5.0.0
 - Unity Editor version : 2021.3.16f1
 - Render Pipeline and version : URP v12.1.8
 - Platform : Windows11

**Comment by atteneder** [comment]
Hi @Urganway ,

Great spot, thanks for reporting. Fix imminent.
