### ISSUE TITLE
.bin file not registered as dependency for .gltf file at editor import

### ISSUE THREAD

**Issue by hybridherbst** [atteneder/glTFast#567]
**Describe the bug**
I got that bug report for UnityGltf and checked if glTFast handles this already, turns out it doesn't :)

**Files**

[glTFBinDependency.zip](https://github.com/atteneder/glTFast/files/10574129/glTFBinDependency.zip)

**To Reproduce**
1. Unzip and put these files into Assets/Something
2. Select the .gltf file and rightclick > Export as Package
3. Note the .bin isn't listed

**Expected behavior**
.bin comes along as a registered dependency

**Additional context**
I did what ShaderGraph also does: parse only the JSON in GatherDependenciesFromSourceFile, then find the buffers and register them. I don't think it's necessary for textures etc. since those will be actual assets and added as dependencies on their own.

**Comment by atteneder** [comment]
Hi,

I couldn't reproduce (the bin file was added as dependency to the package).

The way glTFast does it is the injected IDownloadProvider collects all dependencies which are [registered later on](https://github.com/atteneder/glTFast/blob/fbb84eaa4de01615bd06cf75d2de35de43ee2848/Editor/Scripts/GltfImporter.cs#L272).

Thanks for the effort of double checking glTFast as well 🙏
