### ISSUE TITLE
jsonParse error with some rigged models

### ISSUE THREAD

**Issue by polytropoi** [atteneder/glTFast#575]
**Describe the bug**
jsonParse error on certain models with skinned meshes
<img width="986" alt="Screen Shot 2023-02-21 at 10 59 18 AM" src="https://user-images.githubusercontent.com/1281119/220411044-61826700-dd92-4c0f-9cd3-6f0bfc15c6b7.png">

**Files**
Attach or link to *.gltf/*.glb files that trigger the bug. 
https://ztash.s3.amazonaws.com/xbot1c.glb example of file that fails to parse, but passes validation

**To Reproduce**
https://realitymangler.com/uxr/main/index.html?scene=AWHQ_2023_error see console

**Expected behavior**
https://servicemedia.net/webxr/ObzaRcDuB  aframe version of the same scene, rigged model works fine
https://realitymangler.com/uxr/main/index.html unity webgl version with different model, no error

**Desktop (please complete the following information):**
 - glTFast version  5.0
 - Unity Editor version: 2021.3.18]
 - Render Pipeline and version: builtin
 - Platform: WebGL
 
additionally (if significant for the bug):
happens in both editor and build.  
**Additional context**
I think all the models that trigger this error have Mixamo-generated rigs...

**Comment by atteneder** [comment]
Sorry for getting back to you with delay.

Unfortunately the link to the glb file does not work anymore. Would you mind re-uploading?

**Comment by atteneder** [comment]
I extracted the glb from the aframe version, and was not able to reproduce.

If I missed something, please provide working reproduction instructions and re-open the issue.

Thanks!
