### ISSUE TITLE
Can't load my GLTF file with LoadGltfBinary function

### ISSUE THREAD

**Issue by MarkAlexanderDev** [atteneder/glTFast#578]
Hello,

I have an issue when trying to load a GLTF file. Here is the code :

```
    public async void SetModel(string path) {
      if (!File.Exists(path)) {
          Debug($"File does not exist: {path}");
      }

      byte[] fileData;
      try {
          fileData = File.ReadAllBytes(path);
      } catch (IOException ex) {
          Debug($"Error reading file: {ex.Message}");
          return ;
      }

      Debug(fileData.Length.ToString());

      var gltf = new GltfImport();
      bool success = await gltf.LoadGltfBinary(
          fileData,
          new System.Uri(path)
      );
      if (success) {
          Debug("SUCCESS GLTF");
          var mainScene = await gltf.InstantiateMainSceneAsync(ArPrefab.transform);
      } else {
          Debug("FAIL GLTF");
      }
    }
```

The `success` `boolean` will always be false although `fileDataLenghtToString()` is never equal to zero so I successfully load something in my `byte[]`.

These are the files I am trying to load : 

[gltf.zip](https://github.com/atteneder/glTFast/files/10869758/gltf.zip)

 - glTFast version : 5.0.0
 - Unity Editor version : 2022.1.7f1
 - Render Pipeline and version : not sure to know what it is but here are my settings
![Screenshot 2023-03-02 at 10 36 58](https://user-images.githubusercontent.com/54772403/222390007-1a120b21-0eb1-4079-b60f-dcd268148eea.png)
 - Platform: Android
 
 
 Thanks for your help!!

**Comment by MarkAlexanderDev** [comment]
I switched to the basic `Load` function and it seems to work.

```
    public async void SetModel(string path) {
      if (!File.Exists(path)) {
          Debug($"File does not exist: {path}");
      }

      var gltf = new GltfImport();
      bool success = await gltf.Load(path);
      if (success) {
          Debug("SUCCESS GLTF");
          try {
            await gltf.InstantiateMainSceneAsync(test.transform);
          } catch (Exception e) {
            Debug(e.ToString());
          }
      } else {
          Debug("FAIL GLTF");
      }
    }
```

**Comment by atteneder** [comment]
Hi @MarkAlexanderDev 

Glad you found a solution! The reason `LoadGltfBinary` wasn't working is that it expects a glTF-Binary file and your file is a regular glTF (with JSON payload).

hth
