### ISSUE TITLE
Android & IOS build fix "shaders"

### ISSUE THREAD

**Issue by amrmohamed25** [atteneder/glTFast#580]
### To fix shader errors during android & IOS builds:
you must download all these 5 shaders:
<a href="https://github.com/atteneder/glTFast/blob/main/Runtime/Shader/Built-In/glTFPbrMetallicRoughness.shader">glTFPbrMetallicRoughness.shader</a>,<a href="https://github.com/Siccity/GLTFUtility/blob/master/Materials/Built-in/Standard-Metallic-Blend.shader">Standard-Metallic-Blend.shader</a>, <a href="https://github.com/Siccity/GLTFUtility/blob/master/Materials/Built-in/Standard-Metallic.shader">Standard-Metallic.shader</a>, <a href="https://github.com/Siccity/GLTFUtility/blob/master/Materials/Built-in/Standard-Specular-Blend.shader">Standard-Specular-Blend.shader</a> and <a href="https://github.com/Siccity/GLTFUtility/blob/master/Materials/Built-in/Standard-Specular.shader">Standard-Specular.shader</a>

After downloading these shaders in your project, you should go to Edit-> Project Settings -> Graphics -> Always included Shader -> increase the size by 5 then drag and drop the shaders.

Note: if shaders error still exist, you should include the shaders that caused the errors, you will find them in this <a href="https://github.com/atteneder/glTFast/tree/main/Runtime/Shader/Built-In">link</a>

**Comment by ROBYER1** [comment]
@amrmohamed25 Why are the GLTF Utility shaders required when they are not part of GLTFast?

**Comment by ROBYER1** [comment]
> @ROBYER1 GLTFast works fine for windows but it didnt work when i tried to run on android or IOS. I found that it works by including the shaders that are mentioned, but i dont know if there is another way to make it work on android and ios

Surely if those shaders are from GLTFUtility and not GLTFast, why would GLTFast use them?

**Comment by amrmohamed25** [comment]
Read this : https://github.com/atteneder/glTFast#materials-and-shader-variants

**Comment by ROBYER1** [comment]
Thanks, still didn't fix my issues on android loading GLB files - I get the error `2023/03/21 14:20:11.132 12586 12611 Error AndroidRuntime Cause: null pointer dereference
`

Followed by:
`2023/03/21 14:20:11.132 12586 12611 Error AndroidRuntime       #00 pc 000000000029acac  /vendor/lib64/egl/libGLESv2_adreno.so (BuildId: b87189ccebbe50e571d1bf6b17cf24dc)
`

**Comment by amrmohamed25** [comment]
Did you include all the five shaders?

> Thanks, still didn't fix my issues on android loading GLB files - I get the error `2023/03/21 14:20:11.132 12586 12611 Error AndroidRuntime Cause: null pointer dereference `
> 
> Followed by: `2023/03/21 14:20:11.132 12586 12611 Error AndroidRuntime #00 pc 000000000029acac /vendor/lib64/egl/libGLESv2_adreno.so (BuildId: b87189ccebbe50e571d1bf6b17cf24dc) `

**Comment by amrmohamed25** [comment]
I tested on more than one device and on many glb/gltf models and all worked

**Comment by ROBYER1** [comment]
I did, I will open a separate issue once I have investigated more, my load issue is specific to Android as the files load fine on IOS/Desktop Windows and Mac.

**Comment by amrmohamed25** [comment]
I had that load issue in android and i fixed it by the previous steps

> I did, I will open a separate issue once I have investigated more, my load issue is specific to Android as the files load fine on IOS/Desktop Windows and Mac.

**Comment by amrmohamed25** [comment]
Can you include a screenshot containing all the shaders in the Always included shaders?

> I did, I will open a separate issue once I have investigated more, my load issue is specific to Android as the files load fine on IOS/Desktop Windows and Mac.

**Comment by amrmohamed25** [comment]
Did you try different glb/gltf models?

**Comment by ROBYER1** [comment]
> Did you try different glb/gltf models?

Only happens on Android and only happens with models that have mesh + texture + material, files that don't have materials work.

Going to try using the glTFast/Runtime/Shader/ folder shader graphs as we are using URP + Shader Graph in Unity and not built in Renderer

**Comment by amrmohamed25** [comment]
I didnt test on URP. I hope that you find a solution to your problem

**Comment by ROBYER1** [comment]
Logged my bug here, https://github.com/atteneder/glTFast/issues/590

**Comment by sushitek** [comment]
This isn't working for me either. glTFPbrMetallicRoughness.shader is causing an error all on it's own.

**Comment by amrmohamed25** [comment]
> This isn't working for me either. glTFPbrMetallicRoughness.shader is causing an error all on it's own.

You have the same issues as <a href="https://github.com/atteneder/glTFast/issues/576">here</a>?

**Comment by Morgan-6Freedom** [comment]
I followed the [documentation ](https://github.com/atteneder/glTFast/blob/main/Documentation~/ProjectSetup.md#materials-and-shader-variants)and it worked !

> Run your scene that loads all glTFs you expect in the editor.
Go to Edit->Project Settings->Graphics
At the bottom end you'll see the "Shader Preloading" section
Save the currently tracked shaders/variants to an asset
Take this ShaderVariantCollection asset and add it to the "Preloaded Shaders" list

**Comment by atteneder** [comment]
Thanks @Morgan-6Freedom  for pointing out the docs.

I'm going to assume that following them solves the problem. If not, feel free to re-open or create a new issue.
