### ISSUE TITLE
Shader 'glTF/PbrMetallicRoughness' doesn't have a texture property '_MainTex'

### ISSUE THREAD

**Issue by Gulfick** [atteneder/glTFast#581]
**Describe the bug**
Built-In shaders don't have _MainTex property so unity spam error messages in console. In URP all working without errors.

I made a local package and added the _MainTex property to the shader and the errors stopped. 
If I understand correctly, these errors occur on materials whose Blend Mode is not Opaque

**Files**
[modelglb.zip](https://github.com/atteneder/glTFast/files/10906791/modelglb.zip)

**How to reproduce:**
1. Create new built-in project
2. Add gltf package
3. Add glb model to scene
4. Errors will come

**Expected behavior**
No errors

**Screenshots**
![image](https://user-images.githubusercontent.com/60809468/223355735-5c54c323-bd57-40f9-ad89-fc5f4d3587bb.png)

**Desktop:**
 - glTFast version 5.0.0
 - Unity Editor version [e.g. 2020.3.27f1]
 - Built-in pipline
 - Platform: all platforms

**Comment by Gulfick** [comment]
Created a pull for that fix

https://github.com/atteneder/glTFast/pull/585

**Comment by atteneder** [comment]
Closing this one now.

    I personally never stumbled upon this error
    No steps to reproduce have been provided after requesting them
    I consider the proposed solution a bad practice workaround
    Not sure if adding unused properties has other downsides to it

If you feel like this needs a solution, please provide repro steps and re-open.
