### ISSUE TITLE
Build Fails due to Unreachable code within GltfImport script

### ISSUE THREAD

**Issue by mag-dylanmarkowitz** [atteneder/glTFast#582]
**Describe the bug**
When I try to make an iOS build in Unity using this package version 5.0.0, the build fails. The error points to unreachable code within the GltfImport.cs file.

The error in question:
https://github.com/atteneder/glTFast/blob/197f3b7e32ed733890935324f41c32d6599fc0cd/Runtime/Scripts/GltfImport.cs#L703-L705

You can see that the code returns and then has another line of code afterwards (unreachable).

Using Unity 2020.3.33f1 and Visual Studio 2019

**To Reproduce**
1. Include this package in a Unity project
2. Make a build
3. See it fail

**Expected behavior**
Unity builds should not fail.

**Possible Solution**
One workaround is to store the value from GetDefaultMaterial in a temporary variable and then return that value after the logger is set to null.

**Comment by atteneder** [comment]
Thanks for reporting.

I'm surprised this throws an error and not just a warning. Anyways, looking at the current code this seems to be addressed. Re-open if I'm mistaken.
