### ISSUE TITLE
Exported Unity Scene has some assets turn Pink

### ISSUE THREAD

**Issue by ThatSprite** [atteneder/glTFast#583]
**Describe the bug**
When I export my Unity scenes, some of the Tree assets I use have their foliage turned pink and are broken. This does not happen to all of my assets, and sometimes it only happens to just part of the asset, but I don't know what the cause is. These are prefab assets from Synty Studios.

**Files**
[Campfire Test Scene.zip](https://github.com/atteneder/glTFast/files/10921005/Campfire.Test.Scene.zip)

I put this GLB file into the gLTF Validator, and it produced the following errors, but unfortunately I have no idea what that means or how I can resolve them;

[glTF Validator Errors.txt](https://github.com/atteneder/glTFast/files/10921012/glTF.Validator.Errors.txt)

**To Reproduce**
Unfortunately I do not exactly have the rights to redistribute the prefab assets involved in this error, but the reproduction goes;

1. Add the prefab assets used to a scene 
2. Export it as either GLB or GLTF via glTFast
3. Preview the exported file / load it into another project
4. You can observe that the trees have become pink with broken textures.

**Expected behavior**
I would expect the trees, when exported, to retain their intended colour.

**Screenshots**
![image](https://user-images.githubusercontent.com/14553022/223726174-7ee2bbbc-c0de-4149-8034-66ebfa5c9776.png)
![image](https://user-images.githubusercontent.com/14553022/223726302-0a7f29bd-3e0b-49e1-bcc1-0004ae6a2452.png)

**Desktop (please complete the following information):**
 - glTFast version 5.0.0
 - Unity Editor version 2021.3.20f1
 - Render Pipeline and version - Uncertain what this is... I tried following guides online that alleged they would fix this texture by changing the Render Pipeline, but instead it made every asset in the Project pink and I had to remake it from scratch.
 - Platform: Editor

**Comment by atteneder** [comment]
This is most likely due to missing shader variants. Please consult the [material documentation](https://docs.unity3d.com/Packages/com.unity.cloud.gltfast@6.9/manual/ProjectSetup.html#materials-and-shader-variants) for help.
