### ISSUE TITLE
line index error. 

### ISSUE THREAD

**Issue by veyvin** [atteneder/glTFast#59]
this is a line.
[9076dec0-1b2f-4395-9957-5f2d74b92b80.mod.zip](https://github.com/atteneder/glTFast/files/4242939/9076dec0-1b2f-4395-9957-5f2d74b92b80.mod.zip)
this model in gltf viewer and assimp viewer is  correct. 
in gltfast the index is  0 2 1  3 5 4
the correct index is 0 1 2 3 4 5.

**Comment by atteneder** [comment]
Hey veyvin,

thanks for providing a sample scene (I never tested a file with lines/points)

glTFast has to switch indices order for triangular meshes, but for lines this is indeed an error. Shouldn't take long...expect a fix this week

regards
