### ISSUE TITLE
Resources are not completely cleaned up during runtime

### ISSUE THREAD

**Issue by BekirConsensive** [atteneder/glTFast#598]
**Describe the bug**

During runtime, when a glb file is imported and deleted via GltfImport, resources are not completely cleaned up.

Overall, there is no problem regarding the cleaning up of the resources that are in VRAM. On the other hand, in RAM, the resources are not completely cleaned up. The issue is visible in some relatively larger models.

To load a glTF model via glTFast, the following code is being used:

        gltf = new GLTFast.GltfImport();

        // Create a settings object and configure it accordingly
        var settings = new ImportSettings
        {
            GenerateMipMaps = true,
            AnisotropicFilterLevel = 1,
            NodeNameMethod = NameImportMethod.OriginalUnique
        };

        var success = await gltf.Load(filename, settings);

        if (success)
        {
            var gameObject = new GameObject("glTF");
            await gltf.InstantiateMainSceneAsync(gameObject.transform);

            gameObject.transform.parent = this.gameObject.transform;
        }
        else
        {
            Debug.LogError("Loading glTF failed!");
        }

To delete a glTF model that is imported via glTFast, the following code is being used:

        gltf.Dispose(); // GltfImport instance
        Destroy(gameObject);
        Resources.UnloadUnusedAssets();
**Files**

San-Miguel model from [casual-effect](https://casual-effects.com/g3d/data10/index.html) converted to glb.
https://drive.google.com/file/d/1QnJtwf9SCVfsUzySfymdDYLYiZfx7R79/view?usp=sharing

**To Reproduce**
1. Using the model import script above, import the model.
2. Once the model is loaded, destroy it with the destroy script above.
3. Do this multiple times while watching the RAM usage.

**Expected behavior**
After deleting the model, a significant portion of the used memory is not released. If the steps in the "To Reproduce" section are done enough times, essentially Unity can throw OutOfMemoryException.

**Platform: Desktop**
 - glTFast version - 5.0.0
 - Unity Editor version - 2021.3.13f1
 - Built-in Pipeline
 - Platform: Windows Player

I am not quite sure what the problem is. Maybe some models cause problems or my importing/disposing method is not ideal. Any help would be appreciated.

**Comment by atteneder** [comment]
Thanks for reporting. We're going to track this in issue #726 .
