### ISSUE TITLE
Plugins: Failed to load  when saving

### ISSUE THREAD

**Issue by Mrgove10** [atteneder/glTFast#60]
Hello,
When i save my unity project (ctrl+s) i get these two errors :
```
Plugins: Failed to load '[PATH TO PROJECT]/Library/PackageCache/com.atteneder.draco@c3ee8d09c1ab635bb37f4bb65eb0c7311b01df4e/Runtime/Plugins/x86_64/dracodec_unity.dll' because one or more of its dependencies could not be loaded.
```
and
```
Plugins: Failed to load '[PATH TO PROJECT]/Library/PackageCache/com.atteneder.draco@c3ee8d09c1ab635bb37f4bb65eb0c7311b01df4e/Runtime/Plugins/x86_64/dracodec_unity.dll' because one or more of its dependencies could not be loaded.
UnityEditor.EditorApplication:Internal_CallGlobalEventHandler()
```
Outside of that the library works super well, great work !

**Comment by atteneder** [comment]
Thanks for letting me know!

Strange thing it works otherwise. I'll get access to a windows box next week and then I'll have a look.

**Comment by Mrgove10** [comment]
I also get an error when i build but the wierd thing is : 
build 1 : get the error
build 2 (done right after, not shanging ANYTHING) : no error

I will post the error on build tomorrow

**Comment by Mrgove10** [comment]
For information i am on Unity 2019.3.1f1

**Comment by atteneder** [comment]
Can you check if the mentioned DLL file has a proper size? It should be around 228 kB: 
https://gitlab.com/atteneder/DracoUnity/-/blob/master/Runtime/Plugins/x86_64/dracodec_unity.dll

If that's not the case, you might not have GIT LFS installed, as the install instructions suggest you to.

**Comment by atteneder** [comment]
see https://github.com/atteneder/glTFast#installing

**Comment by Mrgove10** [comment]
x86 = 190kb
x86_64 = 228kb

So everything seams good.

**Comment by atteneder** [comment]
I could reproduce it and will look into it later

**Comment by Mrgove10** [comment]
for information : i ahve updated to the latest release and i still have the issue

**Comment by atteneder** [comment]
workaround:
the current version does not require DracoUnity to be installed, so if you don't need draco mesh compression, just remove the package.

**Comment by Mrgove10** [comment]
seams to have fixed the issue ! thanks !

**Comment by atteneder** [comment]
fyi, seems to be Unity bug:
https://forum.unity.com/threads/dll-not-found-with-standalone-app-but-works-fine-in-editor.389392/page-2

still not fixed though

**Comment by Mrgove10** [comment]
As often with unity bugs :/ We have pause the project on our side so we are not gonne be using the library in a little bit.

**Comment by atteneder** [comment]
alright.
FWIW: a workaround for builds is to move the DLL into the same (root) folder than the .exe file.

**Comment by atteneder** [comment]
fwiw: Install latest version via OpenUPM (see README.md) and you should be fine!
