### ISSUE TITLE
Allow read/write enabled on runtime imported textures

### ISSUE THREAD

**Issue by cpetry** [atteneder/glTFast#601]
**Is your feature request related to a problem? Please describe.**
I need to read and be able to adjust textures after a runtime import.

**Describe the solution you'd like**
Add an option in the ImportSettings

**Describe alternatives you've considered**

**Additional context**
I use gltf files as a basis for my project internal materials and textures. These need to be loaded in runtime and could grow over time while the user adds more materials/textures

**Comment by atteneder** [comment]
Released in [6.8.0](https://docs.unity3d.com/Packages/com.unity.cloud.gltfast@6.8/changelog/CHANGELOG.html#680---2024-09-05)
