### ISSUE TITLE
Texture2D.LoadImage causes CPU spikes and frame stalls on large textures

### ISSUE THREAD

**Issue by havalbon** [atteneder/glTFast#613]
GLTFast uses `Texture2D.LoadImage` to copy image data into textures and upload them to the GPU, which is particularly slow for large textures, and blocks the main thread until the operation is complete. This makes using GLTFast unusable for our purposes.

We are also unable to make use of the KTX load path since we require runtime decoding of user-created content.

We'd like to propose a change to `GLTFImport` and a few related APIs to permit custom loaders to be provided for each supported image format, modeled roughly after the existing KTX loader. The fallback default loader could simply continue to use `Texture2D.LoadImage` as it does today. This may also require a small change to the `KtxUnity` source as well but would not require any additional dependencies. 

It would enable us to optimise the decode by offloading the GPU copy to native code running on a worker thread, while keeping the mip creation on the render thread.

I am willing to contribute a PR for this change.

**Comment by atteneder** [comment]
I've been approached with this idea repeatedly, very strongly agree and coincidentally opened an issue about it recently (#733). I'm going to close this one in favor of the new one.

I hope me not answering sooner was not the reason you did not get around to work on a PR.

Thanks!
