### ISSUE TITLE
Runtime Export GameObjectExport could not be found

### ISSUE THREAD

**Issue by yosun** [atteneder/glTFast#615]
**Describe the bug**

error CS0246: The type or namespace name 'GameObjectExport' could not be found (are you missing a using directive or an assembly reference?)

 (https://github.com/atteneder/glTFast/blob/main/Documentation~/ExportRuntime.md)

Further directions are needed beyond just this: 

Note: The GLTFast.Export namespace can only be used if you reference both glTFast and glTFast.Export Assemblies in your [Assembly Definition](https://docs.unity3d.com/Manual/ScriptCompilationAssemblyDefinitionFiles.html).

**Files**

Attach or link to *.gltf/*.glb files that trigger the bug. 

In addition, make sure to run those files through the [glTF Validator](https://github.khronos.org/glTF-Validator) first. If you encounter errors or warnings, try to make sure they are not responsible for the issue and file a bug report with the software that generated the glTF file as well.

> Note: You have to ZIP archive them first in order for GitHub to accept the upload.

If your files are confidential:

- Try to create a similar, but intellectual-property-free glTF that reproduces the bug in the same way (so any community member can have a look)
- Otherwise, still create this issue and send the files (or a link to them) discretely via email

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - glTFast version
 - Unity Editor version [e.g. 2021.2.1f1]
 - Render Pipeline and version [e.g. Universal Render Pipeline 12.0]
 - Platform: [e.g. Editor, Windows Player, iOS]
 
additionally (if significant for the bug):

 - For WebGL: Browser [e.g. stock browser, safari]

**Additional context**

**Comment by yosun** [comment]
Creating the asmdef that reference the GLTFast and GLTFast.Export and setting it in its own folder etc, then these errors arise 

```
Multiple scripted importers are targeting the extension 'glb' and have all been rejected: GLTFast.Editor.GltfImporter (assembly: /Library/ScriptAssemblies/glTFast.Editor.dll), TriLibCore.Editor.TriLibGLTFScriptedImporter (assembly: /Library/ScriptAssemblies/Assembly-CSharp-Editor.dll) 
UnityEditor.AssetImporters.ScriptedImporter:RegisterScriptedImporters () (at /Users/bokken/build/output/unity/unity/Modules/AssetPipelineEditor/Public/ScriptedImporter.cs:112)

```

and also similar for gltf

**Comment by atteneder** [comment]
So it seems you solved the original problem, that's great!

The second error can be prevented by:

- Removing Trilib from the project
- [Disable the editor import](https://docs.unity3d.com/Packages/com.unity.cloud.gltfast@6.9/manual/ProjectSetup.html#disable-editor-import).
