### ISSUE TITLE
Consider setting up GitHub sponsors

### ISSUE THREAD

**Issue by CarePackage17** [atteneder/glTFast#620]
I'm using your library for a work project and want to convince my employer to send you money.

I think having GitHub Sponsors set up would make this easier :)

**Comment by FrogsInSpace** [comment]
I definitely would support this !
I'm in a similar situation like @CarePackage17 and the recent silence her ealready got me a bit nervous :)

**Comment by mikeskydev** [comment]
I wouldn't be too worried, Unity funds dev time on this via creator's job, and uses it as a dependency in some of their pro offerings!

**Comment by FrogsInSpace** [comment]
Thats nice to hear, 
I always had the impression already that Andreas's work is somehow tied to Unity, but its nice to hear some conformation :)

**Comment by atteneder** [comment]
Ah, you are the best ❤️ 

It's true, I'm on Unity's payroll for 4 years now and wouldn't be comfortable charging for service or accepting donations. Furthermore it might even be illegal if it's beyond a certain threshold.

Maybe I reconsider that position some day in the future, but for now I'm grateful, appreciative of your kind gesture and close this issue.
