### ISSUE TITLE
Model UV Issue

### ISSUE THREAD

**Issue by umresh** [atteneder/glTFast#63]
Hi,
   Applying texture to the loaded model but uv data is not loaded and texture is applied as whole for each mesh.
[Model](https://unity-video.s3-ap-southeast-1.amazonaws.com/GLB/3F54A97D-6E36-49C2-8F2B-A43813F9BF73.glb) and [texture](https://unity-video.s3-ap-southeast-1.amazonaws.com/GLB/1DD0C0C3-C665-42AC-83C8-3C6E809E4C82.png)

**Comment by atteneder** [comment]
Hi,
In this glTF there is no texture assigned to any material. So it's a content issue => closing.

Please test your scenes in a another glTF viewer as a reference. I use this one often:
https://gltf-viewer.donmccurdy.com

**Comment by umresh** [comment]
Yes there is no texture in glb file thats why i'm applying texture in material via script and model looks like texture is applied without uv unwarpping.

**Comment by atteneder** [comment]
Can you verify in another viewer/loader that the UVs are working?

**Comment by umresh** [comment]
Hi, tried on babylonjs viewer its working.
[Link](https://unity-video.s3-ap-southeast-1.amazonaws.com/GLB/babylon.JPG)

**Comment by atteneder** [comment]
Seems like UVs are loaded correctly
<img width="648" alt="grafik" src="https://user-images.githubusercontent.com/2593014/76254483-d2174b80-624c-11ea-9190-cb7e11913bed.png">

I slapped a random texture on it.

**Comment by atteneder** [comment]
Oh, I might have the missing clue for you:
glTF has a different "origin" for UV coordinates than Unity, so it might help to flip the texture in the Y-axis because I do so when importing UVs.
