### ISSUE TITLE
Unable to run gltf sample from web in URP / 2022.3.4f1

### ISSUE THREAD

**Issue by nebis-software** [atteneder/glTFast#634]
Hi,
    I am testing in 2022.3.4f1 with a URP project, and when I run:

```
    void Start()
    {
        var gltf = gameObject.AddComponent<GLTFast.GltfAsset>();
gltf.Url = "https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/Duck/glTF/Duck.gltf";
    }

```
I get the error:
```
NullReferenceException: Object reference not set to an instance of an object
GLTFast.Materials.ShaderGraphMaterialGenerator.GenerateDefaultMaterial (System.Boolean pointsSupport) (at /projects/glTFast-5.0.4/Runtime/Scripts/Material/ShaderGraphMaterialGenerator.cs:180)
GLTFast.Materials.MaterialGenerator.GetDefaultMaterial (System.Boolean pointsSupport) (at /projects/glTFast-5.0.4/Runtime/Scripts/Material/MaterialGenerator.cs:239)
GLTFast.GltfImport.GetDefaultMaterial () (at /projects/glTFast-5.0.4/Runtime/Scripts/GltfImport.cs:698)
GLTFast.GameObjectInstantiator.AddPrimitive (System.UInt32 nodeIndex, System.String meshName, UnityEngine.Mesh mesh, System.Int32[] materialIndices, System.UInt32[] joints, System.Nullable`1[T] rootJoint, System.Single[] morphTargetWeights, System.Int32 primitiveNumeration) (at /projects/glTFast-5.0.4/Runtime/Scripts/GameObjectInstantiator.cs:294)

```

I get this error in the editor simulator. I have added the two shaders 
glTF/PbrMetallicRoughness
Shader Graphs/glTF-pbrMetallicRoughness
to my always included shaders.

Any idea? Thanks!!!
Luigi

**Comment by BrentM-Sturfee** [comment]
I am in a similar situation on iOS running Unity version **2021.3.9f1 / URP**

It works in the Unity Editor on Windows and Mac M1, and it also works on Android. But on iOS I get this:

```
System.NullReferenceException: Object reference not set to an instance of an object.
  at GLTFast.Materials.ShaderGraphMaterialGenerator.GenerateDefaultMaterial (System.Boolean pointsSupport) [0x00000] in <00000000000000000000000000000000>:0 
  at GLTFast.Materials.MaterialGenerator.GetDefaultMaterial (System.Boolean pointsSupport) [0x00000] in <00000000000000000000000000000000>:0 
  at GLTFast.GameObjectInstantiator.AddPrimitive (System.UInt32 nodeIndex, System.String meshName, UnityEngine.Mesh mesh, System.Int32[] materialIndices,
```

**Comment by githubcatw** [comment]
I have this issue too on Unity 2022.3.11f1 with HDRP and glTFast 6.0.1 on an M1 Mac. It works in the Editor but not in a build.

**Comment by anakin78z** [comment]
Same issue, works in Editor, not in an iOS build. Unity 2020.3.18f1, URP. Tested glTFast 4.0.1, 4.9.1, 5.1.0, 5.2.0
Works fine in a different project using the built in render pipeline.

**Comment by d4n3x** [comment]
Any updates on this?

**Comment by d4n3x** [comment]
> Hi, I am testing in 2022.3.4f1 with a URP project, and when I run:
> 
> ```
>     void Start()
>     {
>         var gltf = gameObject.AddComponent<GLTFast.GltfAsset>();
> gltf.Url = "https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/Duck/glTF/Duck.gltf";
>     }
> ```
> 
> I get the error:
> 
> ```
> NullReferenceException: Object reference not set to an instance of an object
> GLTFast.Materials.ShaderGraphMaterialGenerator.GenerateDefaultMaterial (System.Boolean pointsSupport) (at /projects/glTFast-5.0.4/Runtime/Scripts/Material/ShaderGraphMaterialGenerator.cs:180)
> GLTFast.Materials.MaterialGenerator.GetDefaultMaterial (System.Boolean pointsSupport) (at /projects/glTFast-5.0.4/Runtime/Scripts/Material/MaterialGenerator.cs:239)
> GLTFast.GltfImport.GetDefaultMaterial () (at /projects/glTFast-5.0.4/Runtime/Scripts/GltfImport.cs:698)
> GLTFast.GameObjectInstantiator.AddPrimitive (System.UInt32 nodeIndex, System.String meshName, UnityEngine.Mesh mesh, System.Int32[] materialIndices, System.UInt32[] joints, System.Nullable`1[T] rootJoint, System.Single[] morphTargetWeights, System.Int32 primitiveNumeration) (at /projects/glTFast-5.0.4/Runtime/Scripts/GameObjectInstantiator.cs:294)
> ```
> 
> I get this error in the editor simulator. I have added the two shaders glTF/PbrMetallicRoughness Shader Graphs/glTF-pbrMetallicRoughness to my always included shaders.
> 
> Any idea? Thanks!!! Luigi

Have u managed to workaround this?

**Comment by d4n3x** [comment]
I fixed it by creating a ShaderVariantCollection with the GLTF shaders from the package and add it to the preloaded shaders under Graphics.

see this for more information: https://github.com/atteneder/glTFast/blob/main/Documentation%7E/ProjectSetup.md#materials-and-shader-variants

**Comment by atteneder** [comment]
Thanks @d4n3x for explaining the solution.

A problem on another level is that for this problem there would've been an error message that you likely all missed, because you did not use/setup a proper logger. I'm inclined to change the behavior that a logger is in place at all times (unless you explicitely opt out), but that implies changes to the API that have to be carved out carefully first (see #710).
