### ISSUE TITLE
Exported material through glTFast lose color.

### ISSUE THREAD

**Issue by codec-abc** [atteneder/glTFast#639]
**Describe the bug**
When exporting dynamically a GameObject that has some color, the material will lose its color.

**Files**
Here is a sample Unity project that show the bug. It contains a mesh (Blender's suzanne) with a blue material. Import is working fine, I have Suzanne looking identical as in Blender with a blue tinted material. But when I export the same mesh dynamically, I have the same geometry but the material become white.

[TestGLTFast.zip](https://github.com/atteneder/glTFast/files/12462481/TestGLTFast.zip)

**To Reproduce**
1. Open the provided project, and the scene named "Sample Scene"
2. Make sure Suzanne is in the scene and is blue.
3. Click play, the ``Start`` method of the ``Exporter`` script will run, which in turn will generate a ``exported.glb`` file directly under the ``Asset`` Directory
4. Look at ``exported.glb`` file. It is the same geometry but the material color was lost during the export.

**Expected behavior**
Exported materials should keep the base color.

**Screenshots**
Here the 2 versions:
![image](https://github.com/atteneder/glTFast/assets/1208646/9fa9e962-0e07-4b9e-85ad-9fc62699350f)

Left is imported from Blender in Unity using glTFast, right is the result of the export of the left mesh.

**Desktop (please complete the following information):**
 - glTFast version: 5.0.4
 - Unity Editor version: 2022.3.4f1
 - Render Pipeline: Legacy
 - Platform: Windows (Editor)
 
**Additional context**
If this line:
``material.pbrMetallicRoughness.BaseColor = uMaterial.color;``
is put [here in the StandardMaterialExport](https://github.com/atteneder/glTFast/blob/5c36f4405012b13ad14ec871b77ba063c53cbbc3/Runtime/Scripts/Export/StandardMaterialExport.cs#L75)
the problem is solved.
Yet I am not sure this is the correct solution because imho the exported [should pass into this if branch](https://github.com/atteneder/glTFast/blob/5c36f4405012b13ad14ec871b77ba063c53cbbc3/Runtime/Scripts/Export/StandardMaterialExport.cs#L176) and it doesn't.

**Comment by zangjy** [comment]
I encountered the same issue. Has the problem been resolved?
