### ISSUE TITLE
Secondary UV support for the occlusion texture

### ISSUE THREAD

**Issue by prajwalshettydev** [atteneder/glTFast#64]
Hi thanks for the amazing plugin. I understand that this is more of a feature request than an issue. So, currently, in the project I'm working on, I need to connect the Occlusion Texture using the secondary uv of the mesh instead of the primary. Please help me out since it is an urgent need. Thanks again

**Comment by prajwalshettydev** [comment]
I see that you have mentioned [here](https://github.com/atteneder/glTFast/issues/34#issuecomment-559900832) that the 
> Note: the second UV set is loaded, but no material/shader makes use atm.
So, can you please let me know how I can do this? for eg in the "glTFUnityStandardCoreForwardSimple.cginc" I see that "half occlusion = Occlusion(i.tex.xy);" is passed, so I'm guessing I need to pass the uv2 here instead of the uv1, just not sure how exactly to. Thanks!

**Comment by prajwalshettydev** [comment]
Hi, me again, managed to fix it for now by adding this 
`texcoord.zw = TRANSFORM_TEX(v.uv1, _OcclusionMap);`
in the `glTFUnityStandardInput.cginc`'s `TexCoords(VertexInput v)` fn. I will close this thread soon. Thanks for the wonderful plugin.

**Comment by atteneder** [comment]
Hi,

glad you figured out a solution that works for you. I may work  on a more general solution after version 2.0, which uses the new mesh API and and some point maybe the shader graph.

**Comment by prajwalshettydev** [comment]
That'd be great!
