### ISSUE TITLE
glTFPbrMetallicRoughness material is not exporting correctly.

### ISSUE THREAD

**Issue by Raja-1250** [atteneder/glTFast#640]
Describe the bug

I import both  GLB/GLTF files, at runtime and during design time, and subsequently export them as GLB/GLTF files. However, during the export process, the models lose all their material properties, except for the standard shader materials. It's worth noting that my project incorporates MRTK, although I have disabled the MRTK GLTF Importer.

**Files**
[GLB.zip](https://github.com/atteneder/glTFast/files/12511951/GLB.zip)

This is the material of one of the imported GLB :
![image](https://github.com/atteneder/glTFast/assets/144004441/649738cc-96d3-4e7e-9a25-30dc220ba4ed)

To Reproduce
1.  Import any one model from the zip into unity editor.
2.  And place the model in the scene and save.
3. Then export the model using File->Export Scene->glTF-Binary(.glb)
4.  Import the exported file into unity and check the material. You can see that all the properties of the material are empty like in the following image.

Material of the exported file
![image](https://github.com/atteneder/glTFast/assets/144004441/5c1e3d4b-7e2d-489f-bfb3-316836e90995)

**Expected behavior**
Since the glTFPbrMetallicRoughness is officially supported for the export the exported model should retain all the material properties.

**Desktop (please complete the following information):**
 - glTFast version - 5.0.0
 - Unity Editor version 2020.3.48f1
 - Render Pipeline and version 
 - Platform: Editor

Additionally
I have added the export shader variant to the preloaded shaders list.

**Comment by atteneder** [comment]
Thanks for reporting. This has been fixed in 6.5.0.
