### ISSUE TITLE
Change default shader 

### ISSUE THREAD

**Issue by Creepymulder** [atteneder/glTFast#642]
Hi,

When using LoadGltfBinary, it is possible to change the default shader applied ? Right now it's using "glTFPbrMetallicRoughness"

Thanks !

**Comment by AhmadMansy** [comment]
In my case I had to reassign shader after getting the material, but it slows down the loading time, so the better solution for me was creating a `CustomShaderGraphMaterialGenerator` and add my shader name in it.
I think functions that loads shader should all be virtual, we only have `GetUnlitShaderName` and `GetSpecularShaderName` virtual but we need at least this one `LoadShaderByName` being virtual

**Comment by atteneder** [comment]
Hi, 

The cleanest way to do custom shader selection and material creation is to implement `IMaterialGenerator` and pass it as parameter to the `GltfImport` constructor.

hth
