### ISSUE TITLE
Glb become more mettalic when we switch platform from destop to android

### ISSUE THREAD

**Issue by HEL-d** [atteneder/glTFast#645]
![org](https://github.com/atteneder/glTFast/assets/73583362/6564267e-ba2e-4b65-980f-acb946ab9eaf)

**Comment by atteneder** [comment]
Hi,

Can you check if you use DTX5nm style Normal Map Encoding (find it in the *Player Settings* under *Other Settings*?

I assume that's the problem and refer you to #694
