### ISSUE TITLE
git package failing with Package Manager on 2019.3.6f1

### ISSUE THREAD

**Issue by jeanfabre** [atteneder/glTFast#65]
Hi,

 oddly, on 2019.3.6f1, the package manager fails to load the https://github.com/atteneder/glTFast.git

here's the screenshot of the error in the package manager: 
https://imgur.com/PkjHIGN

Thanks,

 Jean

**Comment by atteneder** [comment]
Hi Jean,

it seems like you don't have GIT LFS installed, which is needed for this package.
See https://git-lfs.github.com/ for details.
If you're on a mac, I'd recommend using homebrew to install it.

hth,
andi

**Comment by jeanfabre** [comment]
Ok, thanks, all working now!
