### ISSUE TITLE
KTX spoil mesh texture in Unity build with URP but  it works in the editor

### ISSUE THREAD

**Issue by Ashot1705** [atteneder/glTFast#653]
I work on Unity 2022.3.9f , I use gltfast with ktx and draco, but model mesh texture spoils in unity builds(webgl,android apk) , but it's ok in the editor, I load glt model from 

in Editor:

![image](https://github.com/atteneder/glTFast/assets/148749819/c038dc33-bf23-4bdd-94ca-8d8ae8c6cd05)

in Builds(WebGL,Android):

![image](https://github.com/atteneder/glTFast/assets/148749819/a3836d30-e49c-45e7-a4c1-4fd559936468)

**Comment by atteneder** [comment]
@Ashot1705 Thanks for reporting!

Could you please provide this model (or another one) that lets me reproduce the issue?

**Comment by Ashot1705** [comment]
> @Ashot1705 Thanks for reporting!
> 
> Could you please provide this model (or another one) that lets me reproduce the issue?

I solved the problem,problem was about shaders when I built,the shaders weren't included in build,I solved it with adding shader variants in graphics settings,but it didn't work in unity 2022.3.9f but it worked in unity 2022.3.11f
