### ISSUE TITLE
Unable to Export from Unity with materials

### ISSUE THREAD

**Issue by MatthieuKiskonen** [atteneder/glTFast#654]
**Describe the bug**
Trying to export a gameObject from Unity scene (imported glb) does not include the material. 

I tried to look at export example ( https://github.com/atteneder/glTFast/blob/main/Documentation%7E/ExportRuntime.md ) and trying to use the SimpleExport example. But It returns an error that it can't find GLTFast.Exports from using nor GameObjectExport class.

**Files**
Due to confidential glb I managed to reproduce the issue with GLBs from a different issue

[GLB.zip](https://github.com/atteneder/glTFast/files/13189785/GLB.zip)

**To Reproduce**
1. Import assert into the project
2. Place glb in scene and select it
3. Go to GameObject > Export gltf > gltf-Binary (.glb)
4. Open generated glb and see lack of materials.

**Expected behavior**
The GameObject is exported with material

**Screenshots**

![image](https://github.com/atteneder/glTFast/assets/89856437/e2196075-651d-46b3-bc09-615b982154b3)
![image](https://github.com/atteneder/glTFast/assets/89856437/7432048b-309d-42c5-99d8-9e53fad0d061)

[export.zip](https://github.com/atteneder/glTFast/files/13189813/export.zip)

**Desktop (please complete the following information):**
 - glTFast version v6.0.1
 - Unity Editor version  2022.2.4f1
 - Render Pipeline and version HDRP 14.0.5
 - Platform: Editor

**Additional context**
[MeshMerger.zip](https://github.com/atteneder/glTFast/files/13189944/MeshMerger.zip)

This is the script I am trying to run, I have gltFast v6.0.1 added as package in package manager.

**Comment by atteneder** [comment]
Hi,

I assume you're not using HDRP Lit shaders (since the sources are glTFast imported glbs). It's a known issue that the glTFast shaders won't export well at the moment and thus round-trips are prone to errors.

See #385 and #351 

Always curious what your use-case is. It helps me prioritize working on a solution. Thanks!

**Comment by MatthieuKiskonen** [comment]
Hi,

Our use case is that we create high fidelity rendering of furnished apartments, for this we use Unity to prepare the shots and then we need to export the scene to go through a distributed rendering system. 

We also use a lot of tooling to prepare this as well as blend shapes that we need to convert to static meshes and alike as can be seen in the example script.

**Comment by MatthieuKiskonen** [comment]
Hi,

Is there an option to unpack the glb content on import? Or import using HDRP Lit Shader?
This way I could create the copy with a HDRP Lit shader using the textures and would allow to export an imported glb.

**Comment by Sov3rain** [comment]
Hey @atteneder, any news on the ability to do round-trips import/export at runtime? This feature would be greatly appreciated. We need to be able to import multiple glb files at runtime and reexport then in one scene (bundling them). Avoiding the pain of changing all the materials and swapping maps channels around would be great!.

**Comment by d4n3x** [comment]
Also have the same problem with importing an object during runtime but with URP. Same gltfast version. 
Any updates on this?

**Comment by slonepro** [comment]
Same problems here... Big mystery, the missing textures...

**Comment by youdonotexist** [comment]
Any update on this? @atteneder with the GltFast library going to Unity, is this being worked on internally? Or are you looking for a community PR to solve this issue?

I am interested in round-trip runtime import/export/import using Unity's URP Materials. Right now, importing with URP textures works, but export of that same model fails to export textures/materials.

**Comment by atteneder** [comment]
The next release will festure export of materials based on glTFast's shaders and shader graphs, this enabling import-export round-trips.

Probably comes next week.

Hth

**Comment by Sov3rain** [comment]
> The next release will festure export of materials based on glTFast's shaders and shader graphs, this enabling import-export round-trips.
> 
> Probably comes next week.
> 
> Hth

That's a really good news! We'll test it as soon as it drops 🙂

**Comment by youdonotexist** [comment]
6.5 dropped 

https://docs.unity3d.com/Packages/com.unity.cloud.gltfast@6.5/changelog/CHANGELOG.html

Will test & report back. Thanks @atteneder & Unity Team!

**Comment by flogli** [comment]
Hi,
I've just tried new 6.5 version
Same problem, 
it seems that when I export the model that has glTF/PbrMetallicRoughness (at runtime) and open it on an external gltf/glb viewer the baked material is not displayed, only the mesh with none material or texture

**Comment by vini-guerrero** [comment]
Hello.
Just tested both C# and Editor export, having same issue with `6.6.0 · June 03, 2024`
Export, import in Blender, materials exist but not textures.

**Comment by atteneder** [comment]
Sorry to hear it's not resolved yet.

Can y'all please look if you have the `Image Conversion` built-in package enabled (in the Package Manager) and tell me what render pipeline and shaders you are using?

**Comment by atteneder** [comment]
There's a bug where materials are not exported properly when URP/HDRP are both *NOT* installed.

If that's the case on your end, a fix is incoming.

**Comment by atteneder** [comment]
It's [live](https://docs.unity3d.com/Packages/com.unity.cloud.gltfast@6.7/manual/index.html)!
