### ISSUE TITLE
How to export the rigged avatar with blendshape using this repo

### ISSUE THREAD

**Issue by devunity-yologram** [atteneder/glTFast#659]
I have created an avatar system in Unity where the user can modify the looks of the avatar. It has different blend shapes for different attributes that the user can play with, such as fatness. I also have a clothing system.

I want to export the modified avatar as a gltf. Just like a gltf from ready player me which comes with the rig and everything.

**Comment by Zarbuz** [comment]
It seems that it currently doesn't support export with blendshapes. I've the same issue. Is it something planned ?

**Comment by atteneder** [comment]
There's been initial work in #512 , but I haven't found the time to bring it over the finishing line.

**Comment by atteneder** [comment]
Skinned mesh export has been added in 6.8.0.

For the remaining tasks there's dedicated issues:

- #742 
- #391 
- #740 

Closing this one.
