### ISSUE TITLE
Unable to export draco compressed GLB file at runtime : DracoUnity package needs to be installed

### ISSUE THREAD

**Issue by Sov3rain** [atteneder/glTFast#661]
**Describe the bug**
I can't figure out how to export a Draco compressed GLB file. I installed all packages available from the scope registry with the following versions:
- glTFast 6.0.1
- Draco 3D Data Compression 4.1.0
- KTX/Basis Universal Texture 2.2.3

I added an assembly definition file in my script folder:
![image](https://github.com/atteneder/glTFast/assets/10755450/df4de00c-b9ca-4bce-88d6-d6bd8a2de0c6)

My export script looks like this:

```csharp
var exportSettings = new ExportSettings
{
    Format = GltfFormat.Binary,
    FileConflictResolution = FileConflictResolution.Overwrite,
    Compression = Compression.Draco,
    DracoSettings = new()
    {
        positionQuantization = 12
    }
};

var exporter = new GameObjectExport(exportSettings, logger: logger);
exporter.AddScene(exportables);

bool success = await exporter.SaveToFileAndDispose(Application.persistentDataPath + "/export.glb");
```

I still get the following error:
`DracoUnity package needs to be installed in order to support glTF extension KHR_draco_mesh_compression!`

I can export non-compressed files with no issue.

**Expected behavior**
I would like to be able to export draco-compressed GLB files at runtime.

**Desktop (please complete the following information):**
 - glTFast version: 6.0.1
 - Unity Editor version: 2021.3.28f1
 - Render Pipeline and version: BiRP
 - Platform: Editor, WebGL

**Comment by Muhammad079** [comment]
Did you find any solutions there? @Sov3rain ?

**Comment by Sov3rain** [comment]
> Did you find any solutions there? @Sov3rain ?
> 
> 

Unfortunately, no. Draco compression is not our top priority right now and we clearly need help on this one.

**Comment by monkyver** [comment]
hello, is meshoptimizer supported instead?

**Comment by atteneder** [comment]
You need to install [Draco for Unity 5.0.0](https://docs.unity3d.com/Packages/com.unity.cloud.draco@5.1/manual/index.html) or newer (generally the latest version is recommended).

> **Note**: If you still use the original [DracoUnity](https://openupm.com/packages/com.atteneder.draco/) package (com.atteneder.draco), transition to the one in the link above.

hth

**Comment by atteneder** [comment]
> hello, is meshoptimizer supported instead?

Meshopt compression is supported for import only atm. No immediate plans to do export/compression.
