### ISSUE TITLE
Resample and optimize imported animation curves (similar to Unity's built-in FBX importer)

### ISSUE THREAD

**Issue by kodra-dev** [atteneder/glTFast#663]
**Is your feature request related to a problem? Please describe.**
Unity's built-in FBX has options to resample imported animation curves, which reduces the amount of keyframes by a lot.

The sample animation as .fbx:
![Screenshot 2023-12-20 180554](https://github.com/atteneder/glTFast/assets/117553001/e03902b5-3318-4d43-ad27-09146969422d)

And as .glb:
![Screenshot 2023-12-20 180545](https://github.com/atteneder/glTFast/assets/117553001/65b00e3f-8539-4777-bb2e-dd7e1b4a8666)

See the huge difference in the number of keyframes.

**Describe the solution you'd like**
Something similar to Unity's FBX importer settings:
![Screenshot 2023-12-20 180648](https://github.com/atteneder/glTFast/assets/117553001/6e7d735e-91cf-4cf5-a426-f8064ad1bf1f)

**Describe alternatives you've considered**
Uh... using FBX instead...?

**Comment by atteneder** [comment]
Thanks for the suggestion.

Although I see the value in this feature request, I don't think glTFast should put effort into fixing corrupt or sub-optimal input data (at least before other more essential features are implemented first).

The FBX feature cannot be easily re-used, as it stems from the FBX SDK itself.

I suggest to use other third party tooling to optimize the animation clips.
