### ISSUE TITLE
Namespace GLTFast.Newtonsoft could not be found

### ISSUE THREAD

**Issue by daniel1v** [atteneder/glTFast#671]
**Describe the bug**

Unity Editor shows a compiler error:

` error CS0234: The type or namespace name 'Newtonsoft' does not exist in the namespace 'GLTFast' (are you missing an assembly reference?)
`

following package versions are installed via package manager:

com.unity.nuget.newtonsoft-json  3.2.1
com.unity.cloud.gltfast 6.1.0

**To Reproduce**

Using Unity 2022.3

install com.unity.nuget.newtonsoft-json
install com.unity.cloud.gltfast
try to use namespace GLTFast.Newtonsoft

**Expected behavior**
namespace should be found, because newtonsoft is present

Am I missing something?

**Comment by daniel1v** [comment]
After diving a bit into the package, I noticed, that  [`autoReferenced`](https://github.com/atteneder/glTFast/blob/1e85cf730c714fbe9badc1e370753f4fa4dcfe52/Runtime/Scripts/Newtonsoft/glTFast.Newtonsoft.asmdef#L12) should be set to `true` in the asmdef.

At least it seems to solve my issues.

**Comment by atteneder** [comment]
Hi @daniel1v ,

Glad you found a solution! I'm hesitant to enable autoReference. Imho references should be set explicitely to give devs full control. I'm aware that this is not consistent within glTF....legacy was carried on for now. At some point all asmdefs shoud not be auto referenced.

Thanks.

**Comment by daniel1v** [comment]
Hi @atteneder,

thank you for your reply. I'm not sure if this is a general solution for the issue, because I had to move the package and edit its contents. So it is more a workaround I think and I fear this leads to issues when the package is updated.

Is there a recommended way to solve this, without editing contents of the package? My unity knowledge is limited, so maybe I have overseen something obvious?

**Comment by atteneder** [comment]
I think the original error was resolved in glTFast 6.2.0, which was released yesterday. Feel free to give it a try and report any issues.

With regards to asmdefs, the best practice is to put your own code into an asmdef as well and reference any dependencies explicitely. That should keep compile times (and thus iteration time) short and there are no surprisingly linked libraries. See the [docs](https://docs.unity3d.com/Manual/ScriptCompilationAssemblyDefinitionFiles.html) for details.

**Comment by ManuSense** [comment]
I have the same issue: 

> error CS0234: The type or namespace name 'Newtonsoft' does not exist in the namespace 'GLTFast' (are you missing an assembly reference?)

Unity 2021.3.2f
"com.unity.cloud.gltfast": "6.8.0"
"com.unity.nuget.newtonsoft-json": "3.2.1"

In my case gltfast.newtonsoft asmdef is greyed out so i can't set autoreference to true.  @atteneder  How can i solve this?

**Comment by atteneder** [comment]
@ManuSense I assume you've created a custom script, right? In that case, please create an accompanying assembly definition as well and reference the glTFast.Newtonsoft assembly.
