### ISSUE TITLE
Error Cloning Repository - LFT Over Quota

### ISSUE THREAD

**Issue by jackdaus-at-noblis** [atteneder/glTFast#672]
**Describe the bug**
When I attempt to clone this git repository, I encounter an error, 

>Downloading Documentation~/Images/Unity-glTF-workflows.png (59 KB)
Error downloading object: Documentation~/Images/Unity-glTF-workflows.png (aa50e39): Smudge error: Error downloading Documentation~/Images/Unity-glTF-workflows.png (aa50e3980f8e9a99e53b8347cdde7e293fe37ffb5e1469640379d802ef304541): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

**To Reproduce**
1. Clone the git repository locally by running
`git clone https://github.com/atteneder/glTFast.git`

Here is the full console message,
```
C:\Users\user\source>git clone https://github.com/atteneder/glTFast.git
Cloning into 'glTFast'...
remote: Enumerating objects: 12716, done.
remote: Counting objects: 100% (4737/4737), done.
remote: Compressing objects: 100% (527/527), done.
remote: Total 12716 (delta 4369), reused 4272 (delta 4210), pack-reused 7979
Receiving objects: 100% (12716/12716), 3.51 MiB | 8.90 MiB/s, done.
Resolving deltas: 100% (10380/10380), done.
Updating files: 100% (666/666), done.
Downloading Documentation~/Images/Unity-glTF-workflows.png (59 KB)
Error downloading object: Documentation~/Images/Unity-glTF-workflows.png (aa50e39): Smudge error: Error downloading Documentation~/Images/Unity-glTF-workflows.png (aa50e3980f8e9a99e53b8347cdde7e293fe37ffb5e1469640379d802ef304541): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

Errors logged to 'C:\Users\user\source\glTFast\.git\lfs\logs\20240202T162051.86522.log'.
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: Documentation~/Images/Unity-glTF-workflows.png: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

**Additional context**
It seems like this error is causing problems with opening Unity projects as well.

**Comment by jackdaus-at-noblis** [comment]
In case others are running into this issue, as a workaround, I've replaced this repo in my Unity project's package dependency with the "official" package, https://docs.unity3d.com/Packages/com.unity.cloud.gltfast@6.1/manual/UpgradeGuides.html#transition-to-unity-gltfast

I specified the package version 5.2.0, since the newest package version (6.2.0) seems to break some ReadyPlayerMe related things.

**Comment by atteneder** [comment]
@jackdaus-at-noblis I approve the switch to the Unity package as well!

I refuse to pay GH more and more money out of my private pocket for providing packages free of charge, hence I run out of GIT LFS traffic quota occasionally. Mid-term I'm working on a solution.

Thanks for understanding.

**Comment by jackdaus-at-noblis** [comment]
@atteneder I totally understand! I wouldn't expect anyone to personally finance a free, open source project. I just wanted to make sure you were aware in case you didn't already know.

And of course, thanks for maintaining this repo! I'm sure the time cost is not insignificant. The community appreciates it :)
