### ISSUE TITLE
Derived GameObjectInstantiator classes cannot fire base events

### ISSUE THREAD

**Issue by LaneF** [atteneder/glTFast#675]
When creating a derived class from `GameObjectInstantiator` and overriding `AddPrimitive()` it is not possible to fire the `MeshAdded` event due to rights scoping on `event` and there's not really a clean way to go about doing it otherwise.

I'm not sure what the implications of not firing are just yet, but this seemed like an oversight to me.

**Comment by atteneder** [comment]
Good point!

The obvious solution is to create protected trigger methods for all events like so:

```csharp
protected void OnMeshAdded(
            GameObject gameObject,
            uint nodeIndex,
            string meshName,
            MeshResult meshResult,
            uint[] joints = null,
            uint? rootJoint = null,
            float[] morphTargetWeights = null,
            int primitiveNumeration = 0
            )
        {
            MeshAdded?.Invoke(gameObject,nodeIndex,meshName,meshResult,joints,rootJoint,morphTargetWeights,primitiveNumeration);
        }
```

As you can see this adds quite some boilerplate (and XML doc is missing still).

On the other hand, users who derive from `GameObjectInstantiator` can always introduce their own custom events. That can be a bit redundant though, if they have the same signature and fire at the same time.

I'm indecisive whether to do something about it.

**Comment by atteneder** [comment]
Giving it some more thought I think the best solution is to create your own events in your derivative of `GameObjectInstantiator`. I'd prefer to keep this class (and the code base overall) as lean as possible.

Thanks
