### ISSUE TITLE
Material color changes slightly during export

### ISSUE THREAD

**Issue by markus-senger** [atteneder/glTFast#680]
When a model is exported from Unity to the glb format, it seems that the material color is automatically slightly lightened.

Example:
The following model is being exported from Unity to the .glb format:

![image](https://github.com/atteneder/glTFast/assets/77236323/7e4e42e6-1496-4de9-ad8b-09b08aaee8a0)

 the following shader with the following material color is used:

![image](https://github.com/atteneder/glTFast/assets/77236323/fbd1384e-ccbe-45b0-9c94-a66d28c8e432)

In the next step, the model just exported is imported back into Unity, but the material color is slightly altered:

![image](https://github.com/atteneder/glTFast/assets/77236323/60113354-2f44-47db-aa81-98e4d37f1daa)
![image](https://github.com/atteneder/glTFast/assets/77236323/440b39fd-0e54-43fc-a119-633c730f8371)

The issue occurs regardless of import during runtime or design-time.

 - glTFast version: 6.2.0
 - Unity Editor version: 2021.3.4f1
 - Render Pipeline and version: Built-in
 - Platform: Editor

export code: 
```
          var exportSettings = new ExportSettings
          {
              Format = GltfFormat.Binary,
              FileConflictResolution = FileConflictResolution.Overwrite
          };
          var gameObjectExportSettings = new GameObjectExportSettings
          {
              OnlyActiveInHierarchy = false,
              DisabledComponents = true,
          };
          var export = new GameObjectExport(exportSettings, gameObjectExportSettings);
          export.AddScene(new GameObject[] { exportObject });

          bool success = await export.SaveToFileAndDispose(metaDataHandler.pathCAD.Replace("_cad.json", ".glb"));
```

import code (during runtime):
```
        try
        {
            success = await gltf.LoadGltfBinary(
                                            data,
                                            // The URI of the original data is important for resolving relative URIs within the glTF
                                            new Uri(orgPath),
                                            new ImportSettings()
                                        );
        } catch(Exception e)
        {
            success = false;
            UnityEngine.Debug.Log("LoadGltfBinary failed: " + e.Message);
        }

        if (success)
        {         
            GameObject model = new GameObject("ImportModel");
            model.transform.parent = cadRoot.transform;
            await gltf.InstantiateMainSceneAsync(model.transform);
            ...
```

**Comment by BadSense** [comment]
The colors you export may change depending on whether the color space is gamma or linear.
Try to get the Standard shader color from the script, change it to linear, and export it.
```
Color color = material.GetColor(COLOR_NAME);
material.SetMainColor(color.linear);
```

**Comment by atteneder** [comment]
I agree, this is likely a color space issue. Can you tell me what color space your project uses?

The importer is quite well tested, when it comes to color accuracy, so I assume the exporter messes it up somehow.
