### ISSUE TITLE
Unable to load GLTF model with WEBP texture in Android / IOS builds

### ISSUE THREAD

**Issue by Anthony-Key** [atteneder/glTFast#681]
In our platform we use GLTF models, where some have WebP textures. In its current state, they fail to load. I've tried the forked webp_support, however this isn't working correctly with textures completely broken and models not loading. Is there any chance GLTF unity can support webP in the future for android / ios builds not just windows builds?

**Comment by atteneder** [comment]
Regarding PR #632: I've added a comment that explains why there hasn't been an effort to merge it yet. I recommend we move any discussion about WebP there and close this one.

The next release will contain a fix that'll prevent crashes if you load glTFs with optional WebP at last (see #705).
