### ISSUE TITLE
When loading a glb file, the colors of the materials are changed upon loading.

### ISSUE THREAD

**Issue by Miyasaka-prono82** [atteneder/glTFast#683]
**Describe the bug**
When loading a glb file, the colors of the materials are changed upon loading.

**Files**
[Cube.zip](https://github.com/atteneder/glTFast/files/14476834/Cube.zip)

**To Reproduce**
1. Create a Cube on the Editor and set the color to (R,G,B) = (65,110,50).
[Figure 1]
![fig1](https://github.com/atteneder/glTFast/assets/56023011/a09f2f1f-bfdc-49b6-8ded-1fee095b0235)
2. Export Cube.glb with GLTFast.
    (When importing GLB (exported from Unity Editor) using blender, the colors have already changed.)
3. Drag and drop Cube.glb onto the Editor.
Then, the color of the Cube changed to (R,G,B) = (138,175.122).
[Figure 2]
![fig2](https://github.com/atteneder/glTFast/assets/56023011/9f0c0a36-367b-4676-bcca-9ddef4baf621)
5. I would like to load it with the same color as created (Figure 1).
6. The shader variant is set as shown in the diagram.
![fig3](https://github.com/atteneder/glTFast/assets/56023011/8d1bb441-8d60-42ed-9acc-cec8b4845807)
7. Are there any settings required for this? Please let me know if additional information is needed.
Cube.zip is the model I actually used.

**Desktop (please complete the following information):**
 - GLTFast version 6.2.0
 - Unity Editor 2023.3.16 f1
 - Render Pipeline and version [unknown]
 - Platform: Editor, int the future PC(HTC VIVE), Android(Meta Quest)

**Comment by Miyasaka-prono82** [comment]
It seems that #680 is also experiencing a similar problem.
Have you done any research since then?

**Comment by atteneder** [comment]
Hi,

The fix for this issue was released with [6.7.0](https://docs.unity3d.com/Packages/com.unity.cloud.gltfast@6.7/manual/index.html).

hth
