### ISSUE TITLE
Header authentication

### ISSUE THREAD

**Issue by Merichbier** [atteneder/glTFast#69]
Hi,

Thanks for your work first, looks good I'll test it for sure. I was wondering if this plugin can download a GLTF which is on a protected https url ?

We have a server where we need to authenticate using http headers. Is it possible to set this up and access our assets on our server ?

Cheers

**Comment by atteneder** [comment]
Hi,

honestly, I don't know. glTFast uses regular [UnityWebRequests](https://docs.unity3d.com/ScriptReference/Networking.UnityWebRequest.html) for loading, so it should be possible to submit credentials or a token.

I might have to make this accessible though. If UnityWebRequests work with your server infrastructure and you send me a code snippet, how to achieve it, I can look into creating an API for it.

regards

**Comment by Merichbier** [comment]
Hi,

Thanks for this super fast response !

We usually also work with UnityWebRequest and simply set the authentication header like this :

```c#
request.SetRequestHeader("Authorization", authHeader);
```

It should be quite easy to expose an API to set http header with simple key/value input somewhere

**Comment by atteneder** [comment]
Sounds reasonable.

Maybe register a delegate/callback that let's you work with the request before sending it.
If you need this urgently feel free to go ahead. I can offert to review PRs.

**Comment by atteneder** [comment]
Added in 1.0.1
