### ISSUE TITLE
GLB with sparse enabled not valid

### ISSUE THREAD

**Issue by HarrisonHough** [atteneder/glTFast#691]
**Describe the bug**
We recently added support for sparse on our avatar system. Our fullbody avatars work fine but for some reason the halfbody ones do not. If you try to load the .glb either from code of drag/drop the file into Unity it shows as if it is invalid. 
You can find an example model at the url below

**Files**
This is a halfbody model with the issue
https://models.readyplayer.me/662bad3b3f0967a5debcb171.glb
This is a fullbody model that does NOT have the issue
https://models.readyplayer.me/6629d911aa85550550be7f21.glb

Both pass gltf validation

In addition, make sure to run those files through the [glTF Validator](https://github.khronos.org/glTF-Validator) first. If you encounter errors or warnings, try to make sure they are not responsible for the issue and file a bug report with the software that generated the glTF file as well.

> Note: You have to ZIP archive them first in order for GitHub to accept the upload.

If your files are confidential:

- Try to create a similar, but intellectual-property-free glTF that reproduces the bug in the same way (so any community member can have a look)
- Otherwise, still create this issue and send the files (or a link to them) discretely via email

**To Reproduce**
1. Download a halfbody model
2. import it with gltfast (you can drag/drop the file)
4. File shows as invalid 

**Expected behavior**

**Screenshots**
![image](https://github.com/atteneder/glTFast/assets/7085672/f9157371-0a77-4054-96f0-e6f09b511c94)
![image](https://github.com/atteneder/glTFast/assets/7085672/39d5fa7b-b86c-4c1f-9418-20d4385ddd2c)

**Desktop (please complete the following information):**
 - glTFast version 6.0.1 + 6.4.0
 - Unity Editor version [e.g. 2021.3.32f1]
 - Render Pipeline and version SRP
 - Platform: Editor

**Comment by atteneder** [comment]
Hi Harrison,

Do you mind telling me why you were able to close the issue? I want to exclude bugs on my end, but I'll assume there's been some sort of error in the asset.
