### ISSUE TITLE
Draco exports have wrong mesh bounds at export

### ISSUE THREAD

**Issue by anonymous2585** [atteneder/glTFast#692]
**Describe the bug**
When exporting a mesh using draco compression, the mesh bounds written in the file is inverted on the X axis.

**File**
[OffsetCube.zip](https://github.com/atteneder/glTFast/files/15132379/OffsetCube.zip)

**To Reproduce**
- Export a mesh that has its pivot far from the verticies on the x axis
- Import the mesh at runtime (do not call [Mesh.RecalculateBounds](https://docs.unity3d.com/ScriptReference/Mesh.RecalculateBounds.html) on the mesh after importing)
- Move the camera in 3D space

See the object been culled by Unity even when still in view.

**Expected behavior**
The bounding box is correct and user doesn't need to use Mesh.RecalculateBounds to fix the mesh bounds.

**Proposed fix**
We fixed this issue locally by adding a `-` here:
https://github.com/atteneder/glTFast/blob/ef121f3a88707d79c178f4d573620566b1ced6b9/Runtime/Scripts/Export/GltfWriter.cs#L1213 (changed to `-center.x-extents.x,`)

And here:
https://github.com/atteneder/glTFast/blob/ef121f3a88707d79c178f4d573620566b1ced6b9/Runtime/Scripts/Export/GltfWriter.cs#L1219 (changed to `-center.x+extents.x,`)

If you look at the legacy export, there is the `-` sign on X axis:
https://github.com/atteneder/glTFast/blob/ef121f3a88707d79c178f4d573620566b1ced6b9/Runtime/Scripts/Export/GltfWriter.cs#L1389 so we think it has been forgotten in the draco code.

**Setup**
 - glTFast version 6.3.0
 - Unity Editor version 2023.2.20f1
 - Render Pipeline: build-in
 - Platform: Windows editor

**Comment by anonymous2585** [comment]
@atteneder Can you please take a look at this issue? It affects people using draco exports, and the fix seams pretty easy.

**Comment by atteneder** [comment]
@anonymous2585 Great find and excellent report! The fix will land in one of the upcoming updates.

**Comment by atteneder** [comment]
The fix landed in [6.7.0](https://docs.unity3d.com/Packages/com.unity.cloud.gltfast@6.7/manual/index.html).
