### ISSUE TITLE
What's The Proper Way To Get Game Object From Editor Script As A Buffer?

### ISSUE THREAD

**Issue by vini-guerrero** [atteneder/glTFast#696]
Hello!, hey there.

Considering a Unity Plugin/Tool based on a custom Editor Window, what's the correct approach to load a buffer and retrieve it's GameObject (no instancing, just dynamic reference of the game object)?
I'm not storing the file locally, project requires a buffer since it will be used just for rendering a thumbnail.

```
// asset_glb - httpResponse.Content.ReadAsByteArrayAsync().Result Buffer
var gameObj = new GameObject();
var gltf = new GltfImport();
gameObj = gltf.LoadGltfBinary(asset_glb);
```

![image](https://github.com/atteneder/glTFast/assets/18181786/b6a454e1-60a2-4cd1-ab63-ad43e4c0c271)

**Comment by atteneder** [comment]
Hi,

not sure I understand. You want to load a glTF-binary from a `byte[]` and access a GameObject without instantiation of a scene?

That is not really feasible. Do you mean you want to query (parital) information without displaying the scene or having the glTF's content show up? Please elaborate your use-case.

**Comment by vini-guerrero** [comment]
Yes, correctly, because the intention is for this dynamic Game Object to be used as input for Unity's PreviewRenderUtility (AddSingleGO).
It will be the source for Editor Window render a thumbnail of the mesh/material.
The goal is to not change user's project hierarchy or store unnecessary local files since it's just a thumbnail (multiple API results).
What's the recommended approach for loading this buffer with glTFast?

**Comment by atteneder** [comment]
I see.
There's no way around creating an instance. What I'd try is to create the GameObject(s) hidden by default (root GameObject not active and [hidden in hierarchy](https://docs.unity3d.com/ScriptReference/HideFlags.HideInHierarchy.html)).

You might have to create a custom IInstantiator, but maybe something like this does the trick:

```csharp
// asset_glb - httpResponse.Content.ReadAsByteArrayAsync().Result Buffer
var gameObj = new GameObject("root");
gameObj.SetActive(false);
gameObj.hideFlags = HideFlags.HideInHierarchy;
var gltf = new GltfImport();
await gltf.LoadGltfBinary(asset_glb);
await gltf.InstantiateMainSceneAsync(gameObj.transform);
```

hth

**Comment by atteneder** [comment]
It should work in edit mode as well, as long as you don't run it async. See `GltfImporter` as an example.

**Comment by vini-guerrero** [comment]
Thanks @atteneder I will give it a try!

**Comment by Singh-sid930** [comment]
Were you able to make this work through an editor script? 
I am running inot similar issue.
