### ISSUE TITLE
GameObjectExport and shader problem

### ISSUE THREAD

**Issue by giulianamuto** [atteneder/glTFast#697]
I installed the package in my project following the guide. When I write the export example code it fails to find GameObjectExport. As far as shaders are concerned, however, I cannot insert them into ‘Graphics’ because they are inside a package and I cannot access them.

 I don't know how to do it honestly.

 - glTFast version the last 
 - Unity Editor version 22.3.10.1

**Comment by atteneder** [comment]
Did you, by chance, forgot to reference the assembly definition `glTFast.Export` in your assembly definition?

You should be able to add shaders from a package, but they might be hidden by default. Look for an eye icon that crossed. Click it to also see shaders from a package.

Lastly, glTFast version `last` is not very explicit :) Please report with actual version numbers to make debugging easier on my end.

Thanks.

**Comment by atteneder** [comment]
Closing due to lack of details.
