### ISSUE TITLE
Why the diference of render - transparent texture

### ISSUE THREAD

**Issue by acesolucoes** [atteneder/glTFast#699]
**Describe the bug**

I have a cloth exported in GLTF/GLB that opens in other viewer as intended, but in GLTFast the transparency value is not being respected.

**Files**

It follows in attachment a minimal glb with the issue, as well the rendering in Unity 2022.3.18f1 with GLTFast 6.6 (HDRP) and with another GLTF viewer. The problem also happens in URP with GLTFast 5.0 and presumibly other GLTFast versions too. I didn't have tested in Builtin Pipeline.

[gltf_transparency_issue.zip](https://github.com/user-attachments/files/15916468/gltf_transparency_issue.zip)

**Expected behavior**
The expected behavior is the viewing according to the other GLTF viewers. In case, the CESIUM in screenshots.

**Screenshots**

![unity_gltfast](https://github.com/atteneder/glTFast/assets/2185490/0cce2dca-2183-442c-afa3-2f73b00fcba2)
![cesium_gltf png](https://github.com/atteneder/glTFast/assets/2185490/202860c0-5503-49df-a689-caeaec2eb721)

**Desktop (
 - Platform: Windows Unity 2022.3.18f1 - URP and HDRP
 
additionally (if significant for the bug):

 - Notebook with Windows 11

**Comment by atteneder** [comment]
@acesolucoes Thanks for reporting.

I was able to reproduce and fix it in HDRP.

I did not see that error on URP/2022 though.

Fix will land in 6.7.0, planned for later this week.

hth
