### ISSUE TITLE
Pink Shaders URP on iPhone (fine in editor)

### ISSUE THREAD

**Issue by yosun** [atteneder/glTFast#701]
URP on iPhone is pink shader :-(

tried adding to gltf shaders manually

 2022.3.33f1

**Comment by atteneder** [comment]
> **Upfront**: If you haven't done already, read the [Materials and Shader Variants](https://docs.unity3d.com/Packages/com.unity.cloud.gltfast@6.7/manual/ProjectSetup.html#materials-and-shader-variants) docs.

There's most likely a shader variant missing, but I need more information.

Which shaders (or shader variants) have you added manually and how exactly?

Can you provide the glTF that's causing the error and isolate which materials in it are affected?

**Comment by yosun** [comment]
Apparently it was due to missing a graphics setting "always included shader" - Shader Grahps/glTF-pbrMetallicRoughness -  

Adding that one increased the build time to over an hour on m3max (usually it's less than 30s)

**Comment by yosun** [comment]
is it possible to have some sort of postprocess script check for missing shaders to make this more accessible to a wider Unity crowd? 

i'm not really a shader person so previously i was not aware that Shader Graphs (blue icon) could also be added - usually I just add the colorful S icon

**Comment by atteneder** [comment]
As stated in the docs, adding the whole shader means adding all of its shader variants, which are a  *LOT* (hence the long build time and likely increased build size). It's better to just add the shader variants you'll actually need, but figuring this out is up to you.

I agree, tooling around this topic can definitely be improved.

**Comment by yosun** [comment]
It's a runtime any glb mesh importer so I don't know a priori which materials might be used - I had tried manually extracting the texture from the missing shader material and assigning to known shader but that did not work

**Comment by atteneder** [comment]
You might find the idea I proposed in #703 useful.
