### ISSUE TITLE
Editor import/export

### ISSUE THREAD

**Issue by edgar-rodrigo-santos** [atteneder/glTFast#71]
Hi,

Does glTfast support editor-time gltf import/export?
If not, do you plan on supporting that?

Thanks

**Comment by atteneder** [comment]
Hi Edgar,

unfortuantely not. I don't rule it out completely, but at least I myself won't need/implement it that anytime soon.

I had good experience exporting glTF at editor-time with [UnityGLTF](https://github.com/KhronosGroup/UnityGLTF) though.

hth
