### ISSUE TITLE
Draco and KXT plugins are signed with wrong Identifiers

### ISSUE THREAD

**Issue by kamend** [atteneder/glTFast#712]
**Describe the bug**
We are trying to run Unity's official Draco and KXT plugins and although they work as suppose, in a MacOS build they cause problems when we want to upload that build to TestFlight.

The .bundle in "x86_64" for both plugins is signed with an invalid identifier - "draco_unity" and "ktx_unity" and also the Info.plist file is missing a Bundle Identifier too. 

We can resign and update the identifiers manually, but that will be a pain, if we need to do this every time we make a build.

I know it's not a GLTFast issue, but I assume that these plugins might be developed by the same team.

These are the errors we get in XCode:

![Screenshot 2024-08-14 at 15 53 21](https://github.com/user-attachments/assets/10735a1d-3ec4-41f5-9e63-c4b9421b4255)
![Screenshot 2024-08-14 at 15 53 16](https://github.com/user-attachments/assets/82d637f4-3ff1-4988-93f6-097259fd7ff6)

Thanks in advance!

**Comment by atteneder** [comment]
Thanks for reporting!

Recently I code signed and notarized those binaries, but did not test submission to test flight. Admittedly I don't know too much about Apple code signing.

Just to certify, you're using the latest versions of KTX for Unity (3.4.2) and Draco (5.1.5), right?

I need to investigate and maybe ask an expert.

**Comment by kamend** [comment]
Thanks for the quick reply. Yes, we are using the latest versions available.

**Comment by atteneder** [comment]
Fixes landed in [Draco for Unity 5.1.6](https://docs.unity3d.com/Packages/com.unity.cloud.draco@latest/) and [KTX for Unity 3.4.3](https://docs.unity3d.com/Packages/com.unity.cloud.ktx@3.4/changelog/CHANGELOG.html#343---2024-09-05).

Thanks a lot for your help ❤️
