### ISSUE TITLE
Animation clip load error at runtime when set animation method to Mecanim

### ISSUE THREAD

**Issue by uncle-jerry** [atteneder/glTFast#717]
**Describe the bug**
Animation clip load error at runtime when set animation method to Mecanim.

09-11 17:45:19.093 13676 13695 E Unity   : Can't use AnimationClip::SetCurve at Runtime on non Legacy AnimationClips
09-11 17:45:19.093 13676 13695 E Unity   : GLTFast.AnimationUtils:AddVec3Curves(AnimationClip, String, String, NativeArray`1, NativeArray`1, InterpolationType)
09-11 17:45:19.093 13676 13695 E Unity   : GLTFast.AnimationUtils:AddTranslationCurves(AnimationClip, String, NativeArray`1, NativeArray`1, InterpolationType)

09-11 17:45:19.108 13676 13695 E Unity   : Can't use AnimationClip::SetCurve at Runtime on non Legacy AnimationClips
09-11 17:45:19.108 13676 13695 E Unity   : GLTFast.AnimationUtils:AddRotationCurves(AnimationClip, String, NativeArray`1, NativeArray`1, InterpolationType)

**To Reproduce**
1) Set animation method to Mecanim;
2) Build project as an android apk, load gltf file at runtime;

**Expected behavior**
Animation clips loaded correctly.

**Desktop (please complete the following information):**
 - glTFast version: 6.4.0, 6.8.0
 - Unity Editor version: 2022.3.19f1
 - Render Pipeline and version: built-in
 - Platform: Android
 
additionally (if significant for the bug):

 - For WebGL: Browser [e.g. stock browser, safari]

**Additional context**

**Comment by atteneder** [comment]
Hi @uncle-jerry,

Mecanim support is intended for in-Editor use only. The error you get is a [Unity limitation](https://docs.unity3d.com/6000.0/Documentation/ScriptReference/AnimationClip.SetCurve.html), not a glTFast bug.

Out of curiosity, if not with the legacy animation system, how do you intend to put those animation clips to use at runtime?

**Comment by uncle-jerry** [comment]
Hi @atteneder ,

In our project, the glb files are stored in cloud server, we have to load them at runtime.

**Comment by atteneder** [comment]
> Hi @atteneder ,
> 
> In our project, the glb files are stored in cloud server, we have to load them at runtime.

That makes sense, but why would you need to load animations as mecanim at runtime? That I still don't comprehend. Or in other words, why don't you use the (default) legacy animation?

**Comment by uncle-jerry** [comment]
> > Hi @atteneder ,
> > In our project, the glb files are stored in cloud server, we have to load them at runtime.
> 
> That makes sense, but why would you need to load animations as mecanim at runtime? That I still don't comprehend. Or in other words, why don't you use the (default) legacy animation?

Previously, our animation controlling logic is based on mecanim, so we hope that all animation processed in an uniform manner. As mecanim is not supported to be loaded at runtime, we have added logic to load and control the legacy animation.

Thanks for your reply.

**Comment by atteneder** [comment]
I'm glad you found a solution!

I'd love to provide a mecanim-based solution as well, but until that's not realized the legacy one will do just fine.

Thanks for clarifying.
