### ISSUE TITLE
Draco for Unity build failed because it could not parse the semantic version of the Chinese version of Unity.

### ISSUE THREAD

**Issue by YogurSligh** [atteneder/glTFast#719]
**Describe the bug**
The regular expression used to parse the version number in the structure UnityVersion does not include the special version number of the Chinese version of Unity, such as the version 2021.3.4f1c1 I am currently using.

**To Reproduce**
1. Download the Chinese version of Unity like 2021.3.40f1c1
2. Create an empty project using the urp3D template
3. Import the Draco for Unity package using UPM.
4. Import the glTFast package using UPM.
5. Switch to the WebGL platform and build the project.
6. See error

**Screenshots**

![image](https://github.com/user-attachments/assets/57a9b301-b6a2-4bf3-ba99-b99896b6b745)

**Desktop (please complete the following information):**
 - glTFast version: 6.8.0
 - Draco for Unity version: 5.1.6
 - Unity Editor version: 2021.3.40f1c1
 - Render Pipeline and version: Universal Render Pipeline 12.1.15
 - Platform: WebGL

**Comment by atteneder** [comment]
@YogurSligh Thanks for reporting. A fix is in the making.

**Comment by atteneder** [comment]
Same goes for KTX for Unity, which shares the Unity version code.

**Comment by atteneder** [comment]
Fixed in [Draco for Unity 5.1.8](https://docs.unity3d.com/Packages/com.unity.cloud.draco@5.1/changelog/CHANGELOG.html#518---2024-10-07) and [KTX for Unity 3.4.5](https://docs.unity3d.com/Packages/com.unity.cloud.ktx@3.4/changelog/CHANGELOG.html#345---2024-10-07).
