### ISSUE TITLE
Import failing on some animated models

### ISSUE THREAD

**Issue by sandersdevelopments** [atteneder/glTFast#722]
Hello there!

First of all, thanks for your effort and this wonderful plugin!

We have a very big set of possible .glb uploads on our platform. And these two for example are somehow not being imported and throwing no error at all: 

[animated_files_not_working.zip](https://github.com/user-attachments/files/17220577/animated_files_not_working.zip)

The attached .glb files are being displayed correctly in Blender, the threejs viewer and aswell is not throwing any errors in the gltf validator,...
I also tried to export the gorilla with JPEG textures bc I thought it might have something to do with the web textures. But no chance at all. 

The `myAsset.Load(myMesh);` just returns false for these meshes after it has been loaded and I dont know why.. 

I appreciate any help to find out whats wrong here and thanks in advance!

Environment: 

Unity version: 2022.3.47 
GLTFast version: 6.8.0
KTX for unity: 3.4.4
Draco for Unity: 5.1.6

**Comment by atteneder** [comment]
Hi @sandersdevelopments,

The primary issue is that these glTFs require the extension `EXT_texture_webp`, which is not supported yet. glTFast is reacts accordingly by refusing to load it (even without the WebP textures).

The secondary problem is that you probably load via a custom script and don't set the `logger` paramter in `GltfImport`'s constructor. As a result you don't ever see any of the error messages. One solution is to set `logger: new ConsoleLogger()`.

Admittedly this is bad default behavior, and the fact that you're not the first falling into this trap speaks volume.

But changing the default would break the API, so the fix has to wait.

hth

**Comment by sandersdevelopments** [comment]
That makes sense! And thanks for your quick reply, I appreciate it 🙏🏼

**Comment by atteneder** [comment]
No problem.

In the meantime try to stick with KTX or Jpeg/PNG textures.
