### ISSUE TITLE
Import glb files in editor time

### ISSUE THREAD

**Issue by Singh-sid930** [atteneder/glTFast#729]
Hi, 
I have copied over glb files in the Assets directory and I can drag and drop them into the editor window with ease. 
However, I would like to be able to do this programmatically through a custom editor button.
I have been trying to make that happen but getting the same error as this issue 
https://github.com/atteneder/glTFast/issues/696
note that the issue is triggered at the initialization of the GltfImport() object itself. 
Is there any way to accomplish loading a glb file at editor time by using a custom editor gui button ?

**Comment by atteneder** [comment]
Hi,

two solutions:

## 1. Copy to Assets

Your editor script could:

- Copy glTF files (including all dependencies like .bin and texture files) into the `Assets` folder
- Refresh the asset database to force an import
- Access the importer to do further stuff, like adding the prefab to a scene etc.

## 2. Manual Import

You can manually do an import via script, as you suggested. However, there's couple of things to mind when importing in Editor mode (e.g. you *HAVE TO* import non-async and use an [UninterruptedDeferAgent](https://docs.unity3d.com/Packages/com.unity.cloud.gltfast@6.9/api/GLTFast.UninterruptedDeferAgent.html)).

Please have a look at [GltfImporter](https://github.com/Unity-Technologies/com.unity.cloud.gltfast/blob/64f3257d9354fd61e8a9232690648cc2f1d4b941/Editor/Scripts/GltfImporter.cs) as reference (note: `GltfImporER`, not `GltfImport`).

hth
