### ISSUE TITLE
GLTF asset postprocessor

### ISSUE THREAD

**Issue by VadikPtr** [atteneder/glTFast#731]
**Is your feature request related to a problem? Please describe.**

I have custom material properties in my GLTF file.

**Describe the solution you'd like**

I want my inherited class from `AssetPostprocessor` (or may be some GLTF-dependent *Processor) to work. But for some reason it does not.

**Describe alternatives you've considered**

...

**Additional context**

I tried to make class:

```csharp
public class SH3UAssetPostProcessor : AssetPostprocessor
{
  public void OnPreprocessMaterialDescription(MaterialDescription description, Material material,
                                              AnimationClip[] materialAnimation)
  {
    Debug.Log($"-- material: {description.materialName} ------------------------------");
  }
}
```

In "Asset PostProcessors" for GLTF file Inpector it doesn't show up. But one postprocessor is here - ShaderGraphAssetPostProcessor. My guess is that feature already implemented, but doesn't documented. May be solution to the problem is documentation.

**Comment by VadikPtr** [comment]
I managed to do what I wanted: https://gist.github.com/vadikptr/cbd66e0fab49dc33060c99f961d25b13

**Comment by atteneder** [comment]
Great you got it to run and thanks for sharing that Gist!

**Comment by desenholdb** [comment]
The git link is broken...
Hi, do you guys have anything on it?
Because I'm trying to get custom data during the material generation.

I`ve made this discussion, but it got no attention at all...
https://github.com/atteneder/glTFast/discussions/777

**Comment by VadikPtr** [comment]
@desenholdb Fixed link
