### ISSUE TITLE
glTF Sample Model (GearboxAssy) doesn't render correctly

### ISSUE THREAD

**Issue by mikejurka** [atteneder/glTFast#74]
Steps to reproduce:
1. Clone the glTF samples repo (https://github.com/KhronosGroup/glTF-Sample-Models)
2. Clone https://github.com/atteneder/glTFastDemo
3. In the demo viewer, load "file:///[..base path....]glTF-Sample-Models/2.0/GearboxAssy/glTF-Draco/GearboxAssy.gltf"
You will see that it looks different from the regular GearboxAssy model.

Note: loading the gltf model using Draco in https://gltf-viewer.donmccurdy.com/ looks identical to the non-draco version.

**Comment by mikejurka** [comment]
![Screen Shot 2020-04-28 at 11 22 53 PM](https://user-images.githubusercontent.com/440407/80566172-3500a580-89a7-11ea-9519-088fdfa5fa56.png)
![Screen Shot 2020-04-28 at 11 22 47 PM](https://user-images.githubusercontent.com/440407/80566178-3762ff80-89a7-11ea-961e-5f3ef62ae1cc.png)

**Comment by atteneder** [comment]
Cannot reproduce!

Some weeks/months ago I adressed this bug by changing DracoUnity, so that it inverts one axis in order to make a glTF to Unity space conversoin.

Please try to update your [DracoUnity](https://gitlab.com/atteneder/DracoUnity) package and see if it works afterwards.

**Comment by mikejurka** [comment]
Thanks!!! I'll make sure i upgrade my dracounity version.
