### ISSUE TITLE
Color missing

### ISSUE THREAD

**Issue by tufeixp** [atteneder/glTFast#78]
![image](https://user-images.githubusercontent.com/11953709/83736369-20898a00-a684-11ea-9360-3be11caf3a4d.png)

using:
https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/Buggy/glTF-Draco

**Comment by atteneder** [comment]
Hi,
thanks for reporting.
Can you provide some more information:
- Which operating system?
- Unity version?
- Which rendering backend (built-in, URP, HDRP) ?
- Details about the material (look at the inspector)

Thanks

**Comment by tufeixp** [comment]
Windows 10 Editor mode
Unity 2019.3.5f1
build-tin
about the material: color in yellow, without uv map.

**Comment by atteneder** [comment]
I just tested on macOS, Unity 2019.4.13f1; built-in.

Here's what it looks like:
<img width="1215" alt="grafik" src="https://user-images.githubusercontent.com/2593014/99161265-db688a00-26f0-11eb-957f-dffe00adf918.png">

Import seems fine.
Your lighting seems strange (completely black shadows). Please make sure your lighting was generated (in Lightinig Settings). To ensure this is not a problem, move the object (head) outside of the helmet's shadow like so:

<img width="331" alt="grafik" src="https://user-images.githubusercontent.com/2593014/99161316-634e9400-26f1-11eb-9282-2c7daef4cf4a.png">

I'll test Windows tomorrow.

**Comment by atteneder** [comment]
Assuming this is a non-issue.
