### ISSUE TITLE
Load from byte array

### ISSUE THREAD

**Issue by FreakTheMighty** [atteneder/glTFast#81]
Is it possible to load a glb from a byte array rather than using a url? I need to extract the bytes from a larger file before generating the glb.

**Comment by p-skakun** [comment]
@FreakTheMighty We used custom `IDownloadProvider` implementation for such case.
It accepts byte array as a constructor parameter and `Request` method just returns `IDownload` implementation with filled `data` field.

**Comment by atteneder** [comment]
Hi,

@p-skakun already provided a great answer that I'd support.

Since this question pops up repeatedly I'm considering

- Providing a simpler interface (maybe IDownloadProvider is too much for some)
- Document it better (FAQ or similar)

Anyways, I'm always open to inputs.

Thanks!

**Comment by FreakTheMighty** [comment]
Thanks @p-skakun @atteneder , let me give that interface a try and see if I have any thoughts on improvements.

**Comment by FreakTheMighty** [comment]
So I got it working using the interfaces. Agreed, that it feels a bit clunky. I wonder, could we have something like [this](https://github.com/atteneder/glTFast/blob/a83c230168b0caa74194ac772ecbb747d035ca93/Runtime/Scripts/GltFast.cs#L670) become public function? It would be nice for `url` to be optional. I ended up passing in a dummy https://example.com.

**Comment by atteneder** [comment]
> So I got it working using the interfaces. Agreed, that it feels a bit clunky. I wonder, could we have something like [this](https://github.com/atteneder/glTFast/blob/a83c230168b0caa74194ac772ecbb747d035ca93/Runtime/Scripts/GltFast.cs#L670) become public function? It would be nice for `url` to be optional. I ended up passing in a dummy https://example.com.

That seems doable! I'll check it soon and change it.
Thanks for your input!

**Comment by FreakTheMighty** [comment]
Thank you for this library! My initial tests show it to be much more performant than the one built into MRTK for our use case. I'm looking forward to doing more testing with it.
