### ISSUE TITLE
Marking readability of mesh should be optional and exposed.

### ISSUE THREAD

**Issue by Sudar-shan** [atteneder/glTFast#85]
Hi andreas,
In PrimitiveDracoCreateContext.cs
mesh.UploadMeshData(true);

bool markNoLongerReadable should be exposed.
By default it can be true but this is needed if we want to create collision after the mesh is loaded.

Thanks.

**Comment by atteneder** [comment]
Hi,

True, thanks for bringing it up.

I'll try to look into it soon. Feel free to make a PR if you need it faster.

regards

**Comment by atteneder** [comment]
fixed in upcoming release
