### ISSUE TITLE
WebGL error ArgumentNullException: Value cannot be null. Parameter name: shader

### ISSUE THREAD

**Issue by FriskyBishop** [atteneder/glTFast#88]
Unity 2019.2.1
WebGL Build
glTFast 2.0.0

I get this error every time I try to build and run glTFast  on my aws bucket.

`ArgumentNullException: Value cannot be null. Parameter name: shader
`

The web demo works with my 3D model but when I build and try to load I get this error every time. 
The Unity scene only contains a camera, light, and 1 glftAsset script

**Comment by FriskyBishop** [comment]
i forgot the Materials and Shader Variants step in the setup -_-

**Comment by atteneder** [comment]
Hi,

Thanks for reporting and great that you found a solution.

If you don't mind I'd like to reopen it until there's a more descriptive error message.
