### ISSUE TITLE
How to set the default Unlit material?

### ISSUE THREAD

**Issue by andrewsmoc** [atteneder/glTFast#91]
When I modify the GltFast.cs class on line 1066:
This: primMaterials [m] = materialGenerator.GetPbrMetallicRoughnessMaterial ();

Because of this: materialGenerator.GetUnlitMaterial ();

I get the error:
error CS1061: 'IMaterialGenerator' does not contain a definition for 'GetUnlitMaterial' and no accessible extension method 'GetUnlitMaterial' accepting a first argument of type 'IMaterialGenerator' could be found (are you missing a using directive or an assembly reference?)

What is the correct way to change the default material or shader?

**Comment by atteneder** [comment]
Hi @andrewsmoc,

the best way to use unlit materials is to use the [unlit extension](https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Khronos/KHR_materials_unlit) in your glTF files. You'd have to look up your glTF-generator's/exporter's documentation to see how this is done.

In case you don't have control over the content, but want to override ALL materials to be unlit:
I'd do that by creating a forked version of the DefaultMaterialGenerator which  always creates unlit materials.

The code line you tried to alter is just relevant for the fallback when no (valid) material was assigned.

hth,
Andi
