### ISSUE TITLE
Increase Performance via DOTS (Jobs / ECS / Burst)

### ISSUE THREAD

**Issue by atteneder** [atteneder/glTFast#92]
Unity's approach to improving performance is called [DOTS](https://unity.com/de/dots)

This will not just allow faster loading, it enables very small builds (especially interesting for WebGL).

## Job System

glTFast already takes advantage of C# Jobs and it really pays off! Still, things can always be improved.

## Burst

Some code could be improved by using the Burst compiler. Some early experiments showed good results, but it has to be done thouroughly before it lands.

## Entity-Component-System

The foundation for DOTS glTF loading will be the interface `IInstantiator`. Currently the only implementation is `GameObjectInstantiator`, which creates regular GameObjects. The Plan is to create some sort of `EntityInstantiator`, which works with ECS+DOTS.

## DOTS-Animation

Once animation lands, it should be ported to DOTS as well

**Comment by vjleo** [comment]
Hi Thomas,
I have sent you an email with a suggestion for the `EntityInstantiator`
Hope it helps!

**Comment by atteneder** [comment]
> Hi Thomas,
> I have sent you an email with a suggestion for the `EntityInstantiator`
> Hope it helps!

Hi @vjleo ,

That's a great starting point, thanks! Atm I've only glimpsed over it, but I'll give it a try soon.

DOTS, here we go :)

P.S.: I received an error from my email system last time I tried to reply to your email. Maybe check your domain/email server settings.
P.P.S.: My name's Andi, not Thomas ;)

**Comment by atteneder** [comment]
@vjleo 

Forgot: Consider publishing your work by forking this project! The benefit is that others can try/test it as well. I'm sure this is of interest.

**Comment by juancarlosgermano** [comment]
Hi @atteneder, I made a fork, instead @vjleo. 
If you can take a look, I'll appreciate.

Now I'm trying to convert GltFast.cs with: Job System and Burst Compiler.
I have tried run a Job in a JobComponentSystem to read a path.
I am converting part of GltFast and removing coroutines, and applying complete/execute on jobhandle instead of scheduling there.
My last issue was to get the material and generate mesh, because Unity only lets you create meshes and materials if it's on the Main Thread.
Do you have any suggestions/ideas to implement this?

**Comment by atteneder** [comment]
Please familiarize yourself with the concept of [pull requests](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/about-pull-requests).

Prepare changes you want me to review thouroughly, send a PR (=pull request) and I'll review, give feedback and ideally merge it.

Thanks!

**Comment by juancarlosgermano** [comment]
Ok, I sent a pull request now.

https://github.com/atteneder/glTFast/pull/94

**Comment by DerrickBarra** [comment]
@atteneder glad to see this being poked at, I just wanted to mention that GLTFast should also keep a normal coroutine/single-threaded loading solution as well for compatibility with Unity WebGL (no multi-threading support and can't use while loops).

**Comment by atteneder** [comment]
> @atteneder glad to see this being poked at, I just wanted to mention that GLTFast should also keep a normal coroutine/single-threaded loading solution as well for compatibility with Unity WebGL (no multi-threading support and can't use while loops).

WebGL is an important platform for glTF(ast). The reduced build size of glTFast (compared to UnityGLTF) was a good reason to pursue this project.

So stay assured that it will stay compatible. I'm not sure if it will be via Coroutines though and Web multi-threading (hopefully) will become a thing some day.

**Comment by atteneder** [comment]
There's now an experimental [DOTS implementation](https://github.com/atteneder/glTFast/blob/main/Documentation%7E/features.md#data-oriented-technology-stack).

**Comment by atteneder** [comment]
Although Entities support is still not feature complete I'll close this issue and instead others with a narrower scope.
