### ISSUE TITLE
Attaching collider to the imported model

### ISSUE THREAD

**Issue by waseemkhan1989** [atteneder/glTFast#98]
Please excuse me for this naïve question. I can successfully upload a draco compressed glb file through this awesome library but the problem is that how can I attach collider to the whole model?  Following is the code that I am using for importing the model.

`            var model = gameObject.AddComponent<GLTFast.GltfAsset>();
            model.url = path;
            ResetWrapper();
            model.transform.SetParent(wrapper.transform);
         // its wrong..does not add collider           
             model.gameObject.AddComponent<Collider>();`

The imported model in project hierarchy looks like this:
![Capture](https://user-images.githubusercontent.com/25552247/97314126-ac849400-1867-11eb-9bd2-49890a0a8c70.PNG)

Any help in this regard @Stephengower @atteneder @roomle-atti @dhasl002 ?

**Comment by atteneder** [comment]
Hi,

That's an appropriate question that's been asked before.

The glTF spec does not say anything about physics colliders.

glTFast's default behaviour is to attach no colliders to save resources (some don't use physics, so it's opt-in). Also, this is highly individual. Some models come with additional (lower poly) collider meshes just for physics. glTF wouldn't know how to deal with those.

There are two ways of adding colliders:
- Manually traverse the imported hierarchy (per instance) and add them
- Better, but more sophisticated: Create and use a custom implementation of `IInstantiator` (look up the source)

Also: There's a bug preventing creation of MeshColliders (see #86)

**Comment by waseemkhan1989** [comment]
Thanks for your prompt reply. I highly appreciate it. I looked at the source files such as IInstantiator and other source files that uses this interface.  As I do not have experience with interfaces. I will look into the library again and will try to figure out how to add collider through custom implementation of IInstantiator and then will get back to you. Thanks

**Comment by atteneder** [comment]
Re-reading your initial post: You have to add a collider to each individual glTF Primitive (GameObject with a MeshFilter/Renderer component).

To be able to do that, use a recent development version and look up [Readable Mesh Data](https://github.com/atteneder/glTFast/blob/main/Documentation~/glTFast.md#readable-mesh-data).
