### ISSUE TITLE
Some 3D objects looks deformed/destroyed in the imported model

### ISSUE THREAD

**Issue by waseemkhan1989** [atteneder/glTFast#99]
Hi!

Now, I can successfully import glb files on Quest but some objects in my model looks deformed or destroyed. Here is an example of a car. The image is the original one 

![OriginalHall](https://user-images.githubusercontent.com/25552247/97696264-9d8b2500-1aa5-11eb-908b-1b23f8f25324.PNG)

This is the one imported through GLTFast on Quest:

![com Uraan TopexGLTFast-20201030-114028](https://user-images.githubusercontent.com/25552247/97695964-26559100-1aa5-11eb-80c4-e783dde8b43e.jpg)

How can this issue be corrected?

**Comment by atteneder** [comment]
Thanks for reporting.

Very strange :/

The original image is not from Unity/glTFast, right? From what is it then?

Can you provide the model?

You can also cross-check with alternative glTF viewers like [this great one](https://gltf-viewer.donmccurdy.com/).

**Comment by waseemkhan1989** [comment]
@atteneder Sorry for late replying. I was busy in moving to a new city.

Please find attached the model.

[DWG1_Halle.zip](https://github.com/atteneder/glTFast/files/5486847/DWG1_Halle.zip)

There are also other models with which I am facing the same problem with GLTFast.
Point to be noted! with Unity GLTF library, I am not facing this problem.

Any solution?

**Comment by atteneder** [comment]
What I observed so far:

I'm using Unity's Matrix4x4.rotation and Matrix4x4.lossyScale to decompose the Matrix. This algorithm seem to break if the scale of the object was negative (in some/all axises?).

One workaround is to not use negative scale.

I'll have to investigate if other implementations are more robust.

**Comment by atteneder** [comment]
fix is in the making!

@waseemkhan1989 Would you mind it if I share screenshots of your model for educational purpos in my blog?

**Comment by waseemkhan1989** [comment]
@atteneder  Yeah sure:)
